
# mood/pipeline/keywords/ae.py
AE_KEYWORDS = {
    "finance": [
        "uae economy", "united arab emirates gdp",
        "dubai financial market", "dfm",
        "abu dhabi securities exchange", "adx",
        "central bank uae", "cbuae",
        "uae dirham", "aed",
        "uae inflation", "uae budget", "uae exports",
        "uae trade", "uae market", "uae growth",
        "uae debt", "uae surplus", "uae unemployment",
        "uae wages", "uae housing", "uae mortgage",
        "emirates nbd", "first abu dhabi bank", "fab",
        "adnoc", "abu dhabi national oil",
        "emirates airline", "etisalat", "du telecom",
        "mubadala", "adia", "adq",
        "uae sovereign wealth fund",
        "uae business", "uae investment",
        "uae tourism", "uae manufacturing",
        "uae logistics", "dubai port",
        "uae eu trade", "uae us trade",
        "uae tariffs", "uae fiscal",
        "uae vision 2030", "uae diversification",
        "dubai expo legacy", "uae fintech hub",
        "uae real estate", "dubai property",
        "uae construction", "uae infrastructure",
    ],
    "geopolitics": [
        "uae foreign policy", "uae nato",
        "uae sanctions", "uae diplomacy",
        "uae troops", "uae ukraine", "uae russia",
        "uae ambassador", "uae eu",
        "uae defense", "uae military",
        "abu dhabi talks", "uae security",
        "uae intelligence", "uae us relations",
        "uae us base", "uae iran relations",
        "uae israel", "uae abraham accords",
        "uae hamas", "uae middle east",
        "uae gulf", "uae saudi relations",
        "uae gcc", "uae qatar",
        "uae peacekeeping", "uae un",
        "uae yemen", "uae somalia",
        "uae china relations", "uae india",
        "uae iran war", "strait hormuz uae",
    ],
    "energy": [
        "uae energy", "uae oil", "uae gas",
        "adnoc energy", "uae electricity",
        "uae renewables", "uae solar",
        "masdar uae", "uae wind",
        "uae grid", "uae climate",
        "uae emissions", "uae energy transition",
        "uae hydrogen", "uae lng",
        "uae energy prices", "uae energy security",
        "uae green energy", "uae carbon neutral",
        "uae net zero", "uae fuel prices",
        "uae nuclear", "barakah nuclear",
        "uae cop28 legacy", "uae clean energy",
    ],
    "technology": [
        "uae tech", "dubai tech", "uae startup",
        "uae ai", "uae fintech", "uae digital",
        "uae innovation", "uae cybersecurity",
        "uae software", "uae it sector",
        "uae ecommerce", "uae digital economy",
        "uae smart city", "smart dubai",
        "uae medtech", "uae biotech",
        "uae blockchain", "uae quantum",
        "uae 5g", "uae space",
        "emirates mars mission",
        "uae venture capital",
        "careem uae", "noon ecommerce",
        "uae digital transformation",
    ],
    "health": [
        "uae health", "uae hospital",
        "uae pharma", "uae vaccine",
        "uae healthcare", "uae mental health",
        "uae health system", "uae medicine",
        "uae public health", "uae wellbeing",
        "uae biotech", "uae cancer",
        "cleveland clinic abu dhabi",
        "uae medical tourism",
        "uae health authority",
        "dubai health authority",
        "uae aging population",
    ],
    "crime": [
        "uae corruption", "uae fraud",
        "uae scandal", "uae court",
        "uae investigation", "uae organized crime",
        "uae drug trafficking", "uae money laundering",
        "uae terrorism", "uae police",
        "uae gang", "uae anti corruption",
        "uae cybercrime", "uae scam",
        "uae arrest", "uae human trafficking",
        "uae migrant workers", "uae kafala",
        "uae crypto fraud", "uae financial crime",
    ],
    "politics": [
        "federal national council", "uae parliament",
        "uae election", "uae government",
        "uae minister", "uae prime minister",
        "uae president", "uae coalition",
        "uae opposition", "uae policy",
        "mohamed bin zayed", "mbz",
        "mohammed bin rashid", "mbr",
        "uae reform", "uae immigration",
        "uae integration", "uae welfare",
        "uae citizenship", "uae golden visa",
        "uae judiciary", "uae rule of law",
        "uae democracy", "uae media freedom",
        "uae press freedom", "uae constitution",
        "uae human rights", "uae labour reform",
        "uae expat population",
        "uae federal structure",
    ],
}
