
# mood/pipeline/keywords/ag.py
AG_KEYWORDS = {
    "finance": [
        "antigua economy", "antigua barbuda gdp",
        "eastern caribbean securities exchange",
        "eastern caribbean central bank", "eccb antigua",
        "eastern caribbean dollar antigua", "xcd",
        "antigua inflation", "antigua budget",
        "antigua exports", "antigua trade",
        "antigua market", "antigua growth",
        "antigua debt", "antigua deficit",
        "antigua unemployment", "antigua wages",
        "antigua housing", "antigua mortgage",
        "antigua commercial bank",
        "scotiabank antigua", "rbtt antigua",
        "antigua tourism", "antigua yachting",
        "antigua manufacturing", "antigua agriculture",
        "antigua fisheries", "antigua services",
        "antigua eu trade", "antigua us trade",
        "antigua tariffs", "antigua fiscal",
        "antigua pension fund", "antigua industry",
        "antigua startup", "antigua fintech",
        "antigua real estate", "antigua construction",
        "antigua remittances", "antigua diaspora",
        "antigua offshore finance",
        "antigua citizenship by investment",
        "global citizen antigua",
    ],
    "geopolitics": [
        "antigua foreign policy", "antigua nato",
        "antigua sanctions", "antigua diplomacy",
        "antigua troops", "antigua ukraine",
        "antigua russia", "antigua ambassador",
        "antigua eu", "antigua defense",
        "antigua military", "st johns talks",
        "antigua security", "antigua intelligence",
        "antigua us relations", "antigua caricom",
        "antigua caribbean", "antigua uk relations",
        "antigua commonwealth", "antigua china",
        "antigua peacekeeping", "antigua un",
        "gaston browne foreign policy",
        "antigua climate diplomacy",
        "oecs antigua",
        "antigua us base",
    ],
    "energy": [
        "antigua energy", "antigua electricity",
        "antigua renewables", "antigua solar",
        "antigua wind", "antigua grid",
        "antigua climate", "antigua emissions",
        "antigua energy transition",
        "antigua energy prices", "antigua energy security",
        "antigua green energy", "antigua carbon neutral",
        "antigua net zero", "antigua fuel prices",
        "antigua climate vulnerability",
        "antigua sea level rise",
        "antigua energy independence",
        "apua antigua",
    ],
    "technology": [
        "antigua tech", "st johns tech",
        "antigua startup", "antigua ai",
        "antigua fintech", "antigua digital",
        "antigua innovation", "antigua cybersecurity",
        "antigua software", "antigua it sector",
        "antigua ecommerce", "antigua digital economy",
        "antigua smart city", "antigua medtech",
        "antigua blockchain", "antigua 5g",
        "antigua digital transformation",
        "digicel antigua", "flow antigua",
        "antigua digital citizenship",
        "antigua online gambling",
    ],
    "health": [
        "antigua health", "antigua hospital",
        "antigua pharma", "antigua vaccine",
        "antigua healthcare", "antigua mental health",
        "antigua health system", "antigua medicine",
        "antigua public health", "antigua wellbeing",
        "antigua cancer", "antigua aging population",
        "antigua diabetes", "antigua obesity",
        "mount st john medical centre",
        "antigua health ministry",
        "antigua climate health",
        "antigua medical tourism",
    ],
    "crime": [
        "antigua corruption", "antigua fraud",
        "antigua scandal", "antigua court",
        "antigua investigation", "antigua organized crime",
        "antigua drug trafficking", "antigua money laundering",
        "antigua terrorism", "antigua police",
        "antigua gang", "antigua anti corruption",
        "antigua cybercrime", "antigua scam",
        "antigua arrest", "antigua human trafficking",
        "antigua protest", "antigua riot",
        "antigua political scandal",
        "antigua drug transshipment",
        "antigua offshore banking scandal",
    ],
    "politics": [
        "antigua parliament", "antigua election",
        "antigua government", "antigua minister",
        "antigua prime minister", "antigua coalition",
        "antigua opposition", "ablp antigua",
        "gaston browne", "browne antigua",
        "unp antigua", "antigua policy",
        "antigua reform", "antigua immigration",
        "antigua diaspora", "antigua welfare",
        "antigua citizenship", "antigua referendum",
        "antigua judiciary", "antigua rule of law",
        "antigua democracy", "antigua king",
        "antigua governor general",
        "antigua republic debate",
        "antigua media freedom",
        "antigua constitution",
        "antigua caricom",
        "oecs politics antigua",
        "global citizen organization antigua",
    ],
}
