
# mood/pipeline/keywords/am.py
AM_KEYWORDS = {
    "finance": [
        "armenian economy", "armenia gdp",
        "armenian stock exchange", "amex armenia",
        "central bank armenia", "cba armenia",
        "armenian dram", "amd",
        "armenian inflation", "armenian budget",
        "armenian exports", "armenian trade",
        "armenian market", "armenian growth",
        "armenian debt", "armenian deficit",
        "armenian unemployment", "armenian wages",
        "armenian housing", "armenian mortgage",
        "armenian agriculture", "armenian brandy",
        "armenian diamond", "armenian jewelry",
        "armenian tourism", "armenian eu funds",
        "armenian recovery plan", "armenian pension fund",
        "armenian industry", "armenian it sector",
        "armenian startup", "armenian outsourcing",
        "armenian remittances", "armenian diaspora",
        "armenian banking", "ameriabank",
        "armswissbank", "idbank armenia",
        "armenian real estate", "armenian construction",
        "armenian logistics", "armenian free trade zone",
        "armenian tech revenue", "armenian mining",
        "armenian copper", "armenian molybdenum",
        "chanel armenia", "armenian fashion",
    ],
    "geopolitics": [
        "armenian foreign policy", "armenia nato",
        "armenian sanctions", "armenian diplomacy",
        "armenian troops", "armenia ukraine",
        "armenia russia", "armenian ambassador",
        "armenia eu", "armenian defense",
        "armenian military", "yerevan talks",
        "armenia security", "armenian intelligence",
        "sns armenia", "nagorno karabakh",
        "karabakh", "armenian occupied territories",
        "armenia azerbaijan war", "armenia azerbaijan peace",
        "armenian border", "armenian pro western",
        "armenia eu accession", "armenia nato partnership",
        "us armenia relations", "armenian peace deal",
        "armenia ceasefire", "armenian abkhazia",
        "armenian sovereignty", "armenian diaspora geopolitics",
        "armenian genocide recognition",
        "pashinyan foreign policy",
        "armenia csto withdrawal",
        "armenia russia relations deteriorating",
    ],
    "energy": [
        "armenian energy", "armenian electricity",
        "armenian nuclear", "metsamor nuclear",
        "armenian gas", "armenian renewables",
        "armenian grid", "armenian solar",
        "armenian wind", "armenian hydro",
        "armenian climate", "armenian emissions",
        "armenian energy transition",
        "russian gas armenia", "armenian energy security",
        "armenian energy prices", "armenian lng",
        "armenian biomass", "armenian green energy",
        "armenian energy independence",
        "electric networks armenia",
    ],
    "technology": [
        "armenian tech", "yerevan tech", "armenian startup",
        "armenian ai", "armenian fintech",
        "armenian digital", "armenian innovation",
        "armenian software", "armenian it sector",
        "armenian outsourcing", "armenian cybersecurity",
        "armenian gaming", "armenian e-government",
        "armenian digital transformation",
        "armenian unicorn", "armenian medtech",
        "synopsys armenia", "vmware armenia",
        "armenian semiconductor", "armenian quantum",
        "ucom armenia", "armenian internet",
    ],
    "health": [
        "armenian health", "armenian hospital",
        "armenian pharma", "armenian vaccine",
        "armenian healthcare", "armenian mental health",
        "armenian health system", "armenian medicine",
        "armenian public health", "armenian wellbeing",
        "armenian medical aid", "armenian refugees health",
        "armenian biotech", "armenian cancer",
        "yerevan medical university",
        "armenian war wounded",
    ],
    "crime": [
        "armenian corruption", "armenian fraud",
        "armenian scandal", "armenian court",
        "armenian investigation", "armenian organized crime",
        "armenian drug trafficking", "armenian money laundering",
        "armenian terrorism", "armenian police",
        "armenian gang", "armenian anti corruption",
        "armenian smuggling", "armenian human trafficking",
        "armenian election fraud", "armenian protest",
        "yerevan protest", "armenian opposition arrested",
        "armenian political prisoner",
        "armenian oligarch",
    ],
    "politics": [
        "azgayin joghov", "armenian parliament",
        "armenian election", "armenian government",
        "armenian minister", "armenian prime minister",
        "armenian coalition", "armenian opposition",
        "civil contract armenia", "nikol pashinyan", "pashinyan",
        "robert kocharyan", "serzh sargsyan",
        "armenian revolutionary federation",
        "dashnaktsutyun",
        "armenian policy", "armenian reform",
        "armenian immigration", "armenian diaspora",
        "armenian welfare", "armenian citizenship",
        "armenian referendum", "armenian judiciary",
        "armenian rule of law", "armenian eu relations",
        "armenian democracy", "armenian president",
        "vahagn khachaturyan",
        "armenian media freedom",
        "armenian csto membership",
        "armenian russia relations",
        "armenian eu integration",
        "armenian nato aspirations",
        "armenian protest movement",
    ],
}

