
# mood/pipeline/keywords/ar.py
AR_KEYWORDS = {
    "finance": [
        "argentine economy", "argentina gdp", "merval",
        "bolsa comercio buenos aires", "bcba",
        "central bank argentina", "bcra",
        "argentine peso", "ars",
        "argentine inflation", "argentine hyperinflation",
        "argentine budget", "argentine exports",
        "argentine trade", "argentine market",
        "argentine growth", "argentine debt",
        "argentine deficit", "argentine unemployment",
        "argentine wages", "argentine housing",
        "argentine mortgage", "banco nacion argentina",
        "banco galicia", "banco macro",
        "bbva argentina", "santander argentina",
        "ypf argentina", "mercadolibre argentina",
        "pampa energia", "grupo clarín",
        "argentine business", "argentine investment",
        "argentine tourism", "argentine manufacturing",
        "argentine agriculture", "argentine soybean",
        "argentine beef exports", "argentine wine",
        "argentine lithium", "argentine mining",
        "argentine eu trade", "argentina us trade",
        "argentine tariffs", "argentine fiscal",
        "argentine pension fund", "anses argentina",
        "argentine industry", "argentine startup",
        "argentine fintech", "argentine real estate",
        "argentine construction", "argentine remittances",
        "argentine dollarization", "milei economy",
        "argentine imf deal", "argentina imf",
        "argentine peso devaluation",
        "adorni scandal argentina",
    ],
    "geopolitics": [
        "argentine foreign policy", "argentina nato",
        "argentine sanctions", "argentine diplomacy",
        "argentine troops", "argentina ukraine",
        "argentina russia", "argentine ambassador",
        "argentina eu", "argentine defense",
        "argentine military", "buenos aires talks",
        "argentina security", "argentine intelligence",
        "afip argentina", "argentina us relations",
        "argentina chile", "argentina brazil",
        "argentina venezuela", "argentina falklands",
        "malvinas dispute", "falkland islands",
        "argentina uk falklands",
        "argentina peacekeeping", "argentina un",
        "argentina brics", "argentina g20",
        "milei foreign policy",
        "argentina mercosur",
    ],
    "energy": [
        "argentine energy", "argentine oil", "ypf oil",
        "argentine gas", "vaca muerta",
        "argentine shale", "argentine electricity",
        "argentine renewables", "argentine solar",
        "argentine wind", "argentine hydro",
        "argentine grid", "argentine climate",
        "argentine emissions", "argentine energy transition",
        "argentine hydrogen", "argentine lng",
        "argentine energy prices", "argentine energy security",
        "argentine green energy", "argentine carbon neutral",
        "argentine net zero", "argentine fuel prices",
        "argentine oil production", "argentine refinery",
        "argentine petrochemical",
        "vaca muerta shale gas",
        "argentine lithium energy",
    ],
    "technology": [
        "argentine tech", "buenos aires tech",
        "argentine startup", "argentine ai",
        "argentine fintech", "mercadopago argentina",
        "argentine digital", "argentine innovation",
        "argentine unicorn", "argentine cybersecurity",
        "argentine gaming", "argentine software",
        "argentine it sector", "argentine ecommerce",
        "mercadolibre", "argentine digital economy",
        "argentine semiconductor", "argentine ev",
        "argentine smart city", "argentine medtech",
        "argentine biotech", "argentine quantum",
        "argentine space", "conae argentina",
        "argentine 5g", "argentine blockchain",
        "globant argentina", "despegar argentina",
    ],
    "health": [
        "argentine health", "argentine hospital",
        "argentine pharma", "argentine vaccine",
        "argentine healthcare", "argentine mental health",
        "argentine health system", "argentine medicine",
        "argentine public health", "argentine wellbeing",
        "argentine biotech", "argentine cancer",
        "argentine aging population", "argentine birthrate",
        "anmat argentina", "argentine drug approval",
        "argentine dengue", "argentine malaria",
        "argentine health reform",
    ],
    "crime": [
        "argentine corruption", "argentine fraud",
        "argentine scandal", "argentine court",
        "argentine investigation", "argentine organized crime",
        "argentine drug trafficking", "argentine money laundering",
        "argentine terrorism", "argentine police",
        "argentine gang", "argentine anti corruption",
        "argentine cybercrime", "argentine scam",
        "argentine arrest", "argentine mafia",
        "argentine human trafficking",
        "argentine protest", "argentine riot",
        "argentine political scandal",
        "adorni scandal", "milei corruption",
        "argentine femicide",
        "la campora corruption",
    ],
    "politics": [
        "congreso argentina", "senado argentina",
        "argentine parliament", "argentine election",
        "argentine government", "argentine minister",
        "argentine president", "argentine coalition",
        "argentine opposition", "la libertad avanza",
        "javier milei", "milei",
        "union por la patria", "cristina kirchner",
        "peronism", "kirchnerism",
        "argentine policy", "argentine reform",
        "argentine immigration", "argentine diaspora",
        "argentine welfare", "argentine citizenship",
        "argentine referendum", "argentine judiciary",
        "argentine rule of law", "argentine eu relations",
        "argentine democracy", "argentine media freedom",
        "argentine press freedom", "argentine constitution",
        "argentine federalism", "argentine provinces",
        "milei chainsaw reforms",
        "argentine austerity",
        "adorni government",
    ],
}
