
# mood/pipeline/keywords/au.py
AU_KEYWORDS = {
    "finance": [
        "australian economy", "australia gdp", "asx 200",
        "australian stock exchange", "asx australia",
        "reserve bank australia", "rba",
        "australian dollar", "aud",
        "australian inflation", "australian budget",
        "australian exports", "australian trade",
        "australian market", "australian growth",
        "australian debt", "australian deficit",
        "australian unemployment", "australian wages",
        "australian housing", "australian mortgage",
        "commonwealth bank", "westpac", "anz bank",
        "nab australia", "macquarie bank",
        "bhp", "rio tinto", "fortescue",
        "woodside energy", "santos australia",
        "woolworths", "coles", "wesfarmers",
        "qantas", "telstra", "afterpay",
        "australian business", "australian investment",
        "australian tourism", "australian manufacturing",
        "australian mining", "australian iron ore",
        "australian coal exports", "australian lng",
        "australian agriculture", "australian wheat",
        "australian eu trade", "australia us trade",
        "australian tariffs", "australian fiscal",
        "australian pension fund", "australian super",
        "australian industry", "australian startup",
        "australian unicorn", "australian fintech",
        "australian real estate", "australian construction",
        "australian property market",
    ],
    "geopolitics": [
        "australian foreign policy", "australia nato",
        "australian sanctions", "australian diplomacy",
        "australian troops", "australia ukraine",
        "australia russia", "australian ambassador",
        "australia eu", "australian defense",
        "australian military", "canberra talks",
        "australia security", "australian intelligence",
        "asio australia", "asis australia",
        "australia china relations", "australia us alliance",
        "aukus", "australia uk us",
        "australia japan", "australia india",
        "australia quad", "australia pacific",
        "australian peacekeeping", "australia un",
        "australia middle east", "australia gulf",
        "australia new zealand", "anzus",
        "australia south china sea",
        "australia taiwan", "australia north korea",
    ],
    "energy": [
        "australian energy", "australian coal",
        "australian electricity", "australian renewables",
        "australian solar", "australian wind",
        "australian hydro", "australian grid",
        "australian climate", "australian emissions",
        "australian energy transition", "australian hydrogen",
        "australian lng", "australian energy prices",
        "australian energy security", "australian green energy",
        "australian natural gas", "australian oil",
        "australian carbon neutral", "australian net zero",
        "australian fuel prices", "australian offshore wind",
        "australian nuclear debate", "australian coal phase out",
        "aemo australia", "australian battery",
        "australian critical minerals",
    ],
    "technology": [
        "australian tech", "sydney tech", "australian startup",
        "australian ai", "australian fintech",
        "australian digital", "australian innovation",
        "australian unicorn", "australian cybersecurity",
        "australian gaming", "australian software",
        "australian it sector", "australian ecommerce",
        "australian digital economy", "australian semiconductor",
        "australian ev", "australian smart city",
        "australian medtech", "australian biotech",
        "australian quantum", "australian space",
        "asa australia", "australian 5g",
        "afterpay australia", "canva australia",
        "atlassian australia", "australian blockchain",
    ],
    "health": [
        "australian health", "australian hospital",
        "australian pharma", "australian vaccine",
        "australian healthcare", "australian mental health",
        "australian health system", "australian medicine",
        "australian public health", "australian wellbeing",
        "australian medical tourism", "australian biotech",
        "australian cancer", "australian aging population",
        "australian birthrate", "medicare australia",
        "australian pbs", "australian tga",
        "australian drug approval", "australian gp shortage",
    ],
    "crime": [
        "australian corruption", "australian fraud",
        "australian scandal", "australian court",
        "australian investigation", "australian organized crime",
        "australian drug trafficking", "australian money laundering",
        "australian terrorism", "australian police",
        "australian federal police", "afp australia",
        "australian gang", "australian anti corruption",
        "icac australia", "australian cybercrime",
        "australian scam", "australian arrest",
        "australian bikie gang", "australian mafia",
        "australian human trafficking",
        "australian protest", "australian riot",
    ],
    "politics": [
        "house of representatives australia",
        "australian senate", "australian parliament",
        "australian election", "australian government",
        "australian minister", "australian prime minister",
        "australian coalition", "australian opposition",
        "labor party australia", "anthony albanese",
        "liberal party australia", "peter dutton",
        "greens australia", "adam bandt",
        "australian policy", "australian reform",
        "australian immigration", "australian integration",
        "australian welfare", "australian citizenship",
        "australian referendum", "australian judiciary",
        "australian rule of law", "australian eu relations",
        "australian democracy", "australian king",
        "australian governor general", "australian republic",
        "australian media freedom", "australian press freedom",
        "australian constitution", "australian federalism",
        "australian state politics", "nsw politics",
        "victorian politics", "queensland politics",
        "australian indigenous", "aboriginal rights",
        "australian voice referendum",
    ],
}