
# mood/pipeline/keywords/az.py
AZ_KEYWORDS = {
    "finance": [
        "azerbaijani economy", "azerbaijan gdp",
        "baku stock exchange", "bse azerbaijan",
        "central bank azerbaijan", "cbar",
        "azerbaijani manat", "azn",
        "azerbaijani inflation", "azerbaijani budget",
        "azerbaijani exports", "azerbaijani trade",
        "azerbaijani market", "azerbaijani growth",
        "azerbaijani debt", "azerbaijani deficit",
        "azerbaijani unemployment", "azerbaijani wages",
        "azerbaijani housing", "azerbaijani mortgage",
        "socar", "azerbaijani oil company",
        "azerbaijani oil revenue", "azerbaijani gas revenue",
        "state oil fund azerbaijan", "sofaz",
        "kapital bank azerbaijan", "abb bank",
        "azerbaijani business", "azerbaijani investment",
        "azerbaijani tourism", "azerbaijani manufacturing",
        "azerbaijani agriculture", "azerbaijani pomegranate",
        "azerbaijani eu funds", "azerbaijani recovery plan",
        "azerbaijani pension fund", "azerbaijani industry",
        "azerbaijani it sector", "azerbaijani startup",
        "azerbaijani remittances", "azerbaijani diaspora",
        "baku port", "azerbaijani logistics",
        "azerbaijani free trade zone",
        "azerbaijani mining", "azerbaijani cotton",
    ],
    "geopolitics": [
        "azerbaijani foreign policy", "azerbaijan nato",
        "azerbaijani sanctions", "azerbaijani diplomacy",
        "azerbaijani troops", "azerbaijan ukraine",
        "azerbaijan russia", "azerbaijani ambassador",
        "azerbaijan eu", "azerbaijani defense",
        "azerbaijani military", "baku talks",
        "azerbaijan security", "azerbaijani intelligence",
        "mss azerbaijan", "nagorno karabakh",
        "karabakh", "azerbaijani territories",
        "armenia azerbaijan war", "armenia azerbaijan peace",
        "azerbaijani border", "azerbaijani sovereignty",
        "azerbaijan eu accession", "azerbaijan nato partnership",
        "us azerbaijan relations", "azerbaijani peace deal",
        "azerbaijan ceasefire", "aliyev foreign policy",
        "azerbaijan turkey relations", "azerbaijan israel",
        "caspian sea azerbaijan", "baku tbilisi ceyhan",
        "southern gas corridor",
    ],
    "energy": [
        "azerbaijani energy", "azerbaijani oil",
        "azerbaijani gas", "socar energy",
        "baku tbilisi pipeline", "azerbaijani lng",
        "azerbaijani electricity", "azerbaijani renewables",
        "azerbaijani grid", "azerbaijani solar",
        "azerbaijani wind", "azerbaijani hydro",
        "azerbaijani climate", "azerbaijani emissions",
        "azerbaijani energy transition",
        "azerbaijani energy security", "azerbaijani energy prices",
        "caspian energy", "azerbaijani offshore",
        "southern gas corridor energy",
        "trans adriatic pipeline", "tap pipeline",
        "azerbaijani green energy",
        "cop29 azerbaijan", "baku climate",
    ],
    "technology": [
        "azerbaijani tech", "baku tech", "azerbaijani startup",
        "azerbaijani ai", "azerbaijani fintech",
        "azerbaijani digital", "azerbaijani innovation",
        "azerbaijani software", "azerbaijani it sector",
        "azerbaijani outsourcing", "azerbaijani cybersecurity",
        "azerbaijani gaming", "azerbaijani e-government",
        "azerbaijani digital transformation",
        "azerbaijani unicorn", "azerbaijani medtech",
        "azerbaijani semiconductor", "azerbaijani quantum",
        "azerbaijani internet", "azerbaijani ai law",
        "azerbaijani draft law ai",
        "cop29 tech baku",
    ],
    "health": [
        "azerbaijani health", "azerbaijani hospital",
        "azerbaijani pharma", "azerbaijani vaccine",
        "azerbaijani healthcare", "azerbaijani mental health",
        "azerbaijani health system", "azerbaijani medicine",
        "azerbaijani public health", "azerbaijani wellbeing",
        "azerbaijani medical aid", "azerbaijani biotech",
        "azerbaijani cancer", "baku medical university",
        "azerbaijani war wounded karabakh",
    ],
    "crime": [
        "azerbaijani corruption", "azerbaijani fraud",
        "azerbaijani scandal", "azerbaijani court",
        "azerbaijani investigation", "azerbaijani organized crime",
        "azerbaijani drug trafficking", "azerbaijani money laundering",
        "azerbaijani terrorism", "azerbaijani police",
        "azerbaijani gang", "azerbaijani anti corruption",
        "azerbaijani smuggling", "azerbaijani human trafficking",
        "azerbaijani election fraud", "azerbaijani protest",
        "baku protest", "azerbaijani opposition arrested",
        "azerbaijani political prisoner",
        "azerbaijani oligarch", "aliyev corruption",
        "azerbaijani journalist arrested",
        "azerbaijani media censorship",
    ],
    "politics": [
        "milli majlis", "azerbaijani parliament",
        "azerbaijani election", "azerbaijani government",
        "azerbaijani minister", "azerbaijani prime minister",
        "azerbaijani coalition", "azerbaijani opposition",
        "yeni azerbaycan", "ilham aliyev", "aliyev",
        "mehriban aliyeva", "ali asadov",
        "azerbaijani policy", "azerbaijani reform",
        "azerbaijani immigration", "azerbaijani diaspora",
        "azerbaijani welfare", "azerbaijani citizenship",
        "azerbaijani referendum", "azerbaijani judiciary",
        "azerbaijani rule of law", "azerbaijani eu relations",
        "azerbaijani democracy", "azerbaijani president",
        "azerbaijani media freedom",
        "azerbaijani press freedom",
        "azerbaijani foreign agents law",
        "azerbaijani nato aspirations",
        "azerbaijani protest movement",
        "cop29 politics baku",
        "azerbaijani elections fraud",
    ],
}
