
# mood/pipeline/keywords/ba.py
BA_KEYWORDS = {
    "finance": [
        "bosnian economy", "bosnia gdp",
        "sarajevo stock exchange", "sase bosnia",
        "central bank bosnia", "cbbh",
        "bosnian mark", "bam",
        "bosnian inflation", "bosnian budget",
        "bosnian exports", "bosnian trade",
        "bosnian market", "bosnian growth",
        "bosnian debt", "bosnian deficit",
        "bosnian unemployment", "bosnian wages",
        "bosnian housing", "bosnian mortgage",
        "bh telecom", "elektroprivreda bih",
        "unicredit bosnia", "raiffeisen bosnia",
        "sparkasse bosnia", "nlb bosnia",
        "bosnian business", "bosnian investment",
        "bosnian tourism", "bosnian manufacturing",
        "bosnian agriculture", "bosnian forestry",
        "bosnian eu funds", "bosnian recovery plan",
        "bosnian pension fund", "bosnian industry",
        "bosnian it sector", "bosnian outsourcing",
        "bosnian diaspora remittances",
    ],
    "geopolitics": [
        "bosnian foreign policy", "bosnia nato",
        "bosnian sanctions", "bosnian diplomacy",
        "bosnian troops", "bosnia ukraine", "bosnia russia",
        "bosnian ambassador", "bosnia eu",
        "bosnian defense", "bosnian military",
        "sarajevo talks", "bosnia security",
        "bosnian intelligence", "osa bosnia",
        "republika srpska", "federation bih",
        "dayton agreement", "dayton peace accord",
        "bosnian eu accession", "western balkans bosnia",
        "bosnia middle east", "bosnian peacekeeping",
        "dodik russia", "republika srpska secession",
        "bosnian war legacy", "srebrenica",
        "bosnian nato bid",
    ],
    "energy": [
        "bosnian energy", "bosnian coal", "bosnian coal power",
        "bosnian electricity", "bosnian renewables",
        "bosnian gas", "bosnian grid", "bosnian solar",
        "bosnian wind", "bosnian hydro",
        "bosnian climate", "bosnian emissions",
        "bosnian energy transition", "bosnian energy prices",
        "bosnian energy security", "bosnian coal phase out",
        "elektroprivreda bih", "zel bosnia",
    ],
    "technology": [
        "bosnian tech", "sarajevo tech", "bosnian startup",
        "bosnian ai", "bosnian fintech", "bosnian digital",
        "bosnian innovation", "bosnian software",
        "bosnian it sector", "bosnian outsourcing",
        "bosnian cybersecurity", "bosnian gaming",
        "mostar tech", "banja luka tech",
    ],
    "health": [
        "bosnian health", "bosnian hospital", "bosnian pharma",
        "bosnian vaccine", "bosnian healthcare",
        "bosnian mental health", "bosnian health system",
        "bosnian medicine", "bosnian public health",
        "bosnian wellbeing", "sarajevo medicine university",
        "bosnian war trauma", "bosnian ptsd",
    ],
    "crime": [
        "bosnian corruption", "bosnian fraud", "bosnian scandal",
        "bosnian court", "bosnian investigation",
        "bosnian organized crime", "bosnian drug trafficking",
        "bosnian money laundering", "bosnian terrorism",
        "bosnian police", "sipa bosnia",
        "bosnian gang", "bosnian mafia",
        "bosnian anti corruption", "bosnian war crimes",
        "icty bosnia", "bosnian genocide",
        "bosnian smuggling", "bosnian human trafficking",
    ],
    "politics": [
        "predstavnicki dom", "dom naroda", "bosnian parliament",
        "bosnian election", "bosnian government",
        "bosnian minister", "bosnian prime minister",
        "bosnian coalition", "bosnian opposition",
        "sda bosnia", "hdz bih", "snsd",
        "milorad dodik", "dodik",
        "bakir izetbegovic", "dragan covic",
        "bosnian policy", "bosnian reform",
        "bosnian immigration", "bosnian diaspora",
        "bosnian welfare", "bosnian citizenship",
        "bosnian referendum", "bosnian judiciary",
        "bosnian rule of law", "bosnian eu relations",
        "bosnian democracy", "bosnian presidency",
        "bosnian constitutional court",
        "bosnian ethnic division", "bosnian federalism",
        "trump strait hormuz bosnia",
    ],
}