
# mood/pipeline/keywords/bb.py
BB_KEYWORDS = {
    "finance": [
        "barbados economy", "barbados gdp",
        "barbados stock exchange", "bse barbados",
        "central bank barbados", "cbb barbados",
        "barbados dollar", "bbd",
        "barbados inflation", "barbados budget",
        "barbados exports", "barbados trade",
        "barbados market", "barbados growth",
        "barbados debt", "barbados deficit",
        "barbados unemployment", "barbados wages",
        "barbados housing", "barbados mortgage",
        "first citizens barbados", "republic bank barbados",
        "scotiabank barbados", "rbtt barbados",
        "barbados tourism", "barbados rum",
        "barbados sugar", "barbados manufacturing",
        "barbados agriculture", "barbados fisheries",
        "barbados eu trade", "barbados us trade",
        "barbados tariffs", "barbados fiscal",
        "barbados pension fund", "barbados industry",
        "barbados startup", "barbados fintech",
        "barbados real estate", "barbados construction",
        "barbados remittances", "barbados diaspora",
        "barbados offshore finance",
        "barbados international business",
    ],
    "geopolitics": [
        "barbados foreign policy", "barbados nato",
        "barbados sanctions", "barbados diplomacy",
        "barbados troops", "barbados ukraine",
        "barbados russia", "barbados ambassador",
        "barbados eu", "barbados defense",
        "barbados military", "bridgetown talks",
        "barbados security", "barbados intelligence",
        "barbados us relations", "barbados caricom",
        "barbados caribbean", "barbados uk relations",
        "barbados republic", "barbados commonwealth",
        "barbados peacekeeping", "barbados un",
        "barbados china relations",
        "mia mottley foreign policy",
        "barbados climate diplomacy",
        "bridgetown initiative",
    ],
    "energy": [
        "barbados energy", "barbados electricity",
        "barbados renewables", "barbados solar",
        "barbados wind", "barbados grid",
        "barbados climate", "barbados emissions",
        "barbados energy transition",
        "barbados energy prices", "barbados energy security",
        "barbados green energy", "barbados carbon neutral",
        "barbados net zero", "barbados fuel prices",
        "barbados climate vulnerability",
        "barbados sea level rise",
        "barbados energy independence",
        "barbados 100 percent renewable",
    ],
    "technology": [
        "barbados tech", "bridgetown tech",
        "barbados startup", "barbados ai",
        "barbados fintech", "barbados digital",
        "barbados innovation", "barbados cybersecurity",
        "barbados software", "barbados it sector",
        "barbados ecommerce", "barbados digital economy",
        "barbados smart city", "barbados medtech",
        "barbados blockchain", "barbados 5g",
        "barbados digital transformation",
        "digicel barbados", "flow barbados",
    ],
    "health": [
        "barbados health", "barbados hospital",
        "barbados pharma", "barbados vaccine",
        "barbados healthcare", "barbados mental health",
        "barbados health system", "barbados medicine",
        "barbados public health", "barbados wellbeing",
        "barbados cancer", "barbados aging population",
        "barbados diabetes", "barbados obesity",
        "queen elizabeth hospital barbados",
        "barbados medical tourism",
        "barbados health ministry",
    ],
    "crime": [
        "barbados corruption", "barbados fraud",
        "barbados scandal", "barbados court",
        "barbados investigation", "barbados organized crime",
        "barbados drug trafficking", "barbados money laundering",
        "barbados terrorism", "barbados police",
        "barbados gang", "barbados anti corruption",
        "barbados cybercrime", "barbados scam",
        "barbados arrest", "barbados human trafficking",
        "barbados protest", "barbados riot",
        "barbados political scandal",
        "christ church south barbados",
    ],
    "politics": [
        "barbados parliament", "barbados election",
        "barbados government", "barbados minister",
        "barbados prime minister", "barbados coalition",
        "barbados opposition", "blp barbados",
        "mia mottley", "mottley barbados",
        "dlp barbados", "barbados policy",
        "barbados reform", "barbados immigration",
        "barbados diaspora", "barbados welfare",
        "barbados citizenship", "barbados referendum",
        "barbados judiciary", "barbados rule of law",
        "barbados democracy", "barbados republic",
        "barbados media freedom", "barbados constitution",
        "barbados caricom chair",
        "barbados climate policy",
        "bridgetown initiative climate",
        "wall of fame barbados",
    ],
}
