
# mood/pipeline/keywords/be.py
BE_KEYWORDS = {
    "finance": [
        "belgian economy", "belgium gdp", "bel20",
        "brussels stock exchange", "euronext brussels",
        "national bank belgium", "belgian inflation",
        "belgian budget", "belgian exports", "belgian trade",
        "belgian market", "belgian growth", "belgian debt",
        "belgian deficit", "belgian unemployment",
        "belgian wages", "belgian housing",
        "kbc bank", "ing belgium", "belfius", "argenta",
        "anheuser busch inbev", "ab inbev", "solvay",
        "ucb pharma", "ageas", "proximus", "bekaert",
        "belgian business", "belgian investment",
        "belgian tourism", "belgian chocolate",
        "belgian diamond", "antwerp diamond",
        "belgian logistics", "port of antwerp",
        "belgian steel", "belgian manufacturing",
    ],
    "geopolitics": [
        "belgian foreign policy", "belgium nato",
        "nato headquarters brussels", "belgian sanctions",
        "belgian diplomacy", "belgian troops",
        "belgium ukraine", "belgium russia",
        "belgian ambassador", "belgium eu",
        "eu headquarters belgium", "belgian defense",
        "belgian military", "brussels talks",
        "belgium middle east", "belgian africa",
        "belgian congo", "belgian colonial",
    ],
    "energy": [
        "belgian energy", "belgian nuclear", "engie belgium",
        "belgian electricity", "belgian renewables",
        "belgian gas", "belgian grid", "belgian wind",
        "belgian offshore wind", "belgian solar",
        "belgian climate", "belgian emissions",
        "belgian energy prices", "belgian energy transition",
        "doel nuclear", "tihange nuclear",
    ],
    "technology": [
        "belgian tech", "brussels tech", "belgian startup",
        "belgian ai", "belgian fintech", "belgian digital",
        "belgian innovation", "belgian unicorn",
        "belgian cybersecurity", "imec belgium",
        "belgian semiconductor", "belgian quantum",
    ],
    "health": [
        "belgian health", "belgian hospital", "belgian pharma",
        "ucb belgium", "belgian vaccine", "belgian healthcare",
        "belgian mental health", "belgian health system",
        "belgian medicine", "sciensano",
    ],
    "crime": [
        "belgian corruption", "belgian fraud", "belgian scandal",
        "belgian court", "belgian investigation",
        "belgian organized crime", "belgian drug trafficking",
        "belgian money laundering", "belgian terrorism",
        "belgian police", "belgian shooting",
        "molenbeek", "belgian extremism",
    ],
    "politics": [
        "belgian parliament", "chambre des representants",
        "kamer van volksvertegenwoordigers",
        "belgian election", "belgian government",
        "belgian minister", "belgian prime minister",
        "belgian coalition", "belgian opposition",
        "wallonia", "flanders", "brussels region",
        "nva", "vlaams belang", "ps belgium", "mr belgium",
        "pvda ptb", "cd v", "open vld",
        "de wever", "bart de wever", "belgian policy",
        "belgian reform", "belgian federalism",
        "belgian language divide", "belgian regionalism",
        "belgian citizenship", "belgian immigration",
    ],
}
