
# mood/pipeline/keywords/bg.py
BG_KEYWORDS = {
    "finance": [
        "bulgarian economy", "bulgaria gdp", "sofix index",
        "sofia stock exchange", "bse bulgaria",
        "bulgarian national bank", "bnb", "bulgarian lev", "bgn",
        "bulgarian inflation", "bulgarian budget",
        "bulgarian exports", "bulgarian trade",
        "bulgarian market", "bulgarian growth",
        "bulgarian debt", "bulgarian deficit",
        "bulgarian unemployment", "bulgarian wages",
        "bulgarian housing", "bulgarian mortgage",
        "lukoil bulgaria", "bulgargaz", "nek bulgaria",
        "fibank", "unicredit bulgaria", "dsk bank",
        "postbank bulgaria", "raiffeisen bulgaria",
        "bulgarian business", "bulgarian investment",
        "bulgarian tourism", "bulgarian manufacturing",
        "bulgarian agriculture", "bulgarian wine",
        "bulgarian eu funds", "bulgarian recovery plan",
        "bulgarian pension fund", "bulgarian industry",
        "bulgarian it sector", "bulgarian outsourcing",
        "bulgarian real estate", "bulgarian construction",
    ],
    "geopolitics": [
        "bulgarian foreign policy", "bulgaria nato",
        "bulgarian sanctions", "bulgarian diplomacy",
        "bulgarian troops", "bulgaria ukraine", "bulgaria russia",
        "bulgarian ambassador", "bulgaria eu",
        "bulgarian defense", "bulgarian military",
        "sofia talks", "bulgaria security",
        "bulgarian intelligence", "dans bulgaria",
        "bulgarian air force", "thracian star",
        "bulgarian nato flank", "bulgarian peacekeeping",
        "bulgaria middle east", "bulgarian eastern policy",
        "bulgaria turkey relations", "bulgarian black sea",
        "bulgaria north macedonia relations",
    ],
    "energy": [
        "bulgarian energy", "bulgarian nuclear", "kozloduy",
        "nuclear bulgaria", "bulgarian electricity",
        "bulgarian renewables", "bulgarian gas",
        "bulgarian grid", "bulgarian solar", "bulgarian wind",
        "bulgarian hydro", "bulgarian climate",
        "bulgarian emissions", "bulgarian energy transition",
        "bulgarian hydrogen", "bulgarian lng",
        "bulgarian energy prices", "russian gas bulgaria",
        "bulgarian energy security", "bulgarian coal",
        "nek energy", "bulgartransgaz",
    ],
    "technology": [
        "bulgarian tech", "sofia tech", "bulgarian startup",
        "bulgarian ai", "bulgarian fintech", "bulgarian digital",
        "bulgarian innovation", "bulgarian unicorn",
        "bulgarian cybersecurity", "bulgarian gaming",
        "bulgarian software", "bulgarian it sector",
        "telerik bulgaria", "progress software",
        "bulgarian semiconductor", "plovdiv tech",
        "bulgarian outsourcing", "bulgarian offshore",
    ],
    "health": [
        "bulgarian health", "bulgarian hospital",
        "bulgarian pharma", "bulgarian vaccine",
        "bulgarian healthcare", "bulgarian mental health",
        "bulgarian health system", "bulgarian medicine",
        "nhif bulgaria", "bulgarian public health",
        "bulgarian wellbeing", "bulgarian medical tourism",
        "sofia medicine university",
    ],
    "crime": [
        "bulgarian corruption", "bulgarian fraud",
        "bulgarian scandal", "bulgarian court",
        "bulgarian investigation", "bulgarian organized crime",
        "bulgarian drug trafficking", "bulgarian money laundering",
        "bulgarian terrorism", "bulgarian police",
        "mvr bulgaria", "bulgarian gang",
        "bulgarian mafia", "bulgarian anti corruption",
        "bulgarian oligarch", "bulgarian fraud scheme",
        "bulgarian smuggling", "bulgarian human trafficking",
    ],
    "politics": [
        "narodno sabranie", "bulgarian parliament",
        "bulgarian election", "bulgarian government",
        "bulgarian minister", "bulgarian prime minister",
        "bulgarian coalition", "bulgarian opposition",
        "gerb", "boyko borisov", "bsp bulgaria",
        "pp db bulgaria", "kiril petkov",
        "ataka bulgaria", "vazrazhdane",
        "bulgarian policy", "bulgarian reform",
        "bulgarian immigration", "bulgarian diaspora",
        "bulgarian welfare", "bulgarian citizenship",
        "bulgarian referendum", "bulgarian judiciary",
        "bulgarian rule of law", "bulgarian eu relations",
        "bulgarian democracy", "bulgarian president",
        "rumen radev", "bulgarian schengen",
        "bulgarian euro adoption",
    ],
}

