
# mood/pipeline/keywords/bh.py
BH_KEYWORDS = {
    "finance": [
        "bahrain economy", "bahrain gdp",
        "bahrain bourse", "bahrain stock exchange",
        "central bank bahrain", "cbb",
        "bahraini dinar", "bhd",
        "bahrain inflation", "bahrain budget",
        "bahrain exports", "bahrain trade",
        "bahrain market", "bahrain growth",
        "bahrain debt", "bahrain deficit",
        "bahrain unemployment", "bahrain wages",
        "bahrain housing", "bahrain mortgage",
        "national bank bahrain", "nbb",
        "gulf international bank", "gib",
        "ahli united bank bahrain",
        "arab banking corporation",
        "alba aluminum bahrain",
        "bapco bahrain", "bahrain petroleum",
        "bahrain investment authority", "mof bahrain",
        "bahrain sovereign wealth fund",
        "bahrain business", "bahrain investment",
        "bahrain tourism", "bahrain manufacturing",
        "bahrain vision 2030", "bahrain diversification",
        "bahrain fintech bay", "bahrain financial hub",
        "bahrain eu trade", "bahrain us trade",
        "bahrain tariffs", "bahrain fiscal",
        "bahrain oil revenue", "bahrain f1 economy",
        "formula 1 bahrain economy",
    ],
    "geopolitics": [
        "bahrain foreign policy", "bahrain nato",
        "bahrain sanctions", "bahrain diplomacy",
        "bahrain troops", "bahrain ukraine",
        "bahrain russia", "bahrain ambassador",
        "bahrain eu", "bahrain defense",
        "bahrain military", "manama talks",
        "bahrain security", "bahrain intelligence",
        "bahrain us relations", "bahrain us base",
        "bahrain fifth fleet", "us navy bahrain",
        "bahrain iran relations", "bahrain israel",
        "bahrain abraham accords",
        "bahrain middle east", "bahrain gulf",
        "bahrain saudi relations", "bahrain gcc",
        "bahrain qatar", "bahrain peacekeeping",
        "bahrain un", "bahrain china relations",
        "bahrain india", "gulf security bahrain",
        "bahrain strait hormuz",
    ],
    "energy": [
        "bahrain energy", "bahrain oil", "bahrain gas",
        "bapco energy", "bahrain electricity",
        "bahrain renewables", "bahrain solar",
        "bahrain grid", "bahrain climate",
        "bahrain emissions", "bahrain energy transition",
        "bahrain hydrogen", "bahrain lng",
        "bahrain energy prices", "bahrain energy security",
        "bahrain green energy", "bahrain carbon neutral",
        "bahrain net zero", "bahrain fuel prices",
        "bahrain oil production", "bahrain refinery",
        "bahrain petrochemical", "bahrain energy 2030",
    ],
    "technology": [
        "bahrain tech", "manama tech", "bahrain startup",
        "bahrain ai", "bahrain fintech", "bahrain digital",
        "bahrain innovation", "bahrain cybersecurity",
        "bahrain software", "bahrain it sector",
        "bahrain ecommerce", "bahrain digital economy",
        "bahrain smart city", "bahrain medtech",
        "bahrain blockchain", "bahrain 5g",
        "bahrain fintech bay", "bahrain cloud",
        "bahrain digital transformation",
        "bahrain vision 2030 tech",
        "batelco bahrain", "zain bahrain",
    ],
    "health": [
        "bahrain health", "bahrain hospital",
        "bahrain pharma", "bahrain vaccine",
        "bahrain healthcare", "bahrain mental health",
        "bahrain health system", "bahrain medicine",
        "bahrain public health", "bahrain wellbeing",
        "bahrain biotech", "bahrain cancer",
        "bahrain aging population",
        "bahrain health ministry", "moh bahrain",
        "bahrain medical tourism",
        "king hamad hospital bahrain",
    ],
    "crime": [
        "bahrain corruption", "bahrain fraud",
        "bahrain scandal", "bahrain court",
        "bahrain investigation", "bahrain organized crime",
        "bahrain drug trafficking", "bahrain money laundering",
        "bahrain terrorism", "bahrain police",
        "bahrain gang", "bahrain anti corruption",
        "bahrain cybercrime", "bahrain scam",
        "bahrain arrest", "bahrain human trafficking",
        "bahrain migrant workers", "bahrain kafala",
        "bahrain political prisoner",
        "bahrain opposition arrested",
        "bahrain protest", "bahrain crackdown",
        "bahrain shia opposition",
    ],
    "politics": [
        "council of representatives bahrain",
        "bahrain parliament", "bahrain election",
        "bahrain government", "bahrain minister",
        "bahrain prime minister", "bahrain king",
        "hamad bin isa", "bahrain royal family",
        "bahrain policy", "bahrain reform",
        "bahrain immigration", "bahrain integration",
        "bahrain welfare", "bahrain citizenship",
        "bahrain judiciary", "bahrain rule of law",
        "bahrain democracy", "bahrain media freedom",
        "bahrain press freedom", "bahrain constitution",
        "bahrain human rights", "bahrain labour reform",
        "bahrain expat population",
        "bahrain shia majority",
        "bahrain sunni government",
        "bahrain political reform",
    ],
}

