
# mood/pipeline/keywords/bo.py
BO_KEYWORDS = {
    "finance": [
        "bolivian economy", "bolivia gdp",
        "bolsa boliviana valores", "bbv bolivia",
        "banco central bolivia", "bcb",
        "bolivian boliviano", "bob",
        "bolivian inflation", "bolivian budget",
        "bolivian exports", "bolivian trade",
        "bolivian market", "bolivian growth",
        "bolivian debt", "bolivian deficit",
        "bolivian unemployment", "bolivian wages",
        "bolivian housing", "bolivian mortgage",
        "banco union bolivia", "banco mercantil",
        "banco bisa", "banco nacional bolivia",
        "ypfb bolivia", "bolivian gas company",
        "bolivian lithium", "yacimientos litifera",
        "bolivian mining", "bolivian silver",
        "bolivian zinc", "bolivian tin",
        "bolivian business", "bolivian investment",
        "bolivian tourism", "bolivian manufacturing",
        "bolivian agriculture", "bolivian quinoa",
        "bolivian soy", "bolivian natural gas",
        "bolivian eu trade", "bolivia us trade",
        "bolivian tariffs", "bolivian fiscal",
        "bolivian pension fund", "bolivian industry",
        "bolivian startup", "bolivian fintech",
        "bolivian real estate", "bolivian remittances",
        "bolivian lithium triangle",
    ],
    "geopolitics": [
        "bolivian foreign policy", "bolivia nato",
        "bolivian sanctions", "bolivian diplomacy",
        "bolivian troops", "bolivia ukraine",
        "bolivia russia", "bolivian ambassador",
        "bolivia eu", "bolivian defense",
        "bolivian military", "la paz talks",
        "bolivia security", "bolivian intelligence",
        "bolivia us relations", "bolivia chile",
        "bolivia peru", "bolivia brazil",
        "bolivia argentina", "bolivia sea access",
        "bolivia pacific access",
        "bolivia chile sea dispute",
        "bolivian peacekeeping", "bolivia un",
        "bolivia brics", "bolivia china",
        "arce foreign policy",
        "bolivian coup attempt",
    ],
    "energy": [
        "bolivian energy", "bolivian gas", "ypfb",
        "bolivian oil", "bolivian electricity",
        "bolivian renewables", "bolivian solar",
        "bolivian wind", "bolivian hydro",
        "bolivian grid", "bolivian climate",
        "bolivian emissions", "bolivian energy transition",
        "bolivian hydrogen", "bolivian lng",
        "bolivian energy prices", "bolivian energy security",
        "bolivian green energy", "bolivian carbon neutral",
        "bolivian net zero", "bolivian fuel prices",
        "bolivian gas exports", "bolivian gas reserves",
        "bolivian lithium battery",
        "bolivian energy crisis",
    ],
    "technology": [
        "bolivian tech", "la paz tech", "bolivian startup",
        "bolivian ai", "bolivian fintech",
        "bolivian digital", "bolivian innovation",
        "bolivian cybersecurity", "bolivian software",
        "bolivian it sector", "bolivian ecommerce",
        "bolivian digital economy", "bolivian 5g",
        "bolivian blockchain", "bolivian smart city",
        "bolivian medtech", "bolivian biotech",
        "bolivian lithium tech",
        "bolivian digital transformation",
        "entel bolivia",
    ],
    "health": [
        "bolivian health", "bolivian hospital",
        "bolivian pharma", "bolivian vaccine",
        "bolivian healthcare", "bolivian mental health",
        "bolivian health system", "bolivian medicine",
        "bolivian public health", "bolivian wellbeing",
        "bolivian biotech", "bolivian cancer",
        "bolivian aging population",
        "bolivian dengue", "bolivian malaria",
        "bolivian chagas disease",
        "bolivian tuberculosis",
        "bolivian indigenous health",
        "bolivian amazon medicine",
    ],
    "crime": [
        "bolivian corruption", "bolivian fraud",
        "bolivian scandal", "bolivian court",
        "bolivian investigation", "bolivian organized crime",
        "bolivian drug trafficking", "bolivian cocaine",
        "bolivian money laundering", "bolivian terrorism",
        "bolivian police", "bolivian gang",
        "bolivian anti corruption",
        "bolivian cybercrime", "bolivian scam",
        "bolivian arrest", "bolivian human trafficking",
        "bolivian protest", "bolivian riot",
        "bolivian political scandal",
        "bolivian coup attempt crime",
        "bolivian illegal mining",
        "bolivian political prisoner",
    ],
    "politics": [
        "asamblea legislativa bolivia",
        "bolivian parliament", "bolivian election",
        "bolivian government", "bolivian minister",
        "bolivian president", "bolivian coalition",
        "bolivian opposition", "mas bolivia",
        "luis arce", "arce bolivia",
        "evo morales", "morales bolivia",
        "bolivian policy", "bolivian reform",
        "bolivian immigration", "bolivian diaspora",
        "bolivian welfare", "bolivian citizenship",
        "bolivian referendum", "bolivian judiciary",
        "bolivian rule of law", "bolivian eu relations",
        "bolivian democracy", "bolivian media freedom",
        "bolivian press freedom", "bolivian constitution",
        "bolivian indigenous rights", "tipnis bolivia",
        "bolivian political crisis",
        "bolivian coup",
        "arce morales rivalry",
        "bolivian political instability",
    ],
}