
# mood/pipeline/keywords/br.py
BR_KEYWORDS = {
    "finance": [
        "brazilian economy", "brazil gdp", "ibovespa",
        "b3 stock exchange", "bovespa",
        "central bank brazil", "bcb",
        "brazilian real", "brl",
        "brazilian inflation", "brazilian budget",
        "brazilian exports", "brazilian trade",
        "brazilian market", "brazilian growth",
        "brazilian debt", "brazilian deficit",
        "brazilian unemployment", "brazilian wages",
        "brazilian housing", "brazilian mortgage",
        "itau unibanco", "bradesco", "banco do brasil",
        "caixa economica", "santander brazil",
        "petrobras", "vale", "embraer",
        "ambev", "jbs", "marfrig",
        "weg industries", "localiza",
        "brazilian business", "brazilian investment",
        "brazilian tourism", "brazilian manufacturing",
        "brazilian automotive", "brazilian agriculture",
        "brazilian soybean", "brazilian beef exports",
        "brazilian coffee", "brazilian sugar",
        "brazilian eu trade", "brazil us trade",
        "brazilian tariffs", "brazilian fiscal",
        "brazilian pension fund", "brazilian industry",
        "brazilian startup", "brazilian unicorn",
        "brazilian fintech", "brazilian real estate",
        "brazilian construction", "brazilian logistics",
        "brazil privatization", "brazil pre sal",
        "brazil oil offshore", "petrobras oil",
    ],
    "geopolitics": [
        "brazilian foreign policy", "brazil nato",
        "brazilian sanctions", "brazilian diplomacy",
        "brazilian troops", "brazil ukraine",
        "brazil russia", "brazilian ambassador",
        "brazil eu", "brazilian defense",
        "brazilian military", "brasilia talks",
        "brazil security", "brazilian intelligence",
        "abin brazil", "brazil us relations",
        "brazil china relations", "brazil iran",
        "brazil israel", "brazil middle east",
        "brazil africa", "brazil brics",
        "brazil g20", "brazil un",
        "brazil mercosur", "brazil argentina",
        "brazil venezuela", "brazil colombia",
        "brazil peacekeeping", "brazil amazon",
        "amazon deforestation geopolitics",
        "brazil china trade", "brazil russia trade",
        "lula foreign policy",
    ],
    "energy": [
        "brazilian energy", "brazilian oil",
        "petrobras energy", "brazilian gas",
        "brazilian electricity", "brazilian renewables",
        "brazilian solar", "brazilian wind",
        "brazilian hydro", "itaipu dam",
        "brazilian grid", "brazilian climate",
        "brazilian emissions", "brazilian energy transition",
        "brazilian hydrogen", "brazilian lng",
        "brazilian energy prices", "brazilian energy security",
        "brazilian green energy", "brazilian biofuel",
        "brazilian ethanol", "brazilian carbon neutral",
        "brazilian net zero", "brazilian fuel prices",
        "pre sal oil brazil", "brazilian offshore",
        "amazon hydroelectric", "brazilian nuclear",
    ],
    "technology": [
        "brazilian tech", "sao paulo tech",
        "brazilian startup", "brazilian ai",
        "brazilian fintech", "nubank brazil",
        "brazilian digital", "brazilian innovation",
        "brazilian unicorn", "brazilian cybersecurity",
        "brazilian gaming", "brazilian software",
        "brazilian it sector", "brazilian ecommerce",
        "mercado livre brazil", "brazilian digital economy",
        "brazilian semiconductor", "brazilian ev",
        "brazilian smart city", "brazilian medtech",
        "brazilian biotech", "brazilian quantum",
        "brazilian space", "aeb brazil",
        "brazilian 5g", "brazilian blockchain",
        "totvs brazil", "cielo brazil",
    ],
    "health": [
        "brazilian health", "brazilian hospital",
        "brazilian pharma", "fiocruz",
        "butantan institute", "brazilian vaccine",
        "brazilian healthcare", "brazilian mental health",
        "brazilian health system", "sus brazil",
        "brazilian medicine", "brazilian public health",
        "brazilian wellbeing", "brazilian biotech",
        "brazilian cancer", "brazilian aging population",
        "brazilian dengue", "brazilian zika",
        "brazilian malaria", "anvisa brazil",
        "brazilian drug approval",
        "brazilian amazon medicine",
    ],
    "crime": [
        "brazilian corruption", "brazilian fraud",
        "brazilian scandal", "brazilian court",
        "brazilian investigation", "brazilian organized crime",
        "pcc brazil", "cv brazil",
        "brazilian drug trafficking", "brazilian money laundering",
        "brazilian terrorism", "brazilian police",
        "brazilian gang", "brazilian anti corruption",
        "lava jato", "brazilian cybercrime",
        "brazilian scam", "brazilian arrest",
        "bolsonaro trial", "bolsonaro coup",
        "brazilian human trafficking",
        "brazilian protest", "brazilian riot",
        "amazon illegal mining",
        "amazon deforestation crime",
        "brazilian political scandal",
    ],
    "politics": [
        "camara dos deputados", "senado federal",
        "brazilian parliament", "brazilian election",
        "brazilian government", "brazilian minister",
        "brazilian president", "brazilian coalition",
        "brazilian opposition", "pt brazil",
        "lula", "luiz inacio lula da silva",
        "bolsonaro", "jair bolsonaro",
        "pl brazil", "psdb brazil",
        "mdb brazil", "brazilian policy",
        "brazilian reform", "brazilian immigration",
        "brazilian diaspora", "brazilian welfare",
        "brazilian citizenship", "brazilian referendum",
        "brazilian judiciary", "stf brazil",
        "brazilian supreme court",
        "brazilian rule of law", "brazilian eu relations",
        "brazilian democracy", "brazilian president",
        "brazilian media freedom", "brazilian press freedom",
        "brazilian constitution", "brazilian federalism",
        "amazon politics", "indigenous rights brazil",
        "bolsonaro coup trial",
    ],
}

