
# mood/pipeline/keywords/ca.py
CA_KEYWORDS = {
    "finance": [
        "canadian economy", "canada gdp", "tsx",
        "toronto stock exchange", "tsx composite",
        "bank of canada", "boc",
        "canadian dollar", "cad",
        "canadian inflation", "canadian budget",
        "canadian exports", "canadian trade",
        "canadian market", "canadian growth",
        "canadian debt", "canadian deficit",
        "canadian unemployment", "canadian wages",
        "canadian housing", "canadian mortgage",
        "royal bank canada", "rbc",
        "td bank", "bmo", "scotiabank",
        "cibc", "national bank canada",
        "shopify", "brookfield", "suncor",
        "canadian natural resources", "cnr",
        "barrick gold", "agnico eagle",
        "canadian business", "canadian investment",
        "canadian tourism", "canadian manufacturing",
        "canadian automotive", "canadian agriculture",
        "canadian wheat", "canadian canola",
        "canadian eu trade", "canada us trade",
        "canadian tariffs", "canadian fiscal",
        "canadian pension fund", "cpp",
        "canadian industry", "canadian startup",
        "canadian unicorn", "canadian fintech",
        "canadian real estate", "canadian construction",
        "canadian oil sands", "alberta oil",
        "canadian lumber", "canadian mining",
    ],
    "geopolitics": [
        "canadian foreign policy", "canada nato",
        "canadian sanctions", "canadian diplomacy",
        "canadian troops", "canada ukraine",
        "canada russia", "canadian ambassador",
        "canada eu", "canadian defense",
        "canadian military", "ottawa talks",
        "canada security", "canadian intelligence",
        "csis canada", "canada us relations",
        "canada china relations", "canada iran",
        "canada israel", "canada middle east",
        "canada arctic", "canadian sovereignty",
        "northwest passage canada",
        "canada india relations",
        "canada peacekeeping", "canada un",
        "canada five eyes", "canada aukus",
        "trump canada tariffs", "canada us trade war",
        "canada 51st state", "canada annexation",
        "canadian sovereignty threat",
    ],
    "energy": [
        "canadian energy", "canadian oil",
        "canadian gas", "canadian electricity",
        "canadian renewables", "canadian solar",
        "canadian wind", "canadian hydro",
        "canadian grid", "canadian climate",
        "canadian emissions", "canadian energy transition",
        "canadian hydrogen", "canadian lng",
        "canadian energy prices", "canadian energy security",
        "canadian green energy", "canadian nuclear",
        "canadian carbon tax", "canadian net zero",
        "canadian fuel prices", "alberta oil sands",
        "trans mountain pipeline", "canadian pipeline",
        "canadian offshore wind", "canadian clean energy",
    ],
    "technology": [
        "canadian tech", "toronto tech", "canadian startup",
        "canadian ai", "canadian fintech",
        "canadian digital", "canadian innovation",
        "canadian unicorn", "canadian cybersecurity",
        "canadian gaming", "canadian software",
        "canadian it sector", "shopify canada",
        "canadian semiconductor", "canadian quantum",
        "canadian space", "csa canada",
        "canadian 5g", "canadian blockchain",
        "canadian medtech", "canadian biotech",
        "waterloo tech", "montreal ai",
        "canadian deep learning",
        "element ai canada",
    ],
    "health": [
        "canadian health", "canadian hospital",
        "canadian pharma", "canadian vaccine",
        "canadian healthcare", "canadian mental health",
        "canadian health system", "canadian medicine",
        "canadian public health", "canadian wellbeing",
        "canadian biotech", "canadian cancer",
        "canadian aging population", "canadian birthrate",
        "health canada", "canadian medicare",
        "canadian universal healthcare",
        "canadian drug approval",
        "canadian opioid crisis",
        "canadian mental health crisis",
    ],
    "crime": [
        "canadian corruption", "canadian fraud",
        "canadian scandal", "canadian court",
        "canadian investigation", "canadian organized crime",
        "canadian drug trafficking", "canadian money laundering",
        "canadian terrorism", "canadian police",
        "rcmp canada", "canadian gang",
        "canadian anti corruption", "canadian cybercrime",
        "canadian scam", "canadian arrest",
        "canadian mafia", "canadian human trafficking",
        "canadian protest", "canadian riot",
        "canadian political scandal",
        "canadian convoy protest",
    ],
    "politics": [
        "house of commons canada", "canadian senate",
        "canadian parliament", "canadian election",
        "canadian government", "canadian minister",
        "canadian prime minister", "canadian coalition",
        "canadian opposition", "liberal party canada",
        "conservative party canada", "ndp canada",
        "bloc quebecois", "green party canada",
        "mark carney", "pierre poilievre",
        "jagmeet singh", "canadian policy",
        "canadian reform", "canadian immigration",
        "canadian integration", "canadian welfare",
        "canadian citizenship", "canadian referendum",
        "canadian judiciary", "canadian rule of law",
        "canadian democracy", "canadian king",
        "canadian governor general", "canadian republic",
        "canadian media freedom", "canadian press freedom",
        "canadian constitution", "canadian federalism",
        "quebec sovereignty", "quebec separation",
        "canadian indigenous", "first nations",
        "canadian reconciliation",
        "poilievre unveils",
        "canadian auto plan",
    ],
}

