
# mood/pipeline/keywords/ci.py
CI_KEYWORDS = {
    "finance": [
        "ivory coast economy", "cote divoire gdp",
        "bourse regionale valeurs mobilieres", "brvm",
        "central bank west africa", "bceao ivory coast",
        "west african franc ivory coast", "xof",
        "ivory coast inflation", "ivory coast budget",
        "ivory coast exports", "ivory coast trade",
        "ivory coast market", "ivory coast growth",
        "ivory coast debt", "ivory coast deficit",
        "ivory coast unemployment", "ivory coast wages",
        "ivory coast housing", "ivory coast mortgage",
        "societe generale ivory coast",
        "ecobank ivory coast", "bicici bank",
        "ivory coast cocoa", "cocoa ivory coast",
        "ivory coast coffee", "ivory coast rubber",
        "ivory coast palm oil", "ivory coast cashew",
        "ivory coast oil", "ivory coast gas",
        "ivory coast business", "ivory coast investment",
        "ivory coast tourism", "ivory coast manufacturing",
        "ivory coast agriculture", "ivory coast fisheries",
        "ivory coast eu trade", "ivory coast us trade",
        "ivory coast tariffs", "ivory coast fiscal",
        "ivory coast pension fund", "ivory coast industry",
        "ivory coast startup", "ivory coast fintech",
        "ivory coast real estate", "ivory coast construction",
        "ivory coast remittances", "ivory coast diaspora",
        "ivory coast imf", "ouattara economic policy",
        "abidjan financial hub",
        "ivory coast bond exchange",
    ],
    "geopolitics": [
        "ivory coast foreign policy", "cote divoire nato",
        "ivory coast sanctions", "ivory coast diplomacy",
        "ivory coast troops", "ivory coast ukraine",
        "ivory coast russia", "ivory coast ambassador",
        "ivory coast eu", "ivory coast defense",
        "ivory coast military", "abidjan talks",
        "ivory coast security", "ivory coast intelligence",
        "ivory coast us relations", "ivory coast china",
        "ivory coast brics", "ivory coast africa union",
        "ivory coast ecowas", "ivory coast peacekeeping",
        "ivory coast un", "ivory coast mali",
        "ivory coast burkina faso", "ivory coast guinea",
        "ivory coast ghana", "ivory coast liberia",
        "ivory coast sahel crisis",
        "ouattara foreign policy",
        "ivory coast france relations",
        "ivory coast west africa stability",
    ],
    "energy": [
        "ivory coast energy", "ivory coast electricity",
        "ivory coast renewables", "ivory coast solar",
        "ivory coast wind", "ivory coast hydro",
        "ivory coast grid", "ivory coast climate",
        "ivory coast emissions", "ivory coast energy transition",
        "ivory coast hydrogen", "ivory coast lng",
        "ivory coast energy prices", "ivory coast energy security",
        "ivory coast green energy", "ivory coast carbon neutral",
        "ivory coast net zero", "ivory coast fuel prices",
        "ivory coast oil", "ivory coast gas",
        "cie ivory coast", "ciprel ivory coast",
        "ivory coast offshore oil",
        "ivory coast energy hub",
        "ivory coast bond exchange obligataire",
    ],
    "technology": [
        "ivory coast tech", "abidjan tech",
        "ivory coast startup", "ivory coast ai",
        "ivory coast fintech", "ivory coast digital",
        "ivory coast innovation", "ivory coast unicorn",
        "ivory coast cybersecurity", "ivory coast gaming",
        "ivory coast software", "ivory coast it sector",
        "ivory coast ecommerce", "ivory coast digital economy",
        "ivory coast 5g", "ivory coast blockchain",
        "ivory coast smart city", "ivory coast medtech",
        "ivory coast digital transformation",
        "orange ivory coast", "mtn ivory coast",
        "ivory coast silicon abidjan",
        "ivory coast tech hub",
    ],
    "health": [
        "ivory coast health", "ivory coast hospital",
        "ivory coast pharma", "ivory coast vaccine",
        "ivory coast healthcare", "ivory coast mental health",
        "ivory coast health system", "ivory coast medicine",
        "ivory coast public health", "ivory coast wellbeing",
        "ivory coast biotech", "ivory coast cancer",
        "ivory coast aging population",
        "ivory coast malaria", "ivory coast tuberculosis",
        "ivory coast hiv", "ivory coast cholera",
        "ivory coast dengue", "ivory coast yellow fever",
        "ivory coast health reform",
        "ivory coast universal health",
        "ivory coast medical tourism",
    ],
    "crime": [
        "ivory coast corruption", "ivory coast fraud",
        "ivory coast scandal", "ivory coast court",
        "ivory coast investigation", "ivory coast organized crime",
        "ivory coast drug trafficking", "ivory coast money laundering",
        "ivory coast terrorism", "ivory coast police",
        "ivory coast gang", "ivory coast anti corruption",
        "ivory coast cybercrime", "ivory coast scam",
        "ivory coast arrest", "ivory coast mafia",
        "ivory coast human trafficking",
        "ivory coast protest", "ivory coast riot",
        "ivory coast political scandal",
        "ivory coast jihadist",
        "ivory coast election violence",
        "ivory coast post election crisis",
        "ivory coast femicide",
    ],
    "politics": [
        "assemblee nationale cote divoire",
        "ivory coast parliament", "ivory coast election",
        "ivory coast government", "ivory coast minister",
        "ivory coast president", "ivory coast coalition",
        "ivory coast opposition", "rhdp ivory coast",
        "alassane ouattara", "ouattara ivory coast",
        "pdci ivory coast", "henri konan bedie",
        "ivory coast policy", "ivory coast reform",
        "ivory coast immigration", "ivory coast diaspora",
        "ivory coast welfare", "ivory coast citizenship",
        "ivory coast referendum", "ivory coast judiciary",
        "ivory coast rule of law", "ivory coast eu relations",
        "ivory coast democracy", "ivory coast media freedom",
        "ivory coast press freedom", "ivory coast constitution",
        "ivory coast federalism", "ivory coast regions",
        "ivory coast political stability",
        "ivory coast 2025 election",
        "ivory coast france decolonization",
        "ivory coast cfa franc",
        "lyon ivory coast football",
    ],
}

