
# mood/pipeline/keywords/cl.py
CL_KEYWORDS = {
    "finance": [
        "chilean economy", "chile gdp", "ipsa index",
        "bolsa santiago", "bcs chile",
        "central bank chile", "bcc",
        "chilean peso", "clp",
        "chilean inflation", "chilean budget",
        "chilean exports", "chilean trade",
        "chilean market", "chilean growth",
        "chilean debt", "chilean deficit",
        "chilean unemployment", "chilean wages",
        "chilean housing", "chilean mortgage",
        "banco estado chile", "banco chile",
        "scotiabank chile", "bci bank",
        "itau chile", "santander chile",
        "codelco", "sqm lithium", "antofagasta minerals",
        "chilean copper", "chilean lithium",
        "chilean mining", "chilean gold",
        "chilean business", "chilean investment",
        "chilean tourism", "chilean manufacturing",
        "chilean agriculture", "chilean wine",
        "chilean salmon", "chilean fruit exports",
        "chilean eu trade", "chile us trade",
        "chilean tariffs", "chilean fiscal",
        "chilean pension fund", "afp chile",
        "chilean industry", "chilean startup",
        "chilean fintech", "chilean real estate",
        "chilean construction", "chilean remittances",
        "chilean lithium triangle",
        "codelco copper production",
    ],
    "geopolitics": [
        "chilean foreign policy", "chile nato",
        "chilean sanctions", "chilean diplomacy",
        "chilean troops", "chile ukraine",
        "chile russia", "chilean ambassador",
        "chile eu", "chilean defense",
        "chilean military", "santiago talks",
        "chile security", "chilean intelligence",
        "chile us relations", "chile argentina",
        "chile peru", "chile bolivia",
        "chile pacific alliance",
        "chile peacekeeping", "chile un",
        "chile brics", "chile g20",
        "boric foreign policy",
        "chile mercosur",
        "chilean border dispute",
        "nicolas zepeda chile france",
    ],
    "energy": [
        "chilean energy", "chilean electricity",
        "chilean renewables", "chilean solar",
        "chilean wind", "chilean hydro",
        "chilean grid", "chilean climate",
        "chilean emissions", "chilean energy transition",
        "chilean hydrogen", "chilean lng",
        "chilean energy prices", "chilean energy security",
        "chilean green energy", "chilean carbon neutral",
        "chilean net zero", "chilean fuel prices",
        "chilean lithium energy", "enap chile",
        "chilean offshore wind",
        "chilean green hydrogen",
        "atacama solar chile",
    ],
    "technology": [
        "chilean tech", "santiago tech", "chilean startup",
        "chilean ai", "chilean fintech",
        "chilean digital", "chilean innovation",
        "chilean unicorn", "chilean cybersecurity",
        "chilean gaming", "chilean software",
        "chilean it sector", "chilean ecommerce",
        "chilean digital economy", "chilean semiconductor",
        "chilean ev", "chilean smart city",
        "chilean medtech", "chilean biotech",
        "chilean quantum", "chilean space",
        "chilean 5g", "chilean blockchain",
        "cornershop chile", "buk chile",
        "chilean lithium tech",
    ],
    "health": [
        "chilean health", "chilean hospital",
        "chilean pharma", "chilean vaccine",
        "chilean healthcare", "chilean mental health",
        "chilean health system", "chilean medicine",
        "chilean public health", "chilean wellbeing",
        "chilean biotech", "chilean cancer",
        "chilean aging population", "chilean birthrate",
        "iss chile", "fonasa chile",
        "chilean drug approval",
        "chilean dengue", "chilean malaria",
        "chilean health reform",
    ],
    "crime": [
        "chilean corruption", "chilean fraud",
        "chilean scandal", "chilean court",
        "chilean investigation", "chilean organized crime",
        "chilean drug trafficking", "chilean money laundering",
        "chilean terrorism", "chilean police",
        "chilean gang", "chilean anti corruption",
        "chilean cybercrime", "chilean scam",
        "chilean arrest", "chilean mafia",
        "chilean human trafficking",
        "chilean protest", "chilean riot",
        "chilean political scandal",
        "chilean femicide",
        "chilean mapuche conflict",
        "nicolas zepeda french justice",
        "chilean araucania violence",
    ],
    "politics": [
        "camara diputados chile", "senado chile",
        "chilean parliament", "chilean election",
        "chilean government", "chilean minister",
        "chilean president", "chilean coalition",
        "chilean opposition", "apruebo dignidad",
        "gabriel boric", "boric chile",
        "partido republicano chile", "jose antonio kast",
        "chilean policy", "chilean reform",
        "chilean immigration", "chilean diaspora",
        "chilean welfare", "chilean citizenship",
        "chilean referendum", "chilean judiciary",
        "chilean rule of law", "chilean eu relations",
        "chilean democracy", "chilean media freedom",
        "chilean press freedom", "chilean constitution",
        "chilean constitutional process",
        "chilean federalism", "chilean regions",
        "chilean indigenous rights",
        "mapuche rights chile",
        "chilean pension reform",
    ],
}

