
# mood/pipeline/keywords/cm.py
CM_KEYWORDS = {
    "finance": [
        "cameroonian economy", "cameroon gdp",
        "douala stock exchange", "dsx cameroon",
        "central bank central africa", "beac",
        "central african franc", "xaf",
        "cameroonian inflation", "cameroonian budget",
        "cameroonian exports", "cameroonian trade",
        "cameroonian market", "cameroonian growth",
        "cameroonian debt", "cameroonian deficit",
        "cameroonian unemployment", "cameroonian wages",
        "cameroonian housing", "cameroonian mortgage",
        "afriland first bank", "bicec cameroon",
        "societe generale cameroon", "ecobank cameroon",
        "cameroonian oil", "cameroonian gas",
        "cameroonian timber", "cameroonian cocoa",
        "cameroonian coffee", "cameroonian cotton",
        "cameroonian rubber", "cameroonian palm oil",
        "cameroonian business", "cameroonian investment",
        "cameroonian tourism", "cameroonian manufacturing",
        "cameroonian agriculture", "cameroonian fisheries",
        "cameroonian eu trade", "cameroon us trade",
        "cameroonian tariffs", "cameroonian fiscal",
        "cameroonian pension fund", "cnps cameroon",
        "cameroonian industry", "cameroonian startup",
        "cameroonian fintech", "cameroonian real estate",
        "cameroonian construction", "cameroonian remittances",
        "cameroonian diaspora", "cameroon imf",
        "biya economic policy",
        "kribi deep sea port",
        "cameroon economic zone",
    ],
    "geopolitics": [
        "cameroonian foreign policy", "cameroon nato",
        "cameroonian sanctions", "cameroonian diplomacy",
        "cameroonian troops", "cameroon ukraine",
        "cameroon russia", "cameroonian ambassador",
        "cameroon eu", "cameroonian defense",
        "cameroonian military", "yaounde talks",
        "cameroon security", "cameroonian intelligence",
        "cameroon us relations", "cameroon china",
        "cameroon brics", "cameroon africa union",
        "cameroon ecowas", "cameroon peacekeeping",
        "cameroon un", "cameroon nigeria",
        "cameroon chad", "cameroon car",
        "cameroon central african republic",
        "cameroon boko haram",
        "biya foreign policy",
        "cameroon france relations",
        "cameroon anglophone crisis",
        "ambazonia cameroon",
        "cameroon separatist conflict",
    ],
    "energy": [
        "cameroonian energy", "cameroonian electricity",
        "cameroonian renewables", "cameroonian solar",
        "cameroonian wind", "cameroonian hydro",
        "cameroonian grid", "cameroonian climate",
        "cameroonian emissions", "cameroonian energy transition",
        "cameroonian hydrogen", "cameroonian lng",
        "cameroonian energy prices", "cameroonian energy security",
        "cameroonian green energy", "cameroonian carbon neutral",
        "cameroonian net zero", "cameroonian fuel prices",
        "cameroonian oil", "cameroonian gas",
        "sonara cameroon", "ael cameroon",
        "cameroonian hydroelectric",
        "lom pangar dam cameroon",
        "memve ele dam cameroon",
        "cameroonian energy crisis",
    ],
    "technology": [
        "cameroonian tech", "yaounde tech", "douala tech",
        "cameroonian startup", "cameroonian ai",
        "cameroonian fintech", "cameroonian digital",
        "cameroonian innovation", "cameroonian cybersecurity",
        "cameroonian software", "cameroonian it sector",
        "cameroonian ecommerce", "cameroonian digital economy",
        "cameroonian 5g", "cameroonian blockchain",
        "cameroonian smart city", "cameroonian medtech",
        "cameroonian digital transformation",
        "mtn cameroon", "orange cameroon",
        "cameroonian silicon valley",
        "cameroonian tech hub",
        "cameroonian internet shutdown",
    ],
    "health": [
        "cameroonian health", "cameroonian hospital",
        "cameroonian pharma", "cameroonian vaccine",
        "cameroonian healthcare", "cameroonian mental health",
        "cameroonian health system", "cameroonian medicine",
        "cameroonian public health", "cameroonian wellbeing",
        "cameroonian biotech", "cameroonian cancer",
        "cameroonian aging population",
        "cameroonian malaria", "cameroonian tuberculosis",
        "cameroonian hiv", "cameroonian cholera",
        "cameroonian mpox", "cameroonian yellow fever",
        "cameroonian health reform",
        "cameroonian universal health",
        "cameroonian medical tourism",
        "cameroonian anglophone health crisis",
    ],
    "crime": [
        "cameroonian corruption", "cameroonian fraud",
        "cameroonian scandal", "cameroonian court",
        "cameroonian investigation", "cameroonian organized crime",
        "cameroonian drug trafficking", "cameroonian money laundering",
        "cameroonian terrorism", "cameroonian police",
        "cameroonian gang", "cameroonian anti corruption",
        "conac cameroon", "cameroonian cybercrime",
        "cameroonian scam", "cameroonian arrest",
        "cameroonian human trafficking",
        "cameroonian protest", "cameroonian riot",
        "cameroonian political scandal",
        "cameroonian boko haram attack",
        "ambazonia fighters cameroon",
        "cameroonian anglophone war crimes",
        "cameroonian femicide",
        "cameroon internet shutdown crime",
    ],
    "politics": [
        "assemblee nationale cameroon",
        "cameroonian parliament", "cameroonian election",
        "cameroonian government", "cameroonian minister",
        "cameroonian president", "cameroonian coalition",
        "cameroonian opposition", "rdpc cameroon",
        "paul biya", "biya cameroon",
        "mrc cameroon", "maurice kamto",
        "cameroonian policy", "cameroonian reform",
        "cameroonian immigration", "cameroonian diaspora",
        "cameroonian welfare", "cameroonian citizenship",
        "cameroonian referendum", "cameroonian judiciary",
        "cameroonian rule of law", "cameroonian eu relations",
        "cameroonian democracy", "cameroonian media freedom",
        "cameroonian press freedom", "cameroonian constitution",
        "cameroonian federalism", "cameroonian regions",
        "cameroonian anglophone crisis",
        "ambazonia politics",
        "cameroon france decolonization",
        "cameroonian political prisoners",
        "cameroon tribune politics",
    ],
}

