

# mood/pipeline/keywords/cn.py
CN_KEYWORDS = {
    "finance": [
        "chinese economy", "china gdp", "shanghai stock exchange",
        "shenzhen stock exchange", "csi 300", "hang seng",
        "peoples bank of china", "pboc", "chinese yuan", "cny", "rmb",
        "chinese inflation", "chinese budget", "chinese exports",
        "chinese trade", "chinese market", "chinese growth",
        "chinese debt", "chinese deficit", "chinese unemployment",
        "chinese wages", "chinese housing", "chinese property",
        "alibaba", "tencent", "baidu", "xiaomi", "huawei",
        "byd", "nio", "geely", "great wall motors",
        "icbc", "bank of china", "ccb", "agricultural bank china",
        "chinese business", "chinese investment",
        "chinese tourism", "chinese manufacturing",
        "chinese real estate", "evergrande", "country garden",
        "chinese eu trade", "china us trade", "chinese tariffs",
        "chinese stimulus", "chinese fiscal policy",
        "chinese pension fund", "chinese sovereign fund",
        "made in china", "chinese belt road",
        "chinese foreign investment", "chinese outbound",
    ],
    "geopolitics": [
        "chinese foreign policy", "china nato", "china us relations",
        "chinese sanctions", "chinese diplomacy",
        "chinese troops", "china ukraine", "china russia",
        "chinese ambassador", "china eu",
        "chinese military", "pla china",
        "beijing talks", "china security",
        "chinese intelligence", "mss china",
        "china taiwan", "taiwan strait",
        "south china sea", "east china sea",
        "china north korea", "china india",
        "chinese belt road initiative", "bri",
        "china middle east", "china africa",
        "chinese peacekeeping", "china un",
        "china quad", "china aukus",
        "chinese wolf warrior diplomacy",
        "xi jinping foreign policy",
        "chinese influence operations",
    ],
    "energy": [
        "chinese energy", "chinese nuclear",
        "chinese electricity", "chinese renewables",
        "chinese solar", "chinese wind", "chinese hydro",
        "chinese grid", "chinese climate",
        "chinese emissions", "chinese energy transition",
        "chinese hydrogen", "chinese lng",
        "chinese energy prices", "chinese energy security",
        "chinese offshore wind", "chinese green energy",
        "chinese coal", "chinese coal phase out",
        "chinese carbon neutral", "chinese net zero",
        "chinese ev battery", "catl china",
        "chinese oil imports", "chinese russian oil",
        "three gorges dam",
    ],
    "technology": [
        "chinese tech", "beijing tech", "chinese startup",
        "chinese ai", "deepseek china", "chinese semiconductor",
        "chinese chip", "chinese digital",
        "chinese innovation", "chinese robotics",
        "chinese ev", "chinese battery", "catl",
        "chinese quantum", "chinese cybersecurity",
        "chinese gaming", "chinese software",
        "chinese unicorn", "chinese fintech",
        "chinese space", "cnsa", "chinese 5g",
        "huawei ban", "tiktok china", "bytedance",
        "chinese tech sanctions", "chip war china",
        "smic china", "chinese surveillance tech",
        "chinese facial recognition",
    ],
    "health": [
        "chinese health", "chinese hospital",
        "chinese pharma", "sinovac", "sinopharm",
        "chinese vaccine", "chinese healthcare",
        "chinese mental health", "chinese health system",
        "chinese medicine", "chinese aging population",
        "chinese public health", "chinese biotech",
        "chinese cancer", "chinese covid policy",
        "chinese epidemic", "chinese outbreak",
        "chinese food safety",
    ],
    "crime": [
        "chinese corruption", "chinese fraud",
        "chinese scandal", "chinese court",
        "chinese investigation", "chinese organized crime",
        "chinese drug trafficking", "chinese money laundering",
        "chinese terrorism", "chinese police",
        "chinese gang", "chinese anti corruption",
        "xi jinping anti corruption",
        "chinese cybercrime", "chinese scam",
        "chinese arrest", "chinese dissident",
        "chinese political prisoner",
        "chinese human rights",
        "uyghur persecution",
        "hong kong crackdown",
        "chinese espionage",
    ],
    "politics": [
        "national peoples congress", "chinese parliament",
        "chinese election", "chinese government",
        "chinese minister", "chinese premier",
        "chinese communist party", "ccp",
        "xi jinping", "li qiang",
        "politburo china", "chinese policy",
        "chinese reform", "chinese censorship",
        "chinese propaganda", "chinese media",
        "chinese freedom", "chinese democracy",
        "chinese human rights", "tiananmen",
        "hong kong politics", "taiwan politics",
        "chinese nationalism", "chinese sovereignty",
        "chinese constitution", "chinese law",
        "chinese media freedom",
        "chinese internet censorship", "great firewall",
    ],
}