
# mood/pipeline/keywords/co.py
CO_KEYWORDS = {
    "finance": [
        "colombian economy", "colombia gdp", "colcap",
        "bolsa valores colombia", "bvc colombia",
        "banco de la republica colombia",
        "colombian peso", "cop",
        "colombian inflation", "colombian budget",
        "colombian exports", "colombian trade",
        "colombian market", "colombian growth",
        "colombian debt", "colombian deficit",
        "colombian unemployment", "colombian wages",
        "colombian housing", "colombian mortgage",
        "bancolombia", "davivienda", "banco bogota",
        "ecopetrol", "grupo nutresa", "grupo sura",
        "avianca", "postobón", "colombian business",
        "colombian investment", "colombian tourism",
        "colombian manufacturing", "colombian agriculture",
        "colombian coffee", "colombian flowers",
        "colombian coal", "colombian oil",
        "colombian eu trade", "colombia us trade",
        "colombian tariffs", "colombian fiscal",
        "colombian pension fund", "colombian industry",
        "colombian startup", "colombian fintech",
        "colombian real estate", "colombian construction",
        "colombian remittances", "colombian diaspora",
    ],
    "geopolitics": [
        "colombian foreign policy", "colombia nato",
        "colombian sanctions", "colombian diplomacy",
        "colombian troops", "colombia ukraine",
        "colombia russia", "colombian ambassador",
        "colombia eu", "colombian defense",
        "colombian military", "bogota talks",
        "colombia security", "colombian intelligence",
        "colombia us relations", "colombia venezuela",
        "colombia ecuador border", "colombia panama",
        "colombia peace process", "farc colombia",
        "eln colombia", "colombian guerrilla",
        "colombia peacekeeping", "colombia un",
        "colombia brics", "colombia g20",
        "gustavo petro foreign policy",
        "delcy rodriguez colombia",
    ],
    "energy": [
        "colombian energy", "colombian oil", "ecopetrol",
        "colombian gas", "colombian electricity",
        "colombian renewables", "colombian solar",
        "colombian wind", "colombian hydro",
        "colombian grid", "colombian climate",
        "colombian emissions", "colombian energy transition",
        "colombian hydrogen", "colombian lng",
        "colombian energy prices", "colombian energy security",
        "colombian green energy", "colombian carbon neutral",
        "colombian net zero", "colombian fuel prices",
        "colombian coal exports", "jungle pipeline colombia",
        "colombian gas pipeline explosion",
    ],
    "technology": [
        "colombian tech", "bogota tech", "colombian startup",
        "colombian ai", "colombian fintech",
        "colombian digital", "colombian innovation",
        "colombian unicorn", "colombian cybersecurity",
        "colombian software", "colombian it sector",
        "colombian ecommerce", "colombian digital economy",
        "rappi colombia", "colombian medtech",
        "colombian biotech", "colombian 5g",
        "colombian blockchain", "colombian smart city",
    ],
    "health": [
        "colombian health", "colombian hospital",
        "colombian pharma", "colombian vaccine",
        "colombian healthcare", "colombian mental health",
        "colombian health system", "colombian medicine",
        "colombian public health", "colombian wellbeing",
        "colombian biotech", "colombian cancer",
        "colombian aging population",
        "colombian dengue", "colombian malaria",
        "invima colombia",
    ],
    "crime": [
        "colombian corruption", "colombian fraud",
        "colombian scandal", "colombian court",
        "colombian investigation", "colombian cartel",
        "sinaloa colombia", "cjng colombia",
        "new junta narcotrafico", "super cartels",
        "colombian drug trafficking", "colombian money laundering",
        "colombian terrorism", "colombian police",
        "colombian gang", "colombian anti corruption",
        "colombian cybercrime", "colombian scam",
        "colombian arrest", "farc crime",
        "eln crime", "colombian human trafficking",
        "colombian protest", "colombian riot",
        "colombian political scandal",
        "sebastian marset colombia",
        "insight crime colombia",
    ],
    "politics": [
        "congreso colombia", "senado colombia",
        "colombian parliament", "colombian election",
        "colombian government", "colombian minister",
        "colombian president", "colombian coalition",
        "colombian opposition", "pacto historico",
        "gustavo petro", "petro colombia",
        "partido conservador colombia",
        "partido liberal colombia",
        "colombian policy", "colombian reform",
        "colombian immigration", "colombian diaspora",
        "colombian welfare", "colombian citizenship",
        "colombian referendum", "colombian judiciary",
        "colombian rule of law", "colombian eu relations",
        "colombian democracy", "colombian media freedom",
        "colombian press freedom", "colombian constitution",
        "colombian peace agreement", "colombian coca",
        "colombian drug policy",
    ],
}
