
# mood/pipeline/keywords/cr.py
CR_KEYWORDS = {
    "finance": [
        "costa rican economy", "costa rica gdp",
        "bolsa nacional valores", "bnv costa rica",
        "central bank costa rica", "bccr",
        "costa rican colon", "crc",
        "costa rican inflation", "costa rican budget",
        "costa rican exports", "costa rican trade",
        "costa rican market", "costa rican growth",
        "costa rican debt", "costa rican deficit",
        "costa rican unemployment", "costa rican wages",
        "costa rican housing", "costa rican mortgage",
        "banco nacional costa rica", "bncr",
        "banco costa rica", "bcr bank",
        "scotiabank costa rica", "bac san jose",
        "intel costa rica", "amazon costa rica",
        "hewlett packard costa rica",
        "costa rican medical devices",
        "costa rican tourism", "costa rican coffee",
        "costa rican pineapple", "costa rican banana",
        "costa rican manufacturing", "costa rican agriculture",
        "costa rican eu trade", "costa rica us trade",
        "costa rican tariffs", "costa rican fiscal",
        "costa rican pension fund", "ccss costa rica",
        "costa rican industry", "costa rican startup",
        "costa rican fintech", "costa rican real estate",
        "costa rican construction", "costa rican remittances",
        "costa rican ecotourism",
        "costa rican free trade zone",
        "felipe pacheco costa rica academy",
    ],
    "geopolitics": [
        "costa rican foreign policy", "costa rica nato",
        "costa rican sanctions", "costa rican diplomacy",
        "costa rican troops", "costa rica ukraine",
        "costa rica russia", "costa rican ambassador",
        "costa rica eu", "costa rican defense",
        "costa rica no military", "san jose talks",
        "costa rica security", "costa rican intelligence",
        "costa rica us relations", "costa rica caricom",
        "costa rica caribbean", "costa rica nicaragua",
        "costa rica panama", "costa rica colombia",
        "costa rican peacekeeping", "costa rica un",
        "costa rica china relations",
        "chaves foreign policy",
        "costa rica central america",
        "costa rica neutrality",
    ],
    "energy": [
        "costa rican energy", "costa rican electricity",
        "costa rican renewables", "costa rican solar",
        "costa rican wind", "costa rican hydro",
        "costa rican geothermal", "costa rican grid",
        "costa rican climate", "costa rican emissions",
        "costa rican energy transition",
        "costa rican energy prices", "costa rican energy security",
        "costa rican green energy", "costa rican carbon neutral",
        "costa rican net zero", "costa rican fuel prices",
        "ict costa rica", "coopelesca",
        "costa rica 100 percent renewable",
        "costa rica clean energy leader",
        "costa rican decarbonization",
    ],
    "technology": [
        "costa rican tech", "san jose tech",
        "costa rican startup", "costa rican ai",
        "costa rican fintech", "costa rican digital",
        "costa rican innovation", "costa rican cybersecurity",
        "costa rican software", "costa rican it sector",
        "costa rican ecommerce", "costa rican digital economy",
        "costa rican semiconductor", "costa rican medtech",
        "costa rican biotech", "costa rican 5g",
        "costa rican blockchain",
        "costa rican digital transformation",
        "intel costa rica chips",
        "costa rican medical device exports",
        "costa rican tech hub",
    ],
    "health": [
        "costa rican health", "costa rican hospital",
        "costa rican pharma", "costa rican vaccine",
        "costa rican healthcare", "costa rican mental health",
        "costa rican health system", "ccss healthcare",
        "costa rican medicine", "costa rican public health",
        "costa rican wellbeing", "costa rican biotech",
        "costa rican cancer", "costa rican aging population",
        "costa rican dengue", "costa rican malaria",
        "costa rican universal healthcare",
        "costa rican health reform",
        "costa rican medical tourism",
    ],
    "crime": [
        "costa rican corruption", "costa rican fraud",
        "costa rican scandal", "costa rican court",
        "costa rican investigation", "costa rican organized crime",
        "costa rican drug trafficking", "costa rican money laundering",
        "costa rican terrorism", "costa rican police",
        "costa rican gang", "costa rican anti corruption",
        "costa rican cybercrime", "costa rican scam",
        "costa rican arrest", "costa rican human trafficking",
        "costa rican protest", "costa rican riot",
        "costa rican political scandal",
        "costa rican femicide",
        "costa rican narco violence",
        "limon costa rica crime",
    ],
    "politics": [
        "asamblea legislativa costa rica",
        "costa rican parliament", "costa rican election",
        "costa rican government", "costa rican minister",
        "costa rican president", "costa rican coalition",
        "costa rican opposition", "pln costa rica",
        "rodrigo chaves", "chaves costa rica",
        "partido liberacion nacional",
        "partido unidad social cristiana",
        "costa rican policy", "costa rican reform",
        "costa rican immigration", "costa rican diaspora",
        "costa rican welfare", "costa rican citizenship",
        "costa rican referendum", "costa rican judiciary",
        "costa rican rule of law", "costa rican eu relations",
        "costa rican democracy", "costa rican media freedom",
        "costa rican press freedom", "costa rican constitution",
        "costa rican federalism",
        "costa rican social democracy",
        "costa rica academy awards",
        "costa rica oscar nomination",
    ],
}

