

# mood/pipeline/keywords/cz.py
CZ_KEYWORDS = {
    "finance": [
        "czech economy", "czech gdp", "px index",
        "prague stock exchange", "pse czech",
        "czech national bank", "cnb", "czech koruna", "czk",
        "czech inflation", "czech budget", "czech exports",
        "czech trade", "czech market", "czech growth",
        "czech debt", "czech deficit", "czech unemployment",
        "czech wages", "czech housing", "czech mortgage",
        "skoda auto", "cez energy", "komercni banka",
        "erste czech", "moneta bank", "kb bank",
        "czech business", "czech investment",
        "czech tourism", "czech manufacturing",
        "czech automotive", "czech aerospace",
        "czech agriculture", "czech beer",
        "czech eu funds", "czech recovery plan",
        "czech pension fund", "czech industry",
    ],
    "geopolitics": [
        "czech foreign policy", "czech nato",
        "czech sanctions", "czech diplomacy",
        "czech troops", "czech ukraine", "czech russia",
        "czech ambassador", "czech eu",
        "czech defense", "czech military",
        "prague talks", "czech security",
        "czech intelligence", "bis czech",
        "czech arms exports", "czech weapons",
        "czech helicopter", "czech military aid",
        "czech middle east", "czech peacekeeping",
        "czech russia relations", "czech eastern policy",
    ],
    "energy": [
        "czech energy", "czech nuclear", "dukovany",
        "temelin nuclear", "cez energy",
        "czech electricity", "czech renewables",
        "czech gas", "czech grid", "czech coal",
        "czech climate", "czech emissions",
        "czech energy transition", "czech hydrogen",
        "czech lng", "czech energy prices",
        "russian gas czech", "czech energy security",
        "czech solar", "czech wind",
        "czech coal phase out",
    ],
    "technology": [
        "czech tech", "prague tech", "czech startup",
        "czech ai", "czech fintech", "czech digital",
        "czech innovation", "czech unicorn",
        "czech cybersecurity", "czech gaming",
        "czech software", "czech it sector",
        "avast czech", "jetbrains czech",
        "czech semiconductor", "brno tech",
    ],
    "health": [
        "czech health", "czech hospital", "czech pharma",
        "czech vaccine", "czech healthcare",
        "czech mental health", "czech health system",
        "czech medicine", "vzp czech",
        "czech public health", "czech wellbeing",
        "czech spa", "czech thermal",
    ],
    "crime": [
        "czech corruption", "czech fraud", "czech scandal",
        "czech court", "czech investigation",
        "czech organized crime", "czech drug trafficking",
        "czech money laundering", "czech terrorism",
        "czech police", "policie cr",
        "czech gang", "czech mafia",
        "czech anti corruption", "ncoz czech",
        "czech helicopter parts russia",
    ],
    "politics": [
        "poslanecka snemovna", "senat czech",
        "czech parliament", "czech election",
        "czech government", "czech minister",
        "czech prime minister", "czech coalition",
        "czech opposition", "ods czech",
        "ano czech", "babis", "andrej babis",
        "petr fiala", "spolu coalition",
        "pirati czech", "stan czech",
        "czech policy", "czech reform",
        "czech immigration", "czech integration",
        "czech welfare", "czech citizenship",
        "czech referendum", "czech judiciary",
        "czech rule of law", "czech eu relations",
        "czech democracy", "czech president",
        "petr pavel",
    ],
}