
# mood/pipeline/keywords/dk.py
DK_KEYWORDS = {
    "finance": [
        "danish economy", "denmark gdp", "omx copenhagen",
        "copenhagen stock exchange", "nasdaq copenhagen",
        "danmarks nationalbank", "danish krone", "dkk",
        "danish inflation", "danish budget", "danish exports",
        "danish trade", "danish market", "danish growth",
        "danish debt", "danish surplus", "danish unemployment",
        "danish wages", "danish housing", "danish mortgage",
        "novo nordisk", "ozempic denmark", "wegovy denmark",
        "maersk", "vestas", "coloplast", "demant",
        "gn audio", "pandora", "chr hansen",
        "danske bank", "jyske bank", "sydbank",
        "danish business", "danish investment",
        "danish tourism", "danish agriculture",
        "danish shipping", "danish manufacturing",
        "danish pension fund", "atp denmark",
        "copenhagen airport", "danish airline", "sas denmark",
        "danish profit", "danish revenue",
        "danish fuel", "danish oil reserves",
        "danish childcare fees", "danish cost",
    ],
    "geopolitics": [
        "danish foreign policy", "denmark nato",
        "danish sanctions", "danish diplomacy",
        "danish troops", "denmark ukraine", "denmark russia",
        "danish ambassador", "denmark eu",
        "danish defense", "danish military",
        "copenhagen talks", "denmark arctic",
        "greenland", "faroe islands", "danish territories",
        "denmark middle east", "danish peacekeeping",
        "denmark arms", "denmark israel",
        "war affecting denmark", "denmark conflict",
    ],
    "energy": [
        "danish energy", "danish wind", "danish offshore wind",
        "orsted", "danish electricity", "danish renewables",
        "danish solar", "danish grid", "danish hydro",
        "danish climate", "danish emissions",
        "danish energy transition", "danish hydrogen",
        "danish energy taxes", "energy bills denmark",
        "danish green energy", "danish net zero",
    ],
    "technology": [
        "danish tech", "copenhagen tech", "danish startup",
        "danish ai", "danish fintech", "danish digital",
        "danish innovation", "danish unicorn",
        "danish cybersecurity", "danish medtech",
        "lego digital", "danish gaming",
        "danish robotics", "universal robots",
    ],
    "health": [
        "danish health", "danish hospital", "danish pharma",
        "novo nordisk denmark", "danish vaccine",
        "danish healthcare", "danish mental health",
        "danish health system", "danish medicine",
        "danish wellbeing", "danish happiness",
        "danish cold water swimming",
    ],
    "crime": [
        "danish corruption", "danish fraud", "danish scandal",
        "danish court", "danish high court", "danish supreme court",
        "danish investigation", "danish organized crime",
        "danish gang", "danish drug trafficking",
        "danish money laundering", "danish terrorism",
        "danish police", "danish shooting",
        "danish gang violence", "danish arms sales",
    ],
    "politics": [
        "folketing", "danish parliament", "danish election",
        "danish government", "danish minister",
        "danish prime minister", "danish coalition",
        "danish opposition", "social democrats denmark",
        "danish peoples party", "venstre denmark",
        "mette frederiksen", "jakob ellemann",
        "danish policy", "danish reform",
        "danish citizenship", "danish immigration",
        "danish integration", "danish welfare",
        "danish model", "danish referendum",
        "danish citizenship freeze", "danish crackdown",
        "danish residency", "danish election citizenship",
        "european citizenship rules", "brexit residency denmark",
    ],
}
