
# mood/pipeline/keywords/do.py
DO_KEYWORDS = {
    "finance": [
        "dominican economy", "dominican republic gdp",
        "bolsa valores dominicana", "bvrd",
        "central bank dominican", "bcrd",
        "dominican peso", "dop",
        "dominican inflation", "dominican budget",
        "dominican exports", "dominican trade",
        "dominican market", "dominican growth",
        "dominican debt", "dominican deficit",
        "dominican unemployment", "dominican wages",
        "dominican housing", "dominican mortgage",
        "banreservas", "banco popular dominicano",
        "scotiabank dominicana", "banco bhd",
        "dominican tourism", "dominican rum",
        "dominican cigars", "dominican coffee",
        "dominican cacao", "dominican sugar",
        "dominican manufacturing", "dominican free zones",
        "dominican agriculture", "dominican avocado",
        "dominican eu trade", "dominican us trade",
        "dominican tariffs", "dominican fiscal",
        "dominican pension fund", "dominican industry",
        "dominican startup", "dominican fintech",
        "dominican real estate", "dominican construction",
        "dominican remittances", "dominican diaspora",
        "dominican republic world baseball classic",
    ],
    "geopolitics": [
        "dominican foreign policy", "dominican republic nato",
        "dominican sanctions", "dominican diplomacy",
        "dominican troops", "dominican ukraine",
        "dominican russia", "dominican ambassador",
        "dominican eu", "dominican defense",
        "dominican military", "santo domingo talks",
        "dominican security", "dominican intelligence",
        "dominican us relations", "dominican caricom",
        "dominican caribbean", "dominican haiti",
        "dominican haiti border", "dominican migration",
        "dominican republic haiti conflict",
        "dominican peacekeeping", "dominican un",
        "dominican china relations",
        "abinader foreign policy",
        "dominican republic border wall",
    ],
    "energy": [
        "dominican energy", "dominican electricity",
        "dominican renewables", "dominican solar",
        "dominican wind", "dominican grid",
        "dominican climate", "dominican emissions",
        "dominican energy transition",
        "dominican energy prices", "dominican energy security",
        "dominican green energy", "dominican carbon neutral",
        "dominican net zero", "dominican fuel prices",
        "dominican lng", "dominican natural gas",
        "dominican energy independence",
        "dominican climate vulnerability",
        "ede norte dominicana",
    ],
    "technology": [
        "dominican tech", "santo domingo tech",
        "dominican startup", "dominican ai",
        "dominican fintech", "dominican digital",
        "dominican innovation", "dominican cybersecurity",
        "dominican software", "dominican it sector",
        "dominican ecommerce", "dominican digital economy",
        "dominican smart city", "dominican medtech",
        "dominican blockchain", "dominican 5g",
        "dominican digital transformation",
        "claro dominicana", "altice dominicana",
        "dominican digital hub",
    ],
    "health": [
        "dominican health", "dominican hospital",
        "dominican pharma", "dominican vaccine",
        "dominican healthcare", "dominican mental health",
        "dominican health system", "dominican medicine",
        "dominican public health", "dominican wellbeing",
        "dominican cancer", "dominican aging population",
        "dominican diabetes", "dominican obesity",
        "dominican dengue", "dominican malaria",
        "dominican health ministry",
        "dominican medical tourism",
        "dominican cholera threat",
    ],
    "crime": [
        "dominican corruption", "dominican fraud",
        "dominican scandal", "dominican court",
        "dominican investigation", "dominican organized crime",
        "dominican drug trafficking", "dominican money laundering",
        "dominican terrorism", "dominican police",
        "dominican gang", "dominican anti corruption",
        "dominican cybercrime", "dominican scam",
        "dominican arrest", "dominican mafia",
        "dominican human trafficking",
        "dominican protest", "dominican riot",
        "dominican political scandal",
        "dominican femicide",
        "dominican haitian crime",
        "dominican deportation",
    ],
    "politics": [
        "congreso dominicano", "senado dominicano",
        "dominican parliament", "dominican election",
        "dominican government", "dominican minister",
        "dominican president", "dominican coalition",
        "dominican opposition", "pld dominicana",
        "luis abinader", "abinader",
        "leonel fernandez", "fuerza del pueblo",
        "dominican policy", "dominican reform",
        "dominican immigration", "dominican diaspora",
        "dominican welfare", "dominican citizenship",
        "dominican referendum", "dominican judiciary",
        "dominican rule of law", "dominican eu relations",
        "dominican democracy", "dominican media freedom",
        "dominican press freedom", "dominican constitution",
        "dominican haitian relations",
        "dominican border policy",
        "dominican republic baseball politics",
    ],
}




