
# mood/pipeline/keywords/ec.py
EC_KEYWORDS = {
    "finance": [
        "ecuadorian economy", "ecuador gdp",
        "bolsa valores quito", "bvq ecuador",
        "banco central ecuador", "bce",
        "ecuadorian dollar", "usd ecuador",
        "ecuadorian inflation", "ecuadorian budget",
        "ecuadorian exports", "ecuadorian trade",
        "ecuadorian market", "ecuadorian growth",
        "ecuadorian debt", "ecuadorian deficit",
        "ecuadorian unemployment", "ecuadorian wages",
        "ecuadorian housing", "ecuadorian mortgage",
        "banco pichincha", "banco guayaquil",
        "banco pacifico ecuador", "produbanco",
        "petroecuador", "andes petroleum",
        "ecuadorian mining", "ecuadorian copper",
        "ecuadorian gold", "corriente resources",
        "ecuadorian business", "ecuadorian investment",
        "ecuadorian tourism", "ecuadorian manufacturing",
        "ecuadorian agriculture", "ecuadorian banana",
        "ecuadorian shrimp", "ecuadorian roses",
        "ecuadorian cacao", "ecuadorian oil",
        "ecuadorian eu trade", "ecuador us trade",
        "ecuadorian tariffs", "ecuadorian fiscal",
        "ecuadorian pension fund", "iess ecuador",
        "ecuadorian industry", "ecuadorian startup",
        "ecuadorian fintech", "ecuadorian real estate",
        "ecuadorian remittances", "ecuadorian diaspora",
        "cristian espinosa ambassador ecuador",
    ],
    "geopolitics": [
        "ecuadorian foreign policy", "ecuador nato",
        "ecuadorian sanctions", "ecuadorian diplomacy",
        "ecuadorian troops", "ecuador ukraine",
        "ecuador russia", "ecuadorian ambassador",
        "ecuador eu", "ecuadorian defense",
        "ecuadorian military", "quito talks",
        "ecuador security", "ecuadorian intelligence",
        "ecuador us relations", "ecuador colombia",
        "ecuador peru", "ecuador venezuela",
        "ecuador mexico embassy",
        "ecuador assange", "julian assange ecuador",
        "ecuador peacekeeping", "ecuador un",
        "ecuador pacific alliance",
        "ecuador brics",
        "noboa foreign policy",
        "ecuador stormed embassy",
    ],
    "energy": [
        "ecuadorian energy", "ecuadorian oil",
        "petroecuador oil", "ecuadorian gas",
        "ecuadorian electricity", "ecuadorian renewables",
        "ecuadorian solar", "ecuadorian wind",
        "ecuadorian hydro", "ecuadorian grid",
        "ecuadorian climate", "ecuadorian emissions",
        "ecuadorian energy transition", "ecuadorian hydrogen",
        "ecuadorian energy prices", "ecuadorian energy security",
        "ecuadorian green energy", "ecuadorian carbon neutral",
        "ecuadorian net zero", "ecuadorian fuel prices",
        "ecuadorian oil production", "ecuadorian refinery",
        "ecuadorian petrochemical",
        "amazon oil ecuador",
        "yasuni oil ecuador",
    ],
    "technology": [
        "ecuadorian tech", "quito tech", "ecuadorian startup",
        "ecuadorian ai", "ecuadorian fintech",
        "ecuadorian digital", "ecuadorian innovation",
        "ecuadorian cybersecurity", "ecuadorian software",
        "ecuadorian it sector", "ecuadorian ecommerce",
        "ecuadorian digital economy", "ecuadorian 5g",
        "ecuadorian blockchain", "ecuadorian smart city",
        "ecuadorian medtech", "ecuadorian biotech",
        "ecuadorian digital transformation",
        "ecuadorian galapagos tech",
    ],
    "health": [
        "ecuadorian health", "ecuadorian hospital",
        "ecuadorian pharma", "ecuadorian vaccine",
        "ecuadorian healthcare", "ecuadorian mental health",
        "ecuadorian health system", "ecuadorian medicine",
        "ecuadorian public health", "ecuadorian wellbeing",
        "ecuadorian biotech", "ecuadorian cancer",
        "ecuadorian aging population",
        "ecuadorian dengue", "ecuadorian malaria",
        "arcsa ecuador",
        "ecuadorian amazon medicine",
        "ecuadorian indigenous health",
    ],
    "crime": [
        "ecuadorian corruption", "ecuadorian fraud",
        "ecuadorian scandal", "ecuadorian court",
        "ecuadorian investigation", "ecuadorian organized crime",
        "ecuadorian drug trafficking", "ecuadorian money laundering",
        "ecuadorian terrorism", "ecuadorian police",
        "ecuadorian gang", "ecuadorian anti corruption",
        "ecuadorian cybercrime", "ecuadorian scam",
        "ecuadorian arrest", "ecuadorian mafia",
        "ecuadorian human trafficking",
        "ecuadorian femicide", "ecuador violence",
        "ecuadorian protest", "ecuadorian riot",
        "ecuadorian political scandal",
        "ecuador prison massacre",
        "ecuador gang violence",
        "ecuador security crisis",
        "noboa security policy",
    ],
    "politics": [
        "asamblea nacional ecuador",
        "ecuadorian parliament", "ecuadorian election",
        "ecuadorian government", "ecuadorian minister",
        "ecuadorian president", "ecuadorian coalition",
        "ecuadorian opposition", "accion democratica nacional",
        "daniel noboa", "noboa",
        "rafael correa", "movimiento revolucion ciudadana",
        "ecuadorian policy", "ecuadorian reform",
        "ecuadorian immigration", "ecuadorian diaspora",
        "ecuadorian welfare", "ecuadorian citizenship",
        "ecuadorian referendum", "ecuadorian judiciary",
        "ecuadorian rule of law", "ecuadorian eu relations",
        "ecuadorian democracy", "ecuadorian media freedom",
        "ecuadorian press freedom", "ecuadorian constitution",
        "ecuadorian indigenous rights", "conaie ecuador",
        "ecuadorian political crisis",
        "ecuador ambassador appointed",
    ],
}

