
# mood/pipeline/keywords/ee.py
EE_KEYWORDS = {
    "finance": [
        "estonian economy", "estonia gdp", "omx tallinn",
        "tallinn stock exchange", "nasdaq tallinn",
        "bank of estonia", "eesti pank",
        "estonian euro", "estonian inflation",
        "estonian budget", "estonian exports",
        "estonian trade", "estonian market",
        "estonian growth", "estonian debt",
        "estonian deficit", "estonian unemployment",
        "estonian wages", "estonian housing",
        "estonian mortgage", "luminor estonia",
        "lhv bank", "swedbank estonia", "seb estonia",
        "coop pank", "bigbank estonia",
        "estonian business", "estonian investment",
        "estonian tourism", "estonian manufacturing",
        "estonian logistics", "estonian agriculture",
        "estonian eu funds", "estonian recovery plan",
        "estonian pension fund", "estonian industry",
        "estonian it sector", "estonian startup",
        "transferwise estonia", "wise estonia",
        "bolt estonia", "pipedrive", "starship technologies",
        "estonian unicorn", "estonian tech revenue",
        "tallinn port", "estonian shipping",
    ],
    "geopolitics": [
        "estonian foreign policy", "estonia nato",
        "estonian sanctions", "estonian diplomacy",
        "estonian troops", "estonia ukraine", "estonia russia",
        "estonian ambassador", "estonia eu",
        "estonian defense", "estonian military",
        "tallinn talks", "estonia security",
        "estonian intelligence", "kapo estonia",
        "estonian foreign intelligence", "valisluureamet",
        "estonia russia border", "narva bridge",
        "estonian nato membership", "estonian security policy",
        "estonia middle east", "estonian peacekeeping",
        "estonian independence", "russian minority estonia",
        "estonian osce chairmanship", "nb8 estonia",
    ],
    "energy": [
        "estonian energy", "estonian oil shale",
        "estonian electricity", "estonian renewables",
        "estonian wind", "estonian solar", "estonian grid",
        "estonian climate", "estonian emissions",
        "estonian energy transition", "estonian hydrogen",
        "estonian lng", "estlink cable",
        "estonian energy security", "estonian energy prices",
        "estonian offshore wind", "estonian green energy",
        "eesti energia", "elering estonia",
        "estonian biomass", "estonian district heating",
    ],
    "technology": [
        "estonian tech", "tallinn tech", "estonian startup",
        "estonian ai", "estonian fintech", "e-estonia",
        "estonian digital", "estonian innovation",
        "estonian unicorn", "estonian cybersecurity",
        "estonian gaming", "estonian software",
        "estonian it sector", "estonian outsourcing",
        "transferwise", "wise fintech", "bolt",
        "pipedrive", "skype estonia", "nortal",
        "estonian semiconductor", "tartu tech",
        "estonian quantum", "estonian blockchain",
        "x-road estonia", "estonian digital identity",
        "estonian e-residency",
    ],
    "health": [
        "estonian health", "estonian hospital",
        "estonian pharma", "estonian vaccine",
        "estonian healthcare", "estonian mental health",
        "estonian health system", "estonian medicine",
        "estonian health insurance", "haigekassa",
        "estonian public health", "estonian wellbeing",
        "tartu university hospital", "north estonia medical",
        "estonian genetics", "estonian biobank",
    ],
    "crime": [
        "estonian corruption", "estonian fraud",
        "estonian scandal", "estonian court",
        "estonian investigation", "estonian organized crime",
        "estonian drug trafficking", "estonian money laundering",
        "estonian terrorism", "estonian police",
        "politsei estonia", "estonian gang",
        "estonian anti corruption", "estonian kapo",
        "estonian smuggling", "estonian cybercrime",
        "estonian scam", "estonian banking fraud",
    ],
    "politics": [
        "riigikogu", "estonian parliament",
        "estonian election", "estonian government",
        "estonian minister", "estonian prime minister",
        "estonian coalition", "estonian opposition",
        "reform party estonia", "eesti 200",
        "social democrats estonia", "isamaa",
        "ekre estonia", "keskerakond",
        "kaja kallas", "kristen michal",
        "alar karis", "estonian policy",
        "estonian reform", "estonian immigration",
        "estonian integration", "estonian welfare",
        "estonian citizenship", "estonian referendum",
        "estonian judiciary", "estonian rule of law",
        "estonian eu relations", "estonian democracy",
        "estonian president", "estonian media freedom",
        "russian speaking minority estonia",
        "estonian language policy",
    ],
}

