
# mood/pipeline/keywords/eg.py
EG_KEYWORDS = {
    "finance": [
        "egyptian economy", "egypt gdp", "egx30",
        "egyptian stock exchange", "egx",
        "central bank egypt", "cbe",
        "egyptian pound", "egp",
        "egyptian inflation", "egyptian budget",
        "egyptian exports", "egyptian trade",
        "egyptian market", "egyptian growth",
        "egyptian debt", "egyptian deficit",
        "egyptian unemployment", "egyptian wages",
        "egyptian housing", "egyptian mortgage",
        "national bank egypt", "cib egypt",
        "banque misr", "qnb egypt",
        "suez canal revenue", "egyptian tourism",
        "egyptian manufacturing", "egyptian agriculture",
        "egyptian cotton", "egyptian gas",
        "egyptian eu trade", "egypt us trade",
        "egyptian tariffs", "egyptian fiscal",
        "egyptian pension fund", "egyptian industry",
        "egyptian startup", "egyptian fintech",
        "egyptian real estate", "egyptian construction",
        "egyptian remittances", "egyptian diaspora",
        "egypt imf deal", "egyptian debt crisis",
        "sisi economic policy",
        "ras el hekma egypt",
    ],
    "geopolitics": [
        "egyptian foreign policy", "egypt nato",
        "egyptian sanctions", "egyptian diplomacy",
        "egyptian troops", "egypt ukraine",
        "egypt russia", "egyptian ambassador",
        "egypt eu", "egyptian defense",
        "egyptian military", "cairo talks",
        "egypt security", "egyptian intelligence",
        "gis egypt", "egypt us relations",
        "egypt china relations", "egypt brics",
        "egypt africa union", "egypt arab league",
        "egypt peacekeeping", "egypt un",
        "egypt israel", "egypt gaza",
        "egypt hamas mediation", "egypt ceasefire",
        "egypt sudan conflict", "egypt ethiopia",
        "egypt grand renaissance dam",
        "egypt nile dispute", "egypt libya",
        "egypt saudi relations",
        "sisi foreign policy",
        "suez canal geopolitics",
        "egypt iran war",
    ],
    "energy": [
        "egyptian energy", "egyptian gas",
        "zohr gas field", "egyptian electricity",
        "egyptian renewables", "egyptian solar",
        "egyptian wind", "egyptian hydro",
        "egyptian grid", "egyptian climate",
        "egyptian emissions", "egyptian energy transition",
        "egyptian hydrogen", "egyptian lng",
        "egyptian energy prices", "egyptian energy security",
        "egyptian green energy", "egyptian carbon neutral",
        "egyptian net zero", "egyptian fuel prices",
        "egyptian oil", "egyptian refinery",
        "benban solar egypt",
        "egypt green hydrogen",
        "egypt energy hub",
        "east med gas egypt",
    ],
    "technology": [
        "egyptian tech", "cairo tech", "egyptian startup",
        "egyptian ai", "egyptian fintech",
        "egyptian digital", "egyptian innovation",
        "egyptian unicorn", "egyptian cybersecurity",
        "egyptian gaming", "egyptian software",
        "egyptian it sector", "egyptian ecommerce",
        "egyptian digital economy", "egyptian semiconductor",
        "egyptian ev", "egyptian smart city",
        "egyptian medtech", "egyptian biotech",
        "egyptian 5g", "egyptian blockchain",
        "fawry egypt", "paymob egypt",
        "egyptian silicon valley",
        "smart village cairo",
        "egypt digital transformation",
    ],
    "health": [
        "egyptian health", "egyptian hospital",
        "egyptian pharma", "egyptian vaccine",
        "egyptian healthcare", "egyptian mental health",
        "egyptian health system", "egyptian medicine",
        "egyptian public health", "egyptian wellbeing",
        "egyptian biotech", "egyptian cancer",
        "egyptian aging population",
        "egyptian hepatitis c",
        "egyptian schistosomiasis",
        "egyptian health reform",
        "universal health insurance egypt",
        "egyptian medical tourism",
    ],
    "crime": [
        "egyptian corruption", "egyptian fraud",
        "egyptian scandal", "egyptian court",
        "egyptian investigation", "egyptian organized crime",
        "egyptian drug trafficking", "egyptian money laundering",
        "egyptian terrorism", "egyptian police",
        "egyptian gang", "egyptian anti corruption",
        "egyptian cybercrime", "egyptian scam",
        "egyptian arrest", "egyptian mafia",
        "egyptian human trafficking",
        "egyptian protest", "egyptian riot",
        "egyptian political prisoner",
        "egyptian dissident",
        "egyptian journalist arrested",
        "muslim brotherhood egypt",
        "egyptian femicide",
    ],
    "politics": [
        "peoples assembly egypt", "egyptian parliament",
        "egyptian election", "egyptian government",
        "egyptian minister", "egyptian president",
        "egyptian coalition", "egyptian opposition",
        "abdel fattah el sisi", "sisi egypt",
        "ndc egypt", "egyptian national dialogue",
        "egyptian policy", "egyptian reform",
        "egyptian immigration", "egyptian diaspora",
        "egyptian welfare", "egyptian citizenship",
        "egyptian referendum", "egyptian judiciary",
        "egyptian rule of law", "egyptian eu relations",
        "egyptian democracy", "egyptian media freedom",
        "egyptian press freedom", "egyptian constitution",
        "egyptian federalism", "egyptian provinces",
        "egyptian military council",
        "egyptian political reform",
        "suez canal politics",
        "formula 1 egypt bahrain",
    ],
}