
# mood/pipeline/keywords/es.py
ES_KEYWORDS = {
    "finance": [
        "spanish economy", "spain gdp", "ibex 35", "ibex35",
        "madrid stock exchange", "bolsa madrid",
        "bank of spain", "banco de espana",
        "spanish euro", "spanish inflation",
        "spanish budget", "spanish exports",
        "spanish trade", "spanish market",
        "spanish growth", "spanish debt",
        "spanish deficit", "spanish unemployment",
        "spanish wages", "spanish housing",
        "spanish mortgage", "santander spain",
        "bbva", "caixabank", "sabadell",
        "bankinter", "mapfre",
        "inditex", "zara", "mango",
        "telefonica", "repsol", "iberdrola",
        "ferrovial", "acs group", "acciona",
        "spanish business", "spanish investment",
        "spanish tourism", "spanish manufacturing",
        "spanish automotive", "spanish agriculture",
        "spanish eu funds", "spanish recovery plan",
        "spanish pension fund", "spanish industry",
        "spanish fashion", "spanish food exports",
        "spanish real estate", "spanish construction",
        "spanish fuel", "fuel prices spain",
        "spain economy minister", "spanish benefit",
        "spain child benefit", "spanish fuel prices",
        "spain iran war energy",
    ],
    "geopolitics": [
        "spanish foreign policy", "spain nato",
        "spanish sanctions", "spanish diplomacy",
        "spanish troops", "spain ukraine", "spain russia",
        "spanish ambassador", "spain eu",
        "spanish defense", "spanish military",
        "madrid talks", "spain security",
        "spanish intelligence", "cni spain",
        "spain middle east", "spanish peacekeeping",
        "spain morocco", "spain africa",
        "spain latin america", "spain israel",
        "spain dismisses ambassador", "spanish diplomat",
        "spain ukraine migrants", "spain vulnerable",
        "catalonia", "basque country",
        "spanish sovereignty", "spain gibraltar",
        "spain nato southern flank",
    ],
    "energy": [
        "spanish energy", "spanish electricity",
        "spanish renewables", "spanish solar",
        "spanish wind", "spanish hydro", "spanish grid",
        "spanish climate", "spanish emissions",
        "spanish energy transition", "spanish hydrogen",
        "spanish lng", "spanish energy prices",
        "spanish energy security", "repsol energy",
        "iberdrola energy", "endesa spain",
        "spanish offshore wind", "spanish green energy",
        "spanish nuclear", "spanish coal phase out",
        "spanish energy taxes", "fuel fees spain",
    ],
    "technology": [
        "spanish tech", "madrid tech", "spanish startup",
        "spanish ai", "spanish fintech", "spanish digital",
        "spanish innovation", "spanish unicorn",
        "spanish cybersecurity", "spanish gaming",
        "spanish software", "spanish it sector",
        "cabify spain", "glovo spain", "typeform",
        "spanish semiconductor", "barcelona tech",
        "spanish quantum", "spanish robotics",
        "spanish space agency",
    ],
    "health": [
        "spanish health", "spanish hospital", "spanish pharma",
        "grifols", "almirall", "ferrer pharma",
        "spanish vaccine", "spanish healthcare",
        "spanish mental health", "spanish health system",
        "spanish medicine", "sns spain",
        "spanish public health", "spanish wellbeing",
        "spanish medical tourism", "spanish biotech",
    ],
    "crime": [
        "spanish corruption", "spanish fraud", "spanish scandal",
        "spanish court", "spanish investigation",
        "spanish organized crime", "spanish drug trafficking",
        "spanish money laundering", "spanish terrorism",
        "spanish police", "policia nacional",
        "guardia civil", "spanish gang",
        "spanish anti corruption", "spanish oligarch",
        "spanish fraud scheme", "spanish smuggling",
        "spanish human trafficking", "spanish gender violence",
        "spain fire women", "spain arrested",
        "spain scheme exploiting", "spain gender crime",
        "spain hate crime",
    ],
    "politics": [
        "congreso diputados", "senado espana",
        "spanish parliament", "spanish election",
        "spanish government", "spanish minister",
        "spanish prime minister", "spanish coalition",
        "spanish opposition", "psoe",
        "pedro sanchez", "sanchez",
        "partido popular", "pp spain", "alberto nunez feijoo",
        "vox spain", "santiago abascal",
        "sumar spain", "yolanda diaz",
        "spanish policy", "spanish reform",
        "spanish immigration", "spanish integration",
        "spanish welfare", "spanish citizenship",
        "spanish referendum", "spanish judiciary",
        "spanish rule of law", "spanish eu relations",
        "spanish democracy", "spanish king",
        "felipe vi", "spanish media freedom",
        "catalan independence", "catalan referendum",
        "basque independence", "eta spain",
        "spanish hate speech", "spanish polarisation",
        "spain tracking system", "spanish gender violence",
        "spain women rights", "spain childcare",
        "spain european parliament",
    ],
}

