
# mood/pipeline/keywords/et.py
ET_KEYWORDS = {
    "finance": [
        "ethiopian economy", "ethiopia gdp",
        "ethiopian stock exchange", "esi ethiopia",
        "national bank ethiopia", "nbe",
        "ethiopian birr", "etb",
        "ethiopian inflation", "ethiopian budget",
        "ethiopian exports", "ethiopian trade",
        "ethiopian market", "ethiopian growth",
        "ethiopian debt", "ethiopian deficit",
        "ethiopian unemployment", "ethiopian wages",
        "ethiopian housing", "ethiopian mortgage",
        "commercial bank ethiopia", "cbe ethiopia",
        "awash bank", "dashen bank ethiopia",
        "ethiopian coffee", "ethiopian sesame",
        "ethiopian gold", "ethiopian opal",
        "ethiopian flowers", "ethiopian leather",
        "ethiopian business", "ethiopian investment",
        "ethiopian tourism", "ethiopian manufacturing",
        "ethiopian agriculture", "ethiopian teff",
        "ethiopian eu trade", "ethiopia us trade",
        "ethiopian tariffs", "ethiopian fiscal",
        "ethiopian pension fund", "ethiopian industry",
        "ethiopian startup", "ethiopian fintech",
        "ethiopian real estate", "ethiopian construction",
        "ethiopian remittances", "ethiopian diaspora",
        "ethiopia imf", "abiy economic policy",
        "addis ababa economic hub",
        "ethiopian airlines",
    ],
    "geopolitics": [
        "ethiopian foreign policy", "ethiopia nato",
        "ethiopian sanctions", "ethiopian diplomacy",
        "ethiopian troops", "ethiopia ukraine",
        "ethiopia russia", "ethiopian ambassador",
        "ethiopia eu", "ethiopian defense",
        "ethiopian military", "addis ababa talks",
        "ethiopia security", "ethiopian intelligence",
        "niss ethiopia", "ethiopia us relations",
        "ethiopia china", "ethiopia brics",
        "ethiopia africa union", "ethiopia igad",
        "ethiopia peacekeeping", "ethiopia un",
        "ethiopia tigray", "tigray conflict",
        "ethiopia eritrea", "ethiopia somalia",
        "ethiopia kenya", "ethiopia egypt nile",
        "grand renaissance dam",
        "abiy foreign policy",
        "ethiopia sea access",
        "ethiopia somaliland deal",
        "landslide gamo zone ethiopia",
    ],
    "energy": [
        "ethiopian energy", "ethiopian electricity",
        "ethiopian renewables", "ethiopian solar",
        "ethiopian wind", "ethiopian hydro",
        "ethiopian grid", "ethiopian climate",
        "ethiopian emissions", "ethiopian energy transition",
        "ethiopian hydrogen", "ethiopian lng",
        "ethiopian energy prices", "ethiopian energy security",
        "ethiopian green energy", "ethiopian carbon neutral",
        "ethiopian net zero", "ethiopian fuel prices",
        "grand renaissance dam energy",
        "gerd ethiopia", "ethiopian hydroelectric",
        "ethiopian geothermal",
        "eepco ethiopia",
    ],
    "technology": [
        "ethiopian tech", "addis ababa tech",
        "ethiopian startup", "ethiopian ai",
        "ethiopian fintech", "ethiopian digital",
        "ethiopian innovation", "ethiopian cybersecurity",
        "ethiopian software", "ethiopian it sector",
        "ethiopian ecommerce", "ethiopian digital economy",
        "ethiopian 5g", "ethiopian blockchain",
        "ethiopian smart city", "ethiopian medtech",
        "ethiopian digital transformation",
        "ethiotelecom", "safaricom ethiopia",
        "ethiopian tech hub",
        "iceaddis ethiopia",
    ],
    "health": [
        "ethiopian health", "ethiopian hospital",
        "ethiopian pharma", "ethiopian vaccine",
        "ethiopian healthcare", "ethiopian mental health",
        "ethiopian health system", "ethiopian medicine",
        "ethiopian public health", "ethiopian wellbeing",
        "ethiopian malaria", "ethiopian tuberculosis",
        "ethiopian hiv", "ethiopian cholera",
        "ethiopian famine", "ethiopian drought health",
        "ethiopian health reform",
        "ethiopian universal health",
        "ethiopian maternal health",
        "who ethiopia",
        "ethiopian landslide casualties",
    ],
    "crime": [
        "ethiopian corruption", "ethiopian fraud",
        "ethiopian scandal", "ethiopian court",
        "ethiopian investigation", "ethiopian organized crime",
        "ethiopian drug trafficking", "ethiopian money laundering",
        "ethiopian terrorism", "ethiopian police",
        "ethiopian gang", "ethiopian anti corruption",
        "ethiopian cybercrime", "ethiopian scam",
        "ethiopian arrest", "ethiopian human trafficking",
        "ethiopian protest", "ethiopian riot",
        "ethiopian political prisoner",
        "ethiopian war crimes tigray",
        "ethiopian amhara conflict",
        "ethiopian oromia conflict",
        "ethiopian femicide",
    ],
    "politics": [
        "house of peoples representatives ethiopia",
        "ethiopian parliament", "ethiopian election",
        "ethiopian government", "ethiopian minister",
        "ethiopian prime minister", "ethiopian coalition",
        "ethiopian opposition", "prosperity party",
        "abiy ahmed", "abiy ethiopia",
        "tplf ethiopia", "tigray people",
        "oromo liberation front", "olf ethiopia",
        "ethiopian policy", "ethiopian reform",
        "ethiopian immigration", "ethiopian diaspora",
        "ethiopian welfare", "ethiopian citizenship",
        "ethiopian referendum", "ethiopian judiciary",
        "ethiopian rule of law", "ethiopian eu relations",
        "ethiopian democracy", "ethiopian media freedom",
        "ethiopian press freedom", "ethiopian constitution",
        "ethiopian federalism", "ethiopian regions",
        "ethiopian ethnic federalism",
        "ethiopian political crisis",
        "tigray ceasefire",
        "ethiopian nobel peace prize",
    ],
}

