

# mood/pipeline/keywords/fi.py
FI_KEYWORDS = {
    "finance": [
        "finnish economy", "finland gdp", "omx helsinki",
        "helsinki stock exchange", "nasdaq helsinki",
        "bank of finland", "finnish inflation", "finnish budget",
        "finnish exports", "finnish trade", "finnish market",
        "finnish growth", "finnish debt", "finnish surplus",
        "finnish unemployment", "finnish wages", "finnish housing",
        "nokia", "kone", "neste", "fortum", "wartsila",
        "metso", "outokumpu", "upm kymmene", "stora enso",
        "nordea finland", "op financial", "s bank finland",
        "finnish business", "finnish investment",
        "finnish tourism", "finnish manufacturing",
        "finnish forest industry", "finnish paper",
        "finnish steel", "finnish shipping",
        "foodora finland", "wolt finland",
    ],
    "geopolitics": [
        "finnish foreign policy", "finland nato",
        "finnish sanctions", "finnish diplomacy",
        "finnish troops", "finland ukraine", "finland russia",
        "finnish ambassador", "finland eu",
        "finnish defense", "finnish military",
        "helsinki talks", "finland arctic",
        "finland russia border", "finnish security",
        "finnish intelligence", "finnish nato membership",
        "finland sweden nato", "nordic defense",
        "finland middle east", "finnish peacekeeping",
    ],
    "energy": [
        "finnish energy", "finnish nuclear", "olkiluoto",
        "fortum power", "finnish electricity", "finnish renewables",
        "finnish wind", "finnish solar", "finnish hydro",
        "finnish grid", "finnish climate", "finnish emissions",
        "finnish energy transition", "finnish hydrogen",
        "finnish lng", "finnish energy prices",
        "russian gas finland", "finnish energy security",
    ],
    "technology": [
        "finnish tech", "helsinki tech", "finnish startup",
        "finnish ai", "finnish fintech", "finnish digital",
        "finnish innovation", "finnish unicorn",
        "finnish cybersecurity", "nokia finland",
        "finnish gaming", "supercell", "rovio",
        "finnish robotics", "finnish cleantech",
        "oulu tech", "finnish 5g", "finnish quantum",
    ],
    "health": [
        "finnish health", "finnish hospital", "finnish pharma",
        "orion finland", "finnish vaccine", "finnish healthcare",
        "finnish mental health", "finnish health system",
        "finnish medicine", "thl finland",
        "finnish wellbeing", "finnish happiness",
    ],
    "crime": [
        "finnish corruption", "finnish fraud", "finnish scandal",
        "finnish court", "finnish investigation",
        "finnish organized crime", "finnish drug trafficking",
        "finnish money laundering", "finnish terrorism",
        "finnish police", "finnish shooting",
        "finnish gang", "rikospoliisi",
    ],
    "politics": [
        "eduskunta", "finnish parliament", "finnish election",
        "finnish government", "finnish minister",
        "finnish prime minister", "finnish coalition",
        "finnish opposition", "national coalition finland",
        "finns party", "social democrats finland",
        "centre party finland", "green league finland",
        "alexander stubb", "petteri orpo",
        "elina valtonen", "riikka purra",
        "finnish policy", "finnish reform",
        "finnish immigration", "finnish integration",
        "finnish welfare", "finnish model",
        "finnish citizenship", "finnish referendum",
        "finnish nato policy", "finnish russia policy",
        "finnish ukraine support",
    ],
}

