
# mood/pipeline/keywords/fj.py
FJ_KEYWORDS = {
    "finance": [
        "fiji economy", "fiji gdp",
        "south pacific stock exchange", "spse fiji",
        "reserve bank fiji", "rbf",
        "fiji dollar", "fjd",
        "fiji inflation", "fiji budget",
        "fiji exports", "fiji trade",
        "fiji market", "fiji growth",
        "fiji debt", "fiji deficit",
        "fiji unemployment", "fiji wages",
        "fiji housing", "fiji mortgage",
        "fiji sugar", "fiji gold",
        "fiji timber", "fiji fisheries",
        "fiji water", "fiji airways",
        "anz fiji", "westpac fiji",
        "bsp fiji", "bred bank fiji",
        "fiji business", "fiji investment",
        "fiji tourism", "fiji manufacturing",
        "fiji agriculture", "fiji remittances",
        "fiji diaspora", "fiji pension fund",
        "fiji industry", "fiji construction",
        "fiji real estate", "fiji logistics",
        "fiji trade deal", "fiji eu trade",
        "fiji us trade", "fiji tariffs",
    ],
    "geopolitics": [
        "fiji foreign policy", "fiji nato",
        "fiji sanctions", "fiji diplomacy",
        "fiji troops", "fiji ukraine", "fiji russia",
        "fiji ambassador", "fiji eu",
        "fiji defense", "fiji military",
        "suva talks", "fiji security",
        "fiji intelligence", "fiji australia",
        "fiji china relations", "fiji us relations",
        "fiji pacific", "fiji pacific islands forum",
        "fiji new zealand", "fiji peacekeeping",
        "fiji un", "fiji middle east",
        "fiji solomon islands", "fiji vanuatu",
        "pacific security fiji",
        "fiji coup history",
        "fiji climate change threat",
        "fiji sea level rise",
    ],
    "energy": [
        "fiji energy", "fiji electricity",
        "fiji renewables", "fiji solar",
        "fiji hydro", "fiji wind",
        "fiji grid", "fiji climate",
        "fiji emissions", "fiji energy transition",
        "fiji energy prices", "fiji energy security",
        "fiji green energy", "fiji fuel prices",
        "fiji power outage", "fiji blackout",
        "fiji energy crisis", "fiji carbon neutral",
        "fiji net zero", "fiji climate vulnerability",
        "energy fiji", "fiji power authority",
    ],
    "technology": [
        "fiji tech", "suva tech", "fiji startup",
        "fiji ai", "fiji fintech",
        "fiji digital", "fiji innovation",
        "fiji cybersecurity", "fiji software",
        "fiji it sector", "fiji ecommerce",
        "fiji digital economy", "fiji mobile banking",
        "fiji internet", "fiji connectivity",
        "fiji smart city", "fiji medtech",
        "digicel fiji", "vodafone fiji",
        "fiji digital transformation",
    ],
    "health": [
        "fiji health", "fiji hospital",
        "fiji pharma", "fiji vaccine",
        "fiji healthcare", "fiji mental health",
        "fiji health system", "fiji medicine",
        "fiji public health", "fiji wellbeing",
        "fiji malaria", "fiji tuberculosis",
        "fiji dengue", "fiji typhoid",
        "fiji health crisis", "fiji medical aid",
        "fiji maternal health", "fiji child health",
        "who fiji", "fiji disease outbreak",
        "fiji cyclone health",
    ],
    "crime": [
        "fiji corruption", "fiji fraud",
        "fiji scandal", "fiji court",
        "fiji investigation", "fiji organized crime",
        "fiji drug trafficking", "fiji money laundering",
        "fiji terrorism", "fiji police",
        "fiji gang", "fiji anti corruption",
        "fiji cybercrime", "fiji scam",
        "fiji arrest", "fiji human trafficking",
        "fiji protest", "fiji riot",
        "fiji election fraud",
        "fiji political violence",
    ],
    "politics": [
        "parliament of fiji", "fiji parliament",
        "fiji election", "fiji government",
        "fiji minister", "fiji prime minister",
        "fiji coalition", "fiji opposition",
        "sodelpa fiji", "social democratic liberal",
        "fiji first party", "people's alliance fiji",
        "sitiveni rabuka", "frank bainimarama",
        "fiji policy", "fiji reform",
        "fiji immigration", "fiji diaspora",
        "fiji welfare", "fiji citizenship",
        "fiji referendum", "fiji judiciary",
        "fiji rule of law", "fiji eu relations",
        "fiji democracy", "fiji president",
        "fiji constitution", "fiji coup",
        "fiji media freedom", "fiji press freedom",
        "fiji indigenous", "itaukei rights",
        "fiji indo fijian", "fiji ethnic relations",
        "fiji climate politics",
        "pacific islands forum fiji",
    ],
}