
# mood/pipeline/keywords/fr.py
FR_KEYWORDS = {
    "finance": [
        "french economy", "france gdp", "cac 40", "cac40",
        "paris stock exchange", "euronext paris",
        "banque de france", "french inflation", "french budget",
        "french exports", "french trade", "french market",
        "french growth", "french debt", "french deficit",
        "french unemployment", "french wages", "french housing",
        "lvmh", "total energies", "bnp paribas", "airbus",
        "renault", "peugeot", "stellantis", "michelin",
        "sanofi", "loreal", "hermes", "kering",
        "credit agricole", "societe generale", "axa",
        "french business", "french investment", "french tourism",
        "french industry", "french manufacturing",
        "french luxury", "french fashion",
    ],
    "geopolitics": [
        "french foreign policy", "france nato", "french military",
        "french sanctions", "french diplomacy", "french troops",
        "france ukraine", "france russia", "france china",
        "french ambassador", "france eu", "french president",
        "france middle east", "france africa", "franc cfa",
        "french nuclear deterrent", "french defense",
        "paris talks", "elysee", "quai dorsay",
        "macron foreign", "france sahel",
    ],
    "energy": [
        "french energy", "french nuclear", "edf",
        "french electricity", "french renewables", "french gas",
        "french grid", "french wind", "french solar",
        "french hydro", "french climate", "french emissions",
        "french energy prices", "french energy transition",
        "french lng", "french offshore wind",
    ],
    "technology": [
        "french tech", "paris tech", "french startup",
        "french ai", "french digital", "french fintech",
        "capgemini", "dassault systemes", "atos",
        "french unicorn", "station f", "french innovation",
        "french semiconductor", "french quantum",
    ],
    "health": [
        "french health", "french hospital", "french pharma",
        "sanofi france", "french vaccine", "french healthcare",
        "french mental health", "french health system",
        "securite sociale", "french medicine",
    ],
    "crime": [
        "french corruption", "french fraud", "french scandal",
        "french court", "french investigation",
        "french organized crime", "french drug trafficking",
        "french money laundering", "french terrorism",
        "french riot", "french protest violence",
    ],
    "politics": [
        "assemblee nationale", "senat france", "french parliament",
        "french election", "french government", "french minister",
        "macron", "emmanuel macron", "french president",
        "premier ministre", "french prime minister",
        "rassemblement national", "rn france", "marine le pen",
        "la france insoumise", "melenchon",
        "parti socialiste", "les republicains",
        "french coalition", "french opposition",
        "french policy", "french reform",
        "french protest", "gilets jaunes",
        "french pension reform", "french strikes",
    ],
}