
# mood/pipeline/keywords/gb.py
GB_KEYWORDS = {
    "finance": [
        "uk economy", "uk gdp", "ftse", "ftse 100", "ftse 250",
        "london stock exchange", "bank of england", "gbp",
        "pound sterling", "uk inflation", "uk budget",
        "uk exports", "uk trade", "uk market", "uk growth",
        "uk recession", "uk debt", "uk deficit",
        "uk unemployment", "uk wages", "uk housing",
        "uk mortgage", "uk interest rates",
        "barclays", "hsbc", "lloyds", "natwest",
        "standard chartered", "bp", "shell", "unilever",
        "astrazeneca", "rolls royce", "bae systems",
        "uk business", "uk investment", "uk retail",
        "uk manufacturing", "uk services",
        "chancellor", "autumn statement", "spring budget",
    ],
    "geopolitics": [
        "uk foreign policy", "british military", "uk nato",
        "uk sanctions", "uk diplomacy", "british troops",
        "uk ukraine", "uk russia", "uk china",
        "foreign secretary", "uk ambassador",
        "brexit", "uk eu relations", "northern ireland protocol",
        "uk middle east", "uk africa", "uk commonwealth",
        "british intelligence", "mi6", "gchq",
        "uk defense", "british army", "royal navy",
        "uk security", "five eyes",
    ],
    "energy": [
        "uk energy", "north sea", "uk oil", "uk gas",
        "uk electricity", "uk nuclear", "uk renewables",
        "uk offshore wind", "uk solar", "uk grid",
        "uk net zero", "uk climate", "uk emissions",
        "national grid", "uk energy prices",
        "uk energy security", "uk lng",
        "hinkley point", "sizewell",
    ],
    "technology": [
        "uk tech", "london tech", "uk startup", "uk fintech",
        "uk ai", "uk digital", "uk cybersecurity",
        "arm holdings", "deepmind", "uk unicorn",
        "uk semiconductor", "uk quantum",
        "tech nation", "silicon roundabout",
    ],
    "health": [
        "nhs", "national health service", "uk health",
        "uk hospital", "uk pharma", "uk vaccine",
        "astrazeneca uk", "gsk", "glaxosmithkline",
        "uk mental health", "uk healthcare",
        "uk health crisis", "uk waiting list",
    ],
    "crime": [
        "uk corruption", "uk fraud", "uk scandal",
        "metropolitan police", "uk court", "uk investigation",
        "uk organized crime", "uk drug trafficking",
        "uk money laundering", "uk cybercrime",
        "uk knife crime", "uk terrorism",
        "serious fraud office", "sfo uk",
    ],
    "politics": [
        "house of commons", "house of lords", "westminster",
        "uk parliament", "uk election", "uk government",
        "prime minister", "uk cabinet", "uk minister",
        "labour party", "conservative party", "lib dems",
        "reform uk", "snp", "uk policy", "uk reform",
        "keir starmer", "rishi sunak", "nigel farage",
        "uk coalition", "uk opposition", "uk chancellor",
        "devolution", "scotland independence",
        "welsh government", "northern ireland",
    ],
}
