
# mood/pipeline/keywords/gd.py
GD_KEYWORDS = {
    "finance": [
        "grenada economy", "grenada gdp",
        "eastern caribbean securities exchange",
        "eastern caribbean central bank", "eccb",
        "eastern caribbean dollar", "xcd",
        "grenada inflation", "grenada budget",
        "grenada exports", "grenada trade",
        "grenada market", "grenada growth",
        "grenada debt", "grenada deficit",
        "grenada unemployment", "grenada wages",
        "grenada housing", "grenada mortgage",
        "republic bank grenada",
        "scotiabank grenada", "rbtt grenada",
        "grenada tourism", "grenada nutmeg",
        "grenada cocoa", "grenada spices",
        "grenada agriculture", "grenada fisheries",
        "grenada eu trade", "grenada us trade",
        "grenada tariffs", "grenada fiscal",
        "grenada pension fund", "grenada industry",
        "grenada startup", "grenada fintech",
        "grenada real estate", "grenada construction",
        "grenada remittances", "grenada diaspora",
        "grenada offshore finance",
        "grenada citizenship by investment",
    ],
    "geopolitics": [
        "grenada foreign policy", "grenada nato",
        "grenada sanctions", "grenada diplomacy",
        "grenada troops", "grenada ukraine",
        "grenada russia", "grenada ambassador",
        "grenada eu", "grenada defense",
        "grenada military", "st george talks",
        "grenada security", "grenada intelligence",
        "grenada us relations", "grenada caricom",
        "grenada caribbean", "grenada uk relations",
        "grenada commonwealth", "grenada china",
        "grenada peacekeeping", "grenada un",
        "grenada us invasion history",
        "dick mitchell foreign policy",
        "grenada climate diplomacy",
        "oecs grenada",
    ],
    "energy": [
        "grenada energy", "grenada electricity",
        "grenada renewables", "grenada solar",
        "grenada wind", "grenada grid",
        "grenada climate", "grenada emissions",
        "grenada energy transition",
        "grenada energy prices", "grenada energy security",
        "grenada green energy", "grenada carbon neutral",
        "grenada net zero", "grenada fuel prices",
        "grenada climate vulnerability",
        "grenada sea level rise",
        "grenada energy independence",
        "grenlec grenada",
    ],
    "technology": [
        "grenada tech", "st george tech",
        "grenada startup", "grenada ai",
        "grenada fintech", "grenada digital",
        "grenada innovation", "grenada cybersecurity",
        "grenada software", "grenada it sector",
        "grenada ecommerce", "grenada digital economy",
        "grenada smart city", "grenada medtech",
        "grenada blockchain", "grenada 5g",
        "grenada digital transformation",
        "digicel grenada", "flow grenada",
        "grenada digital citizenship",
    ],
    "health": [
        "grenada health", "grenada hospital",
        "grenada pharma", "grenada vaccine",
        "grenada healthcare", "grenada mental health",
        "grenada health system", "grenada medicine",
        "grenada public health", "grenada wellbeing",
        "grenada cancer", "grenada aging population",
        "grenada diabetes", "grenada obesity",
        "general hospital grenada",
        "grenada medical school",
        "st george university grenada",
        "grenada health ministry",
        "grenada climate health",
    ],
    "crime": [
        "grenada corruption", "grenada fraud",
        "grenada scandal", "grenada court",
        "grenada investigation", "grenada organized crime",
        "grenada drug trafficking", "grenada money laundering",
        "grenada terrorism", "grenada police",
        "grenada gang", "grenada anti corruption",
        "grenada cybercrime", "grenada scam",
        "grenada arrest", "grenada human trafficking",
        "grenada protest", "grenada riot",
        "grenada political scandal",
        "grenada drug transshipment",
    ],
    "politics": [
        "grenada parliament", "grenada election",
        "grenada government", "grenada minister",
        "grenada prime minister", "grenada coalition",
        "grenada opposition", "ndp grenada",
        "dickon mitchell", "mitchell grenada",
        "glp grenada", "grenada policy",
        "grenada reform", "grenada immigration",
        "grenada diaspora", "grenada welfare",
        "grenada citizenship", "grenada referendum",
        "grenada judiciary", "grenada rule of law",
        "grenada democracy", "grenada king",
        "grenada governor general",
        "grenada republic debate",
        "grenada media freedom",
        "grenada constitution",
        "grenada caricom",
        "oecs politics grenada",
        "united we stand grenada",
    ],
}