
# mood/pipeline/keywords/ge.py
GE_KEYWORDS = {
    "finance": [
        "georgian economy", "georgia gdp",
        "georgian stock exchange", "gse georgia",
        "national bank georgia", "nbg georgia",
        "georgian lari", "gel",
        "georgian inflation", "georgian budget",
        "georgian exports", "georgian trade",
        "georgian market", "georgian growth",
        "georgian debt", "georgian deficit",
        "georgian unemployment", "georgian wages",
        "georgian housing", "georgian mortgage",
        "georgian agriculture", "georgian wine",
        "georgian mineral water", "georgian tourism",
        "georgian eu funds", "georgian recovery plan",
        "georgian pension fund", "georgian industry",
        "georgian it sector", "georgian startup",
        "georgian outsourcing", "georgian remittances",
        "georgian banking", "tbcbank", "bank of georgia",
        "liberty bank georgia", "georgians abroad",
        "georgian real estate", "georgian construction",
        "georgian port batumi", "georgian logistics",
        "georgian free trade zone",
    ],
    "geopolitics": [
        "georgian foreign policy", "georgia nato",
        "georgian sanctions", "georgian diplomacy",
        "georgian troops", "georgia ukraine",
        "georgia russia", "georgian ambassador",
        "georgia eu", "georgian defense",
        "georgian military", "tbilisi talks",
        "georgia security", "georgian intelligence",
        "ssg georgia", "south ossetia",
        "abkhazia", "georgian occupied territories",
        "russian occupation georgia",
        "georgian pro western", "georgia eu accession",
        "georgian dream party foreign",
        "kobakhidze foreign policy",
        "moscow mechanism georgia",
        "georgia nato membership bid",
        "georgia eu candidate",
        "georgian sovereignty",
        "georgia us relations",
        "baku tbilisi ceyhan",
        "baku tbilisi kars",
    ],
    "energy": [
        "georgian energy", "georgian electricity",
        "georgian gas", "georgian renewables",
        "georgian grid", "georgian solar",
        "georgian wind", "georgian hydro",
        "georgian climate", "georgian emissions",
        "georgian energy transition",
        "georgian pipeline", "baku tbilisi pipeline",
        "georgian energy security", "georgian energy prices",
        "georgian lng", "georgian biomass",
        "enguri dam georgia", "georgian power plants",
        "georgian energy independence",
        "georgian green energy",
    ],
    "technology": [
        "georgian tech", "tbilisi tech", "georgian startup",
        "georgian ai", "georgian fintech",
        "georgian digital", "georgian innovation",
        "georgian software", "georgian it sector",
        "georgian outsourcing", "georgian cybersecurity",
        "georgian gaming", "georgian e-government",
        "georgian digital transformation",
        "georgian unicorn", "georgian medtech",
        "georgian cleantech", "ai generated georgia",
        "georgian draft law ai",
    ],
    "health": [
        "georgian health", "georgian hospital",
        "georgian pharma", "georgian vaccine",
        "georgian healthcare", "georgian mental health",
        "georgian health system", "georgian medicine",
        "georgian public health", "georgian wellbeing",
        "georgian medical tourism", "tbilisi medicine",
        "georgian biotech", "georgian cancer",
        "aversi pharma", "psp georgia",
    ],
    "crime": [
        "georgian corruption", "georgian fraud",
        "georgian scandal", "georgian court",
        "georgian investigation", "georgian organized crime",
        "georgian drug trafficking", "georgian money laundering",
        "georgian terrorism", "georgian police",
        "police georgia", "georgian gang",
        "georgian anti corruption", "boc georgia",
        "georgian smuggling", "georgian human trafficking",
        "georgian election fraud", "georgian protest",
        "tbilisi protest", "georgian riot",
        "georgian opposition arrested",
        "georgian political prisoner",
        "kobakhidze scandal",
    ],
    "politics": [
        "georgian parliament", "sakartvelos parlamenti",
        "georgian election", "georgian government",
        "georgian minister", "georgian prime minister",
        "georgian coalition", "georgian opposition",
        "georgian dream", "irakli kobakhidze", "kobakhidze",
        "bidzina ivanishvili", "ivanishvili",
        "unity national movement", "mikheil saakashvili",
        "strong georgia", "girchi georgia",
        "georgian policy", "georgian reform",
        "georgian immigration", "georgian diaspora",
        "georgian welfare", "georgian citizenship",
        "georgian referendum", "georgian judiciary",
        "georgian rule of law", "georgian eu relations",
        "georgian democracy", "georgian president",
        "salome zourabichvili",
        "georgian media freedom", "georgian press freedom",
        "georgian foreign agents law",
        "georgian eu suspension",
        "georgian nato aspirations",
        "georgian protest movement",
        "tbilisi demonstrations",
    ],
}

