
# mood/pipeline/keywords/gh.py
GH_KEYWORDS = {
    "finance": [
        "ghanaian economy", "ghana gdp", "gse index",
        "ghana stock exchange", "gse ghana",
        "bank of ghana", "bog",
        "ghanaian cedi", "ghs",
        "ghanaian inflation", "ghanaian budget",
        "ghanaian exports", "ghanaian trade",
        "ghanaian market", "ghanaian growth",
        "ghanaian debt", "ghanaian deficit",
        "ghanaian unemployment", "ghanaian wages",
        "ghanaian housing", "ghanaian mortgage",
        "gcb bank ghana", "ecobank ghana",
        "absa ghana", "standard chartered ghana",
        "ghana commercial bank",
        "newmont ghana", "anglogold ghana",
        "ghana cocoa board", "cocobod",
        "ghana national petroleum", "gnpc",
        "ghanaian business", "ghanaian investment",
        "ghanaian tourism", "ghanaian manufacturing",
        "ghanaian mining", "ghanaian gold",
        "ghanaian cocoa", "ghanaian oil",
        "ghanaian agriculture", "ghanaian cashew",
        "ghanaian eu trade", "ghana us trade",
        "ghanaian tariffs", "ghanaian fiscal",
        "ghanaian pension fund", "ssnit ghana",
        "ghanaian industry", "ghanaian startup",
        "ghanaian fintech", "ghanaian real estate",
        "ghanaian construction", "ghanaian remittances",
        "ghanaian diaspora", "ghana imf deal",
        "mahama economic policy",
        "ghana debt restructuring",
        "gh200000 robbery ghana",
    ],
    "geopolitics": [
        "ghanaian foreign policy", "ghana nato",
        "ghanaian sanctions", "ghanaian diplomacy",
        "ghanaian troops", "ghana ukraine",
        "ghana russia", "ghanaian ambassador",
        "ghana eu", "ghanaian defense",
        "ghanaian military", "accra talks",
        "ghana security", "ghanaian intelligence",
        "nis ghana", "ghana us relations",
        "ghana china relations", "ghana brics",
        "ghana africa union", "ghana ecowas",
        "ghana peacekeeping", "ghana un",
        "ghana burkina faso", "ghana mali",
        "ghana togo", "ghana ivory coast",
        "ghana sahel crisis",
        "mahama foreign policy",
        "ghana west africa stability",
    ],
    "energy": [
        "ghanaian energy", "ghanaian electricity",
        "ghanaian renewables", "ghanaian solar",
        "ghanaian wind", "ghanaian hydro",
        "ghanaian grid", "ghanaian climate",
        "ghanaian emissions", "ghanaian energy transition",
        "ghanaian hydrogen", "ghanaian lng",
        "ghanaian energy prices", "ghanaian energy security",
        "ghanaian green energy", "ghanaian carbon neutral",
        "ghanaian net zero", "ghanaian fuel prices",
        "ghanaian oil", "ghanaian gas",
        "ghana national gas company",
        "tema oil refinery",
        "ghanaian offshore oil",
        "akosombo dam ghana",
        "ghana power crisis",
        "ghana dumsor",
    ],
    "technology": [
        "ghanaian tech", "accra tech", "ghanaian startup",
        "ghanaian ai", "ghanaian fintech",
        "ghanaian digital", "ghanaian innovation",
        "ghanaian unicorn", "ghanaian cybersecurity",
        "ghanaian gaming", "ghanaian software",
        "ghanaian it sector", "ghanaian ecommerce",
        "ghanaian digital economy", "ghanaian semiconductor",
        "ghanaian ev", "ghanaian smart city",
        "ghanaian medtech", "ghanaian biotech",
        "ghanaian 5g", "ghanaian blockchain",
        "mtn ghana fintech", "expresspay ghana",
        "ghanaian silicon accra",
        "ghanaian tech hub",
        "ghana innovation hub",
    ],
    "health": [
        "ghanaian health", "ghanaian hospital",
        "ghanaian pharma", "ghanaian vaccine",
        "ghanaian healthcare", "ghanaian mental health",
        "ghanaian health system", "ghanaian medicine",
        "ghanaian public health", "ghanaian wellbeing",
        "ghanaian biotech", "ghanaian cancer",
        "ghanaian aging population",
        "ghanaian malaria", "ghanaian tuberculosis",
        "ghanaian hiv", "ghanaian cholera",
        "ghanaian dengue", "ghanaian mpox",
        "food and drugs authority ghana",
        "ghanaian health reform",
        "nhis ghana", "ghanaian universal health",
        "korle bu hospital ghana",
    ],
    "crime": [
        "ghanaian corruption", "ghanaian fraud",
        "ghanaian scandal", "ghanaian court",
        "ghanaian investigation", "ghanaian organized crime",
        "ghanaian drug trafficking", "ghanaian money laundering",
        "ghanaian terrorism", "ghanaian police",
        "ghanaian gang", "ghanaian anti corruption",
        "osi ghana", "cid ghana",
        "ghanaian cybercrime", "ghanaian scam",
        "ghanaian arrest", "ghanaian robbery",
        "ghanaian human trafficking",
        "ghanaian protest", "ghanaian riot",
        "ghanaian political scandal",
        "ghanaian election violence",
        "ghanaian galamsey", "illegal mining ghana",
        "ghanaian femicide",
        "police arrest five ghana robbery",
    ],
    "politics": [
        "parliament of ghana", "ghanaian parliament",
        "ghanaian election", "ghanaian government",
        "ghanaian minister", "ghanaian president",
        "ghanaian coalition", "ghanaian opposition",
        "ndc ghana", "john mahama", "mahama ghana",
        "npp ghana", "mahamudu bawumia",
        "ghanaian policy", "ghanaian reform",
        "ghanaian immigration", "ghanaian diaspora",
        "ghanaian welfare", "ghanaian citizenship",
        "ghanaian referendum", "ghanaian judiciary",
        "ghanaian rule of law", "ghanaian eu relations",
        "ghanaian democracy", "ghanaian media freedom",
        "ghanaian press freedom", "ghanaian constitution",
        "ghanaian federalism", "ghanaian regions",
        "ghanaian decentralization",
        "ghana 2024 election result",
        "ghana peaceful transition",
        "ghana democratic model",
    ],
}
