
# mood/pipeline/keywords/gr.py
GR_KEYWORDS = {
    "finance": [
        "greek economy", "greece gdp", "athex index",
        "athens stock exchange", "helex greece",
        "bank of greece", "trapeza ellados",
        "greek euro", "greek inflation",
        "greek budget", "greek exports",
        "greek trade", "greek market",
        "greek growth", "greek debt",
        "greek deficit", "greek unemployment",
        "greek wages", "greek housing",
        "greek mortgage", "piraeus bank",
        "national bank greece", "alpha bank",
        "eurobank greece", "attica bank",
        "hellenic petroleum", "motor oil greece",
        "opap greece", "jumbo greece",
        "mytilineos", "terna energy",
        "greek business", "greek investment",
        "greek tourism", "greek shipping",
        "greek manufacturing", "greek agriculture",
        "greek eu funds", "greek recovery plan",
        "greek pension fund", "greek industry",
        "greek maritime", "greek ferry",
        "greek real estate", "greek construction",
        "greek bailout legacy", "greek austerity legacy",
        "greek economic recovery",
    ],
    "geopolitics": [
        "greek foreign policy", "greece nato",
        "greek sanctions", "greek diplomacy",
        "greek troops", "greece ukraine", "greece russia",
        "greek ambassador", "greece eu",
        "greek defense", "greek military",
        "athens talks", "greece security",
        "greek intelligence", "eis greece",
        "greece turkey", "aegean dispute",
        "greek turkish relations", "greek cypriot",
        "greece middle east", "greek peacekeeping",
        "greece israel", "greece iran",
        "greek missile", "iran turkey greece",
        "nato greece", "greek nato southern flank",
        "greek foreign minister", "george gerapetritis",
        "greece north macedonia", "greece albania",
        "greek eez", "eastern mediterranean greece",
    ],
    "energy": [
        "greek energy", "greek electricity", "greek gas",
        "greek renewables", "greek solar",
        "greek wind", "greek hydro", "greek grid",
        "greek climate", "greek emissions",
        "greek energy transition", "greek hydrogen",
        "greek lng", "greek energy prices",
        "greek energy security", "greek offshore wind",
        "greek green energy", "greek natural gas",
        "eastern mediterranean gas", "greek pipeline",
        "elpedison", "ppc greece", "desfa greece",
        "greek coal phase out", "greek biomass",
    ],
    "technology": [
        "greek tech", "athens tech", "greek startup",
        "greek ai", "greek fintech", "greek digital",
        "greek innovation", "greek unicorn",
        "greek cybersecurity", "greek gaming",
        "greek software", "greek it sector",
        "greek outsourcing", "greek semiconductor",
        "thessaloniki tech", "greek quantum",
        "greek space", "greek robotics",
        "skroutz greece", "e-food greece",
    ],
    "health": [
        "greek health", "greek hospital", "greek pharma",
        "pharmathen greece", "vianex greece",
        "greek vaccine", "greek healthcare",
        "greek mental health", "greek health system",
        "greek medicine", "eopyy greece",
        "greek public health", "greek wellbeing",
        "greek medical tourism", "greek biotech",
        "greek cancer research",
    ],
    "crime": [
        "greek corruption", "greek fraud", "greek scandal",
        "greek court", "greek investigation",
        "greek organized crime", "greek drug trafficking",
        "greek money laundering", "greek terrorism",
        "greek police", "elliniki astynomia",
        "greek gang", "greek anti corruption",
        "greek oligarch", "greek fraud scheme",
        "greek smuggling", "greek human trafficking",
        "greek protest", "exarchia athens",
        "greek riot", "greek migrant crisis",
        "greek train crash", "tempi disaster",
    ],
    "politics": [
        "vouli ton ellinon", "greek parliament",
        "greek election", "greek government",
        "greek minister", "greek prime minister",
        "greek coalition", "greek opposition",
        "nea dimokratia", "kyriakos mitsotakis", "mitsotakis",
        "syriza", "stefanos kasselakis",
        "pasok", "nikos androulakis",
        "greek policy", "greek reform",
        "greek immigration", "greek integration",
        "greek welfare", "greek citizenship",
        "greek referendum", "greek judiciary",
        "greek rule of law", "greek eu relations",
        "greek democracy", "greek president",
        "katerina sakellaropoulou",
        "greek media freedom", "greek press freedom",
        "greek wiretapping scandal",
        "greek asylum policy", "greek border",
        "greek ancient history", "greek culture",
        "greek mythology",
    ],
}

