
# mood/pipeline/keywords/hu.py
HU_KEYWORDS = {
    "finance": [
        "hungarian economy", "hungary gdp", "bux index",
        "budapest stock exchange", "bet hungary",
        "magyar nemzeti bank", "mnb", "hungarian forint", "huf",
        "hungarian inflation", "hungarian budget",
        "hungarian exports", "hungarian trade",
        "hungarian market", "hungarian growth",
        "hungarian debt", "hungarian deficit",
        "hungarian unemployment", "hungarian wages",
        "hungarian housing", "hungarian mortgage",
        "mol hungary", "otp bank", "richter gedeon",
        "magyar telekom", "opus global",
        "hungarian business", "hungarian investment",
        "hungarian tourism", "hungarian manufacturing",
        "hungarian automotive", "hungarian agriculture",
        "hungarian eu funds", "hungarian recovery plan",
        "hungarian pension fund", "hungarian industry",
        "wizz air", "hungarian airlines",
        "hungarian retail", "hungarian construction",
    ],
    "geopolitics": [
        "hungarian foreign policy", "hungary nato",
        "hungarian sanctions", "hungarian diplomacy",
        "hungarian troops", "hungary ukraine", "hungary russia",
        "hungarian ambassador", "hungary eu",
        "hungarian defense", "hungarian military",
        "budapest talks", "hungary security",
        "hungarian intelligence", "aih hungary",
        "orban foreign policy", "hungarian veto",
        "hungary china", "hungary russia relations",
        "hungarian eastern opening", "hungary middle east",
        "hungarian peacekeeping", "hungary balkans",
        "hungary serbia relations",
    ],
    "energy": [
        "hungarian energy", "hungarian nuclear", "paks",
        "paks2 nuclear", "hungarian electricity",
        "hungarian renewables", "hungarian gas",
        "hungarian grid", "hungarian solar",
        "hungarian climate", "hungarian emissions",
        "hungarian energy transition", "hungarian hydrogen",
        "russian gas hungary", "hungarian energy security",
        "hungarian energy prices", "mol energy",
        "hungarian wind", "hungarian biomass",
    ],
    "technology": [
        "hungarian tech", "budapest tech", "hungarian startup",
        "hungarian ai", "hungarian fintech", "hungarian digital",
        "hungarian innovation", "hungarian unicorn",
        "hungarian cybersecurity", "hungarian gaming",
        "hungarian software", "hungarian it sector",
        "prezi hungary", "logmein hungary",
        "hungarian semiconductor", "debrecen tech",
        "samsung hungary", "hungarian battery",
        "catl hungary", "sk innovation hungary",
    ],
    "health": [
        "hungarian health", "hungarian hospital",
        "hungarian pharma", "richter pharma",
        "hungarian vaccine", "hungarian healthcare",
        "hungarian mental health", "hungarian health system",
        "hungarian medicine", "neak hungary",
        "hungarian public health", "hungarian wellbeing",
        "semmelweis university",
    ],
    "crime": [
        "hungarian corruption", "hungarian fraud",
        "hungarian scandal", "hungarian court",
        "hungarian investigation", "hungarian organized crime",
        "hungarian drug trafficking", "hungarian money laundering",
        "hungarian terrorism", "hungarian police",
        "rendorseg hungary", "hungarian gang",
        "hungarian anti corruption",
        "neak fraud hungary", "hungarian oligarch",
    ],
    "politics": [
        "orszaggyules", "hungarian parliament",
        "hungarian election", "hungarian government",
        "hungarian minister", "hungarian prime minister",
        "hungarian coalition", "hungarian opposition",
        "fidesz", "viktor orban", "orban",
        "kdnp hungary", "dk hungary", "momentum hungary",
        "peter magyar", "tisza party",
        "hungarian policy", "hungarian reform",
        "hungarian immigration", "hungarian integration",
        "hungarian welfare", "hungarian citizenship",
        "hungarian referendum", "hungarian judiciary",
        "hungarian rule of law", "hungarian eu relations",
        "hungarian democracy", "hungarian president",
        "tamas sulyok", "hungarian media freedom",
        "hungarian academic freedom",
    ],
}


