
# mood/pipeline/keywords/id_.py
ID_KEYWORDS = {
    "finance": [
        "indonesian economy", "indonesia gdp", "idx composite",
        "indonesia stock exchange", "idx indonesia",
        "bank indonesia", "bi indonesia",
        "indonesian rupiah", "idr",
        "indonesian inflation", "indonesian budget",
        "indonesian exports", "indonesian trade",
        "indonesian market", "indonesian growth",
        "indonesian debt", "indonesian deficit",
        "indonesian unemployment", "indonesian wages",
        "indonesian housing", "indonesian mortgage",
        "pertamina", "bri bank", "mandiri bank",
        "bni indonesia", "bca bank indonesia",
        "telkom indonesia", "astra international",
        "indonesian business", "indonesian investment",
        "indonesian tourism", "indonesian manufacturing",
        "indonesian automotive", "indonesian agriculture",
        "indonesian palm oil", "indonesian coal exports",
        "indonesian nickel", "indonesian copper",
        "indonesian eu funds", "indonesian recovery plan",
        "indonesian pension fund", "bpjs indonesia",
        "indonesian industry", "indonesian it sector",
        "indonesian startup", "indonesian unicorn",
        "indonesian real estate", "indonesian construction",
        "indonesia us trade", "indonesian tariffs",
        "indonesian trade deal", "indonesian fiscal",
        "indonesian fdi", "indonesian remittances",
        "gojek", "tokopedia", "grab indonesia",
        "bukalapak", "traveloka",
    ],
    "geopolitics": [
        "indonesian foreign policy", "indonesia nato",
        "indonesian sanctions", "indonesian diplomacy",
        "indonesian troops", "indonesia ukraine",
        "indonesia russia", "indonesian ambassador",
        "indonesia eu", "indonesian defense",
        "indonesian military", "jakarta talks",
        "indonesia security", "indonesian intelligence",
        "indonesia china relations", "south china sea indonesia",
        "natuna islands", "indonesia us relations",
        "indonesia asean", "indonesia australia",
        "indonesia japan", "indonesia india",
        "indonesian peacekeeping", "indonesia un",
        "indonesia middle east", "indonesia gulf",
        "indonesia malaysia border", "indonesia papua",
        "west papua conflict",
    ],
    "energy": [
        "indonesian energy", "indonesian coal",
        "indonesian electricity", "indonesian renewables",
        "indonesian solar", "indonesian wind",
        "indonesian hydro", "indonesian grid",
        "indonesian climate", "indonesian emissions",
        "indonesian energy transition", "indonesian hydrogen",
        "indonesian lng", "indonesian energy prices",
        "indonesian energy security", "indonesian green energy",
        "indonesian natural gas", "indonesian oil",
        "pertamina energy", "pln indonesia",
        "indonesian carbon neutral", "indonesian net zero",
        "indonesian fuel prices", "indonesian geothermal",
        "indonesian nickel battery", "indonesian ev battery",
    ],
    "technology": [
        "indonesian tech", "jakarta tech", "indonesian startup",
        "indonesian ai", "indonesian fintech",
        "indonesian digital", "indonesian innovation",
        "indonesian unicorn", "indonesian cybersecurity",
        "indonesian gaming", "indonesian software",
        "indonesian it sector", "indonesian ecommerce",
        "indonesian digital economy", "indonesian semiconductor",
        "indonesian ev", "indonesian smart city",
        "indonesian medtech", "gojek indonesia",
        "tokopedia indonesia", "indonesian blockchain",
        "indonesian quantum", "kominfo indonesia",
        "indonesian digital transformation",
    ],
    "health": [
        "indonesian health", "indonesian hospital",
        "indonesian pharma", "indonesian vaccine",
        "indonesian healthcare", "indonesian mental health",
        "indonesian health system", "indonesian medicine",
        "indonesian public health", "indonesian wellbeing",
        "indonesian medical tourism", "indonesian biotech",
        "indonesian cancer", "indonesian dengue",
        "indonesian malaria", "indonesian tuberculosis",
        "kemenkes indonesia", "indonesian aging population",
        "indonesian air pollution health",
    ],
    "crime": [
        "indonesian corruption", "indonesian fraud",
        "indonesian scandal", "indonesian court",
        "indonesian investigation", "indonesian organized crime",
        "indonesian drug trafficking", "indonesian money laundering",
        "indonesian terrorism", "indonesian police",
        "polri indonesia", "indonesian gang",
        "indonesian anti corruption", "kpk indonesia",
        "indonesian cybercrime", "indonesian scam",
        "indonesian arrest", "indonesian mafia",
        "indonesian human trafficking",
        "indonesian protest", "indonesian riot",
        "indonesian terrorism jemaah islamiyah",
        "indonesian radical islamist",
    ],
    "politics": [
        "dewan perwakilan rakyat", "dpr indonesia",
        "indonesian parliament", "indonesian election",
        "indonesian government", "indonesian minister",
        "indonesian president", "indonesian coalition",
        "indonesian opposition", "pdi p indonesia",
        "golkar indonesia", "gerindra indonesia",
        "prabowo subianto", "prabowo",
        "joko widodo", "jokowi",
        "megawati sukarnoputri",
        "indonesian policy", "indonesian reform",
        "indonesian immigration", "indonesian diaspora",
        "indonesian welfare", "indonesian citizenship",
        "indonesian referendum", "indonesian judiciary",
        "indonesian rule of law", "indonesian eu relations",
        "indonesian democracy", "indonesian media freedom",
        "indonesian press freedom", "indonesian constitution",
        "indonesian federalism", "papua autonomy",
        "indonesian pancasila", "indonesian islam",
        "indonesian religious freedom",
    ],
}