
# mood/pipeline/keywords/il.py
IL_KEYWORDS = {
    "finance": [
        "israeli economy", "israel gdp", "tel aviv stock exchange",
        "tase israel", "bank of israel",
        "israeli shekel", "ils",
        "israeli inflation", "israeli budget",
        "israeli exports", "israeli trade",
        "israeli market", "israeli growth",
        "israeli debt", "israeli deficit",
        "israeli unemployment", "israeli wages",
        "israeli housing", "israeli mortgage",
        "check point software", "nice systems",
        "amdocs", "teva pharmaceutical",
        "tower semiconductor", "elbit systems",
        "rafael advanced defense", "israel aerospace",
        "israeli business", "israeli investment",
        "israeli tourism", "israeli manufacturing",
        "israeli agriculture", "israeli tech",
        "israeli eu trade", "israel us trade",
        "israeli tariffs", "israeli fiscal",
        "israeli pension fund", "israeli industry",
        "israeli startup", "israeli unicorn",
        "israeli fintech", "israeli real estate",
        "israeli construction", "israeli logistics",
        "israel war economy", "israeli defense spending",
        "israeli reconstruction", "israel us aid",
    ],
    "geopolitics": [
        "israeli foreign policy", "israel nato",
        "israeli sanctions", "israeli diplomacy",
        "israeli troops", "israel ukraine", "israel russia",
        "israeli ambassador", "israel eu",
        "israeli defense", "israeli military", "idf",
        "tel aviv talks", "israel security",
        "israeli intelligence", "mossad",
        "shin bet", "israel iran war",
        "israel iran conflict", "iran attack israel",
        "israel us relations", "israel germany",
        "israel france", "israel uk",
        "israel gaza", "gaza war",
        "israel hamas", "israel hezbollah",
        "israel lebanon", "israel syria",
        "israel west bank", "israeli settlements",
        "two state solution", "israel palestine",
        "israel saudi normalization", "abraham accords",
        "israel middle east", "israel gulf",
        "israel un", "israel icj",
        "israeli airstrike", "israeli ground operation",
        "israeli hostages", "october 7",
        "israel drone attack", "israel missile defense",
        "iron dome", "israel arrow missile",
        "israel f35", "israeli air force",
    ],
    "energy": [
        "israeli energy", "israeli gas",
        "leviathan gas field", "tamar gas field",
        "israeli electricity", "israeli renewables",
        "israeli solar", "israeli wind",
        "israeli grid", "israeli climate",
        "israeli emissions", "israeli energy transition",
        "israeli hydrogen", "israeli lng",
        "israeli energy prices", "israeli energy security",
        "israeli green energy", "israeli carbon neutral",
        "israeli net zero", "israeli fuel prices",
        "israeli offshore gas", "israeli energy exports",
        "israel egypt gas", "israel jordan gas",
    ],
    "technology": [
        "israeli tech", "tel aviv tech", "israeli startup",
        "israeli ai", "israeli cybersecurity",
        "check point israel", "palo alto israel",
        "israeli semiconductor", "israeli chip",
        "israeli digital", "israeli innovation",
        "israeli unicorn", "israeli fintech",
        "israeli medtech", "israeli biotech",
        "israeli drone tech", "israeli defense tech",
        "israeli space", "israeli satellite",
        "waze israel", "mobileye israel",
        "israeli quantum", "israeli 5g",
        "silicon wadi", "israeli venture capital",
        "israeli deep tech",
    ],
    "health": [
        "israeli health", "israeli hospital",
        "israeli pharma", "teva israel",
        "israeli vaccine", "israeli healthcare",
        "israeli mental health", "israeli health system",
        "israeli medicine", "israeli public health",
        "israeli wellbeing", "israeli biotech",
        "israeli cancer research", "israeli aging",
        "magen david adom", "israeli trauma medicine",
        "israeli war wounded", "israeli ptsd",
        "clalit health services", "maccabi healthcare",
    ],
    "crime": [
        "israeli corruption", "israeli fraud",
        "israeli scandal", "israeli court",
        "israeli investigation", "israeli organized crime",
        "israeli drug trafficking", "israeli money laundering",
        "israeli terrorism", "israeli police",
        "israeli gang", "israeli anti corruption",
        "israeli cybercrime", "israeli scam",
        "israeli arrest", "israeli mafia",
        "israeli human trafficking",
        "israeli protest", "israeli riot",
        "netanyahu trial", "netanyahu corruption",
        "israeli political scandal",
    ],
    "politics": [
        "knesset", "israeli parliament",
        "israeli election", "israeli government",
        "israeli minister", "israeli prime minister",
        "israeli coalition", "israeli opposition",
        "likud", "benjamin netanyahu", "netanyahu",
        "yesh atid", "yair lapid",
        "national unity israel", "benny gantz",
        "labor israel", "meretz",
        "israeli policy", "israeli reform",
        "israeli immigration", "israeli diaspora",
        "israeli welfare", "israeli citizenship",
        "israeli referendum", "israeli judiciary",
        "israeli judicial reform", "israeli rule of law",
        "israeli democracy", "israeli president",
        "isaac herzog", "israeli media freedom",
        "israeli press freedom", "israeli constitution",
        "israeli arab citizens", "israeli arab party",
        "war cabinet israel", "israeli security cabinet",
        "israeli ceasefire", "israeli hostage deal",
    ],
}