
# mood/pipeline/keywords/in.py
IN_KEYWORDS = {
    "finance": [
        "indian economy", "india gdp", "sensex", "nifty 50",
        "bombay stock exchange", "bse india", "nse india",
        "reserve bank india", "rbi", "indian rupee", "inr",
        "indian inflation", "indian budget", "indian exports",
        "indian trade", "indian market", "indian growth",
        "indian debt", "indian deficit", "indian unemployment",
        "indian wages", "indian housing", "indian mortgage",
        "tata group", "reliance industries", "infosys",
        "wipro", "hcl tech", "tcs", "hdfc bank",
        "icici bank", "axis bank", "kotak mahindra",
        "adani group", "ambani", "mukesh ambani",
        "indian business", "indian investment",
        "indian tourism", "indian manufacturing",
        "indian automotive", "indian agriculture",
        "indian eu funds", "indian recovery plan",
        "indian pension fund", "indian industry",
        "indian it sector", "indian outsourcing",
        "indian real estate", "indian construction",
        "indian pharma", "indian generic drugs",
        "indian startup ecosystem", "indian unicorn",
        "make in india", "indian fdi",
        "indian trade deal", "india us trade",
        "india eu trade", "indian tariffs",
        "indian fiscal", "indian stimulus",
        "lpg india", "indian fuel prices",
    ],
    "geopolitics": [
        "indian foreign policy", "india nato",
        "india us relations", "indian sanctions",
        "indian diplomacy", "indian troops",
        "india ukraine", "india russia",
        "indian ambassador", "india eu",
        "indian defense", "indian military",
        "new delhi talks", "india security",
        "indian intelligence", "raw india",
        "india china border", "lac india",
        "india pakistan", "kashmir conflict",
        "india china relations", "india japan",
        "india quad", "india aukus",
        "india middle east", "india africa",
        "indian peacekeeping", "india un",
        "india bangladesh", "india sri lanka",
        "india nepal", "india bhutan",
        "india iran relations", "india gulf",
        "india israel", "india russia oil",
        "indian ocean", "india maritime",
    ],
    "energy": [
        "indian energy", "indian nuclear",
        "indian electricity", "indian renewables",
        "indian solar", "indian wind", "indian hydro",
        "indian grid", "indian climate",
        "indian emissions", "indian energy transition",
        "indian hydrogen", "indian lng",
        "indian energy prices", "indian energy security",
        "indian offshore wind", "indian green energy",
        "indian coal", "indian coal phase out",
        "indian carbon neutral", "indian net zero",
        "indian oil imports", "indian russian oil",
        "adani green energy", "tata power",
        "ntpc india", "indian power sector",
        "lpg shortage india", "indian gas",
    ],
    "technology": [
        "indian tech", "bangalore tech", "indian startup",
        "indian ai", "indian semiconductor",
        "indian chip", "indian digital",
        "indian innovation", "indian robotics",
        "indian ev", "indian battery",
        "indian quantum", "indian cybersecurity",
        "indian gaming", "indian software",
        "indian unicorn", "indian fintech",
        "indian space", "isro", "indian 5g",
        "infosys india", "wipro india", "tcs india",
        "indian outsourcing", "indian it exports",
        "indian deeptech", "indian medtech",
        "india stack", "upi india", "aadhaar",
        "indian digital transformation",
    ],
    "health": [
        "indian health", "indian hospital",
        "indian pharma", "sun pharma",
        "cipla", "dr reddy", "lupin pharma",
        "indian vaccine", "serum institute",
        "indian healthcare", "indian mental health",
        "indian health system", "indian medicine",
        "ayurveda", "indian aging population",
        "indian public health", "indian biotech",
        "indian cancer", "indian dengue",
        "indian malaria", "indian tuberculosis",
        "indian air pollution health",
        "indian water sanitation",
    ],
    "crime": [
        "indian corruption", "indian fraud",
        "indian scandal", "indian court",
        "indian investigation", "indian organized crime",
        "indian drug trafficking", "indian money laundering",
        "indian terrorism", "indian police",
        "indian gang", "indian anti corruption",
        "cbi india", "ed india",
        "indian cybercrime", "indian scam",
        "indian arrest", "indian mafia",
        "indian human trafficking",
        "indian communal violence",
        "indian rape case", "india women safety",
        "indian protest", "indian riot",
    ],
    "politics": [
        "lok sabha", "rajya sabha", "indian parliament",
        "indian election", "indian government",
        "indian minister", "indian prime minister",
        "indian coalition", "indian opposition",
        "bjp india", "narendra modi", "modi",
        "congress party india", "rahul gandhi",
        "aap india", "arvind kejriwal",
        "indian policy", "indian reform",
        "indian immigration", "indian diaspora",
        "indian welfare", "indian citizenship",
        "indian referendum", "indian judiciary",
        "indian rule of law", "indian eu relations",
        "indian democracy", "indian president",
        "droupadi murmu", "indian media freedom",
        "indian constitution", "indian federalism",
        "hindutva", "indian secularism",
        "indian caste system", "indian reservation",
        "indian election commission",
        "tamil politics", "kerala politics",
        "maharashtra politics", "bengal politics",
    ],
}