
# mood/pipeline/keywords/ir.py
IR_KEYWORDS = {
    "finance": [
        "iranian economy", "iran gdp",
        "tehran stock exchange", "tse iran",
        "central bank iran", "cbi iran",
        "iranian rial", "irr",
        "iranian toman", "iran inflation",
        "iran budget", "iran exports",
        "iran trade", "iran market", "iran growth",
        "iran debt", "iran deficit",
        "iran unemployment", "iran wages",
        "iran housing", "iran mortgage",
        "iran oil revenue", "iran gas revenue",
        "iran sanctions economy",
        "iran frozen assets", "iran swift ban",
        "iran parallel economy", "iran black market",
        "iran currency collapse", "iran rial crash",
        "iran business", "iran investment",
        "iran tourism", "iran manufacturing",
        "iran agriculture", "iran pistachio",
        "iran saffron", "iran carpet exports",
        "iran petrochemical", "iran steel",
        "iran copper", "iran minerals",
        "iran china trade", "iran russia trade",
        "iran india oil", "iran sanctions evasion",
    ],
    "geopolitics": [
        "iranian foreign policy", "iran nato",
        "iranian sanctions", "iranian diplomacy",
        "iranian troops", "iran ukraine", "iran russia",
        "iranian ambassador", "iran eu",
        "iranian military", "irgc",
        "tehran talks", "iran security",
        "iranian intelligence", "mois iran",
        "iran us relations", "iran nuclear deal",
        "jcpoa", "iran nuclear program",
        "iran uranium enrichment",
        "iran israel war", "iran attack israel",
        "iran israel conflict",
        "iran hezbollah", "iran hamas",
        "iran houthis", "iran proxy",
        "iran strait hormuz",
        "iran gulf", "iran saudi relations",
        "iran gcc", "iran qatar",
        "iran middle east", "iran peacekeeping",
        "iran un", "iran syria",
        "iran iraq", "iran afghanistan",
        "iran pakistan", "iran azerbaijan",
        "iran armenia", "iran turkey",
        "iran china relations", "iran india",
        "iran hypersonic missile",
        "iran drone attack",
        "iran ballistic missile",
        "iran air defense",
        "iran khamenei", "iran revolutionary guard",
        "iranian war effort",
    ],
    "energy": [
        "iranian energy", "iranian oil",
        "iranian gas", "iran electricity",
        "iran renewables", "iran solar",
        "iran wind", "iran hydro",
        "iran grid", "iran climate",
        "iran emissions", "iran energy transition",
        "iran lng", "iran energy prices",
        "iran energy security", "iran green energy",
        "iran nuclear energy", "iran bushehr",
        "iran carbon neutral", "iran net zero",
        "iran fuel prices", "iran petrochemical",
        "iran oil sanctions", "iran oil exports",
        "iran gas exports", "iran energy sanctions",
        "iran russian energy cooperation",
        "iran china energy deal",
        "strait hormuz oil",
        "gulf oil iran war",
    ],
    "technology": [
        "iranian tech", "tehran tech", "iranian startup",
        "iranian ai", "iranian fintech",
        "iranian digital", "iranian innovation",
        "iranian cybersecurity", "iranian hacking",
        "iranian cyber attack", "iranian software",
        "iranian it sector", "iranian ecommerce",
        "iranian digital economy", "iranian drone tech",
        "iranian missile technology",
        "iranian defense technology",
        "iranian satellite", "iran space program",
        "iranian blockchain", "iranian quantum",
        "iranian internet censorship",
        "iran internet shutdown",
        "iranian vpn usage",
    ],
    "health": [
        "iranian health", "iranian hospital",
        "iranian pharma", "iranian vaccine",
        "iranian healthcare", "iranian mental health",
        "iranian health system", "iranian medicine",
        "iranian public health", "iranian wellbeing",
        "iranian biotech", "iranian cancer",
        "iranian war wounded", "iranian casualties",
        "iranian medical aid", "iran health crisis",
        "iranian traditional medicine",
        "iranian aging population",
    ],
    "crime": [
        "iranian corruption", "iranian fraud",
        "iranian scandal", "iranian court",
        "iranian investigation", "iranian organized crime",
        "iranian drug trafficking", "iranian money laundering",
        "iranian terrorism", "iranian police",
        "iranian gang", "iranian anti corruption",
        "iranian cybercrime", "iranian scam",
        "iranian arrest", "iranian mafia",
        "iranian human trafficking",
        "iranian protest", "iranian riot",
        "iranian political prisoner",
        "iranian dissident", "iranian journalist arrested",
        "iranian opposition arrested",
        "iran war crimes", "iranian atrocities",
        "mahsa amini", "iranian women protest",
        "iranian execution",
        "mojtaba khamenei",
    ],
    "politics": [
        "majles iran", "iranian parliament",
        "iranian election", "iranian government",
        "iranian minister", "iranian president",
        "iranian supreme leader", "khamenei",
        "ali khamenei", "mojtaba khamenei",
        "masoud pezeshkian", "iranian coalition",
        "iranian opposition", "reformists iran",
        "hardliners iran", "iranian policy",
        "iranian reform", "iranian immigration",
        "iranian diaspora", "iranian refugees",
        "iranian welfare", "iranian citizenship",
        "iranian referendum", "iranian judiciary",
        "iranian rule of law", "iranian eu relations",
        "iranian democracy", "iranian media freedom",
        "iranian press freedom", "iranian constitution",
        "iranian theocracy", "iranian velayat faqih",
        "iranian revolutionary guard politics",
        "iranian wartime politics",
        "iranian ceasefire talks",
        "iranian nuclear negotiations",
    ],
}