
# mood/pipeline/keywords/is_.py
IS_KEYWORDS = {
    "finance": [
        "icelandic economy", "iceland gdp",
        "nasdaq iceland", "icelandic stock exchange",
        "central bank iceland", "sedlabanki",
        "icelandic krona", "isk",
        "icelandic inflation", "icelandic budget",
        "icelandic exports", "icelandic trade",
        "icelandic market", "icelandic growth",
        "icelandic unemployment", "icelandic wages",
        "icelandic fishing", "icelandic fish",
        "icelandic tourism", "icelandic aluminum",
        "icelandic energy revenue", "icelandic business",
        "icelandic investment", "reykjavik economy",
        "icelandic banking", "arion bank", "islandsbanki",
        "landsbankinn", "icelandic pension fund",
    ],
    "geopolitics": [
        "icelandic foreign policy", "iceland nato",
        "icelandic diplomacy", "icelandic sanctions",
        "iceland eu", "icelandic military",
        "reykjavik talks", "arctic iceland",
        "icelandic peacekeeping", "iceland russia",
        "iceland ukraine", "icelandic ambassador",
        "icelandic security", "north atlantic iceland",
        "keflavik base", "icelandic coast guard",
        "iceland greenland", "arctic council iceland",
    ],
    "energy": [
        "icelandic energy", "icelandic geothermal",
        "icelandic hydro", "iceland electricity",
        "icelandic renewables", "reykjavik energy",
        "iceland green energy", "icelandic grid",
        "icelandic hydrogen", "icelandic carbon",
        "icelandic volcano", "icelandic eruption",
        "icelandic power", "icelandic heating",
        "landsvirkjun", "orkuveita reykjavikur",
        "icelandic data center", "iceland bitcoin mining",
    ],
    "technology": [
        "icelandic tech", "reykjavik tech", "icelandic startup",
        "icelandic ai", "icelandic fintech", "icelandic digital",
        "icelandic innovation", "icelandic data center",
        "iceland cloud", "icelandic gaming",
        "icelandic cybersecurity", "icelandic quantum",
        "ccpgames iceland", "eve online iceland",
    ],
    "health": [
        "icelandic health", "icelandic hospital",
        "icelandic pharma", "icelandic vaccine",
        "icelandic healthcare", "icelandic mental health",
        "icelandic health system", "icelandic medicine",
        "landspitali", "icelandic genetics",
        "decode genetics", "icelandic wellbeing",
        "icelandic labor market", "icelandic work life",
    ],
    "crime": [
        "icelandic corruption", "icelandic fraud",
        "icelandic scandal", "icelandic court",
        "icelandic investigation", "icelandic police",
        "icelandic drug trafficking", "icelandic money laundering",
        "icelandic gang", "reykjavik crime",
        "icesave scandal", "icelandic banking scandal",
    ],
    "politics": [
        "althing", "icelandic parliament", "icelandic election",
        "icelandic government", "icelandic minister",
        "icelandic prime minister", "icelandic coalition",
        "icelandic opposition", "independence party iceland",
        "left greens iceland", "progressive party iceland",
        "social democratic alliance iceland",
        "bjarni benediktsson", "katrin jakobsdottir",
        "icelandic policy", "icelandic reform",
        "icelandic immigration", "icelandic welfare",
        "icelandic model", "icelandic citizenship",
        "icelandic referendum", "icelandic labor market model",
        "icelandic strikes", "icelandic unions",
    ],
}

