

# mood/pipeline/keywords/it.py
IT_KEYWORDS = {
    "finance": [
        "italian economy", "italy gdp", "ftse mib",
        "milan stock exchange", "borsa italiana",
        "bank of italy", "banca italia",
        "italian euro", "italian inflation",
        "italian budget", "italian exports",
        "italian trade", "italian market",
        "italian growth", "italian debt",
        "italian deficit", "italian unemployment",
        "italian wages", "italian housing",
        "italian mortgage", "unicredit", "intesa sanpaolo",
        "mediobanca", "banco bpm", "bper banca",
        "eni", "enel", "ferrari", "fiat", "stellantis",
        "leonardo italy", "finmeccanica",
        "generali insurance", "assicurazioni generali",
        "pirelli", "prysmian", "telecom italia",
        "italian business", "italian investment",
        "italian tourism", "italian manufacturing",
        "italian automotive", "italian agriculture",
        "italian eu funds", "italian recovery plan",
        "pnrr italy", "italian pension fund",
        "italian industry", "italian fashion",
        "italian luxury", "italian food exports",
        "italian tariffs", "us italy tariffs",
        "italian pasta tariffs", "italian brands tariffs",
        "italian transport strike", "italy strike",
        "italian fuel costs", "italian fuel prices",
    ],
    "geopolitics": [
        "italian foreign policy", "italy nato",
        "italian sanctions", "italian diplomacy",
        "italian troops", "italy ukraine", "italy russia",
        "italian ambassador", "italy eu",
        "italian defense", "italian military",
        "rome talks", "italy security",
        "italian intelligence", "aise italy",
        "italy middle east", "italian peacekeeping",
        "italy africa", "italy china",
        "italy libya", "italian mediterranean",
        "italy israel", "italian ambassador israel",
        "italy iraq", "italian base iraq",
        "italy withdrawing troops", "italian foreign minister",
        "antonio tajani", "giorgia meloni foreign",
    ],
    "energy": [
        "italian energy", "italian gas", "italian electricity",
        "italian renewables", "italian solar",
        "italian wind", "italian hydro", "italian grid",
        "italian climate", "italian emissions",
        "italian energy transition", "italian hydrogen",
        "italian lng", "italian energy prices",
        "italian energy security", "eni energy",
        "italian offshore wind", "italian green energy",
        "iran driving fuel italy", "fuel costs italy",
        "italian nuclear debate",
    ],
    "technology": [
        "italian tech", "milan tech", "italian startup",
        "italian ai", "italian fintech", "italian digital",
        "italian innovation", "italian unicorn",
        "italian cybersecurity", "italian gaming",
        "italian software", "italian it sector",
        "leonardo tech", "reply italy",
        "italian semiconductor", "rome tech",
        "italian quantum", "italian space agency",
        "asi italy", "italian robotics",
    ],
    "health": [
        "italian health", "italian hospital", "italian pharma",
        "chiesi farmaceutici", "menarini", "recordati",
        "italian vaccine", "italian healthcare",
        "italian mental health", "italian health system",
        "italian medicine", "ssn italy",
        "italian public health", "italian wellbeing",
        "italian medical tourism", "italian biotech",
    ],
    "crime": [
        "italian corruption", "italian fraud", "italian scandal",
        "italian court", "italian investigation",
        "italian organized crime", "italian mafia",
        "camorra", "ndrangheta", "cosa nostra",
        "italian drug trafficking", "italian money laundering",
        "italian terrorism", "italian police",
        "polizia italiana", "carabinieri",
        "italian anti corruption", "anac italy",
        "italian oligarch", "italian fraud scheme",
        "italian smuggling", "italian human trafficking",
    ],
    "politics": [
        "camera dei deputati", "senato italiano",
        "italian parliament", "italian election",
        "italian government", "italian minister",
        "italian prime minister", "italian coalition",
        "italian opposition", "fratelli italia",
        "giorgia meloni", "meloni",
        "lega matteo salvini", "salvini",
        "forza italia", "berlusconi",
        "partito democratico", "movimento 5 stelle",
        "italian policy", "italian reform",
        "italian immigration", "italian integration",
        "italian welfare", "italian citizenship",
        "italian referendum", "italian judiciary",
        "italian rule of law", "italian eu relations",
        "italian democracy", "italian president",
        "sergio mattarella", "italian media freedom",
        "italian justice reform", "italian constitutional court",
        "italian citizenship rules",
    ],
}

