
# mood/pipeline/keywords/jm.py
JM_KEYWORDS = {
    "finance": [
        "jamaican economy", "jamaica gdp",
        "jamaica stock exchange", "jse jamaica",
        "bank of jamaica", "boj jamaica",
        "jamaican dollar", "jmd",
        "jamaican inflation", "jamaican budget",
        "jamaican exports", "jamaican trade",
        "jamaican market", "jamaican growth",
        "jamaican debt", "jamaican deficit",
        "jamaican unemployment", "jamaican wages",
        "jamaican housing", "jamaican mortgage",
        "national commercial bank jamaica", "ncb",
        "scotiabank jamaica", "jn bank",
        "sagicor jamaica", "caribbean cement",
        "jamaican tourism", "jamaican rum",
        "jamaican coffee", "jamaican bauxite",
        "jamaican alumina", "jamaican agriculture",
        "jamaican manufacturing", "jamaican logistics",
        "jamaican eu trade", "jamaica us trade",
        "jamaican tariffs", "jamaican fiscal",
        "jamaican pension fund", "jamaican industry",
        "jamaican startup", "jamaican fintech",
        "jamaican real estate", "jamaican construction",
        "jamaican remittances", "jamaican diaspora",
        "jamaican digital tax",
        "jamaican offshore finance",
    ],
    "geopolitics": [
        "jamaican foreign policy", "jamaica nato",
        "jamaican sanctions", "jamaican diplomacy",
        "jamaican troops", "jamaica ukraine",
        "jamaica russia", "jamaican ambassador",
        "jamaica eu", "jamaican defense",
        "jamaican military", "kingston talks",
        "jamaica security", "jamaican intelligence",
        "jamaica us relations", "jamaica caricom",
        "jamaica caribbean", "jamaica uk relations",
        "jamaica commonwealth", "jamaica china",
        "jamaican peacekeeping", "jamaica un",
        "jamaica cuba relations",
        "holness foreign policy",
        "jamaica reparations",
        "jamaica colonial legacy",
    ],
    "energy": [
        "jamaican energy", "jamaican electricity",
        "jamaican renewables", "jamaican solar",
        "jamaican wind", "jamaican grid",
        "jamaican climate", "jamaican emissions",
        "jamaican energy transition",
        "jamaican energy prices", "jamaican energy security",
        "jamaican green energy", "jamaican carbon neutral",
        "jamaican net zero", "jamaican fuel prices",
        "jamaican lng", "jps jamaica",
        "jamaican energy independence",
        "jamaican climate vulnerability",
        "jamaican sea level rise",
    ],
    "technology": [
        "jamaican tech", "kingston tech",
        "jamaican startup", "jamaican ai",
        "jamaican fintech", "jamaican digital",
        "jamaican innovation", "jamaican cybersecurity",
        "jamaican software", "jamaican it sector",
        "jamaican ecommerce", "jamaican digital economy",
        "jamaican smart city", "jamaican medtech",
        "jamaican blockchain", "jamaican 5g",
        "jamaican digital transformation",
        "digicel jamaica", "flow jamaica",
        "jamaican digital tax battle",
    ],
    "health": [
        "jamaican health", "jamaican hospital",
        "jamaican pharma", "jamaican vaccine",
        "jamaican healthcare", "jamaican mental health",
        "jamaican health system", "jamaican medicine",
        "jamaican public health", "jamaican wellbeing",
        "jamaican cancer", "jamaican aging population",
        "jamaican diabetes", "jamaican obesity",
        "university hospital west indies",
        "jamaican medical tourism",
        "jamaican health ministry",
        "jamaican ncd crisis",
        "jamaican mental health crisis",
    ],
    "crime": [
        "jamaican corruption", "jamaican fraud",
        "jamaican scandal", "jamaican court",
        "jamaican investigation", "jamaican organized crime",
        "jamaican drug trafficking", "jamaican money laundering",
        "jamaican terrorism", "jamaican police",
        "jamaican gang", "jamaican anti corruption",
        "jamaican cybercrime", "jamaican scam",
        "jamaican arrest", "jamaican mafia",
        "jamaican human trafficking",
        "jamaican protest", "jamaican riot",
        "jamaican political scandal",
        "jamaican lottery scam",
        "jamaican extortion",
        "jamaican garrison politics",
        "jamaican gun violence",
    ],
    "politics": [
        "jamaican parliament", "jamaican election",
        "jamaican government", "jamaican minister",
        "jamaican prime minister", "jamaican coalition",
        "jamaican opposition", "jlp jamaica",
        "andrew holness", "holness jamaica",
        "pnp jamaica", "mark golding",
        "jamaican policy", "jamaican reform",
        "jamaican immigration", "jamaican diaspora",
        "jamaican welfare", "jamaican citizenship",
        "jamaican referendum", "jamaican judiciary",
        "jamaican rule of law", "jamaican eu relations",
        "jamaican democracy", "jamaican king",
        "jamaican governor general",
        "jamaican republic debate",
        "jamaican media freedom",
        "jamaican constitution",
        "jamaican reparations debate",
        "caricom jamaica",
    ],
}
