
# mood/pipeline/keywords/jp.py
JP_KEYWORDS = {
    "finance": [
        "japanese economy", "japan gdp", "nikkei", "nikkei 225",
        "tokyo stock exchange", "tse japan", "topix",
        "bank of japan", "boj", "japanese yen", "jpy",
        "japanese inflation", "japanese budget", "japanese exports",
        "japanese trade", "japanese market", "japanese growth",
        "japanese debt", "japanese deficit", "japanese unemployment",
        "japanese wages", "japanese housing", "japanese mortgage",
        "toyota", "honda", "nissan", "sony", "panasonic",
        "softbank", "nintendo", "canon", "hitachi", "toshiba",
        "mitsubishi", "sumitomo", "mitsui", "itochu",
        "mizuho", "mufg", "sumitomo mitsui banking", "nomura",
        "japanese business", "japanese investment",
        "japanese tourism", "japanese manufacturing",
        "japanese automotive", "japanese electronics",
        "japanese semiconductor", "japanese chip",
        "japanese eu trade", "japanese trade deal",
        "japan us trade", "japanese tariffs",
        "japanese fiscal", "japanese stimulus",
        "japanese pension fund", "gpif japan",
    ],
    "geopolitics": [
        "japanese foreign policy", "japan nato", "japan us alliance",
        "japanese sanctions", "japanese diplomacy",
        "japanese troops", "japan ukraine", "japan russia",
        "japanese ambassador", "japan eu",
        "japanese defense", "japanese military",
        "tokyo talks", "japan security",
        "japanese intelligence", "japan china",
        "japan taiwan", "japan north korea",
        "east china sea", "south china sea japan",
        "japanese sdf", "japanese self defense",
        "japan middle east", "japanese peacekeeping",
        "japan india relations", "japan quad",
        "japan south korea", "japanese rearmament",
        "japan us security treaty",
    ],
    "energy": [
        "japanese energy", "japanese nuclear",
        "fukushima", "japanese electricity",
        "japanese renewables", "japanese solar",
        "japanese wind", "japanese hydro",
        "japanese grid", "japanese climate",
        "japanese emissions", "japanese energy transition",
        "japanese hydrogen", "japanese lng",
        "japanese energy prices", "japanese energy security",
        "japanese offshore wind", "japanese green energy",
        "tepco", "japanese coal phase out",
        "japanese carbon neutral", "japanese net zero",
    ],
    "technology": [
        "japanese tech", "tokyo tech", "japanese startup",
        "japanese ai", "japanese semiconductor",
        "japanese chip", "japanese digital",
        "japanese innovation", "japanese robotics",
        "japanese automation", "japanese ev",
        "japanese battery", "japanese quantum",
        "japanese cybersecurity", "japanese gaming",
        "nintendo japan", "sony japan", "japanese software",
        "japanese unicorn", "japanese fintech",
        "japanese space", "jaxa", "japanese 5g",
        "japanese deeptech", "japanese medtech",
    ],
    "health": [
        "japanese health", "japanese hospital",
        "japanese pharma", "takeda japan",
        "astellas", "daiichi sankyo",
        "japanese vaccine", "japanese healthcare",
        "japanese mental health", "japanese health system",
        "japanese medicine", "japanese aging population",
        "japanese longevity", "japanese public health",
        "japanese biotech", "japanese cancer",
        "japanese dementia", "japanese birthrate",
    ],
    "crime": [
        "japanese corruption", "japanese fraud",
        "japanese scandal", "japanese court",
        "japanese investigation", "japanese organized crime",
        "yakuza", "japanese drug trafficking",
        "japanese money laundering", "japanese terrorism",
        "japanese police", "keisatsu japan",
        "japanese gang", "japanese anti corruption",
        "japanese cybercrime", "japanese scam",
        "japanese murder", "japanese arrest",
    ],
    "politics": [
        "national diet japan", "japanese parliament",
        "japanese election", "japanese government",
        "japanese minister", "japanese prime minister",
        "japanese coalition", "japanese opposition",
        "ldp japan", "liberal democratic party japan",
        "cdp japan", "komeito japan",
        "japanese policy", "japanese reform",
        "japanese immigration", "japanese integration",
        "japanese welfare", "japanese citizenship",
        "japanese referendum", "japanese judiciary",
        "japanese constitution", "japanese pacifism",
        "japanese emperor", "japanese royal family",
        "japanese media freedom", "japanese press",
        "japanese power majority", "japanese fiscal policy",
        "japanese ruling bloc",
    ],
}
