
# mood/pipeline/keywords/ke.py
KE_KEYWORDS = {
    "finance": [
        "kenyan economy", "kenya gdp", "nse index",
        "nairobi stock exchange", "nse kenya",
        "central bank kenya", "cbk",
        "kenyan shilling", "kes",
        "kenyan inflation", "kenyan budget",
        "kenyan exports", "kenyan trade",
        "kenyan market", "kenyan growth",
        "kenyan debt", "kenyan deficit",
        "kenyan unemployment", "kenyan wages",
        "kenyan housing", "kenyan mortgage",
        "equity bank kenya", "kcb bank",
        "cooperative bank kenya", "ncba bank",
        "safaricom", "mpesa kenya",
        "kenya airways", "east african breweries",
        "kenyan business", "kenyan investment",
        "kenyan tourism", "kenyan manufacturing",
        "kenyan agriculture", "kenyan tea",
        "kenyan coffee", "kenyan flowers",
        "kenyan horticulture", "kenyan avocado",
        "kenyan eu trade", "kenya us trade",
        "kenyan tariffs", "kenyan fiscal",
        "kenyan pension fund", "nssf kenya",
        "kenyan industry", "kenyan startup",
        "kenyan fintech", "kenyan real estate",
        "kenyan construction", "kenyan remittances",
        "kenyan diaspora", "kenyan imf deal",
        "ruto economic policy",
        "kenyan tax protests",
    ],
    "geopolitics": [
        "kenyan foreign policy", "kenya nato",
        "kenyan sanctions", "kenyan diplomacy",
        "kenyan troops", "kenya ukraine",
        "kenya russia", "kenyan ambassador",
        "kenya eu", "kenyan defense",
        "kenyan military", "nairobi talks",
        "kenya security", "kenyan intelligence",
        "nis kenya", "kenya us relations",
        "kenya china relations", "kenya brics",
        "kenya africa union", "kenya igad",
        "kenya peacekeeping", "kenya un",
        "kenya somalia", "kenya ethiopia",
        "kenya south sudan", "kenya drc",
        "kenya au peace security",
        "ruto foreign policy",
        "kenya east africa community",
        "kenyan election observer",
        "kenya horn of africa",
    ],
    "energy": [
        "kenyan energy", "kenyan electricity",
        "kenyan renewables", "kenyan solar",
        "kenyan wind", "kenyan geothermal",
        "kenyan hydro", "kenyan grid",
        "kenyan climate", "kenyan emissions",
        "kenyan energy transition", "kenyan hydrogen",
        "kenyan lng", "kenyan energy prices",
        "kenyan energy security", "kenyan green energy",
        "kenyan carbon neutral", "kenyan net zero",
        "kenyan fuel prices", "kenyan oil",
        "kengen kenya", "kenya power",
        "kenyan offshore wind",
        "kenyan green hydrogen",
        "lake turkana wind kenya",
        "kenyan geothermal energy",
    ],
    "technology": [
        "kenyan tech", "nairobi tech", "kenyan startup",
        "kenyan ai", "kenyan fintech",
        "kenyan digital", "kenyan innovation",
        "kenyan unicorn", "kenyan cybersecurity",
        "kenyan gaming", "kenyan software",
        "kenyan it sector", "kenyan ecommerce",
        "kenyan digital economy", "kenyan semiconductor",
        "kenyan ev", "kenyan smart city",
        "kenyan medtech", "kenyan biotech",
        "kenyan 5g", "kenyan blockchain",
        "mpesa fintech", "safaricom tech",
        "kenyan silicon savannah",
        "ihub nairobi", "kenyan tech hub",
        "twiga foods kenya",
    ],
    "health": [
        "kenyan health", "kenyan hospital",
        "kenyan pharma", "kenyan vaccine",
        "kenyan healthcare", "kenyan mental health",
        "kenyan health system", "kenyan medicine",
        "kenyan public health", "kenyan wellbeing",
        "kenyan biotech", "kenyan cancer",
        "kenyan aging population",
        "kenyan malaria", "kenyan tuberculosis",
        "kenyan hiv", "kenyan cholera",
        "kenyan dengue", "kenyan mpox",
        "pharmacy board kenya",
        "kenyan health reform",
        "kenyan universal healthcare",
        "nhif kenya",
    ],
    "crime": [
        "kenyan corruption", "kenyan fraud",
        "kenyan scandal", "kenyan court",
        "kenyan investigation", "kenyan organized crime",
        "kenyan drug trafficking", "kenyan money laundering",
        "kenyan terrorism", "kenyan police",
        "kenyan gang", "kenyan anti corruption",
        "eacc kenya", "dci kenya",
        "kenyan cybercrime", "kenyan scam",
        "kenyan arrest", "kenyan mafia",
        "kenyan human trafficking",
        "kenyan protest", "kenyan riot",
        "kenyan political scandal",
        "al shabaab kenya",
        "kenyan election violence",
        "kenyan femicide",
        "kenyan gen z protest",
        "ruto corruption",
    ],
    "politics": [
        "national assembly kenya", "kenyan senate",
        "kenyan parliament", "kenyan election",
        "kenyan government", "kenyan minister",
        "kenyan president", "kenyan coalition",
        "kenyan opposition", "uba kenya",
        "william ruto", "ruto kenya",
        "odm kenya", "raila odinga",
        "azimio kenya", "jubilee party kenya",
        "kenyan policy", "kenyan reform",
        "kenyan immigration", "kenyan diaspora",
        "kenyan welfare", "kenyan citizenship",
        "kenyan referendum", "kenyan judiciary",
        "kenyan rule of law", "kenyan eu relations",
        "kenyan democracy", "kenyan media freedom",
        "kenyan press freedom", "kenyan constitution",
        "kenyan federalism", "kenyan counties",
        "kenyan devolution",
        "kenyan housing project ruto",
        "kenyan tax protest 2024",
        "au peace security kenya",
    ],
}

