
# mood/pipeline/keywords/kg.py
KG_KEYWORDS = {
    "finance": [
        "kyrgyzstan economy", "kyrgyzstan gdp",
        "kyrgyz stock exchange", "kse kyrgyzstan",
        "national bank kyrgyzstan", "nbkr",
        "kyrgyzstani som", "kgs",
        "kyrgyzstan inflation", "kyrgyzstan budget",
        "kyrgyzstan exports", "kyrgyzstan trade",
        "kyrgyzstan market", "kyrgyzstan growth",
        "kyrgyzstan debt", "kyrgyzstan deficit",
        "kyrgyzstan unemployment", "kyrgyzstan wages",
        "kyrgyzstan housing", "kyrgyzstan mortgage",
        "kyrgyzstan gold", "kyrgyzstan coal",
        "kyrgyzstan minerals", "kumtor gold mine",
        "kyrgyzstan agriculture", "kyrgyzstan livestock",
        "kyrgyzstan business", "kyrgyzstan investment",
        "kyrgyzstan tourism", "kyrgyzstan manufacturing",
        "kyrgyzstan eu funds", "kyrgyzstan industry",
        "kyrgyzstan startup", "kyrgyzstan fintech",
        "kyrgyzstan belt road", "kyrgyzstan logistics",
        "kyrgyzstan remittances", "kyrgyzstan diaspora",
        "kyrgyzstan kazakhstan cooperation",
    ],
    "geopolitics": [
        "kyrgyzstan foreign policy", "kyrgyzstan nato",
        "kyrgyzstan sanctions", "kyrgyzstan diplomacy",
        "kyrgyzstan troops", "kyrgyzstan ukraine",
        "kyrgyzstan russia", "kyrgyzstan ambassador",
        "kyrgyzstan eu", "kyrgyzstan defense",
        "kyrgyzstan military", "bishkek talks",
        "kyrgyzstan security", "kyrgyzstan intelligence",
        "kyrgyzstan china", "kyrgyzstan us relations",
        "kyrgyzstan csto", "kyrgyzstan sco",
        "kyrgyzstan central asia", "kyrgyzstan afghanistan",
        "kyrgyzstan peacekeeping", "kyrgyzstan un",
        "kyrgyzstan tajikistan border conflict",
        "kyrgyzstan uzbekistan border",
        "kyrgyzstan water dispute",
        "kyrgyzstan environmental cooperation",
        "manas air base kyrgyzstan",
    ],
    "energy": [
        "kyrgyzstan energy", "kyrgyzstan electricity",
        "kyrgyzstan renewables", "kyrgyzstan solar",
        "kyrgyzstan wind", "kyrgyzstan hydro",
        "kyrgyzstan grid", "kyrgyzstan climate",
        "kyrgyzstan emissions", "kyrgyzstan energy transition",
        "kyrgyzstan energy prices", "kyrgyzstan energy security",
        "kyrgyzstan coal", "kyrgyzstan gas",
        "kyrgyzstan carbon neutral", "kyrgyzstan net zero",
        "kyrgyzstan fuel prices", "kyrgyzstan power outage",
        "kyrgyzstan blackout", "kyrgyzstan energy crisis",
        "naryn river kyrgyzstan", "toktogul reservoir",
    ],
    "technology": [
        "kyrgyzstan tech", "bishkek tech",
        "kyrgyzstan startup", "kyrgyzstan ai",
        "kyrgyzstan fintech", "kyrgyzstan digital",
        "kyrgyzstan innovation", "kyrgyzstan cybersecurity",
        "kyrgyzstan software", "kyrgyzstan it sector",
        "kyrgyzstan ecommerce", "kyrgyzstan digital economy",
        "kyrgyzstan blockchain", "kyrgyzstan smart city",
        "kyrgyzstan 5g", "kyrgyzstan medtech",
        "kyrgyzstan digital transformation",
        "megacom kyrgyzstan", "beeline kyrgyzstan",
    ],
    "health": [
        "kyrgyzstan health", "kyrgyzstan hospital",
        "kyrgyzstan pharma", "kyrgyzstan vaccine",
        "kyrgyzstan healthcare", "kyrgyzstan mental health",
        "kyrgyzstan health system", "kyrgyzstan medicine",
        "kyrgyzstan public health", "kyrgyzstan wellbeing",
        "kyrgyzstan tuberculosis", "kyrgyzstan malaria",
        "kyrgyzstan cancer", "kyrgyzstan aging population",
        "kyrgyzstan traditional medicine",
        "kyrgyzstan health crisis",
    ],
    "crime": [
        "kyrgyzstan corruption", "kyrgyzstan fraud",
        "kyrgyzstan scandal", "kyrgyzstan court",
        "kyrgyzstan investigation", "kyrgyzstan organized crime",
        "kyrgyzstan drug trafficking", "kyrgyzstan money laundering",
        "kyrgyzstan terrorism", "kyrgyzstan police",
        "kyrgyzstan gang", "kyrgyzstan anti corruption",
        "kyrgyzstan cybercrime", "kyrgyzstan scam",
        "kyrgyzstan arrest", "kyrgyzstan human trafficking",
        "kyrgyzstan protest", "kyrgyzstan riot",
        "kyrgyzstan political prisoner",
        "kyrgyzstan coup", "kyrgyzstan unrest",
        "kyrgyzstan border conflict",
    ],
    "politics": [
        "jogorku kenesh", "kyrgyzstan parliament",
        "kyrgyzstan election", "kyrgyzstan government",
        "kyrgyzstan minister", "kyrgyzstan president",
        "sdpk kyrgyzstan", "mekenim kyrgyzstan",
        "sadyr japarov", "japarov",
        "kyrgyzstan policy", "kyrgyzstan reform",
        "kyrgyzstan immigration", "kyrgyzstan diaspora",
        "kyrgyzstan welfare", "kyrgyzstan citizenship",
        "kyrgyzstan referendum", "kyrgyzstan judiciary",
        "kyrgyzstan rule of law", "kyrgyzstan eu relations",
        "kyrgyzstan democracy", "kyrgyzstan media freedom",
        "kyrgyzstan press freedom", "kyrgyzstan constitution",
        "kyrgyzstan political instability",
        "kyrgyzstan revolution history",
    ],
}
