
# mood/pipeline/keywords/kr.py
KR_KEYWORDS = {
    "finance": [
        "south korean economy", "korea gdp", "kospi",
        "korea stock exchange", "krx korea",
        "bank of korea", "bok korea",
        "korean won", "krw",
        "korean inflation", "korean budget", "korean exports",
        "korean trade", "korean market", "korean growth",
        "korean debt", "korean deficit", "korean unemployment",
        "korean wages", "korean housing", "korean mortgage",
        "samsung electronics", "lg electronics", "hyundai",
        "kia motors", "sk hynix", "posco",
        "kb financial", "shinhan bank", "hana bank",
        "korean business", "korean investment",
        "korean tourism", "korean manufacturing",
        "korean automotive", "korean semiconductor",
        "korean shipbuilding", "korean steel",
        "korean eu trade", "korea us trade",
        "korean tariffs", "korean fiscal",
        "korean pension fund", "nps korea",
        "korean chaebol", "korean conglomerate",
        "korean startup", "korean unicorn",
        "korean fintech", "korean real estate",
        "korean construction", "korean logistics",
    ],
    "geopolitics": [
        "south korean foreign policy", "korea nato",
        "korean sanctions", "korean diplomacy",
        "korean troops", "korea ukraine", "korea russia",
        "korean ambassador", "korea eu",
        "korean defense", "korean military",
        "seoul talks", "korea security",
        "korean intelligence", "nis korea",
        "north korea", "dprk", "kim jong un",
        "korean peninsula", "dmz korea",
        "korea us alliance", "usfk",
        "korea japan relations", "korea china",
        "korea taiwan strait", "korean reunification",
        "north korean missile", "north korean nuclear",
        "trump kim talks", "korean summit",
        "korea middle east", "korean peacekeeping",
        "korea un", "korean nato partner",
    ],
    "energy": [
        "korean energy", "korean nuclear",
        "korean electricity", "korean renewables",
        "korean solar", "korean wind", "korean hydro",
        "korean grid", "korean climate",
        "korean emissions", "korean energy transition",
        "korean hydrogen", "korean lng",
        "korean energy prices", "korean energy security",
        "korean offshore wind", "korean green energy",
        "korean coal", "korean natural gas",
        "kepco korea", "korean carbon neutral",
        "korean net zero", "korean fuel prices",
        "korean nuclear plant", "korean smr",
        "korean battery", "korean ev battery",
    ],
    "technology": [
        "korean tech", "seoul tech", "korean startup",
        "korean ai", "korean semiconductor",
        "samsung chip", "sk hynix chip",
        "korean digital", "korean innovation",
        "korean robotics", "korean ev",
        "korean battery", "korean quantum",
        "korean cybersecurity", "korean gaming",
        "korean software", "korean it sector",
        "korean unicorn", "korean fintech",
        "korean space", "kari korea",
        "korean 5g", "korean display",
        "lg display", "samsung display",
        "korean medtech", "korean biotech",
        "kakao korea", "naver korea",
        "korean webtoon", "korean content",
    ],
    "health": [
        "korean health", "korean hospital",
        "korean pharma", "celltrion",
        "samsung biologics", "korean vaccine",
        "korean healthcare", "korean mental health",
        "korean health system", "korean medicine",
        "korean public health", "korean wellbeing",
        "korean biotech", "korean cancer",
        "korean aging population", "korean birthrate",
        "korean traditional medicine",
        "moh korea", "korean dementia",
    ],
    "crime": [
        "korean corruption", "korean fraud",
        "korean scandal", "korean court",
        "korean investigation", "korean organized crime",
        "korean drug trafficking", "korean money laundering",
        "korean terrorism", "korean police",
        "korean gang", "korean anti corruption",
        "acrc korea", "korean cybercrime",
        "korean scam", "korean arrest",
        "korean impeachment", "korean political scandal",
        "korean protest", "korean riot",
    ],
    "politics": [
        "national assembly korea", "korean parliament",
        "korean election", "korean government",
        "korean minister", "korean prime minister",
        "korean president", "korean coalition",
        "korean opposition", "people power party",
        "democratic party korea", "yoon suk yeol",
        "yoon", "lee jae myung",
        "korean policy", "korean reform",
        "korean immigration", "korean welfare",
        "korean citizenship", "korean referendum",
        "korean judiciary", "korean rule of law",
        "korean democracy", "korean media freedom",
        "korean press freedom", "korean constitution",
        "korean martial law", "korean impeachment",
        "korean constitutional court",
    ],
}