

# mood/pipeline/keywords/kw.py
KW_KEYWORDS = {
    "finance": [
        "kuwait economy", "kuwait gdp",
        "boursa kuwait", "kuwait stock exchange",
        "central bank kuwait", "cbk",
        "kuwaiti dinar", "kwd",
        "kuwait inflation", "kuwait budget",
        "kuwait exports", "kuwait trade",
        "kuwait market", "kuwait growth",
        "kuwait debt", "kuwait surplus",
        "kuwait unemployment", "kuwait wages",
        "kuwait housing", "kuwait mortgage",
        "national bank kuwait", "nbk",
        "kuwait finance house", "kfh",
        "gulf bank kuwait", "burgan bank",
        "kuwait petroleum", "kpc",
        "knpc kuwait", "kufpec",
        "kuwait investment authority", "kia kuwait",
        "kuwait sovereign wealth fund",
        "kuwait business", "kuwait investment",
        "kuwait tourism", "kuwait manufacturing",
        "kuwait vision 2035", "kuwait diversification",
        "kuwait eu trade", "kuwait us trade",
        "kuwait tariffs", "kuwait fiscal",
        "kuwait oil revenue", "kuwait oil production",
        "opec kuwait", "kuwait oil price",
    ],
    "geopolitics": [
        "kuwait foreign policy", "kuwait nato",
        "kuwait sanctions", "kuwait diplomacy",
        "kuwait troops", "kuwait ukraine", "kuwait russia",
        "kuwait ambassador", "kuwait eu",
        "kuwait defense", "kuwait military",
        "kuwait city talks", "kuwait security",
        "kuwait intelligence", "kuwait us relations",
        "kuwait us base", "kuwait iran relations",
        "kuwait israel", "kuwait middle east",
        "kuwait gulf", "kuwait saudi relations",
        "kuwait gcc", "kuwait qatar",
        "kuwait peacekeeping", "kuwait un",
        "kuwait iraq relations", "kuwait border",
        "kuwait china relations", "kuwait india",
        "gulf security kuwait", "kuwait strait hormuz",
        "middle east monitor", "gulf states security",
    ],
    "energy": [
        "kuwait energy", "kuwait oil", "kuwait gas",
        "kuwait petroleum", "kuwait electricity",
        "kuwait renewables", "kuwait solar",
        "kuwait grid", "kuwait climate",
        "kuwait emissions", "kuwait energy transition",
        "kuwait hydrogen", "kuwait lng",
        "kuwait energy prices", "kuwait energy security",
        "kuwait green energy", "kuwait carbon neutral",
        "kuwait net zero", "kuwait fuel prices",
        "kuwait oil production", "opec kuwait",
        "kuwait oil reserves", "kuwait refinery",
        "kuwait petrochemical", "kuwait energy 2035",
    ],
    "technology": [
        "kuwait tech", "kuwait startup",
        "kuwait ai", "kuwait fintech", "kuwait digital",
        "kuwait innovation", "kuwait cybersecurity",
        "kuwait software", "kuwait it sector",
        "kuwait ecommerce", "kuwait digital economy",
        "kuwait smart city", "kuwait medtech",
        "kuwait blockchain", "kuwait 5g",
        "kuwait digital transformation",
        "kuwait vision 2035 tech",
        "zain kuwait", "ooredoo kuwait",
    ],
    "health": [
        "kuwait health", "kuwait hospital",
        "kuwait pharma", "kuwait vaccine",
        "kuwait healthcare", "kuwait mental health",
        "kuwait health system", "kuwait medicine",
        "kuwait public health", "kuwait wellbeing",
        "kuwait biotech", "kuwait cancer",
        "kuwait aging population",
        "kuwait health ministry",
        "kuwait medical tourism",
    ],
    "crime": [
        "kuwait corruption", "kuwait fraud",
        "kuwait scandal", "kuwait court",
        "kuwait investigation", "kuwait organized crime",
        "kuwait drug trafficking", "kuwait money laundering",
        "kuwait terrorism", "kuwait police",
        "kuwait gang", "kuwait anti corruption",
        "kuwait cybercrime", "kuwait scam",
        "kuwait arrest", "kuwait human trafficking",
        "kuwait migrant workers", "kuwait kafala",
        "kuwait political prisoner",
    ],
    "politics": [
        "national assembly kuwait", "kuwait parliament",
        "kuwait election", "kuwait government",
        "kuwait minister", "kuwait prime minister",
        "kuwait emir", "kuwait crown prince",
        "mishal al ahmad", "kuwait royal family",
        "kuwait policy", "kuwait reform",
        "kuwait immigration", "kuwait integration",
        "kuwait welfare", "kuwait citizenship",
        "kuwait judiciary", "kuwait rule of law",
        "kuwait democracy", "kuwait media freedom",
        "kuwait press freedom", "kuwait constitution",
        "kuwait human rights", "kuwait labour reform",
        "kuwait expat population", "kuwait bidun",
        "kuwait political crisis",
        "kuwait dissolved parliament",
    ],
}
