
# mood/pipeline/keywords/kz.py
KZ_KEYWORDS = {
    "finance": [
        "kazakhstan economy", "kazakhstan gdp",
        "astana international exchange", "aix kazakhstan",
        "national bank kazakhstan", "nbk",
        "kazakhstani tenge", "kzt",
        "kazakhstan inflation", "kazakhstan budget",
        "kazakhstan exports", "kazakhstan trade",
        "kazakhstan market", "kazakhstan growth",
        "kazakhstan debt", "kazakhstan deficit",
        "kazakhstan unemployment", "kazakhstan wages",
        "kazatomprom", "kazakhmys", "halyk bank",
        "kaspi bank", "kcell kazakhstan",
        "kazakhstan oil", "tengiz oil",
        "kashagan oil", "karachaganak",
        "kazakhstan business", "kazakhstan investment",
        "kazakhstan tourism", "kazakhstan manufacturing",
        "kazakhstan agriculture", "kazakhstan wheat",
        "kazakhstan eu funds", "kazakhstan industry",
        "kazakhstan startup", "kazakhstan fintech",
        "kazakhstan belt road", "kazakhstan logistics",
    ],
    "geopolitics": [
        "kazakhstan foreign policy", "kazakhstan nato",
        "kazakhstan sanctions", "kazakhstan diplomacy",
        "kazakhstan troops", "kazakhstan ukraine",
        "kazakhstan russia", "kazakhstan ambassador",
        "kazakhstan eu", "kazakhstan defense",
        "kazakhstan military", "astana talks",
        "kazakhstan security", "kazakhstan intelligence",
        "kazakhstan china", "kazakhstan us relations",
        "kazakhstan csto", "kazakhstan sco",
        "kazakhstan central asia", "kazakhstan caspian",
        "kazakhstan peacekeeping", "kazakhstan un",
        "kazakhstan constitutional referendum",
    ],
    "energy": [
        "kazakhstan energy", "kazakhstan oil",
        "kazakhstan gas", "kazakhstan electricity",
        "kazakhstan renewables", "kazakhstan solar",
        "kazakhstan wind", "kazakhstan hydro",
        "kazakhstan grid", "kazakhstan climate",
        "kazakhstan emissions", "kazakhstan energy transition",
        "kazakhstan lng", "kazakhstan energy prices",
        "kazakhstan energy security", "kazakhstan uranium",
        "kazatomprom uranium", "kazakhstan nuclear",
        "kazakhstan pipeline", "cpc pipeline",
        "kazakhstan carbon neutral",
    ],
    "technology": [
        "kazakhstan tech", "astana tech", "kazakhstan startup",
        "kazakhstan ai", "kazakhstan fintech",
        "kazakhstan digital", "kazakhstan innovation",
        "kazakhstan cybersecurity", "kazakhstan software",
        "kazakhstan it sector", "kaspi tech",
        "kazakhstan digital economy", "kazakhstan blockchain",
        "kazakhstan smart city", "kazakhstan 5g",
    ],
    "health": [
        "kazakhstan health", "kazakhstan hospital",
        "kazakhstan pharma", "kazakhstan vaccine",
        "kazakhstan healthcare", "kazakhstan mental health",
        "kazakhstan health system", "kazakhstan medicine",
        "kazakhstan public health", "kazakhstan wellbeing",
        "kazakhstan biotech", "kazakhstan cancer",
    ],
    "crime": [
        "kazakhstan corruption", "kazakhstan fraud",
        "kazakhstan scandal", "kazakhstan court",
        "kazakhstan investigation", "kazakhstan organized crime",
        "kazakhstan drug trafficking", "kazakhstan money laundering",
        "kazakhstan terrorism", "kazakhstan police",
        "kazakhstan anti corruption", "kazakhstan protest",
        "kazakhstan january events", "kazakhstan unrest",
    ],
    "politics": [
        "majilis kazakhstan", "kazakhstan parliament",
        "kazakhstan election", "kazakhstan government",
        "kazakhstan minister", "kazakhstan president",
        "nur otan", "amanat party",
        "kassym jomart tokayev", "tokayev",
        "kazakhstan policy", "kazakhstan reform",
        "kazakhstan immigration", "kazakhstan welfare",
        "kazakhstan citizenship", "kazakhstan referendum",
        "kazakhstan judiciary", "kazakhstan democracy",
        "kazakhstan media freedom", "kazakhstan constitution",
    ],
}