
# mood/pipeline/keywords/lt.py
LT_KEYWORDS = {
    "finance": [
        "lithuanian economy", "lithuania gdp", "omx vilnius",
        "vilnius stock exchange", "nasdaq vilnius",
        "bank of lithuania", "lietuvos bankas",
        "lithuanian euro", "lithuanian inflation",
        "lithuanian budget", "lithuanian exports",
        "lithuanian trade", "lithuanian market",
        "lithuanian growth", "lithuanian debt",
        "lithuanian deficit", "lithuanian unemployment",
        "lithuanian wages", "lithuanian housing",
        "lithuanian mortgage", "luminor lithuania",
        "seb lithuania", "swedbank lithuania",
        "siauliu bankas", "medicinos bankas",
        "lithuanian business", "lithuanian investment",
        "lithuanian tourism", "lithuanian manufacturing",
        "lithuanian logistics", "lithuanian agriculture",
        "lithuanian eu funds", "lithuanian recovery plan",
        "lithuanian pension fund", "lithuanian industry",
        "lithuanian it sector", "lithuanian startup",
        "lithuanian laser", "lithuanian fintech",
        "klaipeda port", "lithuanian shipping",
        "lithuanian furniture", "lithuanian food exports",
        "ignitis group", "lithuanian energy revenue",
        "rail baltica lithuania",
    ],
    "geopolitics": [
        "lithuanian foreign policy", "lithuania nato",
        "lithuanian sanctions", "lithuanian diplomacy",
        "lithuanian troops", "lithuania ukraine",
        "lithuania russia", "lithuanian ambassador",
        "lithuania eu", "lithuanian defense",
        "lithuanian military", "vilnius talks",
        "lithuania security", "lithuanian intelligence",
        "vsd lithuania", "suwalki gap",
        "kaliningrad lithuania", "lithuanian nato membership",
        "lithuanian security policy", "lithuania middle east",
        "lithuanian peacekeeping", "lithuanian independence",
        "russian minority lithuania", "lithuania occupation",
        "rail baltica geopolitics", "lithuanian arms ukraine",
        "lithuanian weapons ukraine", "ukraine weapons lithuania",
        "lithuanian foreign minister", "gabrielius landsbergis",
        "russian oil sanctions lithuania",
    ],
    "energy": [
        "lithuanian energy", "lithuanian electricity",
        "lithuanian renewables", "lithuanian wind",
        "lithuanian solar", "lithuanian hydro",
        "lithuanian grid", "lithuanian climate",
        "lithuanian emissions", "lithuanian energy transition",
        "lithuanian hydrogen", "klaipeda lng",
        "lithuanian energy security", "lithuanian energy prices",
        "lithuanian offshore wind", "lithuanian green energy",
        "ignitis energy", "amber grid",
        "lithuanian biomass", "lithuanian district heating",
        "lithuanian gas", "litgrid",
        "baltic energy independence",
    ],
    "technology": [
        "lithuanian tech", "vilnius tech", "lithuanian startup",
        "lithuanian ai", "lithuanian fintech", "lithuanian digital",
        "lithuanian innovation", "lithuanian unicorn",
        "lithuanian cybersecurity", "lithuanian gaming",
        "lithuanian software", "lithuanian it sector",
        "lithuanian outsourcing", "lithuanian semiconductor",
        "lithuanian quantum", "lithuanian blockchain",
        "lithuanian e-government", "lithuanian digital identity",
        "vinted lithuania", "kevin lithuania",
        "lithuanian medtech", "lithuanian cleantech",
        "kaunas tech", "ktu lithuania",
    ],
    "health": [
        "lithuanian health", "lithuanian hospital",
        "lithuanian pharma", "lithuanian vaccine",
        "lithuanian healthcare", "lithuanian mental health",
        "lithuanian health system", "lithuanian medicine",
        "lithuanian health insurance", "vlk lithuania",
        "lithuanian public health", "lithuanian wellbeing",
        "vilnius university hospital", "lithuanian genetics",
        "lithuanian biobank", "lithuanian medical tourism",
        "lithuanian suicide rate", "lithuanian cancer",
    ],
    "crime": [
        "lithuanian corruption", "lithuanian fraud",
        "lithuanian scandal", "lithuanian court",
        "lithuanian investigation", "lithuanian organized crime",
        "lithuanian drug trafficking", "lithuanian money laundering",
        "lithuanian terrorism", "lithuanian police",
        "lietuvos policija", "lithuanian gang",
        "lithuanian anti corruption", "sttt lithuania",
        "lithuanian smuggling", "lithuanian cybercrime",
        "lithuanian scam", "lithuanian banking fraud",
        "lithuanian serious crimes", "lithuanian prosecution",
        "lithuanian amber theft",
    ],
    "politics": [
        "seimas", "lithuanian parliament",
        "lithuanian election", "lithuanian government",
        "lithuanian minister", "lithuanian prime minister",
        "lithuanian coalition", "lithuanian opposition",
        "ts lkd", "homeland union lithuania",
        "vilija blinkeviciute", "ingrida simonyte",
        "gitanas nauseda", "social democrats lithuania",
        "lvzs lithuania", "dp lithuania",
        "lithuanian policy", "lithuanian reform",
        "lithuanian immigration", "lithuanian integration",
        "lithuanian welfare", "lithuanian citizenship",
        "lithuanian referendum", "lithuanian judiciary",
        "lithuanian rule of law", "lithuanian eu relations",
        "lithuanian democracy", "lithuanian president",
        "lithuanian media freedom",
        "russian speaking minority lithuania",
        "lithuanian language policy",
        "lithuanian nato spending",
        "lithuanian prime minister ruginiene",
        "inga ruginiene",
    ],
}

