
# mood/pipeline/keywords/lv.py
LV_KEYWORDS = {
    "finance": [
        "latvian economy", "latvia gdp", "omx riga",
        "riga stock exchange", "nasdaq riga",
        "bank of latvia", "latvijas banka",
        "latvian euro", "latvian inflation",
        "latvian budget", "latvian exports",
        "latvian trade", "latvian market",
        "latvian growth", "latvian debt",
        "latvian deficit", "latvian unemployment",
        "latvian wages", "latvian housing",
        "latvian mortgage", "luminor latvia",
        "signet bank", "swedbank latvia",
        "seb latvia", "citadele bank",
        "latvian business", "latvian investment",
        "latvian tourism", "latvian manufacturing",
        "latvian logistics", "latvian agriculture",
        "latvian eu funds", "latvian recovery plan",
        "latvian pension fund", "latvian industry",
        "latvian it sector", "latvian startup",
        "latvian timber", "latvian pharma",
        "riga port", "latvian shipping",
        "latvian trade stats", "latvian retail",
        "temu latvia", "latvian postal service",
        "latvijas pasts",
    ],
    "geopolitics": [
        "latvian foreign policy", "latvia nato",
        "latvian sanctions", "latvian diplomacy",
        "latvian troops", "latvia ukraine", "latvia russia",
        "latvian ambassador", "latvia eu",
        "latvian defense", "latvian military",
        "riga talks", "latvia security",
        "latvian intelligence", "latvian sab",
        "latvia russia border", "latvian nato membership",
        "latvian security policy", "latvia middle east",
        "latvian peacekeeping", "latvian independence",
        "russian minority latvia", "latvia occupation",
        "latvian occupation museum", "venice biennale latvia",
        "rail baltica latvia",
    ],
    "energy": [
        "latvian energy", "latvian electricity",
        "latvian renewables", "latvian wind",
        "latvian solar", "latvian hydro",
        "latvian grid", "latvian climate",
        "latvian emissions", "latvian energy transition",
        "latvian hydrogen", "latvian lng",
        "latvian energy security", "latvian energy prices",
        "latvian offshore wind", "latvian green energy",
        "latvenergo", "augstsprieguma tikls",
        "latvian biomass", "latvian district heating",
        "latvian gas", "conexus baltic grid",
    ],
    "technology": [
        "latvian tech", "riga tech", "latvian startup",
        "latvian ai", "latvian fintech", "latvian digital",
        "latvian innovation", "latvian unicorn",
        "latvian cybersecurity", "latvian gaming",
        "latvian software", "latvian it sector",
        "latvian outsourcing", "latvian semiconductor",
        "latvian quantum", "latvian blockchain",
        "latvian e-government", "latvian digital identity",
        "sonarworks latvia", "mikrotik latvia",
        "latvian medtech", "latvian cleantech",
    ],
    "health": [
        "latvian health", "latvian hospital",
        "latvian pharma", "latvian vaccine",
        "latvian healthcare", "latvian mental health",
        "latvian health system", "latvian medicine",
        "latvian health insurance", "nhi latvia",
        "latvian public health", "latvian wellbeing",
        "riga stradins university", "latvian genetics",
        "latvian biobank", "latvian medical tourism",
    ],
    "crime": [
        "latvian corruption", "latvian fraud",
        "latvian scandal", "latvian court",
        "latvian investigation", "latvian organized crime",
        "latvian drug trafficking", "latvian money laundering",
        "latvian terrorism", "latvian police",
        "latvijas policija", "latvian gang",
        "latvian anti corruption", "knab latvia",
        "latvian smuggling", "latvian cybercrime",
        "latvian scam", "latvian banking fraud",
        "latvian serious crimes", "latvian prosecution",
    ],
    "politics": [
        "saeima", "latvian parliament",
        "latvian election", "latvian government",
        "latvian minister", "latvian prime minister",
        "latvian coalition", "latvian opposition",
        "jv latvia", "evika silina",
        "ap latvia", "edgars rinkevics",
        "na latvia", "inese lesinska",
        "latvian policy", "latvian reform",
        "latvian immigration", "latvian integration",
        "latvian welfare", "latvian citizenship",
        "latvian referendum", "latvian judiciary",
        "latvian rule of law", "latvian eu relations",
        "latvian democracy", "latvian president",
        "latvian media freedom",
        "russian speaking minority latvia",
        "latvian language policy",
        "latvian schengen", "latvian nato spending",
    ],
}

