
# mood/pipeline/keywords/ly.py
LY_KEYWORDS = {
    "finance": [
        "libyan economy", "libya gdp",
        "libyan stock exchange", "lse libya",
        "central bank libya", "cbl",
        "libyan dinar", "lyd",
        "libyan inflation", "libyan budget",
        "libyan exports", "libyan trade",
        "libyan market", "libyan growth",
        "libyan debt", "libyan deficit",
        "libyan unemployment", "libyan wages",
        "libyan housing", "libyan reconstruction",
        "sahara bank libya", "wahda bank",
        "national commercial bank libya",
        "libyan oil revenue", "libyan gas revenue",
        "noc libya", "national oil corporation",
        "libyan business", "libyan investment",
        "libyan tourism", "libyan manufacturing",
        "libyan agriculture", "libyan dates",
        "libyan eu trade", "libya us trade",
        "libyan tariffs", "libyan fiscal",
        "libyan pension fund", "libyan industry",
        "libyan reconstruction fund",
        "libyan remittances", "libyan diaspora",
        "libyan oil fields", "libyan oil output",
        "atib bank libya",
        "majaal libya",
        "xtreme libya",
    ],
    "geopolitics": [
        "libyan foreign policy", "libya nato",
        "libyan sanctions", "libyan diplomacy",
        "libyan troops", "libya ukraine",
        "libya russia", "libyan ambassador",
        "libya eu", "libyan defense",
        "libyan military", "tripoli talks",
        "libya security", "libyan intelligence",
        "libya us relations", "libya china",
        "libya brics", "libya africa union",
        "libya arab league", "libya peacekeeping",
        "libya un", "libya civil war",
        "libyan conflict", "gnna libya",
        "libyan national army", "lna khalifa haftar",
        "haftar libya", "dbeibah libya",
        "libya turkey", "libya russia wagner",
        "libya egypt relations", "libya tunisia",
        "libya algeria", "libya migration",
        "libyan coast guard", "libyan migration crisis",
        "un envoy libya",
        "libya iran",
        "libyan ceasefire",
    ],
    "energy": [
        "libyan energy", "libyan oil", "noc libya",
        "libyan gas", "libyan electricity",
        "libyan renewables", "libyan solar",
        "libyan grid", "libyan climate",
        "libyan emissions", "libyan energy transition",
        "libyan energy prices", "libyan energy security",
        "libyan oil production", "libyan oil fields",
        "sharara oil field", "el feel oil field",
        "libyan oil exports", "libyan refinery",
        "libyan petrochemical", "libyan pipeline",
        "libyan energy crisis",
        "libyan power outage",
        "libyan oil revenue",
    ],
    "technology": [
        "libyan tech", "tripoli tech", "libyan startup",
        "libyan ai", "libyan fintech",
        "libyan digital", "libyan innovation",
        "libyan cybersecurity", "libyan software",
        "libyan it sector", "libyan ecommerce",
        "libyan digital economy", "libyan 5g",
        "libyan blockchain", "libyan internet",
        "libyan digital transformation",
        "libyana telecom", "lptic libya",
        "libyan connectivity",
    ],
    "health": [
        "libyan health", "libyan hospital",
        "libyan pharma", "libyan vaccine",
        "libyan healthcare", "libyan mental health",
        "libyan health system", "libyan medicine",
        "libyan public health", "libyan wellbeing",
        "libyan cancer", "libyan aging population",
        "libyan health crisis", "libyan medical aid",
        "libyan war wounded", "libyan casualties",
        "libyan flood health", "libyan derna flood",
        "who libya", "libyan disease outbreak",
        "libyan medical evacuation",
    ],
    "crime": [
        "libyan corruption", "libyan fraud",
        "libyan scandal", "libyan court",
        "libyan investigation", "libyan organized crime",
        "libyan drug trafficking", "libyan money laundering",
        "libyan terrorism", "libyan police",
        "libyan gang", "libyan anti corruption",
        "libyan cybercrime", "libyan scam",
        "libyan arrest", "libyan militia",
        "libyan human trafficking",
        "libyan protest", "libyan riot",
        "libyan political prisoner",
        "libyan war crimes",
        "libyan smuggling",
        "libyan kidnapping",
        "wagner libya",
        "libyan arms trafficking",
    ],
    "politics": [
        "libyan parliament", "libyan election",
        "libyan government", "libyan minister",
        "libyan prime minister", "libyan coalition",
        "libyan opposition", "gnu libya",
        "government national unity libya",
        "abdul hamid dbeibah", "dbeibah",
        "khalifa haftar", "haftar",
        "house of representatives libya",
        "libyan high state council",
        "libyan policy", "libyan reform",
        "libyan immigration", "libyan refugees",
        "libyan welfare", "libyan citizenship",
        "libyan referendum", "libyan judiciary",
        "libyan rule of law", "libyan eu relations",
        "libyan democracy", "libyan media freedom",
        "libyan press freedom", "libyan constitution",
        "libyan political crisis",
        "libyan reconciliation",
        "libyan unity government",
        "un support mission libya",
        "unsmil libya",
        "libyan election dispute",
    ],
}