
# mood/pipeline/keywords/ma.py
MA_KEYWORDS = {
    "finance": [
        "moroccan economy", "morocco gdp", "masi index",
        "casablanca stock exchange", "bvc morocco",
        "bank al maghrib", "bam morocco",
        "moroccan dirham", "mad",
        "moroccan inflation", "moroccan budget",
        "moroccan exports", "moroccan trade",
        "moroccan market", "moroccan growth",
        "moroccan debt", "moroccan deficit",
        "moroccan unemployment", "moroccan wages",
        "moroccan housing", "moroccan mortgage",
        "attijariwafa bank", "bmce bank",
        "banque populaire morocco", "cih bank",
        "ocp group", "maroc telecom",
        "royal air maroc", "bmw morocco",
        "moroccan business", "moroccan investment",
        "moroccan tourism", "moroccan manufacturing",
        "moroccan phosphate", "moroccan agriculture",
        "moroccan argan oil", "moroccan citrus",
        "moroccan fisheries", "moroccan textiles",
        "moroccan eu trade", "morocco us trade",
        "moroccan tariffs", "moroccan fiscal",
        "moroccan pension fund", "moroccan industry",
        "moroccan startup", "moroccan fintech",
        "moroccan real estate", "moroccan construction",
        "moroccan remittances", "moroccan diaspora",
        "morocco imf", "moroccan economic growth",
        "akhannouch economic policy",
        "morocco atlantic hub",
    ],
    "geopolitics": [
        "moroccan foreign policy", "morocco nato",
        "moroccan sanctions", "moroccan diplomacy",
        "moroccan troops", "morocco ukraine",
        "morocco russia", "moroccan ambassador",
        "morocco eu", "moroccan defense",
        "moroccan military", "rabat talks",
        "morocco security", "moroccan intelligence",
        "dged morocco", "morocco us relations",
        "morocco china relations", "morocco brics",
        "morocco africa union", "morocco arab league",
        "morocco peacekeeping", "morocco un",
        "morocco israel", "morocco abraham accords",
        "morocco algeria conflict", "western sahara",
        "polisario front", "morocco sahara",
        "morocco spain relations", "morocco eu migration",
        "morocco ceuta melilla",
        "akhannouch foreign policy",
        "morocco atlantic alliance",
        "morocco iran",
    ],
    "energy": [
        "moroccan energy", "moroccan electricity",
        "moroccan renewables", "moroccan solar",
        "moroccan wind", "moroccan hydro",
        "moroccan grid", "moroccan climate",
        "moroccan emissions", "moroccan energy transition",
        "moroccan hydrogen", "moroccan lng",
        "moroccan energy prices", "moroccan energy security",
        "moroccan green energy", "moroccan carbon neutral",
        "moroccan net zero", "moroccan fuel prices",
        "moroccan gas", "moroccan oil",
        "noor solar morocco", "ouarzazate solar",
        "moroccan green hydrogen",
        "moroccan offshore wind",
        "morocco energy hub africa",
        "onee morocco",
    ],
    "technology": [
        "moroccan tech", "casablanca tech",
        "moroccan startup", "moroccan ai",
        "moroccan fintech", "moroccan digital",
        "moroccan innovation", "moroccan unicorn",
        "moroccan cybersecurity", "moroccan gaming",
        "moroccan software", "moroccan it sector",
        "moroccan ecommerce", "moroccan digital economy",
        "moroccan semiconductor", "moroccan ev",
        "moroccan smart city", "moroccan medtech",
        "moroccan biotech", "moroccan 5g",
        "moroccan blockchain",
        "moroccan digital transformation",
        "inwi morocco", "maroc telecom tech",
        "morocco digital hub africa",
        "technopark casablanca",
    ],
    "health": [
        "moroccan health", "moroccan hospital",
        "moroccan pharma", "moroccan vaccine",
        "moroccan healthcare", "moroccan mental health",
        "moroccan health system", "moroccan medicine",
        "moroccan public health", "moroccan wellbeing",
        "moroccan biotech", "moroccan cancer",
        "moroccan aging population",
        "moroccan dengue", "moroccan malaria",
        "moroccan health reform",
        "moroccan universal health coverage",
        "moroccan medical tourism",
        "moroccan earthquake health",
        "laylat al qadr morocco",
    ],
    "crime": [
        "moroccan corruption", "moroccan fraud",
        "moroccan scandal", "moroccan court",
        "moroccan investigation", "moroccan organized crime",
        "moroccan drug trafficking", "moroccan money laundering",
        "moroccan terrorism", "moroccan police",
        "moroccan gang", "moroccan anti corruption",
        "moroccan cybercrime", "moroccan scam",
        "moroccan arrest", "moroccan mafia",
        "moroccan human trafficking",
        "moroccan protest", "moroccan riot",
        "moroccan political scandal",
        "moroccan jihadist",
        "moroccan migration crime",
        "moroccan femicide",
    ],
    "politics": [
        "chambre des representants morocco",
        "moroccan parliament", "moroccan election",
        "moroccan government", "moroccan minister",
        "moroccan prime minister", "moroccan king",
        "king mohammed vi", "moroccan royal family",
        "rnp morocco", "aziz akhannouch",
        "pjd morocco", "istiqlal morocco",
        "moroccan policy", "moroccan reform",
        "moroccan immigration", "moroccan diaspora",
        "moroccan welfare", "moroccan citizenship",
        "moroccan referendum", "moroccan judiciary",
        "moroccan rule of law", "moroccan eu relations",
        "moroccan democracy", "moroccan media freedom",
        "moroccan press freedom", "moroccan constitution",
        "moroccan federalism", "moroccan regions",
        "moroccan autonomy plan",
        "western sahara politics",
        "moroccan world cup 2030",
        "morocco 2030 football",
    ],
}
