
# mood/pipeline/keywords/md.py
MD_KEYWORDS = {
    "finance": [
        "moldovan economy", "moldova gdp",
        "moldova stock exchange", "moldovan capital market",
        "national bank moldova", "bnm moldova",
        "moldovan leu", "mdl",
        "moldovan inflation", "moldovan budget",
        "moldovan exports", "moldovan trade",
        "moldovan market", "moldovan growth",
        "moldovan debt", "moldovan deficit",
        "moldovan unemployment", "moldovan wages",
        "moldovan housing", "moldovan mortgage",
        "moldovan agriculture", "moldovan wine",
        "moldovan fruit exports", "moldovan food",
        "moldovan eu funds", "moldovan recovery plan",
        "moldovan pension fund", "moldovan industry",
        "moldovan it sector", "moldovan startup",
        "moldovan outsourcing", "moldovan remittances",
        "moldovan diaspora remittances",
        "moldovan banking", "maib moldova",
        "victoriabank moldova", "moldindconbank",
        "moldovan tourism", "moldovan construction",
        "moldovan eu accession funds",
    ],
    "geopolitics": [
        "moldovan foreign policy", "moldova nato",
        "moldovan sanctions", "moldovan diplomacy",
        "moldovan troops", "moldova ukraine",
        "moldova russia", "moldovan ambassador",
        "moldova eu", "moldovan defense",
        "moldovan military", "chisinau talks",
        "moldova security", "moldovan intelligence",
        "sis moldova", "transnistria",
        "transnistrian conflict", "moldovan border",
        "russian influence moldova",
        "moldovan pro western", "moldova eu accession",
        "moldovan volunteers ukraine",
        "moldova needy help",
        "moldova osce chairmanship",
        "gagauzia moldova", "moldovan sovereignty",
        "moldova nato partnership",
    ],
    "energy": [
        "moldovan energy", "moldovan electricity",
        "moldovan gas", "moldovan renewables",
        "moldovan grid", "moldovan solar",
        "moldovan wind", "moldovan hydro",
        "moldovan climate", "moldovan emissions",
        "moldovan energy transition",
        "russian gas moldova", "moldovan energy crisis",
        "moldovan power", "transnistria energy",
        "moldovan energy security", "moldovan energy prices",
        "cuciurgan power plant", "moldovan lng",
        "moldovan energy independence",
    ],
    "technology": [
        "moldovan tech", "chisinau tech", "moldovan startup",
        "moldovan ai", "moldovan fintech",
        "moldovan digital", "moldovan innovation",
        "moldovan software", "moldovan it sector",
        "moldovan outsourcing", "moldovan cybersecurity",
        "moldovan gaming", "moldovan e-government",
        "moldovan digital transformation",
        "tekwill moldova", "moldovan unicorn",
    ],
    "health": [
        "moldovan health", "moldovan hospital",
        "moldovan pharma", "moldovan vaccine",
        "moldovan healthcare", "moldovan mental health",
        "moldovan health system", "moldovan medicine",
        "moldovan public health", "moldovan wellbeing",
        "moldovan medical aid", "moldovan refugees health",
        "cnam moldova", "moldovan medical university",
    ],
    "crime": [
        "moldovan corruption", "moldovan fraud",
        "moldovan scandal", "moldovan court",
        "moldovan investigation", "moldovan organized crime",
        "moldovan drug trafficking", "moldovan money laundering",
        "moldovan terrorism", "moldovan police",
        "politia moldova", "moldovan gang",
        "moldovan anti corruption", "cna moldova",
        "moldovan smuggling", "moldovan human trafficking",
        "moldovan election fraud", "russian interference moldova",
        "moldovan oligarch", "ilan shor moldova",
    ],
    "politics": [
        "parlamentul republicii moldova", "moldovan parliament",
        "moldovan election", "moldovan government",
        "moldovan minister", "moldovan prime minister",
        "moldovan coalition", "moldovan opposition",
        "pas moldova", "maia sandu", "sandu",
        "bloc electoral al comunistilor",
        "psrm moldova", "igor dodon",
        "moldovan policy", "moldovan reform",
        "moldovan immigration", "moldovan diaspora",
        "moldovan welfare", "moldovan citizenship",
        "moldovan referendum", "moldovan judiciary",
        "moldovan rule of law", "moldovan eu relations",
        "moldovan democracy", "moldovan president",
        "moldovan media freedom",
        "russian interference moldovan election",
        "moldovan eu candidate status",
        "moldovan nato aspirations",
        "gagauzia autonomy",
    ],
}
