
# mood/pipeline/keywords/mk.py
MK_KEYWORDS = {
    "finance": [
        "macedonian economy", "north macedonia gdp",
        "macedonian stock exchange", "mse macedonia",
        "national bank macedonia", "nbrm",
        "macedonian denar", "mkd",
        "macedonian inflation", "macedonian budget",
        "macedonian exports", "macedonian trade",
        "macedonian market", "macedonian growth",
        "macedonian debt", "macedonian deficit",
        "macedonian unemployment", "macedonian wages",
        "macedonian housing", "macedonian mortgage",
        "evn macedonia", "telekom makedonija",
        "stopanska banka", "komercijalna banka mk",
        "nlt bank", "unicredit macedonia",
        "macedonian business", "macedonian investment",
        "macedonian tourism", "macedonian manufacturing",
        "macedonian agriculture", "macedonian wine",
        "macedonian eu funds", "macedonian recovery plan",
        "macedonian pension fund", "macedonian industry",
        "macedonian it sector", "macedonian outsourcing",
    ],
    "geopolitics": [
        "macedonian foreign policy", "north macedonia nato",
        "macedonian sanctions", "macedonian diplomacy",
        "macedonian troops", "macedonia ukraine",
        "macedonia russia", "macedonian ambassador",
        "north macedonia eu", "macedonian defense",
        "macedonian military", "skopje talks",
        "macedonia security", "macedonian intelligence",
        "prespa agreement", "prespa accord",
        "bulgaria macedonia dispute", "greece macedonia",
        "macedonian name dispute", "macedonian eu accession",
        "western balkans macedonia", "macedonia middle east",
        "macedonian peacekeeping", "macedonian nato membership",
    ],
    "energy": [
        "macedonian energy", "macedonian coal", "rea macedonia",
        "macedonian electricity", "macedonian renewables",
        "macedonian gas", "macedonian grid",
        "macedonian solar", "macedonian wind",
        "macedonian hydro", "macedonian climate",
        "macedonian emissions", "macedonian energy transition",
        "macedonian energy prices", "macedonian energy security",
        "macedonian coal phase out", "macedonian biomass",
        "elem macedonia", "macedonian power plants",
    ],
    "technology": [
        "macedonian tech", "skopje tech", "macedonian startup",
        "macedonian ai", "macedonian fintech",
        "macedonian digital", "macedonian innovation",
        "macedonian software", "macedonian it sector",
        "macedonian outsourcing", "macedonian cybersecurity",
        "macedonian gaming", "macedonian unicorn",
        "bitola tech", "macedonian semiconductor",
    ],
    "health": [
        "macedonian health", "macedonian hospital",
        "macedonian pharma", "macedonian vaccine",
        "macedonian healthcare", "macedonian mental health",
        "macedonian health system", "macedonian medicine",
        "macedonian public health", "macedonian wellbeing",
        "skopje medicine university", "macedonian fzom",
    ],
    "crime": [
        "macedonian corruption", "macedonian fraud",
        "macedonian scandal", "macedonian court",
        "macedonian investigation", "macedonian organized crime",
        "macedonian drug trafficking", "macedonian money laundering",
        "macedonian terrorism", "macedonian police",
        "mvr macedonia", "macedonian gang",
        "macedonian anti corruption", "dksk macedonia",
        "macedonian smuggling", "macedonian human trafficking",
        "macedonian protest", "femicide macedonia",
        "march skopje protest",
    ],
    "politics": [
        "sobranie", "macedonian parliament",
        "macedonian election", "macedonian government",
        "macedonian minister", "macedonian prime minister",
        "macedonian coalition", "macedonian opposition",
        "vmro dpmne", "hristijan mickoski",
        "sdsm", "oliver spasovski",
        "dui macedonia", "besa macedonia",
        "macedonian policy", "macedonian reform",
        "macedonian immigration", "macedonian diaspora",
        "macedonian welfare", "macedonian citizenship",
        "macedonian referendum", "macedonian judiciary",
        "macedonian rule of law", "macedonian eu relations",
        "macedonian democracy", "macedonian president",
        "gordana siljanovska", "macedonian ethnic relations",
        "albanian minority macedonia",
    ],
}
