
# mood/pipeline/keywords/mm.py
MM_KEYWORDS = {
    "finance": [
        "myanmar economy", "myanmar gdp",
        "yangon stock exchange", "ysx myanmar",
        "central bank myanmar", "cbm myanmar",
        "myanmar kyat", "mmk",
        "myanmar inflation", "myanmar budget",
        "myanmar exports", "myanmar trade",
        "myanmar market", "myanmar growth",
        "myanmar debt", "myanmar deficit",
        "myanmar unemployment", "myanmar wages",
        "myanmar housing", "myanmar mortgage",
        "myanmar business", "myanmar investment",
        "myanmar tourism", "myanmar manufacturing",
        "myanmar agriculture", "myanmar rice",
        "myanmar teak", "myanmar jade",
        "myanmar ruby", "myanmar gems",
        "myanmar garment industry", "myanmar textiles",
        "myanmar eu sanctions economy",
        "myanmar trade restrictions",
        "myanmar remittances", "myanmar diaspora",
        "myanmar banking", "kbz bank",
        "aya bank myanmar", "myanmar real estate",
        "myanmar construction", "myanmar logistics",
    ],
    "geopolitics": [
        "myanmar foreign policy", "myanmar nato",
        "myanmar sanctions", "myanmar diplomacy",
        "myanmar troops", "myanmar ukraine",
        "myanmar russia", "myanmar ambassador",
        "myanmar eu", "myanmar military",
        "naypyidaw talks", "myanmar security",
        "myanmar intelligence", "myanmar china",
        "myanmar us relations", "myanmar asean",
        "myanmar civil war", "myanmar junta",
        "myanmar resistance", "myanmar pdf",
        "peoples defense force myanmar",
        "myanmar arakan army", "myanmar tnla",
        "myanmar knla", "myanmar ethnic armed",
        "myanmar coup", "myanmar military coup",
        "myanmar india border", "myanmar thailand border",
        "myanmar china border", "myanmar rohingya",
        "myanmar rakhine", "myanmar peacekeeping",
        "myanmar un", "myanmar middle east",
    ],
    "energy": [
        "myanmar energy", "myanmar electricity",
        "myanmar renewables", "myanmar solar",
        "myanmar wind", "myanmar hydro",
        "myanmar grid", "myanmar climate",
        "myanmar emissions", "myanmar energy transition",
        "myanmar gas", "myanmar oil",
        "myanmar energy prices", "myanmar energy security",
        "myanmar green energy", "myanmar coal",
        "myanmar natural gas", "myanmar pipeline",
        "myanmar power outage", "myanmar blackout",
        "myanmar energy crisis",
    ],
    "technology": [
        "myanmar tech", "yangon tech", "myanmar startup",
        "myanmar ai", "myanmar fintech",
        "myanmar digital", "myanmar innovation",
        "myanmar cybersecurity", "myanmar gaming",
        "myanmar software", "myanmar it sector",
        "myanmar ecommerce", "myanmar digital economy",
        "myanmar internet shutdown", "myanmar vpn",
        "myanmar mobile banking", "myanmar wave money",
        "myanmar blockchain", "myanmar digital payments",
    ],
    "health": [
        "myanmar health", "myanmar hospital",
        "myanmar pharma", "myanmar vaccine",
        "myanmar healthcare", "myanmar mental health",
        "myanmar health system", "myanmar medicine",
        "myanmar public health", "myanmar wellbeing",
        "myanmar biotech", "myanmar cancer",
        "myanmar dengue", "myanmar malaria",
        "myanmar tuberculosis", "myanmar hiv",
        "myanmar health crisis", "myanmar war wounded",
        "myanmar humanitarian health",
        "myanmar medical aid",
    ],
    "crime": [
        "myanmar corruption", "myanmar fraud",
        "myanmar scandal", "myanmar court",
        "myanmar investigation", "myanmar organized crime",
        "myanmar drug trafficking", "myanmar scam",
        "myanmar money laundering", "myanmar terrorism",
        "myanmar police", "myanmar gang",
        "myanmar human trafficking",
        "myanmar cyber scam", "myanmar scam compound",
        "myanmar forced labor", "myanmar slavery",
        "myanmar war crimes", "myanmar atrocities",
        "myanmar genocide", "myanmar ethnic cleansing",
        "myanmar political prisoner",
        "myanmar aung san suu kyi",
        "myanmar opposition arrested",
    ],
    "politics": [
        "pyidaungsu hluttaw", "myanmar parliament",
        "myanmar election", "myanmar government",
        "myanmar minister", "myanmar prime minister",
        "myanmar coalition", "myanmar opposition",
        "min aung hlaing", "myanmar junta leader",
        "nld myanmar", "aung san suu kyi",
        "myanmar sac", "state administration council",
        "myanmar nug", "national unity government",
        "myanmar policy", "myanmar reform",
        "myanmar immigration", "myanmar refugees",
        "myanmar welfare", "myanmar citizenship",
        "myanmar rohingya citizenship",
        "myanmar judiciary", "myanmar rule of law",
        "myanmar democracy", "myanmar president",
        "myanmar media freedom", "myanmar press freedom",
        "myanmar constitution", "myanmar federalism",
        "myanmar ethnic minorities",
        "myanmar ceasefire", "myanmar peace talks",
        "myanmar china influence",
        "myanmar russia arms",
    ],
}