
# mood/pipeline/keywords/mx.py
MX_KEYWORDS = {
    "finance": [
        "mexican economy", "mexico gdp", "ipc index",
        "bolsa mexicana valores", "bmv mexico",
        "banco de mexico", "banxico",
        "mexican peso", "mxn",
        "mexican inflation", "mexican budget",
        "mexican exports", "mexican trade",
        "mexican market", "mexican growth",
        "mexican debt", "mexican deficit",
        "mexican unemployment", "mexican wages",
        "mexican housing", "mexican mortgage",
        "bbva mexico", "banamex", "banorte",
        "hsbc mexico", "scotiabank mexico",
        "pemex", "cemex", "america movil",
        "grupo bimbo", "walmex", "femsa",
        "grupo modelo", "gruma", "alfa group",
        "mexican business", "mexican investment",
        "mexican tourism", "mexican manufacturing",
        "mexican automotive", "mexican agriculture",
        "mexican avocado", "mexican tomato",
        "mexican eu trade", "mexico us trade",
        "mexican tariffs", "mexican fiscal",
        "mexican nearshoring", "mexico nearshoring",
        "mexican pension fund", "afore mexico",
        "mexican industry", "mexican startup",
        "mexican unicorn", "mexican fintech",
        "mexican real estate", "mexican construction",
        "mexican remittances", "mexican diaspora",
        "usmca mexico", "nafta mexico",
        "trump mexico tariffs",
    ],
    "geopolitics": [
        "mexican foreign policy", "mexico nato",
        "mexican sanctions", "mexican diplomacy",
        "mexican troops", "mexico ukraine",
        "mexico russia", "mexican ambassador",
        "mexico eu", "mexican defense",
        "mexican military", "mexico city talks",
        "mexico security", "mexican intelligence",
        "cisen mexico", "mexico us relations",
        "mexico china relations", "mexico iran",
        "mexico israel", "mexico middle east",
        "mexico central america", "mexico migration",
        "mexico border", "mexico us border",
        "mexican cartels geopolitics",
        "mexico peacekeeping", "mexico un",
        "mexico brics", "mexico g20",
        "mexico fentanyl us",
        "trump mexico", "mexico tariff threat",
        "kristi noem mexico",
        "mexico us security cooperation",
    ],
    "energy": [
        "mexican energy", "mexican oil", "pemex oil",
        "mexican gas", "mexican electricity",
        "mexican renewables", "mexican solar",
        "mexican wind", "mexican hydro",
        "mexican grid", "mexican climate",
        "mexican emissions", "mexican energy transition",
        "mexican hydrogen", "mexican lng",
        "mexican energy prices", "mexican energy security",
        "mexican green energy", "mexican carbon neutral",
        "mexican net zero", "mexican fuel prices",
        "mexican oil production", "pemex debt",
        "mexican refinery", "mexican petrochemical",
        "mexican energy reform",
        "cfe mexico", "mexican electricity prices",
    ],
    "technology": [
        "mexican tech", "mexico city tech",
        "mexican startup", "mexican ai",
        "mexican fintech", "mexican digital",
        "mexican innovation", "mexican unicorn",
        "mexican cybersecurity", "mexican gaming",
        "mexican software", "mexican it sector",
        "mexican ecommerce", "mexican digital economy",
        "mexican semiconductor", "mexican ev",
        "mexican smart city", "mexican medtech",
        "mexican biotech", "mexican quantum",
        "mexican space", "mexican 5g",
        "mexican blockchain", "clip mexico",
        "konfio mexico", "kavak mexico",
        "mexican nearshoring tech",
    ],
    "health": [
        "mexican health", "mexican hospital",
        "mexican pharma", "mexican vaccine",
        "mexican healthcare", "mexican mental health",
        "mexican health system", "imss mexico",
        "issste mexico", "mexican medicine",
        "mexican public health", "mexican wellbeing",
        "mexican biotech", "mexican cancer",
        "mexican aging population", "mexican birthrate",
        "cofepris mexico", "mexican drug approval",
        "mexican fentanyl crisis",
        "mexican obesity epidemic",
        "mexican diabetes epidemic",
        "mexican indigenous health",
    ],
    "crime": [
        "mexican corruption", "mexican fraud",
        "mexican scandal", "mexican court",
        "mexican investigation", "mexican cartel",
        "cjng", "sinaloa cartel",
        "mexican drug trafficking", "mexican money laundering",
        "mexican terrorism", "mexican police",
        "mexican gang", "mexican anti corruption",
        "mexican cybercrime", "mexican scam",
        "mexican arrest", "mexican mafia",
        "mexican human trafficking",
        "mexican femicide", "mexico violence",
        "mexican protest", "mexican riot",
        "mexican political scandal",
        "mexican journalist killed",
        "mexican cartel violence",
        "mexico security crisis",
        "fentanyl mexico",
        "axe knife machete mexico",
    ],
    "politics": [
        "camara de diputados mexico",
        "senado mexico", "mexican parliament",
        "mexican election", "mexican government",
        "mexican minister", "mexican president",
        "mexican coalition", "mexican opposition",
        "morena mexico", "claudia sheinbaum",
        "sheinbaum", "pan mexico", "pri mexico",
        "mexican policy", "mexican reform",
        "mexican immigration", "mexican migrants",
        "mexican welfare", "mexican citizenship",
        "mexican referendum", "mexican judiciary",
        "mexican rule of law", "mexican eu relations",
        "mexican democracy", "mexican media freedom",
        "mexican press freedom", "mexican constitution",
        "mexican federalism", "mexican state politics",
        "mexican indigenous rights",
        "mexican judicial reform",
        "trump mexico relations",
        "mexico 220 million dollars",
    ],
}

