
# mood/pipeline/keywords/my.py
MY_KEYWORDS = {
    "finance": [
        "malaysian economy", "malaysia gdp", "klci index",
        "bursa malaysia", "kuala lumpur stock exchange",
        "bank negara malaysia", "bnm malaysia",
        "malaysian ringgit", "myr",
        "malaysian inflation", "malaysian budget",
        "malaysian exports", "malaysian trade",
        "malaysian market", "malaysian growth",
        "malaysian debt", "malaysian deficit",
        "malaysian unemployment", "malaysian wages",
        "malaysian housing", "malaysian mortgage",
        "petronas", "maybank", "cimb bank",
        "public bank malaysia", "rhb bank",
        "tenaga nasional", "axiata", "maxis",
        "malaysian business", "malaysian investment",
        "malaysian tourism", "malaysian manufacturing",
        "malaysian automotive", "proton malaysia",
        "malaysian agriculture", "malaysian palm oil",
        "malaysian rubber", "malaysian timber",
        "malaysian eu funds", "malaysian recovery plan",
        "malaysian pension fund", "epf malaysia",
        "malaysian industry", "malaysian it sector",
        "malaysian startup", "malaysian real estate",
        "malaysia us trade", "malaysian tariffs",
        "malaysia trade deal", "malaysian fiscal",
    ],
    "geopolitics": [
        "malaysian foreign policy", "malaysia nato",
        "malaysian sanctions", "malaysian diplomacy",
        "malaysian troops", "malaysia ukraine",
        "malaysia russia", "malaysian ambassador",
        "malaysia eu", "malaysian defense",
        "malaysian military", "kuala lumpur talks",
        "malaysia security", "malaysian intelligence",
        "malaysia china relations", "malaysia us relations",
        "malaysia asean", "malaysia south china sea",
        "malaysia singapore relations",
        "malaysia indonesia relations",
        "malaysia thailand relations",
        "malaysian peacekeeping", "malaysia un",
        "malaysia middle east", "malaysia gulf",
        "malaysia israel", "malaysia iran",
    ],
    "energy": [
        "malaysian energy", "malaysian oil",
        "malaysian gas", "petronas energy",
        "malaysian electricity", "malaysian renewables",
        "malaysian solar", "malaysian wind",
        "malaysian hydro", "malaysian grid",
        "malaysian climate", "malaysian emissions",
        "malaysian energy transition", "malaysian hydrogen",
        "malaysian lng", "malaysian energy prices",
        "malaysian energy security", "malaysian green energy",
        "malaysian coal", "malaysian natural gas",
        "malaysian carbon neutral", "malaysian net zero",
        "malaysian fuel prices", "malaysian petrochemical",
        "sarawak energy", "sabah energy",
    ],
    "technology": [
        "malaysian tech", "kuala lumpur tech",
        "malaysian startup", "malaysian ai",
        "malaysian fintech", "malaysian digital",
        "malaysian innovation", "malaysian unicorn",
        "malaysian cybersecurity", "malaysian gaming",
        "malaysian software", "malaysian it sector",
        "malaysian ecommerce", "malaysian digital economy",
        "malaysian semiconductor", "malaysian ev",
        "malaysian smart city", "malaysian medtech",
        "grab malaysia", "malaysian blockchain",
        "malaysian quantum", "mdec malaysia",
    ],
    "health": [
        "malaysian health", "malaysian hospital",
        "malaysian pharma", "malaysian vaccine",
        "malaysian healthcare", "malaysian mental health",
        "malaysian health system", "malaysian medicine",
        "malaysian public health", "malaysian wellbeing",
        "malaysian medical tourism", "malaysian biotech",
        "malaysian cancer", "malaysian dengue",
        "malaysian malaria", "moh malaysia",
        "malaysian aging population",
    ],
    "crime": [
        "malaysian corruption", "malaysian fraud",
        "malaysian scandal", "malaysian court",
        "malaysian investigation", "malaysian organized crime",
        "malaysian drug trafficking", "malaysian money laundering",
        "malaysian terrorism", "malaysian police",
        "pdrm malaysia", "malaysian gang",
        "malaysian anti corruption", "macc malaysia",
        "malaysian cybercrime", "malaysian scam",
        "malaysian arrest", "malaysian mafia",
        "malaysian human trafficking",
        "malaysian protest", "malaysian riot",
        "najib razak", "1mdb scandal",
    ],
    "politics": [
        "dewan rakyat", "dewan negara", "malaysian parliament",
        "malaysian election", "malaysian government",
        "malaysian minister", "malaysian prime minister",
        "malaysian coalition", "malaysian opposition",
        "pakatan harapan", "anwar ibrahim", "anwar",
        "perikatan nasional", "muhyiddin yassin",
        "umno malaysia", "bersatu malaysia",
        "dap malaysia", "pkr malaysia",
        "malaysian policy", "malaysian reform",
        "malaysian immigration", "malaysian integration",
        "malaysian welfare", "malaysian citizenship",
        "malaysian referendum", "malaysian judiciary",
        "malaysian rule of law", "malaysian eu relations",
        "malaysian democracy", "malaysian king",
        "agong malaysia", "malaysian royal family",
        "malaysian media freedom", "malaysian press freedom",
        "malaysian constitution", "malaysian federalism",
        "sabah sarawak politics",
    ],
}