
# mood/pipeline/keywords/mz.py
MZ_KEYWORDS = {
    "finance": [
        "mozambican economy", "mozambique gdp",
        "mozambique stock exchange", "bolsa valores mozambique",
        "bank of mozambique", "bm mozambique",
        "mozambican metical", "mzn",
        "mozambican inflation", "mozambican budget",
        "mozambican exports", "mozambican trade",
        "mozambican market", "mozambican growth",
        "mozambican debt", "mozambican deficit",
        "mozambican unemployment", "mozambican wages",
        "mozambican housing", "mozambican mortgage",
        "millennium bim mozambique", "standard bank mozambique",
        "absa mozambique", "fnb mozambique",
        "mozambican natural gas", "total mozambique",
        "eni mozambique", "rovuma gas field",
        "mozambican coal", "mozambican graphite",
        "mozambican ruby", "mozambican business",
        "mozambican investment", "mozambican tourism",
        "mozambican manufacturing", "mozambican agriculture",
        "mozambican cashew", "mozambican prawns",
        "mozambican eu trade", "mozambique us trade",
        "mozambican tariffs", "mozambican fiscal",
        "mozambican pension fund", "inss mozambique",
        "mozambican industry", "mozambican startup",
        "mozambican fintech", "mozambican real estate",
        "mozambican construction", "mozambican remittances",
        "mozambican diaspora", "mozambique imf",
        "chapo economic policy",
        "mozambican lng project",
        "total lng mozambique",
    ],
    "geopolitics": [
        "mozambican foreign policy", "mozambique nato",
        "mozambican sanctions", "mozambican diplomacy",
        "mozambican troops", "mozambique ukraine",
        "mozambique russia", "mozambican ambassador",
        "mozambique eu", "mozambican defense",
        "mozambican military", "maputo talks",
        "mozambique security", "mozambican intelligence",
        "sise mozambique", "mozambique us relations",
        "mozambique china", "mozambique brics",
        "mozambique africa union", "mozambique sadc",
        "mozambique peacekeeping", "mozambique un",
        "mozambique zimbabwe", "mozambique zambia",
        "mozambique tanzania", "mozambique malawi",
        "mozambique south africa", "mozambique eswatini",
        "mozambican insurgency", "cabo delgado",
        "isis mozambique", "ansar al sunna",
        "chapo foreign policy",
        "mozambique rwanda troops",
        "mozambique sadc mission",
        "bobi wine mozambique",
    ],
    "energy": [
        "mozambican energy", "mozambican gas",
        "mozambican electricity", "mozambican renewables",
        "mozambican solar", "mozambican wind",
        "mozambican hydro", "mozambican grid",
        "mozambican climate", "mozambican emissions",
        "mozambican energy transition",
        "mozambican hydrogen", "mozambican lng",
        "mozambican energy prices", "mozambican energy security",
        "mozambican green energy", "mozambican carbon neutral",
        "mozambican net zero", "mozambican fuel prices",
        "total mozambique lng", "eni mozambique gas",
        "rovuma lng mozambique",
        "cahora bassa dam",
        "edm mozambique",
        "mozambican offshore gas",
    ],
    "technology": [
        "mozambican tech", "maputo tech", "mozambican startup",
        "mozambican ai", "mozambican fintech",
        "mozambican digital", "mozambican innovation",
        "mozambican cybersecurity", "mozambican software",
        "mozambican it sector", "mozambican ecommerce",
        "mozambican digital economy", "mozambican 5g",
        "mozambican blockchain", "mozambican smart city",
        "mozambican medtech", "mozambican digital transformation",
        "vodacom mozambique", "tmcel mozambique",
        "mozambican mobile money",
        "mozambican tech hub",
    ],
    "health": [
        "mozambican health", "mozambican hospital",
        "mozambican pharma", "mozambican vaccine",
        "mozambican healthcare", "mozambican mental health",
        "mozambican health system", "mozambican medicine",
        "mozambican public health", "mozambican wellbeing",
        "mozambican malaria", "mozambican tuberculosis",
        "mozambican hiv", "mozambican cholera",
        "mozambican health reform",
        "mozambican universal health",
        "maputo central hospital",
        "mozambican maternal health",
        "misau mozambique",
        "mozambican cabo delgado health",
        "mozambican cyclone health",
    ],
    "crime": [
        "mozambican corruption", "mozambican fraud",
        "mozambican scandal", "mozambican court",
        "mozambican investigation", "mozambican organized crime",
        "mozambican drug trafficking", "mozambican money laundering",
        "mozambican terrorism", "mozambican police",
        "mozambican gang", "mozambican anti corruption",
        "gccc mozambique", "mozambican cybercrime",
        "mozambican scam", "mozambican arrest",
        "mozambican human trafficking",
        "mozambican protest", "mozambican riot",
        "mozambican political scandal",
        "cabo delgado insurgency",
        "mozambican jihadist",
        "mozambican election violence",
        "mozambican femicide",
        "tuna bonds scandal mozambique",
    ],
    "politics": [
        "assembleia da republica mozambique",
        "mozambican parliament", "mozambican election",
        "mozambican government", "mozambican minister",
        "mozambican president", "mozambican coalition",
        "mozambican opposition", "frelimo mozambique",
        "daniel chapo", "chapo mozambique",
        "renamo mozambique", "ossufo momade",
        "podemos mozambique",
        "mozambican policy", "mozambican reform",
        "mozambican immigration", "mozambican diaspora",
        "mozambican welfare", "mozambican citizenship",
        "mozambican referendum", "mozambican judiciary",
        "mozambican rule of law", "mozambican eu relations",
        "mozambican democracy", "mozambican media freedom",
        "mozambican press freedom", "mozambican constitution",
        "mozambican federalism", "mozambican provinces",
        "mozambican political crisis",
        "mozambican election dispute",
        "mozambican post election violence",
        "club of mozambique news",
    ],
}
