
# mood/pipeline/keywords/na.py
NA_KEYWORDS = {
    "finance": [
        "namibian economy", "namibia gdp",
        "namibia stock exchange", "nsx namibia",
        "bank of namibia", "bon",
        "namibian dollar", "nad",
        "namibian inflation", "namibian budget",
        "namibian exports", "namibian trade",
        "namibian market", "namibian growth",
        "namibian debt", "namibian deficit",
        "namibian unemployment", "namibian wages",
        "namibian housing", "namibian mortgage",
        "first national bank namibia", "fnb namibia",
        "standard bank namibia", "nedbank namibia",
        "bank windhoek", "letshego namibia",
        "namibian diamonds", "namdeb namibia",
        "namibian uranium", "rossing uranium",
        "husab uranium namibia", "namibian gold",
        "namibian copper", "namibian zinc",
        "namibian fishing", "namibian tourism",
        "namibian business", "namibian investment",
        "namibian manufacturing", "namibian agriculture",
        "namibian eu trade", "namibia us trade",
        "namibian tariffs", "namibian fiscal",
        "namibian pension fund", "gipf namibia",
        "namibian industry", "namibian startup",
        "namibian fintech", "namibian real estate",
        "namibian construction", "namibian remittances",
        "namibian diaspora", "namibia imf",
        "mbumba economic policy",
        "namibian green hydrogen",
        "namibian lng",
        "namibian offshore gas",
        "troubled spurs namibian",
    ],
    "geopolitics": [
        "namibian foreign policy", "namibia nato",
        "namibian sanctions", "namibian diplomacy",
        "namibian troops", "namibia ukraine",
        "namibia russia", "namibian ambassador",
        "namibia eu", "namibian defense",
        "namibian military", "windhoek talks",
        "namibia security", "namibian intelligence",
        "namibia us relations", "namibia china",
        "namibia brics", "namibia africa union",
        "namibia sadc", "namibia peacekeeping",
        "namibia un", "namibia south africa",
        "namibia botswana", "namibia zambia",
        "namibia angola", "namibia zimbabwe",
        "namibia germany reparations",
        "herero nama genocide namibia",
        "mbumba foreign policy",
        "namibia icj case",
        "namibia walvis bay",
    ],
    "energy": [
        "namibian energy", "namibian electricity",
        "namibian renewables", "namibian solar",
        "namibian wind", "namibian hydro",
        "namibian grid", "namibian climate",
        "namibian emissions", "namibian energy transition",
        "namibian hydrogen", "namibian green hydrogen",
        "namibian lng", "namibian energy prices",
        "namibian energy security", "namibian green energy",
        "namibian carbon neutral", "namibian net zero",
        "namibian fuel prices", "namibian offshore gas",
        "namibian uranium energy",
        "nampower namibia",
        "namibian solar project",
        "namibian wind farm",
        "namibia hydrogen hub africa",
    ],
    "technology": [
        "namibian tech", "windhoek tech", "namibian startup",
        "namibian ai", "namibian fintech",
        "namibian digital", "namibian innovation",
        "namibian cybersecurity", "namibian software",
        "namibian it sector", "namibian ecommerce",
        "namibian digital economy", "namibian 5g",
        "namibian blockchain", "namibian smart city",
        "namibian medtech", "namibian digital transformation",
        "mtn namibia", "telecom namibia",
        "namibian mobile money",
        "namibian tech hub",
        "namibian silicon valley",
    ],
    "health": [
        "namibian health", "namibian hospital",
        "namibian pharma", "namibian vaccine",
        "namibian healthcare", "namibian mental health",
        "namibian health system", "namibian medicine",
        "namibian public health", "namibian wellbeing",
        "namibian malaria", "namibian tuberculosis",
        "namibian hiv", "namibian cholera",
        "namibian health reform",
        "namibian universal health",
        "windhoek central hospital",
        "namibian maternal health",
        "nampharm namibia",
        "namibian community health",
    ],
    "crime": [
        "namibian corruption", "namibian fraud",
        "namibian scandal", "namibian court",
        "namibian investigation", "namibian organized crime",
        "namibian drug trafficking", "namibian money laundering",
        "namibian terrorism", "namibian police",
        "namibian gang", "namibian anti corruption",
        "acc namibia", "namibian cybercrime",
        "namibian scam", "namibian arrest",
        "namibian human trafficking",
        "namibian protest", "namibian riot",
        "namibian political scandal",
        "namibian election violence",
        "namibian femicide",
        "namibian poaching",
        "namibian wildlife crime",
    ],
    "politics": [
        "national assembly namibia", "namibian parliament",
        "namibian election", "namibian government",
        "namibian minister", "namibian president",
        "namibian coalition", "namibian opposition",
        "swapo namibia", "netumbo nandi ndaitwah",
        "ndaitwah namibia", "pdm namibia",
        "ica namibia", "namibian policy",
        "namibian reform", "namibian immigration",
        "namibian diaspora", "namibian welfare",
        "namibian citizenship", "namibian referendum",
        "namibian judiciary", "namibian rule of law",
        "namibian eu relations", "namibian democracy",
        "namibian media freedom", "namibian press freedom",
        "namibian constitution", "namibian federalism",
        "namibian regions", "namibian political stability",
        "namibian first female president",
        "namibia germany genocide reparations",
        "namibian land reform",
        "namibian san community",
    ],
}