
# mood/pipeline/keywords/ng.py
NG_KEYWORDS = {
    "finance": [
        "nigerian economy", "nigeria gdp", "ngx index",
        "nigerian stock exchange", "ngx",
        "central bank nigeria", "cbn",
        "nigerian naira", "ngn",
        "nigerian inflation", "nigerian budget",
        "nigerian exports", "nigerian trade",
        "nigerian market", "nigerian growth",
        "nigerian debt", "nigerian deficit",
        "nigerian unemployment", "nigerian wages",
        "nigerian housing", "nigerian mortgage",
        "zenith bank", "gtbank", "access bank",
        "first bank nigeria", "uba nigeria",
        "dangote group", "nnpc nigeria",
        "mtv nigeria", "airtel nigeria",
        "nigerian business", "nigerian investment",
        "nigerian tourism", "nigerian manufacturing",
        "nigerian oil", "nigerian gas",
        "nigerian agriculture", "nigerian cocoa",
        "nigerian sesame", "nigerian cashew",
        "nigerian eu trade", "nigeria us trade",
        "nigerian tariffs", "nigerian fiscal",
        "nigerian pension fund", "pencom nigeria",
        "nigerian industry", "nigerian startup",
        "nigerian fintech", "nigerian real estate",
        "nigerian construction", "nigerian remittances",
        "nigerian diaspora", "dangote refinery",
        "tinubu economic policy",
        "nigerian subsidy removal",
        "nigerian naira devaluation",
    ],
    "geopolitics": [
        "nigerian foreign policy", "nigeria nato",
        "nigerian sanctions", "nigerian diplomacy",
        "nigerian troops", "nigeria ukraine",
        "nigeria russia", "nigerian ambassador",
        "nigeria eu", "nigerian defense",
        "nigerian military", "abuja talks",
        "nigeria security", "nigerian intelligence",
        "dss nigeria", "nigeria us relations",
        "nigeria china relations", "nigeria brics",
        "nigeria africa union", "nigeria ecowas",
        "nigeria peacekeeping", "nigeria un",
        "nigeria niger coup", "nigeria mali",
        "nigeria cameroon", "nigeria lake chad",
        "nigeria boko haram", "boko haram nigeria",
        "iswap nigeria", "nigeria bandit attacks",
        "tinubu foreign policy",
        "nigeria ghana relations",
        "nigerian election observer",
    ],
    "energy": [
        "nigerian energy", "nigerian oil", "nnpc",
        "nigerian gas", "nigerian electricity",
        "nigerian renewables", "nigerian solar",
        "nigerian wind", "nigerian grid",
        "nigerian climate", "nigerian emissions",
        "nigerian energy transition", "nigerian hydrogen",
        "nigerian lng", "nigerian energy prices",
        "nigerian energy security", "nigerian green energy",
        "nigerian carbon neutral", "nigerian net zero",
        "nigerian fuel prices", "nigerian subsidy",
        "nigerian oil production", "nigerian refinery",
        "nigerian petrochemical", "nigerian pipeline",
        "dangote refinery energy",
        "nigerian power sector",
        "nigerian power outage",
    ],
    "technology": [
        "nigerian tech", "lagos tech", "nigerian startup",
        "nigerian ai", "nigerian fintech",
        "nigerian digital", "nigerian innovation",
        "nigerian unicorn", "nigerian cybersecurity",
        "nigerian gaming", "nigerian software",
        "nigerian it sector", "nigerian ecommerce",
        "nigerian digital economy", "nigerian semiconductor",
        "nigerian ev", "nigerian smart city",
        "nigerian medtech", "nigerian biotech",
        "nigerian 5g", "nigerian blockchain",
        "flutterwave nigeria", "paystack nigeria",
        "andela nigeria", "kuda bank nigeria",
        "nigerian tech hub", "yaba tech",
    ],
    "health": [
        "nigerian health", "nigerian hospital",
        "nigerian pharma", "nigerian vaccine",
        "nigerian healthcare", "nigerian mental health",
        "nigerian health system", "nigerian medicine",
        "nigerian public health", "nigerian wellbeing",
        "nigerian biotech", "nigerian cancer",
        "nigerian aging population",
        "nigerian malaria", "nigerian tuberculosis",
        "nigerian hiv", "nigerian polio",
        "nigerian cholera", "nigerian lassa fever",
        "nafdac nigeria", "nigerian drug approval",
        "nigerian health reform",
        "nigerian maternal health",
    ],
    "crime": [
        "nigerian corruption", "nigerian fraud",
        "nigerian scandal", "nigerian court",
        "nigerian investigation", "nigerian organized crime",
        "nigerian drug trafficking", "nigerian money laundering",
        "nigerian terrorism", "nigerian police",
        "nigerian gang", "nigerian anti corruption",
        "efcc nigeria", "icpc nigeria",
        "nigerian cybercrime", "nigerian scam",
        "nigerian yahoo yahoo", "nigerian 419",
        "nigerian arrest", "nigerian mafia",
        "nigerian human trafficking",
        "nigerian protest", "nigerian riot",
        "nigerian political scandal",
        "nigerian banditry", "nigerian kidnapping",
        "nigerian farmer herder conflict",
        "nigerian election violence",
        "tinubu scandal",
        "ireti kingibe suspension",
    ],
    "politics": [
        "national assembly nigeria", "nigerian senate",
        "nigerian parliament", "nigerian election",
        "nigerian government", "nigerian minister",
        "nigerian president", "nigerian coalition",
        "nigerian opposition", "apc nigeria",
        "bola tinubu", "tinubu nigeria",
        "pdp nigeria", "atiku abubakar",
        "labour party nigeria", "peter obi",
        "nigerian policy", "nigerian reform",
        "nigerian immigration", "nigerian diaspora",
        "nigerian welfare", "nigerian citizenship",
        "nigerian referendum", "nigerian judiciary",
        "nigerian rule of law", "nigerian eu relations",
        "nigerian democracy", "nigerian media freedom",
        "nigerian press freedom", "nigerian constitution",
        "nigerian federalism", "nigerian states",
        "nigerian restructuring",
        "sultan sokoto tinubu visit",
        "tinubu campaign rice donation",
        "adc suspension nigeria",
    ],
}