# mood/pipeline/keywords/nl.py
NL_KEYWORDS = {
    "finance": [
        "dutch economy", "netherlands gdp", "aex",
        "amsterdam stock exchange", "euronext amsterdam",
        "dutch national bank", "dnb netherlands",
        "dutch inflation", "dutch budget", "dutch exports",
        "dutch trade", "dutch market", "dutch growth",
        "dutch debt", "dutch deficit", "dutch unemployment",
        "dutch wages", "dutch housing", "dutch mortgage",
        "shell netherlands", "philips", "asml",
        "ing bank", "abn amro", "rabobank",
        "unilever netherlands", "heineken", "akzo nobel",
        "wolters kluwer", "adyen", "nxp semiconductors",
        "dutch business", "dutch investment", "dutch tourism",
        "dutch agriculture", "dutch logistics", "rotterdam port",
        "dutch pension fund", "apg", "pggm",
    ],
    "geopolitics": [
        "dutch foreign policy", "netherlands nato",
        "dutch sanctions", "dutch diplomacy", "dutch troops",
        "netherlands ukraine", "netherlands russia",
        "dutch ambassador", "netherlands eu",
        "dutch defense", "dutch military",
        "the hague", "icj netherlands", "icc netherlands",
        "netherlands middle east", "dutch africa",
        "dutch caribbean", "dutch overseas territories",
    ],
    "energy": [
        "dutch energy", "groningen gas", "dutch gas",
        "dutch electricity", "dutch renewables",
        "dutch offshore wind", "dutch solar", "dutch grid",
        "dutch climate", "dutch emissions", "dutch lng",
        "dutch energy transition", "dutch hydrogen",
        "shell energy netherlands", "dutch energy prices",
    ],
    "technology": [
        "asml netherlands", "dutch tech", "dutch startup",
        "dutch ai", "dutch fintech", "dutch semiconductor",
        "dutch digital", "dutch innovation",
        "dutch unicorn", "techleap", "dutch quantum",
        "nxp dutch", "dutch cybersecurity",
    ],
    "health": [
        "dutch health", "dutch hospital", "dutch pharma",
        "dutch vaccine", "dutch healthcare",
        "dutch mental health", "dutch health system",
        "dutch medicine", "netherlands health",
    ],
    "crime": [
        "dutch corruption", "dutch fraud", "dutch scandal",
        "dutch court", "dutch investigation",
        "dutch organized crime", "dutch drug trafficking",
        "dutch money laundering", "dutch cybercrime",
        "dutch mafia", "mocro maffia",
        "dutch terrorism", "dutch police",
        "amsterdam explosion", "dutch shooting",
    ],
    "politics": [
        "tweede kamer", "eerste kamer", "dutch parliament",
        "dutch election", "dutch government", "dutch minister",
        "dutch prime minister", "dutch coalition",
        "pvv", "vvd", "d66", "nsc", "bbb",
        "geert wilders", "mark rutte", "dick schoof",
        "dutch policy", "dutch reform", "dutch opposition",
        "dutch citizenship", "dutch immigration",
        "dutch integration", "dutch referendum",
    ],
}
