
# mood/pipeline/keywords/no.py
NO_KEYWORDS = {
    "finance": [
        "norwegian economy", "norway gdp", "oslo bors",
        "oslo stock exchange", "osebx",
        "norges bank", "norwegian krone", "nok",
        "norwegian inflation", "norwegian budget",
        "norwegian exports", "norwegian trade",
        "norwegian market", "norwegian growth",
        "norwegian debt", "norwegian surplus",
        "norwegian unemployment", "norwegian wages",
        "norwegian housing", "norwegian mortgage",
        "equinor", "dnb bank", "telenor",
        "yara", "norsk hydro", "kongsberg",
        "orkla", "mowi", "salmar",
        "norwegian oil fund", "sovereign wealth fund",
        "government pension fund", "nbim",
        "norwegian salmon", "norwegian shipping",
        "norwegian seafood", "norwegian fish",
        "norwegian business", "norwegian investment",
        "norwegian tourism", "norwegian manufacturing",
    ],
    "geopolitics": [
        "norwegian foreign policy", "norway nato",
        "norwegian sanctions", "norwegian diplomacy",
        "norwegian troops", "norway ukraine", "norway russia",
        "norwegian ambassador", "norway eu", "norway ees",
        "norwegian defense", "norwegian military",
        "oslo talks", "norway arctic", "svalbard",
        "norway middle east", "norwegian peacekeeping",
        "norway security", "norwegian intelligence",
        "barents sea", "norwegian sea",
    ],
    "energy": [
        "norwegian energy", "norwegian oil", "norwegian gas",
        "equinor energy", "north sea norway",
        "norwegian electricity", "norwegian hydro",
        "norwegian renewables", "norwegian wind",
        "norwegian offshore", "norwegian pipeline",
        "norwegian lng", "norwegian grid",
        "norwegian climate", "norwegian emissions",
        "norwegian energy transition", "norwegian hydrogen",
        "norwegian carbon capture", "northern lights ccs",
    ],
    "technology": [
        "norwegian tech", "oslo tech", "norwegian startup",
        "norwegian ai", "norwegian fintech", "norwegian digital",
        "norwegian innovation", "norwegian unicorn",
        "norwegian cybersecurity", "norwegian maritime tech",
        "norwegian offshore tech", "norwegian cleantech",
        "kahoot", "opera browser", "norwegian gaming",
    ],
    "health": [
        "norwegian health", "norwegian hospital",
        "norwegian pharma", "norwegian vaccine",
        "norwegian healthcare", "norwegian mental health",
        "norwegian health system", "norwegian medicine",
        "norwegian public health", "folkehelseinstituttet",
    ],
    "crime": [
        "norwegian corruption", "norwegian fraud",
        "norwegian scandal", "norwegian court",
        "norwegian investigation", "norwegian organized crime",
        "norwegian drug trafficking", "norwegian money laundering",
        "norwegian terrorism", "norwegian police",
        "norwegian shooting", "kripos norway",
    ],
    "politics": [
        "storting", "norwegian parliament", "norwegian election",
        "norwegian government", "norwegian minister",
        "norwegian prime minister", "norwegian coalition",
        "norwegian opposition", "labour norway",
        "conservative norway", "progress party norway",
        "jonas gahr store", "erna solberg",
        "norwegian policy", "norwegian reform",
        "norwegian immigration", "norwegian welfare",
        "norwegian model", "norwegian citizenship",
        "norwegian oil policy", "norwegian climate policy",
    ],
}