
# mood/pipeline/keywords/nz.py
NZ_KEYWORDS = {
    "finance": [
        "new zealand economy", "new zealand gdp", "nzx 50",
        "new zealand stock exchange", "nzx",
        "reserve bank new zealand", "rbnz",
        "new zealand dollar", "nzd",
        "new zealand inflation", "new zealand budget",
        "new zealand exports", "new zealand trade",
        "new zealand market", "new zealand growth",
        "new zealand debt", "new zealand deficit",
        "new zealand unemployment", "new zealand wages",
        "new zealand housing", "new zealand mortgage",
        "anz new zealand", "westpac nz",
        "bnz bank", "asb bank new zealand",
        "fonterra", "a2 milk", "fisher paykel",
        "air new zealand", "spark nz",
        "new zealand business", "new zealand investment",
        "new zealand tourism", "new zealand manufacturing",
        "new zealand agriculture", "new zealand dairy",
        "new zealand wool", "new zealand kiwifruit",
        "new zealand wine", "new zealand seafood",
        "new zealand eu trade", "new zealand us trade",
        "new zealand tariffs", "new zealand fiscal",
        "new zealand pension fund", "nz super fund",
        "new zealand industry", "new zealand startup",
        "new zealand fintech", "new zealand real estate",
        "new zealand construction", "new zealand property",
    ],
    "geopolitics": [
        "new zealand foreign policy", "new zealand nato",
        "new zealand sanctions", "new zealand diplomacy",
        "new zealand troops", "new zealand ukraine",
        "new zealand russia", "new zealand ambassador",
        "new zealand eu", "new zealand defense",
        "new zealand military", "wellington talks",
        "new zealand security", "new zealand intelligence",
        "gcsb new zealand", "nzsis",
        "new zealand china relations",
        "new zealand us relations", "new zealand five eyes",
        "new zealand australia", "anzac",
        "new zealand pacific", "new zealand pacific islands",
        "new zealand peacekeeping", "new zealand un",
        "new zealand middle east", "new zealand gulf",
        "new zealand south china sea",
        "new zealand taiwan", "new zealand aukus",
    ],
    "energy": [
        "new zealand energy", "new zealand electricity",
        "new zealand renewables", "new zealand solar",
        "new zealand wind", "new zealand hydro",
        "new zealand grid", "new zealand climate",
        "new zealand emissions", "new zealand energy transition",
        "new zealand hydrogen", "new zealand lng",
        "new zealand energy prices", "new zealand energy security",
        "new zealand green energy", "new zealand geothermal",
        "new zealand carbon neutral", "new zealand net zero",
        "new zealand fuel prices", "new zealand coal",
        "transpower new zealand", "new zealand ets",
        "new zealand offshore wind",
    ],
    "technology": [
        "new zealand tech", "auckland tech", "new zealand startup",
        "new zealand ai", "new zealand fintech",
        "new zealand digital", "new zealand innovation",
        "new zealand unicorn", "new zealand cybersecurity",
        "new zealand gaming", "new zealand software",
        "new zealand it sector", "new zealand ecommerce",
        "new zealand digital economy", "new zealand ev",
        "new zealand smart city", "new zealand medtech",
        "new zealand biotech", "new zealand quantum",
        "new zealand space", "rocketlab new zealand",
        "new zealand 5g", "new zealand blockchain",
        "xero new zealand", "new zealand saas",
    ],
    "health": [
        "new zealand health", "new zealand hospital",
        "new zealand pharma", "new zealand vaccine",
        "new zealand healthcare", "new zealand mental health",
        "new zealand health system", "new zealand medicine",
        "new zealand public health", "new zealand wellbeing",
        "new zealand biotech", "new zealand cancer",
        "new zealand aging population", "new zealand birthrate",
        "ministry of health nz", "new zealand pharmac",
        "new zealand drug approval", "new zealand gp",
        "new zealand maori health",
    ],
    "crime": [
        "new zealand corruption", "new zealand fraud",
        "new zealand scandal", "new zealand court",
        "new zealand investigation", "new zealand organized crime",
        "new zealand drug trafficking", "new zealand money laundering",
        "new zealand terrorism", "new zealand police",
        "nz police", "new zealand gang",
        "new zealand anti corruption", "sfo new zealand",
        "new zealand cybercrime", "new zealand scam",
        "new zealand arrest", "new zealand gang violence",
        "mongrel mob", "black power nz",
        "new zealand human trafficking",
        "new zealand protest", "new zealand riot",
        "christchurch attack",
    ],
    "politics": [
        "new zealand parliament", "new zealand election",
        "new zealand government", "new zealand minister",
        "new zealand prime minister", "new zealand coalition",
        "new zealand opposition", "national party nz",
        "christopher luxon", "labour party nz",
        "chris hipkins", "act party nz",
        "david seymour", "new zealand first",
        "winston peters", "greens nz",
        "new zealand policy", "new zealand reform",
        "new zealand immigration", "new zealand integration",
        "new zealand welfare", "new zealand citizenship",
        "new zealand referendum", "new zealand judiciary",
        "new zealand rule of law", "new zealand eu relations",
        "new zealand democracy", "new zealand king",
        "new zealand governor general", "new zealand republic",
        "new zealand media freedom", "new zealand press freedom",
        "new zealand constitution", "new zealand treaty",
        "treaty of waitangi", "maori rights",
        "new zealand indigenous", "new zealand co governance",
    ],
}
