
# mood/pipeline/keywords/om.py
OM_KEYWORDS = {
    "finance": [
        "oman economy", "oman gdp",
        "muscat securities market", "msm oman",
        "central bank oman", "cbo",
        "omani rial", "omr",
        "oman inflation", "oman budget",
        "oman exports", "oman trade",
        "oman market", "oman growth",
        "oman debt", "oman deficit",
        "oman unemployment", "oman wages",
        "oman housing", "oman mortgage",
        "bank muscat", "national bank oman",
        "bank dhofar", "ahli bank oman",
        "oman oil company", "ood oman",
        "pdo oman", "petroleum development oman",
        "oman investment authority", "oia",
        "oman sovereign wealth fund",
        "oman business", "oman investment",
        "oman tourism", "oman manufacturing",
        "oman vision 2040", "oman diversification",
        "oman eu trade", "oman us trade",
        "oman tariffs", "oman fiscal",
        "oman oil revenue", "oman gas revenue",
        "oman lng", "oman port salalah",
        "oman port sohar", "oman logistics hub",
    ],
    "geopolitics": [
        "oman foreign policy", "oman nato",
        "oman sanctions", "oman diplomacy",
        "oman troops", "oman ukraine", "oman russia",
        "oman ambassador", "oman eu",
        "oman defense", "oman military",
        "muscat talks", "oman security",
        "oman intelligence", "oman us relations",
        "oman iran relations", "oman mediation",
        "oman israel", "oman middle east",
        "oman gulf", "oman saudi relations",
        "oman gcc", "oman qatar",
        "oman peacekeeping", "oman un",
        "oman china relations", "oman india",
        "oman strait hormuz", "oman neutrality",
        "oman diplomacy iran us",
        "oman back channel diplomacy",
        "oman yemen conflict",
    ],
    "energy": [
        "oman energy", "oman oil", "oman gas",
        "pdo energy", "oman electricity",
        "oman renewables", "oman solar",
        "oman wind", "oman grid",
        "oman climate", "oman emissions",
        "oman energy transition", "oman hydrogen",
        "oman lng", "oman energy prices",
        "oman energy security", "oman green energy",
        "oman carbon neutral", "oman net zero",
        "oman fuel prices", "oman oil production",
        "oman refinery", "oman petrochemical",
        "oman energy 2040", "oman green hydrogen",
        "oman solar project",
    ],
    "technology": [
        "oman tech", "muscat tech", "oman startup",
        "oman ai", "oman fintech", "oman digital",
        "oman innovation", "oman cybersecurity",
        "oman software", "oman it sector",
        "oman ecommerce", "oman digital economy",
        "oman smart city", "oman medtech",
        "oman blockchain", "oman 5g",
        "oman digital transformation",
        "oman vision 2040 tech",
        "omantel", "ooredoo oman",
        "oman technology park",
    ],
    "health": [
        "oman health", "oman hospital",
        "oman pharma", "oman vaccine",
        "oman healthcare", "oman mental health",
        "oman health system", "oman medicine",
        "oman public health", "oman wellbeing",
        "oman biotech", "oman cancer",
        "oman aging population",
        "oman health ministry", "moh oman",
        "oman medical tourism",
        "royal hospital oman",
        "sultan qaboos hospital",
    ],
    "crime": [
        "oman corruption", "oman fraud",
        "oman scandal", "oman court",
        "oman investigation", "oman organized crime",
        "oman drug trafficking", "oman money laundering",
        "oman terrorism", "oman police",
        "oman gang", "oman anti corruption",
        "oman cybercrime", "oman scam",
        "oman arrest", "oman human trafficking",
        "oman migrant workers", "oman kafala",
        "oman political prisoner",
        "oman protest",
    ],
    "politics": [
        "majlis al dawla oman", "majlis al shura",
        "oman parliament", "oman election",
        "oman government", "oman minister",
        "oman prime minister", "oman sultan",
        "haitham bin tariq", "oman royal family",
        "oman policy", "oman reform",
        "oman immigration", "oman integration",
        "oman welfare", "oman citizenship",
        "oman judiciary", "oman rule of law",
        "oman democracy", "oman media freedom",
        "oman press freedom", "oman constitution",
        "oman human rights", "oman labour reform",
        "oman expat population",
        "oman omanisation", "oman vision 2040 politics",
        "oman political stability",
        "oman succession",
    ],
}

