
# mood/pipeline/keywords/pe.py
PE_KEYWORDS = {
    "finance": [
        "peruvian economy", "peru gdp", "s&p bvl peru",
        "bolsa valores lima", "bvl peru",
        "central bank peru", "bcrp",
        "peruvian sol", "pen",
        "peruvian inflation", "peruvian budget",
        "peruvian exports", "peruvian trade",
        "peruvian market", "peruvian growth",
        "peruvian debt", "peruvian deficit",
        "peruvian unemployment", "peruvian wages",
        "peruvian housing", "peruvian mortgage",
        "banco de credito peru", "bcp peru",
        "bbva peru", "interbank peru",
        "scotiabank peru", "mibanco",
        "southern copper peru", "cerro verde",
        "antamina peru", "las bambas",
        "peruvian mining", "peruvian copper",
        "peruvian gold", "peruvian silver",
        "peruvian business", "peruvian investment",
        "peruvian tourism", "peruvian manufacturing",
        "peruvian agriculture", "peruvian asparagus",
        "peruvian blueberry", "peruvian quinoa",
        "peruvian eu trade", "peru us trade",
        "peruvian tariffs", "peruvian fiscal",
        "peruvian pension fund", "afp peru",
        "peruvian industry", "peruvian startup",
        "peruvian fintech", "peruvian real estate",
        "peruvian construction", "peruvian remittances",
        "napoleon becer peru elections",
    ],
    "geopolitics": [
        "peruvian foreign policy", "peru nato",
        "peruvian sanctions", "peruvian diplomacy",
        "peruvian troops", "peru ukraine",
        "peru russia", "peruvian ambassador",
        "peru eu", "peruvian defense",
        "peruvian military", "lima talks",
        "peru security", "peruvian intelligence",
        "peru us relations", "peru chile",
        "peru bolivia", "peru ecuador",
        "peru colombia", "peru brazil",
        "peruvian peacekeeping", "peru un",
        "peru brics", "peru g20",
        "peruvian border dispute",
        "peru pacific alliance",
        "jungle pipeline peru",
        "gas pipeline explosion peru",
    ],
    "energy": [
        "peruvian energy", "peruvian oil",
        "peruvian gas", "peruvian electricity",
        "peruvian renewables", "peruvian solar",
        "peruvian wind", "peruvian hydro",
        "peruvian grid", "peruvian climate",
        "peruvian emissions", "peruvian energy transition",
        "peruvian hydrogen", "peruvian lng",
        "peruvian energy prices", "peruvian energy security",
        "peruvian green energy", "peruvian carbon neutral",
        "peruvian net zero", "peruvian fuel prices",
        "camisea gas peru", "peru lng",
        "peruvian mining energy",
        "fragile gas system peru",
    ],
    "technology": [
        "peruvian tech", "lima tech", "peruvian startup",
        "peruvian ai", "peruvian fintech",
        "peruvian digital", "peruvian innovation",
        "peruvian unicorn", "peruvian cybersecurity",
        "peruvian software", "peruvian it sector",
        "peruvian ecommerce", "peruvian digital economy",
        "peruvian semiconductor", "peruvian ev",
        "peruvian smart city", "peruvian medtech",
        "peruvian biotech", "peruvian 5g",
        "peruvian blockchain",
        "peruvian digital transformation",
    ],
    "health": [
        "peruvian health", "peruvian hospital",
        "peruvian pharma", "peruvian vaccine",
        "peruvian healthcare", "peruvian mental health",
        "peruvian health system", "peruvian medicine",
        "peruvian public health", "peruvian wellbeing",
        "peruvian biotech", "peruvian cancer",
        "peruvian aging population",
        "peruvian dengue", "peruvian malaria",
        "peruvian tuberculosis",
        "digemid peru",
        "peruvian amazon medicine",
        "peruvian traditional medicine",
    ],
    "crime": [
        "peruvian corruption", "peruvian fraud",
        "peruvian scandal", "peruvian court",
        "peruvian investigation", "peruvian organized crime",
        "peruvian drug trafficking", "peruvian money laundering",
        "peruvian terrorism", "peruvian police",
        "peruvian gang", "peruvian anti corruption",
        "peruvian cybercrime", "peruvian scam",
        "peruvian arrest", "sendero luminoso",
        "peruvian human trafficking",
        "peruvian illegal mining",
        "peruvian protest", "peruvian riot",
        "peruvian political scandal",
        "peruvian femicide",
        "peruvian political instability",
    ],
    "politics": [
        "congreso peru", "peruvian parliament",
        "peruvian election", "peruvian government",
        "peruvian minister", "peruvian president",
        "peruvian coalition", "peruvian opposition",
        "dina boluarte", "boluarte",
        "fuerza popular peru", "keiko fujimori",
        "peruvian policy", "peruvian reform",
        "peruvian immigration", "peruvian diaspora",
        "peruvian welfare", "peruvian citizenship",
        "peruvian referendum", "peruvian judiciary",
        "peruvian rule of law", "peruvian eu relations",
        "peruvian democracy", "peruvian media freedom",
        "peruvian press freedom", "peruvian constitution",
        "peruvian federalism", "peruvian indigenous",
        "peruvian political crisis",
        "peru 2026 elections",
        "napoleon becer presidential",
    ],
}
