
# mood/pipeline/keywords/pg.py
PG_KEYWORDS = {
    "finance": [
        "papua new guinea economy", "png gdp",
        "port moresby stock exchange", "pomsx",
        "bank of papua new guinea", "bpng",
        "png kina", "pgk",
        "png inflation", "png budget",
        "png exports", "png trade",
        "png market", "png growth",
        "png debt", "png deficit",
        "png unemployment", "png wages",
        "png housing", "png mortgage",
        "oil search png", "santos png",
        "exxon png", "png lng",
        "png minerals", "png gold",
        "png copper", "png nickel",
        "bank south pacific", "kina bank",
        "png business", "png investment",
        "png tourism", "png manufacturing",
        "png agriculture", "png coffee",
        "png cocoa", "png palm oil",
        "png timber", "png fisheries",
        "png eu funds", "png recovery plan",
        "png pension fund", "png industry",
        "png remittances", "png diaspora",
    ],
    "geopolitics": [
        "png foreign policy", "papua new guinea nato",
        "png sanctions", "png diplomacy",
        "png troops", "png ukraine", "png russia",
        "png ambassador", "png eu",
        "png defense", "png military",
        "port moresby talks", "png security",
        "png intelligence", "png australia",
        "png china relations", "png us relations",
        "png pacific", "png asean",
        "png peacekeeping", "png un",
        "png middle east", "png bougainville",
        "bougainville independence",
        "png solomon islands",
        "pacific security png",
    ],
    "energy": [
        "png energy", "png electricity",
        "png renewables", "png solar",
        "png hydro", "png grid",
        "png climate", "png emissions",
        "png energy transition", "png lng",
        "png energy prices", "png energy security",
        "png green energy", "png natural gas",
        "png oil", "png petrochemical",
        "png carbon neutral", "png net zero",
        "png fuel prices", "png power outage",
        "png blackout", "png energy crisis",
    ],
    "technology": [
        "png tech", "png startup",
        "png ai", "png fintech",
        "png digital", "png innovation",
        "png cybersecurity", "png software",
        "png it sector", "png ecommerce",
        "png digital economy", "png mobile banking",
        "png internet", "png connectivity",
        "png smart city", "png medtech",
        "digicel png", "bmobile png",
    ],
    "health": [
        "png health", "png hospital",
        "png pharma", "png vaccine",
        "png healthcare", "png mental health",
        "png health system", "png medicine",
        "png public health", "png wellbeing",
        "png malaria", "png tuberculosis",
        "png hiv", "png dengue",
        "png health crisis", "png medical aid",
        "png maternal health", "png child health",
        "who png", "png disease outbreak",
    ],
    "crime": [
        "png corruption", "png fraud",
        "png scandal", "png court",
        "png investigation", "png organized crime",
        "png drug trafficking", "png money laundering",
        "png terrorism", "png police",
        "png gang", "png anti corruption",
        "png cybercrime", "png scam",
        "png arrest", "png tribal conflict",
        "png highlands conflict",
        "png human trafficking",
        "png protest", "png riot",
        "png election violence",
    ],
    "politics": [
        "national parliament png", "png parliament",
        "png election", "png government",
        "png minister", "png prime minister",
        "png coalition", "png opposition",
        "pangu party png", "people's national congress",
        "james marape", "peter o'neill",
        "png policy", "png reform",
        "png immigration", "png diaspora",
        "png welfare", "png citizenship",
        "png referendum", "png judiciary",
        "png rule of law", "png eu relations",
        "png democracy", "png king",
        "png governor general", "png constitution",
        "bougainville referendum",
        "png media freedom",
        "png press freedom",
        "png tribal politics",
        "png highlands politics",
    ],
}
