
# mood/pipeline/keywords/ph.py
PH_KEYWORDS = {
    "finance": [
        "philippine economy", "philippines gdp", "psei index",
        "philippine stock exchange", "pse philippines",
        "bangko sentral pilipinas", "bsp philippines",
        "philippine peso", "php",
        "philippine inflation", "philippine budget",
        "philippine exports", "philippine trade",
        "philippine market", "philippine growth",
        "philippine debt", "philippine deficit",
        "philippine unemployment", "philippine wages",
        "philippine housing", "philippine mortgage",
        "sm group", "ayala group", "jg summit",
        "metrobank", "bdo unibank", "bpi philippines",
        "pldt", "globe telecom", "meralco",
        "philippine business", "philippine investment",
        "philippine tourism", "philippine manufacturing",
        "philippine automotive", "philippine agriculture",
        "philippine rice", "philippine coconut",
        "philippine eu funds", "philippine recovery plan",
        "philippine pension fund", "sss philippines",
        "philippine industry", "philippine it sector",
        "philippine bpo", "philippine outsourcing",
        "philippine startup", "philippine real estate",
        "philippines us trade", "philippine tariffs",
        "philippine trade deal", "philippine fiscal",
        "philippine remittances", "ofw remittances",
    ],
    "geopolitics": [
        "philippine foreign policy", "philippines nato",
        "philippine sanctions", "philippine diplomacy",
        "philippine troops", "philippines ukraine",
        "philippines russia", "philippine ambassador",
        "philippines eu", "philippine defense",
        "philippine military", "manila talks",
        "philippines security", "philippine intelligence",
        "philippines china", "south china sea philippines",
        "west philippine sea", "spratly islands",
        "scarborough shoal", "philippines us relations",
        "philippines us military", "vfa philippines",
        "philippines asean", "philippines japan",
        "philippines australia", "philippine peacekeeping",
        "philippines un", "philippines middle east",
        "philippines gulf", "ofw middle east",
    ],
    "energy": [
        "philippine energy", "philippine electricity",
        "philippine renewables", "philippine solar",
        "philippine wind", "philippine hydro",
        "philippine grid", "philippine climate",
        "philippine emissions", "philippine energy transition",
        "philippine hydrogen", "philippine lng",
        "philippine energy prices", "philippine energy security",
        "philippine green energy", "philippine coal",
        "philippine natural gas", "philippine geothermal",
        "philippine carbon neutral", "philippine net zero",
        "philippine fuel prices", "meralco energy",
        "philippine power outage", "philippine blackout",
    ],
    "technology": [
        "philippine tech", "manila tech", "philippine startup",
        "philippine ai", "philippine fintech",
        "philippine digital", "philippine innovation",
        "philippine unicorn", "philippine cybersecurity",
        "philippine gaming", "philippine software",
        "philippine it sector", "philippine bpo",
        "philippine ecommerce", "philippine digital economy",
        "philippine semiconductor", "philippine ev",
        "philippine smart city", "philippine medtech",
        "grab philippines", "gcash", "paymaya",
        "philippine blockchain", "dito telecom",
    ],
    "health": [
        "philippine health", "philippine hospital",
        "philippine pharma", "philippine vaccine",
        "philippine healthcare", "philippine mental health",
        "philippine health system", "philippine medicine",
        "philippine public health", "philippine wellbeing",
        "philippine medical tourism", "philippine biotech",
        "philippine cancer", "philippine dengue",
        "philippine malaria", "doh philippines",
        "philippine aging population",
        "philippine typhoon health",
    ],
    "crime": [
        "philippine corruption", "philippine fraud",
        "philippine scandal", "philippine court",
        "philippine investigation", "philippine organized crime",
        "philippine drug war", "philippine drug trafficking",
        "philippine money laundering", "philippine terrorism",
        "philippine police", "pnp philippines",
        "philippine gang", "philippine anti corruption",
        "ombudsman philippines", "philippine cybercrime",
        "philippine scam", "philippine arrest",
        "philippine kidnapping", "philippine abu sayyaf",
        "philippine human trafficking",
        "philippine extrajudicial killing",
        "philippine protest", "philippine riot",
    ],
    "politics": [
        "house of representatives philippines",
        "philippine senate", "philippine parliament",
        "philippine election", "philippine government",
        "philippine minister", "philippine president",
        "philippine coalition", "philippine opposition",
        "ferdinand marcos", "bongbong marcos", "marcos",
        "leni robredo", "sara duterte",
        "rodrigo duterte", "duterte",
        "pdp laban", "lakas cmd",
        "philippine policy", "philippine reform",
        "philippine immigration", "philippine diaspora",
        "philippine welfare", "philippine citizenship",
        "philippine referendum", "philippine judiciary",
        "philippine rule of law", "philippine eu relations",
        "philippine democracy", "philippine media freedom",
        "philippine press freedom", "philippine constitution",
        "philippine federalism", "mindanao conflict",
        "bangsamoro", "philippine martial law",
    ],
}