
# mood/pipeline/keywords/pk.py
PK_KEYWORDS = {
    "finance": [
        "pakistani economy", "pakistan gdp", "kse 100",
        "karachi stock exchange", "psx pakistan",
        "state bank pakistan", "sbp",
        "pakistani rupee", "pkr",
        "pakistani inflation", "pakistani budget",
        "pakistani exports", "pakistani trade",
        "pakistani market", "pakistani growth",
        "pakistani debt", "pakistani deficit",
        "pakistani unemployment", "pakistani wages",
        "pakistani housing", "pakistani mortgage",
        "habib bank", "hbl pakistan",
        "united bank pakistan", "ubl",
        "meezan bank", "mcb bank pakistan",
        "pakistan petroleum", "ogdc pakistan",
        "pakistan state oil", "pso",
        "pakistani business", "pakistani investment",
        "pakistani tourism", "pakistani manufacturing",
        "pakistani textile", "pakistani agriculture",
        "pakistani cotton", "pakistani rice",
        "pakistani eu trade", "pakistan us trade",
        "pakistani tariffs", "pakistani fiscal",
        "pakistani pension fund", "eobi pakistan",
        "pakistani industry", "pakistani startup",
        "pakistani fintech", "pakistani real estate",
        "pakistani construction", "pakistani remittances",
        "pakistani diaspora", "pakistan imf deal",
        "shehbaz economic policy",
        "pakistani debt crisis",
        "pakistani currency devaluation",
        "cpec pakistan china",
    ],
    "geopolitics": [
        "pakistani foreign policy", "pakistan nato",
        "pakistani sanctions", "pakistani diplomacy",
        "pakistani troops", "pakistan ukraine",
        "pakistan russia", "pakistani ambassador",
        "pakistan eu", "pakistani defense",
        "pakistani military", "islamabad talks",
        "pakistan security", "pakistani intelligence",
        "isi pakistan", "pakistan us relations",
        "pakistan china relations", "cpec",
        "pakistan india relations", "kashmir conflict",
        "line of control pakistan",
        "pakistan afghanistan", "pakistan iran",
        "pakistan turkey", "pakistan saudi",
        "pakistan brics", "pakistan sco",
        "pakistan peacekeeping", "pakistan un",
        "pakistan nuclear weapons",
        "dar diplomacy pakistan",
        "pakistan regional peace",
        "pakistan taliban",
        "pakistan afghanistan border",
    ],
    "energy": [
        "pakistani energy", "pakistani gas",
        "pakistani electricity", "pakistani renewables",
        "pakistani solar", "pakistani wind",
        "pakistani hydro", "pakistani grid",
        "pakistani climate", "pakistani emissions",
        "pakistani energy transition", "pakistani hydrogen",
        "pakistani lng", "pakistani energy prices",
        "pakistani energy security", "pakistani green energy",
        "pakistani carbon neutral", "pakistani net zero",
        "pakistani fuel prices", "pakistani coal",
        "pakistani nuclear energy", "chashma nuclear",
        "cpec energy projects",
        "pakistan energy crisis",
        "pakistan power outage",
        "pakistan circular debt energy",
    ],
    "technology": [
        "pakistani tech", "karachi tech", "pakistani startup",
        "pakistani ai", "pakistani fintech",
        "pakistani digital", "pakistani innovation",
        "pakistani unicorn", "pakistani cybersecurity",
        "pakistani gaming", "pakistani software",
        "pakistani it sector", "pakistani freelancers",
        "pakistani ecommerce", "pakistani digital economy",
        "pakistani 5g", "pakistani blockchain",
        "pakistani smart city", "pakistani medtech",
        "jazz pakistan", "telenor pakistan",
        "pakistani silicon valley",
        "pakistani it exports",
        "lahore tech",
    ],
    "health": [
        "pakistani health", "pakistani hospital",
        "pakistani pharma", "pakistani vaccine",
        "pakistani healthcare", "pakistani mental health",
        "pakistani health system", "pakistani medicine",
        "pakistani public health", "pakistani wellbeing",
        "pakistani cancer", "pakistani aging population",
        "pakistani polio", "pakistani dengue",
        "pakistani tuberculosis", "pakistani malaria",
        "pakistani flood health",
        "pakistani health reform",
        "drap pakistan",
        "pakistani maternal health",
        "pakistani child health",
    ],
    "crime": [
        "pakistani corruption", "pakistani fraud",
        "pakistani scandal", "pakistani court",
        "pakistani investigation", "pakistani organized crime",
        "pakistani drug trafficking", "pakistani money laundering",
        "pakistani terrorism", "pakistani police",
        "pakistani gang", "pakistani anti corruption",
        "nab pakistan", "fia pakistan",
        "pakistani cybercrime", "pakistani scam",
        "pakistani arrest", "pakistani human trafficking",
        "pakistani protest", "pakistani riot",
        "pakistani political scandal",
        "pakistani blasphemy case",
        "pakistani femicide",
        "pakistani honor killing",
        "imran khan arrest",
        "pakistani political prisoner",
    ],
    "politics": [
        "national assembly pakistan", "pakistani senate",
        "pakistani parliament", "pakistani election",
        "pakistani government", "pakistani minister",
        "pakistani prime minister", "pakistani coalition",
        "pakistani opposition", "pml n pakistan",
        "shehbaz sharif", "shehbaz pakistan",
        "pti pakistan", "imran khan",
        "ppp pakistan", "asif zardari",
        "pakistani policy", "pakistani reform",
        "pakistani immigration", "pakistani diaspora",
        "pakistani welfare", "pakistani citizenship",
        "pakistani referendum", "pakistani judiciary",
        "pakistani rule of law", "pakistani eu relations",
        "pakistani democracy", "pakistani media freedom",
        "pakistani press freedom", "pakistani constitution",
        "pakistani federalism", "pakistani provinces",
        "pakistani military politics",
        "dar stresses dialogue",
        "pakistan regional peace diplomacy",
        "hindu mosque temple pakistan",
    ],
}