

# mood/pipeline/keywords/pl.py
PL_KEYWORDS = {
    "finance": [
        "polish economy", "poland gdp", "wig20", "wig",
        "warsaw stock exchange", "gpw poland",
        "national bank poland", "nbp", "polish zloty", "pln",
        "polish inflation", "polish budget", "polish exports",
        "polish trade", "polish market", "polish growth",
        "polish debt", "polish deficit", "polish unemployment",
        "polish wages", "polish housing", "polish mortgage",
        "pkn orlen", "pko bank", "pko bp", "pzu insurance",
        "kghm", "lotos", "polish energy group", "tauron",
        "polish business", "polish investment",
        "polish tourism", "polish manufacturing",
        "polish agriculture", "polish food exports",
        "polish logistics", "polish construction",
        "polish eu funds", "polish recovery plan",
        "polish pension fund", "polish zloty exchange",
    ],
    "geopolitics": [
        "polish foreign policy", "poland nato",
        "polish sanctions", "polish diplomacy",
        "polish troops", "poland ukraine", "poland russia",
        "polish ambassador", "poland eu",
        "polish defense", "polish military",
        "warsaw talks", "poland belarus",
        "poland border", "polish security",
        "polish intelligence", "abw poland",
        "poland middle east", "polish peacekeeping",
        "poland germany relations", "polish eastern flank",
        "polish nato spending", "poland us relations",
    ],
    "energy": [
        "polish energy", "polish coal", "polish gas",
        "polish electricity", "polish renewables",
        "polish wind", "polish solar", "polish grid",
        "polish climate", "polish emissions",
        "polish energy transition", "polish hydrogen",
        "polish lng", "polish energy prices",
        "russian gas poland", "polish energy security",
        "polish nuclear", "polish offshore wind",
        "polish coal phase out", "tauron energy",
    ],
    "technology": [
        "polish tech", "warsaw tech", "polish startup",
        "polish ai", "polish fintech", "polish digital",
        "polish innovation", "polish unicorn",
        "polish cybersecurity", "polish gaming",
        "cd projekt", "cyberpunk poland", "techland",
        "polish software", "polish it sector",
        "polish semiconductor", "cracow tech",
    ],
    "health": [
        "polish health", "polish hospital", "polish pharma",
        "polish vaccine", "polish healthcare",
        "polish mental health", "polish health system",
        "polish medicine", "nfz poland",
        "polish public health", "polish wellbeing",
    ],
    "crime": [
        "polish corruption", "polish fraud", "polish scandal",
        "polish court", "polish investigation",
        "polish organized crime", "polish drug trafficking",
        "polish money laundering", "polish terrorism",
        "polish police", "polish shooting",
        "cba poland", "polish anti corruption",
        "polish gang", "polish mafia",
        "polish abolition anti corruption",
    ],
    "politics": [
        "sejm", "senat poland", "polish parliament",
        "polish election", "polish government",
        "polish minister", "polish prime minister",
        "polish coalition", "polish opposition",
        "donald tusk", "pis", "prawo i sprawiedliwosc",
        "jaroslaw kaczynski", "andrzej duda",
        "konfederacja", "td poland", "lewica poland",
        "polish policy", "polish reform",
        "polish immigration", "polish integration",
        "polish welfare", "polish model",
        "polish citizenship", "polish referendum",
        "polish judiciary", "polish rule of law",
        "polish eu relations", "polish democracy",
    ],
}

