
# mood/pipeline/keywords/pt.py
PT_KEYWORDS = {
    "finance": [
        "portuguese economy", "portugal gdp", "psi index",
        "lisbon stock exchange", "euronext lisbon",
        "bank of portugal", "banco de portugal",
        "portuguese euro", "portuguese inflation",
        "portuguese budget", "portuguese exports",
        "portuguese trade", "portuguese market",
        "portuguese growth", "portuguese debt",
        "portuguese deficit", "portuguese unemployment",
        "portuguese wages", "portuguese housing",
        "portuguese mortgage", "caixa geral depositos",
        "bcp bank", "novo banco", "santander portugal",
        "millennium bcp", "bpi bank",
        "edp portugal", "galp energia",
        "nos telecoms", "sonae", "jeronimo martins",
        "portuguese business", "portuguese investment",
        "portuguese tourism", "portuguese manufacturing",
        "portuguese agriculture", "portuguese wine",
        "portuguese eu funds", "portuguese recovery plan",
        "prt recovery plan", "portuguese pension fund",
        "portuguese industry", "portuguese cork",
        "portuguese golden visa", "portuguese nhr",
        "portuguese real estate", "portuguese construction",
        "portuguese tech", "portuguese outsourcing",
        "portuguese remittances", "portuguese diaspora",
        "parrot recovery portugal",
    ],
    "geopolitics": [
        "portuguese foreign policy", "portugal nato",
        "portuguese sanctions", "portuguese diplomacy",
        "portuguese troops", "portugal ukraine",
        "portugal russia", "portuguese ambassador",
        "portugal eu", "portuguese defense",
        "portuguese military", "lisbon talks",
        "portugal security", "portuguese intelligence",
        "sied portugal", "portugal africa",
        "portuguese speaking", "lusophone",
        "portugal brazil", "portugal angola",
        "portugal mozambique", "cplp",
        "peace not war portugal", "lisbon protest",
        "portugal middle east", "portuguese peacekeeping",
        "portugal nato southern flank",
    ],
    "energy": [
        "portuguese energy", "portuguese electricity",
        "portuguese renewables", "portuguese solar",
        "portuguese wind", "portuguese hydro",
        "portuguese grid", "portuguese climate",
        "portuguese emissions", "portuguese energy transition",
        "portuguese hydrogen", "portuguese lng",
        "portuguese energy prices", "portuguese energy security",
        "edp renewables", "portuguese offshore wind",
        "portuguese green energy", "portuguese nuclear debate",
        "portuguese coal phase out", "portuguese biomass",
        "redes energeticas nacionais",
    ],
    "technology": [
        "portuguese tech", "lisbon tech", "portuguese startup",
        "portuguese ai", "portuguese fintech",
        "portuguese digital", "portuguese innovation",
        "portuguese unicorn", "portuguese cybersecurity",
        "portuguese gaming", "portuguese software",
        "portuguese it sector", "portuguese outsourcing",
        "farfetch portugal", "feedzai", "talkdesk",
        "portuguese semiconductor", "porto tech",
        "portuguese quantum", "web summit lisbon",
        "portuguese space", "portuguese robotics",
    ],
    "health": [
        "portuguese health", "portuguese hospital",
        "portuguese pharma", "bial pharma",
        "portuguese vaccine", "portuguese healthcare",
        "portuguese mental health", "portuguese health system",
        "portuguese medicine", "sns portugal",
        "portuguese public health", "portuguese wellbeing",
        "portuguese medical tourism", "portuguese biotech",
        "portuguese cancer research",
    ],
    "crime": [
        "portuguese corruption", "portuguese fraud",
        "portuguese scandal", "portuguese court",
        "portuguese investigation", "portuguese organized crime",
        "portuguese drug trafficking", "portuguese money laundering",
        "portuguese terrorism", "portuguese police",
        "policia judiciaria", "gnr portugal",
        "portuguese gang", "portuguese anti corruption",
        "portuguese oligarch", "portuguese fraud scheme",
        "portuguese smuggling", "portuguese human trafficking",
        "portuguese protest", "lisbon demonstration",
        "peace protest portugal",
    ],
    "politics": [
        "assembleia da republica", "portuguese parliament",
        "portuguese election", "portuguese government",
        "portuguese minister", "portuguese prime minister",
        "portuguese coalition", "portuguese opposition",
        "ps portugal", "pedro nuno santos",
        "psd portugal", "luis montenegro",
        "chega", "andre ventura",
        "il portugal", "livre portugal",
        "portuguese policy", "portuguese reform",
        "portuguese immigration", "portuguese integration",
        "portuguese welfare", "portuguese citizenship",
        "portuguese referendum", "portuguese judiciary",
        "portuguese rule of law", "portuguese eu relations",
        "portuguese democracy", "portuguese president",
        "marcelo rebelo de sousa", "portuguese media freedom",
        "portuguese golden visa reform",
        "portuguese nhr reform",
    ],
}

