
# mood/pipeline/keywords/py.py
PY_KEYWORDS = {
    "finance": [
        "paraguayan economy", "paraguay gdp",
        "bolsa valores asuncion", "bvpasa",
        "central bank paraguay", "bcp",
        "paraguayan guarani", "pyg",
        "paraguayan inflation", "paraguayan budget",
        "paraguayan exports", "paraguayan trade",
        "paraguayan market", "paraguayan growth",
        "paraguayan debt", "paraguayan deficit",
        "paraguayan unemployment", "paraguayan wages",
        "paraguayan housing", "paraguayan mortgage",
        "banco continental paraguay",
        "banco itau paraguay", "vision banco",
        "banco regional paraguay",
        "itaipu dam paraguay", "itaipu energy",
        "paraguayan soybean", "paraguayan beef",
        "paraguayan corn", "paraguayan wheat",
        "paraguayan business", "paraguayan investment",
        "paraguayan tourism", "paraguayan manufacturing",
        "paraguayan agriculture", "paraguayan stevia",
        "paraguayan eu trade", "paraguay us trade",
        "paraguayan tariffs", "paraguayan fiscal",
        "paraguayan pension fund", "ips paraguay",
        "paraguayan industry", "paraguayan startup",
        "paraguayan fintech", "paraguayan real estate",
        "paraguayan construction", "paraguayan remittances",
        "paraguayan crypto hub", "paraguay bitcoin",
        "paraguayan maquiladora",
    ],
    "geopolitics": [
        "paraguayan foreign policy", "paraguay nato",
        "paraguayan sanctions", "paraguayan diplomacy",
        "paraguayan troops", "paraguay ukraine",
        "paraguay russia", "paraguayan ambassador",
        "paraguay eu", "paraguayan defense",
        "paraguayan military", "asuncion talks",
        "paraguay security", "paraguayan intelligence",
        "paraguay us relations", "paraguay argentina",
        "paraguay brazil", "paraguay bolivia",
        "paraguay mercosur", "paraguay taiwan",
        "paraguay china", "paraguay taiwan relations",
        "paraguayan peacekeeping", "paraguay un",
        "paraguay brics", "paraguay g20",
        "santiago pena foreign policy",
        "paraguay triple frontier",
        "paraguay border crime",
    ],
    "energy": [
        "paraguayan energy", "paraguayan electricity",
        "itaipu hydroelectric", "yacyreta dam",
        "paraguayan renewables", "paraguayan solar",
        "paraguayan wind", "paraguayan hydro",
        "paraguayan grid", "paraguayan climate",
        "paraguayan emissions", "paraguayan energy transition",
        "paraguayan hydrogen", "paraguayan lng",
        "paraguayan energy prices", "paraguayan energy security",
        "paraguayan green energy", "paraguayan carbon neutral",
        "paraguayan net zero", "paraguayan fuel prices",
        "paraguayan energy exports",
        "ande paraguay", "petrobras paraguay",
        "paraguayan energy surplus",
    ],
    "technology": [
        "paraguayan tech", "asuncion tech",
        "paraguayan startup", "paraguayan ai",
        "paraguayan fintech", "paraguayan digital",
        "paraguayan innovation", "paraguayan unicorn",
        "paraguayan cybersecurity", "paraguayan gaming",
        "paraguayan software", "paraguayan it sector",
        "paraguayan ecommerce", "paraguayan digital economy",
        "paraguayan semiconductor", "paraguayan ev",
        "paraguayan smart city", "paraguayan medtech",
        "paraguayan biotech", "paraguayan 5g",
        "paraguayan blockchain", "paraguayan crypto",
        "paraguayan bitcoin mining",
        "paraguayan digital transformation",
        "tigo paraguay", "personal paraguay",
    ],
    "health": [
        "paraguayan health", "paraguayan hospital",
        "paraguayan pharma", "paraguayan vaccine",
        "paraguayan healthcare", "paraguayan mental health",
        "paraguayan health system", "paraguayan medicine",
        "paraguayan public health", "paraguayan wellbeing",
        "paraguayan biotech", "paraguayan cancer",
        "paraguayan aging population", "paraguayan birthrate",
        "mspbs paraguay", "paraguayan drug approval",
        "paraguayan dengue", "paraguayan malaria",
        "paraguayan chagas disease",
        "paraguayan health reform",
        "paraguayan indigenous health",
    ],
    "crime": [
        "paraguayan corruption", "paraguayan fraud",
        "paraguayan scandal", "paraguayan court",
        "paraguayan investigation", "paraguayan organized crime",
        "paraguayan drug trafficking", "paraguayan cocaine",
        "paraguayan money laundering", "paraguayan terrorism",
        "paraguayan police", "paraguayan gang",
        "paraguayan anti corruption",
        "paraguayan cybercrime", "paraguayan scam",
        "paraguayan arrest", "paraguayan mafia",
        "paraguayan human trafficking",
        "paraguayan protest", "paraguayan riot",
        "paraguayan political scandal",
        "paraguayan triple frontier crime",
        "paraguayan contraband",
        "sebastian marset paraguay",
        "paraguayan femicide",
        "paraguayan political corruption",
    ],
    "politics": [
        "congreso paraguay", "senado paraguay",
        "paraguayan parliament", "paraguayan election",
        "paraguayan government", "paraguayan minister",
        "paraguayan president", "paraguayan coalition",
        "paraguayan opposition", "partido colorado",
        "santiago pena", "pena paraguay",
        "efrain alegre", "partido liberal paraguay",
        "paraguayan policy", "paraguayan reform",
        "paraguayan immigration", "paraguayan diaspora",
        "paraguayan welfare", "paraguayan citizenship",
        "paraguayan referendum", "paraguayan judiciary",
        "paraguayan rule of law", "paraguayan eu relations",
        "paraguayan democracy", "paraguayan media freedom",
        "paraguayan press freedom", "paraguayan constitution",
        "paraguayan federalism", "paraguayan regions",
        "paraguayan indigenous rights",
        "paraguayan colorado dominance",
        "paraguayan political stability",
        "paraguay taiwan recognition",
    ],
}