
# mood/pipeline/keywords/qa.py
QA_KEYWORDS = {
    "finance": [
        "qatar economy", "qatar gdp", "qatar exchange",
        "qe qatar", "qatar central bank", "qcb",
        "qatari riyal", "qar",
        "qatar inflation", "qatar budget", "qatar exports",
        "qatar trade", "qatar market", "qatar growth",
        "qatar debt", "qatar surplus", "qatar unemployment",
        "qatar wages", "qatar housing", "qatar mortgage",
        "qatar national bank", "qnb",
        "qatar petroleum", "qatarenergy",
        "qatar airways", "ooredoo qatar",
        "qatar investment authority", "qia",
        "qatar sovereign wealth fund",
        "qatar business", "qatar investment",
        "qatar tourism", "qatar manufacturing",
        "qatar lng exports", "qatar gas",
        "qatar eu trade", "qatar us trade",
        "qatar tariffs", "qatar fiscal",
        "qatar world cup legacy", "qatar infrastructure",
        "qatar 2030 vision", "qatar diversification",
    ],
    "geopolitics": [
        "qatar foreign policy", "qatar nato",
        "qatar sanctions", "qatar diplomacy",
        "qatar troops", "qatar ukraine", "qatar russia",
        "qatar ambassador", "qatar eu",
        "qatar defense", "qatar military",
        "doha talks", "qatar security",
        "qatar intelligence", "qatar us relations",
        "qatar us base", "al udeid",
        "qatar iran relations", "qatar israel",
        "qatar hamas", "qatar mediation",
        "qatar middle east", "qatar gulf",
        "qatar saudi relations", "qatar blockade",
        "qatar gcc", "qatar asean",
        "qatar peacekeeping", "qatar un",
        "qatar taliban talks", "qatar afghanistan",
    ],
    "energy": [
        "qatar energy", "qatar lng",
        "qatar gas", "qatar oil",
        "qatar electricity", "qatar renewables",
        "qatar solar", "qatar grid",
        "qatar climate", "qatar emissions",
        "qatar energy transition", "qatar hydrogen",
        "qatar energy prices", "qatar energy security",
        "qatar green energy", "qatar carbon neutral",
        "qatar net zero", "qatar fuel prices",
        "qatarenergy lng", "qatar north field",
        "qatar gas expansion",
    ],
    "technology": [
        "qatar tech", "doha tech", "qatar startup",
        "qatar ai", "qatar fintech", "qatar digital",
        "qatar innovation", "qatar cybersecurity",
        "qatar software", "qatar it sector",
        "qatar ecommerce", "qatar digital economy",
        "qatar smart city", "qatar medtech",
        "qatar science technology park", "qstp",
        "qatar university tech", "qatar blockchain",
        "qatar 5g", "qatar quantum",
    ],
    "health": [
        "qatar health", "qatar hospital",
        "qatar pharma", "qatar vaccine",
        "qatar healthcare", "qatar mental health",
        "qatar health system", "qatar medicine",
        "qatar public health", "qatar wellbeing",
        "qatar biotech", "qatar cancer",
        "hamad medical corporation",
        "qatar sidra medicine",
        "qatar national health strategy",
    ],
    "crime": [
        "qatar corruption", "qatar fraud",
        "qatar scandal", "qatar court",
        "qatar investigation", "qatar organized crime",
        "qatar drug trafficking", "qatar money laundering",
        "qatar terrorism", "qatar police",
        "qatar gang", "qatar anti corruption",
        "qatar cybercrime", "qatar scam",
        "qatar arrest", "qatar human trafficking",
        "qatar migrant workers", "qatar kafala",
        "qatar world cup corruption",
        "qatar fifa scandal",
    ],
    "politics": [
        "qatar parliament", "qatar election",
        "qatar government", "qatar minister",
        "qatar prime minister", "qatar emir",
        "tamim bin hamad", "tamim",
        "qatar policy", "qatar reform",
        "qatar immigration", "qatar integration",
        "qatar welfare", "qatar citizenship",
        "qatar judiciary", "qatar rule of law",
        "qatar democracy", "qatar media freedom",
        "qatar press freedom", "qatar constitution",
        "qatar shura council", "qatar advisory council",
        "qatar labour reform", "qatar migrant rights",
        "qatar human rights",
    ],
}
