
# mood/pipeline/keywords/ro.py
RO_KEYWORDS = {
    "finance": [
        "romanian economy", "romania gdp", "bet index",
        "bucharest stock exchange", "bvb romania",
        "national bank romania", "bnr", "romanian leu", "ron",
        "romanian inflation", "romanian budget",
        "romanian exports", "romanian trade",
        "romanian market", "romanian growth",
        "romanian debt", "romanian deficit",
        "romanian unemployment", "romanian wages",
        "romanian housing", "romanian mortgage",
        "omv petrom", "romgaz", "transelectrica",
        "brd bank", "bcr bank", "raiffeisen romania",
        "banca transilvania", "ing romania",
        "romanian business", "romanian investment",
        "romanian tourism", "romanian manufacturing",
        "romanian automotive", "romanian agriculture",
        "romanian eu funds", "romanian recovery plan",
        "romanian pension fund", "romanian industry",
        "romanian it sector", "romanian outsourcing",
        "romanian real estate", "romanian construction",
    ],
    "geopolitics": [
        "romanian foreign policy", "romania nato",
        "romanian sanctions", "romanian diplomacy",
        "romanian troops", "romania ukraine", "romania russia",
        "romanian ambassador", "romania eu",
        "romanian defense", "romanian military",
        "bucharest talks", "romania security",
        "romanian intelligence", "sri romania",
        "black sea romania", "romanian nato flank",
        "romania moldova relations", "romanian peacekeeping",
        "romania middle east", "romanian eastern policy",
        "romania us relations", "romanian nato spending",
    ],
    "energy": [
        "romanian energy", "romanian nuclear", "cernavoda",
        "nuclear romania", "romanian electricity",
        "romanian renewables", "romanian gas", "romanian oil",
        "romanian grid", "romanian solar", "romanian wind",
        "romanian hydro", "romanian climate", "romanian emissions",
        "romanian energy transition", "romanian hydrogen",
        "romanian lng", "romanian energy prices",
        "black sea gas", "romanian offshore gas",
        "romgaz energy", "romgaz neptun deep",
        "romanian energy security", "romanian coal",
    ],
    "technology": [
        "romanian tech", "bucharest tech", "romanian startup",
        "romanian ai", "romanian fintech", "romanian digital",
        "romanian innovation", "romanian unicorn",
        "romanian cybersecurity", "romanian gaming",
        "romanian software", "romanian it sector",
        "ui path romania", "bitdefender",
        "romanian semiconductor", "cluj tech",
        "techangel romania", "romanian outsourcing",
    ],
    "health": [
        "romanian health", "romanian hospital", "romanian pharma",
        "romanian vaccine", "romanian healthcare",
        "romanian mental health", "romanian health system",
        "romanian medicine", "cas romania",
        "romanian public health", "romanian wellbeing",
        "romanian medical tourism",
    ],
    "crime": [
        "romanian corruption", "romanian fraud", "romanian scandal",
        "romanian court", "romanian investigation",
        "romanian organized crime", "romanian drug trafficking",
        "romanian money laundering", "romanian terrorism",
        "romanian police", "politia romana",
        "romanian gang", "romanian mafia",
        "dna romania", "romanian anti corruption",
        "romanian oligarch", "romanian fraud scheme",
        "eurovision romania",
    ],
    "politics": [
        "camera deputatilor", "senat romania",
        "romanian parliament", "romanian election",
        "romanian government", "romanian minister",
        "romanian prime minister", "romanian coalition",
        "romanian opposition", "psd romania",
        "pnl romania", "usr romania", "aur romania",
        "george simion", "marcel ciolacu",
        "nicolae ciuca", "calin georgescu",
        "romanian policy", "romanian reform",
        "romanian immigration", "romanian diaspora",
        "romanian welfare", "romanian citizenship",
        "romanian referendum", "romanian judiciary",
        "romanian rule of law", "romanian eu relations",
        "romanian democracy", "romanian president",
        "romanian constitutional court",
    ],
}