
# mood/pipeline/keywords/rs.py
RS_KEYWORDS = {
    "finance": [
        "serbian economy", "serbia gdp", "belex index",
        "belgrade stock exchange", "bvb serbia",
        "national bank serbia", "nbs serbia",
        "serbian dinar", "rsd",
        "serbian inflation", "serbian budget",
        "serbian exports", "serbian trade",
        "serbian market", "serbian growth",
        "serbian debt", "serbian deficit",
        "serbian unemployment", "serbian wages",
        "serbian housing", "serbian mortgage",
        "nis serbia", "telekom srbija",
        "komercijalna banka", "banca intesa serbia",
        "raiffeisen serbia", "unicredit serbia",
        "serbian business", "serbian investment",
        "serbian tourism", "serbian manufacturing",
        "serbian automotive", "serbian agriculture",
        "serbian eu funds", "serbian recovery plan",
        "serbian pension fund", "serbian industry",
        "serbian it sector", "serbian outsourcing",
        "fiat serbia", "stellantis serbia",
    ],
    "geopolitics": [
        "serbian foreign policy", "serbia nato",
        "serbian sanctions", "serbian diplomacy",
        "serbian troops", "serbia ukraine", "serbia russia",
        "serbian ambassador", "serbia eu",
        "serbian defense", "serbian military",
        "belgrade talks", "serbia security",
        "serbian intelligence", "bia serbia",
        "vucic foreign policy", "serbian neutrality",
        "serbia russia relations", "serbia china",
        "serbia kosovo", "serbian eu accession",
        "western balkans serbia", "serbia middle east",
        "serbian peacekeeping", "serbia nato partnership",
    ],
    "energy": [
        "serbian energy", "serbian coal", "ems serbia",
        "eps serbia", "serbian electricity",
        "serbian renewables", "serbian gas",
        "serbian grid", "serbian solar", "serbian wind",
        "serbian hydro", "serbian climate",
        "serbian emissions", "serbian energy transition",
        "russian gas serbia", "serbian energy security",
        "serbian energy prices", "serbian coal phase out",
        "serbian lng", "serbian biomass",
    ],
    "technology": [
        "serbian tech", "belgrade tech", "serbian startup",
        "serbian ai", "serbian fintech", "serbian digital",
        "serbian innovation", "serbian unicorn",
        "serbian cybersecurity", "serbian gaming",
        "serbian software", "serbian it sector",
        "nordeus serbia", "levi9 serbia",
        "serbian semiconductor", "novi sad tech",
        "serbian outsourcing", "serbian offshore",
    ],
    "health": [
        "serbian health", "serbian hospital", "serbian pharma",
        "serbian vaccine", "serbian healthcare",
        "serbian mental health", "serbian health system",
        "serbian medicine", "rfzo serbia",
        "serbian public health", "serbian wellbeing",
        "belgrade medicine university",
    ],
    "crime": [
        "serbian corruption", "serbian fraud", "serbian scandal",
        "serbian court", "serbian investigation",
        "serbian organized crime", "serbian drug trafficking",
        "serbian money laundering", "serbian terrorism",
        "serbian police", "mup serbia",
        "serbian gang", "serbian mafia",
        "serbian anti corruption", "acas serbia",
        "serbian oligarch", "serbian fraud scheme",
        "serbian smuggling", "serbian human trafficking",
        "serbian protest", "serbian riot",
    ],
    "politics": [
        "skupstina srbije", "serbian parliament",
        "serbian election", "serbian government",
        "serbian minister", "serbian prime minister",
        "serbian coalition", "serbian opposition",
        "sns serbia", "aleksandar vucic", "vucic",
        "sps serbia", "ivica dacic",
        "sza serbia", "dragan djilas",
        "serbian policy", "serbian reform",
        "serbian immigration", "serbian diaspora",
        "serbian welfare", "serbian citizenship",
        "serbian referendum", "serbian judiciary",
        "serbian rule of law", "serbian eu relations",
        "serbian democracy", "serbian president",
        "serbian protest movement", "serbian students",
    ],
}

