
# mood/pipeline/keywords/ru.py
RU_KEYWORDS = {
    "finance": [
        "russian economy", "russia gdp", "moex index",
        "moscow stock exchange", "moscow exchange",
        "central bank russia", "bank rossii",
        "russian ruble", "rub", "russian inflation",
        "russian budget", "russian exports",
        "russian trade", "russian market",
        "russian growth", "russian debt",
        "russian deficit", "russian unemployment",
        "russian wages", "russian housing",
        "russian sanctions economy", "russian oil revenue",
        "russian gas revenue", "russian fossil fuel revenue",
        "gazprom", "rosneft", "lukoil", "novatek",
        "sberbank", "vtb bank", "alfa bank",
        "russian oligarch", "russian billionaire",
        "russian defense spending", "russian military budget",
        "russian civilian economy", "russian currency",
        "russian capital flight", "russian asset freeze",
        "russian frozen assets", "russian swift ban",
        "russian import substitution", "russian parallel imports",
        "russian economic isolation", "russian gdp war",
    ],
    "geopolitics": [
        "russian foreign policy", "russia nato",
        "russian military", "russian defense",
        "russia ukraine", "russian invasion",
        "kremlin", "putin", "vladimir putin",
        "russian troops", "russian attack",
        "russian offensive", "russian frontline",
        "russian intelligence", "fsb russia", "gru russia",
        "russian influence", "russian hybrid warfare",
        "russia middle east", "russia africa",
        "russia china", "russia iran",
        "russian peace talks", "russian ceasefire",
        "russian hit squad", "russian assassination",
        "russia armenia", "russia azerbaijan",
        "russia georgia", "russia belarus",
        "russia moldova", "russian propaganda",
        "russian disinformation", "russian interference",
        "russian nuclear threat", "russian nuclear weapons",
        "russian arctic", "russian northern sea route",
    ],
    "energy": [
        "russian energy", "russian oil", "russian gas",
        "russian pipeline", "nord stream",
        "russian lng", "russian electricity",
        "russian nuclear energy", "rosatom",
        "russian energy sanctions", "russian oil price cap",
        "russian energy revenue", "russian fossil fuels",
        "russian energy exports", "russian oil exports",
        "russian gas exports", "russian coal exports",
        "russian energy isolation", "russian oil tanker",
        "russian shadow fleet", "russian oil india",
        "russian oil china", "russian oil turkey",
    ],
    "technology": [
        "russian tech", "russian ai", "russian digital",
        "russian internet", "runet", "russian censorship",
        "russian tech sanctions", "russian chip shortage",
        "russian semiconductor shortage",
        "yandex", "vk russia", "russian social media",
        "russian surveillance technology",
        "russian military technology", "russian drone",
        "russian weapon technology", "russian cyber",
    ],
    "health": [
        "russian health", "russian hospital", "russian pharma",
        "russian vaccine", "sputnik v",
        "russian healthcare", "russian medicine",
        "russian health system", "russian public health",
        "russian drug shortage", "russian medical",
        "russian mental health war", "russian soldier health",
    ],
    "crime": [
        "russian corruption", "russian fraud", "russian scandal",
        "russian court", "russian investigation",
        "russian organized crime", "russian drug trafficking",
        "russian money laundering", "russian terrorism",
        "russian police", "russian fsb",
        "russian gang", "russian mafia",
        "russian oligarch arrested", "russian sanctions evasion",
        "russian smuggling", "russian human trafficking",
        "russian political prisoner", "russian opposition arrested",
        "navalny", "alexei navalny",
        "russian show trial", "russian fake election",
        "russian war crimes", "russian atrocities",
        "russian assassination abroad",
        "russian hit squad abroad",
    ],
    "politics": [
        "gosudarstvennaya duma", "russian parliament",
        "russian election", "russian government",
        "russian minister", "russian prime minister",
        "russian president", "vladimir putin", "putin",
        "kremlin policy", "russian regime",
        "russian opposition", "russian protest",
        "meduza russia", "novaya gazeta",
        "russian policy", "russian reform",
        "russian censorship", "russian media",
        "russian freedom", "russian democracy",
        "russian repression", "russian exile",
        "russian political prisoner",
        "alexei navalny", "navalny",
        "mikhail khodorkovsky",
        "russian state duma elections",
        "russian propaganda machine",
        "russian foreign agent law",
        "russian lgbt ban",
    ],
}
