
# mood/pipeline/keywords/rw.py
RW_KEYWORDS = {
    "finance": [
        "rwandan economy", "rwanda gdp",
        "rwanda stock exchange", "rse rwanda",
        "national bank rwanda", "nbr",
        "rwandan franc", "rwf",
        "rwandan inflation", "rwandan budget",
        "rwandan exports", "rwandan trade",
        "rwandan market", "rwandan growth",
        "rwandan debt", "rwandan deficit",
        "rwandan unemployment", "rwandan wages",
        "rwandan housing", "rwandan mortgage",
        "bank of kigali", "equity bank rwanda",
        "i&m bank rwanda", "access bank rwanda",
        "rwandan coffee", "rwandan tea",
        "rwandan minerals", "rwandan coltan",
        "rwandan pyrethrum", "rwandan flowers",
        "rwandan business", "rwandan investment",
        "rwandan tourism", "rwandan manufacturing",
        "rwandan agriculture", "rwandan fisheries",
        "rwandan eu trade", "rwanda us trade",
        "rwandan tariffs", "rwandan fiscal",
        "rwandan pension fund", "rssb rwanda",
        "rwandan industry", "rwandan startup",
        "rwandan fintech", "rwandan real estate",
        "rwandan construction", "rwandan remittances",
        "rwandan diaspora", "rwanda imf",
        "kagame economic policy",
        "kigali financial hub",
        "prism project rwanda",
        "affordable housing rwanda",
    ],
    "geopolitics": [
        "rwandan foreign policy", "rwanda nato",
        "rwandan sanctions", "rwandan diplomacy",
        "rwandan troops", "rwanda ukraine",
        "rwanda russia", "rwandan ambassador",
        "rwanda eu", "rwandan defense",
        "rwandan military", "kigali talks",
        "rwanda security", "rwandan intelligence",
        "niss rwanda", "rwanda us relations",
        "rwanda china", "rwanda brics",
        "rwanda africa union", "rwanda igad",
        "rwanda peacekeeping", "rwanda un",
        "rwanda drc", "rwanda congo conflict",
        "m23 rwanda drc", "rwanda uganda",
        "rwanda burundi", "rwanda kenya",
        "kagame foreign policy",
        "rwanda east africa community",
        "rwanda un peacekeeping",
        "rwanda genocide legacy",
        "rwanda reconciliation",
    ],
    "energy": [
        "rwandan energy", "rwandan electricity",
        "rwandan renewables", "rwandan solar",
        "rwandan wind", "rwandan hydro",
        "rwandan grid", "rwandan climate",
        "rwandan emissions", "rwandan energy transition",
        "rwandan hydrogen", "rwandan methane",
        "rwandan energy prices", "rwandan energy security",
        "rwandan green energy", "rwandan carbon neutral",
        "rwandan net zero", "rwandan fuel prices",
        "lake kivu methane rwanda",
        "rwandan hydroelectric",
        "reco rwanda", "rwandan energy access",
        "rwandan solar home systems",
    ],
    "technology": [
        "rwandan tech", "kigali tech", "rwandan startup",
        "rwandan ai", "rwandan fintech",
        "rwandan digital", "rwandan innovation",
        "rwandan unicorn", "rwandan cybersecurity",
        "rwandan gaming", "rwandan software",
        "rwandan it sector", "rwandan ecommerce",
        "rwandan digital economy", "rwandan 5g",
        "rwandan blockchain", "rwandan smart city",
        "rwandan medtech", "rwandan drone delivery",
        "rwandan digital transformation",
        "mtn rwanda", "airtel rwanda",
        "kigali innovation city",
        "rwandan silicon valley",
        "zipline rwanda drones",
        "rwandan tech hub",
    ],
    "health": [
        "rwandan health", "rwandan hospital",
        "rwandan pharma", "rwandan vaccine",
        "rwandan healthcare", "rwandan mental health",
        "rwandan health system", "rwandan medicine",
        "rwandan public health", "rwandan wellbeing",
        "rwandan malaria", "rwandan tuberculosis",
        "rwandan hiv", "rwandan cholera",
        "rwandan health reform",
        "rwandan universal health",
        "rwandan community health",
        "rbc rwanda", "rwandan mutuelle",
        "king faisal hospital rwanda",
        "rwandan maternal health",
        "rwandan genocide health legacy",
    ],
    "crime": [
        "rwandan corruption", "rwandan fraud",
        "rwandan scandal", "rwandan court",
        "rwandan investigation", "rwandan organized crime",
        "rwandan drug trafficking", "rwandan money laundering",
        "rwandan terrorism", "rwandan police",
        "rwandan gang", "rwandan anti corruption",
        "office ombudsman rwanda",
        "rwandan cybercrime", "rwandan scam",
        "rwandan arrest", "rwandan human trafficking",
        "rwandan protest", "rwandan riot",
        "rwandan political prisoner",
        "rwandan opposition arrested",
        "rwandan dissident",
        "rwandan genocide suspects",
        "ictr rwanda",
        "gacaca courts rwanda",
    ],
    "politics": [
        "parliament of rwanda", "rwandan parliament",
        "rwandan election", "rwandan government",
        "rwandan minister", "rwandan president",
        "rwandan coalition", "rwandan opposition",
        "rpf rwanda", "paul kagame", "kagame rwanda",
        "fdlr rwanda", "rwandan opposition party",
        "rwandan policy", "rwandan reform",
        "rwandan immigration", "rwandan diaspora",
        "rwandan welfare", "rwandan citizenship",
        "rwandan referendum", "rwandan judiciary",
        "rwandan rule of law", "rwandan eu relations",
        "rwandan democracy", "rwandan media freedom",
        "rwandan press freedom", "rwandan constitution",
        "rwandan federalism", "rwandan districts",
        "rwandan political stability",
        "rwandan vision 2050",
        "rwandan genocide commemoration",
        "kwibuka rwanda",
        "uk rwanda asylum deal",
        "rwanda asylum seekers",
    ],
}