
# mood/pipeline/keywords/sa.py
SA_KEYWORDS = {
    "finance": [
        "saudi economy", "saudi arabia gdp", "tadawul",
        "saudi stock exchange", "tasi index",
        "saudi central bank", "sama",
        "saudi riyal", "sar",
        "saudi inflation", "saudi budget", "saudi exports",
        "saudi trade", "saudi market", "saudi growth",
        "saudi debt", "saudi surplus", "saudi unemployment",
        "saudi wages", "saudi housing", "saudi mortgage",
        "saudi national bank", "snb",
        "al rajhi bank", "riyad bank",
        "aramco", "saudi aramco",
        "sabic", "maaden", "stc telecom",
        "saudi investment authority", "pif",
        "saudi sovereign wealth fund",
        "saudi business", "saudi investment",
        "saudi tourism", "saudi manufacturing",
        "saudi vision 2030", "saudi diversification",
        "neom", "saudi giga projects",
        "saudi eu trade", "saudi us trade",
        "saudi tariffs", "saudi fiscal",
        "saudi pension fund", "gosi saudi",
        "saudi industry", "saudi startup",
        "saudi unicorn", "saudi fintech",
        "saudi real estate", "saudi construction",
        "saudi logistics", "saudi infrastructure",
        "aramco oil production", "saudi oil output",
        "opec saudi", "saudi oil price",
    ],
    "geopolitics": [
        "saudi foreign policy", "saudi arabia nato",
        "saudi sanctions", "saudi diplomacy",
        "saudi troops", "saudi ukraine", "saudi russia",
        "saudi ambassador", "saudi eu",
        "saudi defense", "saudi military",
        "riyadh talks", "saudi security",
        "saudi intelligence", "saudi us relations",
        "saudi us arms deal", "saudi iran relations",
        "saudi iran normalization", "saudi israel",
        "saudi normalization", "saudi hamas",
        "saudi hezbollah", "saudi middle east",
        "saudi gulf", "saudi qatar",
        "saudi gcc", "saudi yemen war",
        "saudi peacekeeping", "saudi un",
        "saudi syria", "saudi iraq",
        "saudi pakistan", "saudi china relations",
        "saudi india", "saudi egypt",
        "mbs foreign policy", "mohammed bin salman",
        "saudi aramco geopolitics",
        "saudi oil weapon",
        "opec plus saudi",
    ],
    "energy": [
        "saudi energy", "saudi oil", "saudi gas",
        "aramco production", "saudi electricity",
        "saudi renewables", "saudi solar",
        "saudi wind", "saudi grid",
        "saudi climate", "saudi emissions",
        "saudi energy transition", "saudi hydrogen",
        "saudi lng", "saudi energy prices",
        "saudi energy security", "saudi green energy",
        "saudi carbon neutral", "saudi net zero",
        "saudi fuel prices", "saudi petrochemical",
        "saudi oil output", "opec saudi production",
        "saudi renewable energy", "neom energy",
        "saudi green initiative",
        "saudi aramco emissions",
    ],
    "technology": [
        "saudi tech", "riyadh tech", "saudi startup",
        "saudi ai", "saudi fintech", "saudi digital",
        "saudi innovation", "saudi cybersecurity",
        "saudi software", "saudi it sector",
        "saudi ecommerce", "saudi digital economy",
        "saudi smart city", "neom tech",
        "saudi medtech", "saudi biotech",
        "saudi blockchain", "saudi quantum",
        "saudi 5g", "saudi space",
        "saudi aramco tech", "sabic tech",
        "saudi vision 2030 tech",
        "saudi venture capital",
        "saudi digital transformation",
    ],
    "health": [
        "saudi health", "saudi hospital",
        "saudi pharma", "saudi vaccine",
        "saudi healthcare", "saudi mental health",
        "saudi health system", "saudi medicine",
        "saudi public health", "saudi wellbeing",
        "saudi biotech", "saudi cancer",
        "saudi aging population", "saudi birthrate",
        "saudi medical tourism",
        "saudi health ministry",
        "saudi vision 2030 health",
        "saudi universal healthcare",
    ],
    "crime": [
        "saudi corruption", "saudi fraud",
        "saudi scandal", "saudi court",
        "saudi investigation", "saudi organized crime",
        "saudi drug trafficking", "saudi money laundering",
        "saudi terrorism", "saudi police",
        "saudi gang", "saudi anti corruption",
        "saudi cybercrime", "saudi scam",
        "saudi arrest", "saudi human trafficking",
        "saudi migrant workers", "saudi kafala",
        "saudi dissident", "saudi journalist",
        "jamal khashoggi", "saudi political prisoner",
        "saudi protest", "saudi women rights",
        "saudi execution", "saudi death penalty",
    ],
    "politics": [
        "saudi shura council", "saudi parliament",
        "saudi election", "saudi government",
        "saudi minister", "saudi prime minister",
        "saudi king", "saudi crown prince",
        "mohammed bin salman", "mbs",
        "king salman", "saudi royal family",
        "saudi policy", "saudi reform",
        "saudi immigration", "saudi integration",
        "saudi welfare", "saudi citizenship",
        "saudi judiciary", "saudi rule of law",
        "saudi democracy", "saudi media freedom",
        "saudi press freedom", "saudi constitution",
        "saudi human rights", "saudi labour reform",
        "saudi women rights", "saudi driving ban lifted",
        "saudi vision 2030 politics",
        "saudi religious police",
        "saudi modernization",
    ],
}
