
# mood/pipeline/keywords/se.py
SE_KEYWORDS = {
    "finance": [
        "swedish economy", "sweden gdp", "omx stockholm",
        "stockholm stock exchange", "nasdaq stockholm",
        "riksbank", "swedish krona", "sek",
        "swedish inflation", "swedish budget", "swedish exports",
        "swedish trade", "swedish market", "swedish growth",
        "swedish debt", "swedish deficit", "swedish unemployment",
        "swedish wages", "swedish housing", "swedish mortgage",
        "volvo", "scania", "ericsson", "h&m", "ikea",
        "spotify", "klarna", "nordea sweden",
        "handelsbanken", "seb sweden", "swedbank",
        "swedish match", "hexagon", "atlas copco",
        "assa abloy", "essity", "electrolux",
        "swedish business", "swedish investment",
        "swedish tourism", "swedish manufacturing",
        "swedish steel", "swedish forest industry",
        "swedish pension fund", "ap fonden",
    ],
    "geopolitics": [
        "swedish foreign policy", "sweden nato",
        "swedish sanctions", "swedish diplomacy",
        "swedish troops", "sweden ukraine", "sweden russia",
        "swedish ambassador", "sweden eu",
        "swedish defense", "swedish military",
        "stockholm talks", "sweden finland nato",
        "sweden middle east", "swedish peacekeeping",
        "swedish neutrality", "sweden security",
    ],
    "energy": [
        "swedish energy", "swedish nuclear", "vattenfall",
        "swedish electricity", "swedish renewables",
        "swedish wind", "swedish solar", "swedish hydro",
        "swedish grid", "swedish climate", "swedish emissions",
        "swedish energy prices", "swedish energy transition",
        "swedish hydrogen", "swedish offshore wind",
        "ringhals nuclear", "forsmark nuclear",
    ],
    "technology": [
        "swedish tech", "stockholm tech", "swedish startup",
        "swedish ai", "swedish fintech", "swedish digital",
        "swedish innovation", "swedish unicorn",
        "swedish cybersecurity", "ericsson sweden",
        "spotify sweden", "klarna sweden",
        "swedish gaming", "king games", "paradox",
        "mojang minecraft", "swedish semiconductor",
    ],
    "health": [
        "swedish health", "swedish hospital", "swedish pharma",
        "astrazeneca sweden", "swedish vaccine",
        "swedish healthcare", "swedish mental health",
        "swedish health system", "swedish medicine",
        "karolinska", "swedish covid response",
    ],
    "crime": [
        "swedish corruption", "swedish fraud", "swedish scandal",
        "swedish court", "swedish investigation",
        "swedish organized crime", "swedish gang",
        "swedish drug trafficking", "swedish money laundering",
        "swedish terrorism", "swedish police",
        "swedish shooting", "swedish explosion",
        "swedish gang violence",
    ],
    "politics": [
        "riksdag", "swedish parliament", "swedish election",
        "swedish government", "swedish minister",
        "swedish prime minister", "swedish coalition",
        "swedish opposition", "swedish democrats", "sd sweden",
        "moderate party sweden", "social democrats sweden",
        "ulf kristersson", "magdalena andersson",
        "swedish policy", "swedish reform",
        "swedish immigration", "swedish integration",
        "swedish welfare", "swedish model",
        "swedish citizenship", "swedish referendum",
    ],
}