
# mood/pipeline/keywords/sg.py
SG_KEYWORDS = {
    "finance": [
        "singapore economy", "singapore gdp", "straits times index",
        "sti singapore", "singapore exchange", "sgx",
        "monetary authority singapore", "mas singapore",
        "singapore dollar", "sgd",
        "singapore inflation", "singapore budget", "singapore exports",
        "singapore trade", "singapore market", "singapore growth",
        "singapore debt", "singapore surplus", "singapore unemployment",
        "singapore wages", "singapore housing", "singapore hdb",
        "dbs bank", "ocbc", "uob singapore",
        "singtel", "capitaland", "jardine matheson",
        "singapore airlines", "sia", "changi airport",
        "singapore business", "singapore investment",
        "singapore tourism", "singapore manufacturing",
        "singapore fintech", "singapore logistics",
        "singapore port", "singapore shipping",
        "singapore pension", "cpf singapore",
        "singapore trade deal", "singapore us trade",
        "singapore eu trade", "singapore tariffs",
    ],
    "geopolitics": [
        "singapore foreign policy", "singapore nato",
        "singapore sanctions", "singapore diplomacy",
        "singapore troops", "singapore ukraine", "singapore russia",
        "singapore ambassador", "singapore eu",
        "singapore defense", "singapore military",
        "singapore security", "singapore intelligence",
        "singapore china relations", "singapore us relations",
        "singapore india relations", "singapore asean",
        "asean summit", "asean singapore",
        "singapore middle east", "singapore peacekeeping",
        "singapore strait of malacca", "malacca strait",
        "singapore taiwan", "singapore south china sea",
    ],
    "energy": [
        "singapore energy", "singapore electricity",
        "singapore renewables", "singapore solar",
        "singapore grid", "singapore climate",
        "singapore emissions", "singapore energy transition",
        "singapore hydrogen", "singapore lng",
        "singapore energy prices", "singapore energy security",
        "singapore green energy", "singapore carbon tax",
        "singapore net zero", "singapore fuel prices",
        "singapore oil refining", "singapore petrochemical",
    ],
    "technology": [
        "singapore tech", "singapore startup",
        "singapore ai", "singapore fintech", "singapore digital",
        "singapore innovation", "singapore unicorn",
        "singapore cybersecurity", "singapore gaming",
        "singapore software", "singapore it sector",
        "grab singapore", "sea limited", "shopee",
        "singapore semiconductor", "singapore quantum",
        "singapore smart city", "singapore digital economy",
        "singapore medtech", "singapore biotech",
    ],
    "health": [
        "singapore health", "singapore hospital",
        "singapore pharma", "singapore vaccine",
        "singapore healthcare", "singapore mental health",
        "singapore health system", "singapore medicine",
        "singapore public health", "singapore wellbeing",
        "singapore aging population", "singapore biotech",
        "singapore cancer", "singapore dengue",
        "moh singapore",
    ],
    "crime": [
        "singapore corruption", "singapore fraud",
        "singapore scandal", "singapore court",
        "singapore investigation", "singapore organized crime",
        "singapore drug trafficking", "singapore money laundering",
        "singapore terrorism", "singapore police",
        "spf singapore", "singapore gang",
        "singapore anti corruption", "cpib singapore",
        "singapore cybercrime", "singapore scam",
        "singapore death penalty", "singapore hanging",
    ],
    "politics": [
        "singapore parliament", "singaporean election",
        "singapore government", "singapore minister",
        "singapore prime minister", "singapore coalition",
        "singapore opposition", "pap singapore",
        "peoples action party", "lawrence wong",
        "lee hsien loong", "wp singapore",
        "workers party singapore", "singapore policy",
        "singapore reform", "singapore immigration",
        "singapore integration", "singapore welfare",
        "singapore citizenship", "singapore referendum",
        "singapore judiciary", "singapore rule of law",
        "singapore democracy", "singapore president",
        "tharman shanmugaratnam", "singapore media freedom",
        "singapore press freedom",
    ],
}