
# mood/pipeline/keywords/si.py
SI_KEYWORDS = {
    "finance": [
        "slovenian economy", "slovenia gdp", "sbi top index",
        "ljubljana stock exchange", "ljse slovenia",
        "bank of slovenia", "banka slovenije",
        "slovenian euro", "slovenian inflation",
        "slovenian budget", "slovenian exports",
        "slovenian trade", "slovenian market",
        "slovenian growth", "slovenian debt",
        "slovenian deficit", "slovenian unemployment",
        "slovenian wages", "slovenian housing",
        "slovenian mortgage", "krka slovenia",
        "petrol slovenia", "nlb bank", "nova kbm",
        "generali slovenia", "triglav insurance",
        "telekom slovenije", "mercator",
        "slovenian business", "slovenian investment",
        "slovenian tourism", "slovenian manufacturing",
        "slovenian automotive", "slovenian agriculture",
        "slovenian eu funds", "slovenian recovery plan",
        "slovenian pension fund", "slovenian industry",
        "slovenian it sector", "slovenian outsourcing",
        "slovenian pharmaceutical", "lek slovenia",
        "changan deepal slovenia",
    ],
    "geopolitics": [
        "slovenian foreign policy", "slovenia nato",
        "slovenian sanctions", "slovenian diplomacy",
        "slovenian troops", "slovenia ukraine",
        "slovenia russia", "slovenian ambassador",
        "slovenia eu", "slovenian defense",
        "slovenian military", "ljubljana talks",
        "slovenia security", "slovenian intelligence",
        "sova slovenia", "slovenian peacekeeping",
        "slovenia middle east", "slovenian eastern policy",
        "slovenia balkans", "slovenian nato membership",
        "slovenia croatia relations",
        "slovenian adriatic",
    ],
    "energy": [
        "slovenian energy", "slovenian nuclear", "krsko",
        "nek nuclear", "slovenian electricity",
        "slovenian renewables", "slovenian gas",
        "slovenian grid", "slovenian solar",
        "slovenian wind", "slovenian hydro",
        "slovenian climate", "slovenian emissions",
        "slovenian energy transition", "slovenian hydrogen",
        "russian gas slovenia", "slovenian energy security",
        "slovenian energy prices", "gen energija",
        "slovenian coal", "slovenian biomass",
    ],
    "technology": [
        "slovenian tech", "ljubljana tech", "slovenian startup",
        "slovenian ai", "slovenian fintech",
        "slovenian digital", "slovenian innovation",
        "slovenian unicorn", "slovenian cybersecurity",
        "slovenian gaming", "slovenian software",
        "slovenian it sector", "slovenian outsourcing",
        "outfit7 slovenia", "talking tom",
        "slovenian semiconductor", "maribor tech",
        "slovenian cleantech", "slovenian medtech",
    ],
    "health": [
        "slovenian health", "slovenian hospital",
        "slovenian pharma", "lek pharma", "krka pharma",
        "slovenian vaccine", "slovenian healthcare",
        "slovenian mental health", "slovenian health system",
        "slovenian medicine", "zzzs slovenia",
        "slovenian public health", "slovenian wellbeing",
        "ljubljana medicine university",
    ],
    "crime": [
        "slovenian corruption", "slovenian fraud",
        "slovenian scandal", "slovenian court",
        "slovenian investigation", "slovenian organized crime",
        "slovenian drug trafficking", "slovenian money laundering",
        "slovenian terrorism", "slovenian police",
        "policija slovenija", "slovenian gang",
        "slovenian anti corruption", "kpk slovenia",
        "slovenian smuggling", "slovenian human trafficking",
        "slovenian protest",
    ],
    "politics": [
        "drzavni zbor", "drzavni svet", "slovenian parliament",
        "slovenian election", "slovenian government",
        "slovenian minister", "slovenian prime minister",
        "slovenian coalition", "slovenian opposition",
        "gibanje svoboda", "robert golob", "golob",
        "sds slovenia", "janez jansa",
        "nsi slovenia", "sd slovenia",
        "slovenian policy", "slovenian reform",
        "slovenian immigration", "slovenian integration",
        "slovenian welfare", "slovenian citizenship",
        "slovenian referendum", "slovenian judiciary",
        "slovenian rule of law", "slovenian eu relations",
        "slovenian democracy", "slovenian president",
        "natasa pirc musar", "slovenian media freedom",
    ],
}
