
# mood/pipeline/keywords/sk.py
SK_KEYWORDS = {
    "finance": [
        "slovak economy", "slovakia gdp", "sax index",
        "bratislava stock exchange", "bsse slovakia",
        "national bank slovakia", "nbs", "slovak euro",
        "slovak inflation", "slovak budget",
        "slovak exports", "slovak trade",
        "slovak market", "slovak growth",
        "slovak debt", "slovak deficit",
        "slovak unemployment", "slovak wages",
        "slovak housing", "slovak mortgage",
        "volkswagen slovakia", "kia slovakia",
        "stellantis slovakia", "samsung slovakia",
        "slsp bank", "vub bank", "tatra banka",
        "csob slovakia", "slovak telekom",
        "slovak business", "slovak investment",
        "slovak tourism", "slovak manufacturing",
        "slovak automotive", "slovak agriculture",
        "slovak eu funds", "slovak recovery plan",
        "slovak pension fund", "slovak industry",
        "slovak arms exports", "slovak weapons",
        "slovak shells", "slovak ammunition",
    ],
    "geopolitics": [
        "slovak foreign policy", "slovakia nato",
        "slovak sanctions", "slovak diplomacy",
        "slovak troops", "slovakia ukraine", "slovakia russia",
        "slovak ambassador", "slovakia eu",
        "slovak defense", "slovak military",
        "bratislava talks", "slovakia security",
        "slovak intelligence", "sis slovakia",
        "fico foreign policy", "slovak veto",
        "slovakia russia relations", "slovak eastern policy",
        "slovakia middle east", "slovak peacekeeping",
        "slovakia balkans", "slovakia hungary relations",
        "slovak arms exports ukraine",
    ],
    "energy": [
        "slovak energy", "slovak nuclear", "mochovce",
        "bohunice nuclear", "slovak electricity",
        "slovak renewables", "slovak gas",
        "slovak grid", "slovak solar", "slovak wind",
        "slovak climate", "slovak emissions",
        "slovak energy transition", "slovak hydrogen",
        "russian gas slovakia", "slovak energy security",
        "slovak energy prices", "spp slovakia",
        "slovak coal", "slovak biomass",
    ],
    "technology": [
        "slovak tech", "bratislava tech", "slovak startup",
        "slovak ai", "slovak fintech", "slovak digital",
        "slovak innovation", "slovak unicorn",
        "slovak cybersecurity", "slovak gaming",
        "slovak software", "slovak it sector",
        "eset slovakia", "pixel federation",
        "slovak semiconductor", "kosice tech",
        "t systems slovakia", "accenture slovakia",
    ],
    "health": [
        "slovak health", "slovak hospital", "slovak pharma",
        "slovak vaccine", "slovak healthcare",
        "slovak mental health", "slovak health system",
        "slovak medicine", "vszp slovakia",
        "slovak public health", "slovak wellbeing",
        "comenius university medicine",
    ],
    "crime": [
        "slovak corruption", "slovak fraud", "slovak scandal",
        "slovak court", "slovak investigation",
        "slovak organized crime", "slovak drug trafficking",
        "slovak money laundering", "slovak terrorism",
        "slovak police", "policia sr",
        "slovak gang", "slovak mafia",
        "naka slovakia", "slovak anti corruption",
        "jan kuciak", "slovak journalist murder",
        "slovak oligarch", "slovak fraud scheme",
    ],
    "politics": [
        "narodna rada", "slovak parliament",
        "slovak election", "slovak government",
        "slovak minister", "slovak prime minister",
        "slovak coalition", "slovak opposition",
        "smer sd", "robert fico", "fico",
        "hlas sd", "peter pellegrini",
        "progressive slovakia", "kdu slovakia",
        "slovak policy", "slovak reform",
        "slovak immigration", "slovak integration",
        "slovak welfare", "slovak citizenship",
        "slovak referendum", "slovak judiciary",
        "slovak rule of law", "slovak eu relations",
        "slovak democracy", "slovak president",
        "slovak media freedom",
    ],
}
