
# mood/pipeline/keywords/sn.py
SN_KEYWORDS = {
    "finance": [
        "senegalese economy", "senegal gdp",
        "bourse regionale valeurs mobilieres", "brvm",
        "central bank west africa", "bceao",
        "west african franc", "xof",
        "senegalese inflation", "senegalese budget",
        "senegalese exports", "senegalese trade",
        "senegalese market", "senegalese growth",
        "senegalese debt", "senegalese deficit",
        "senegalese unemployment", "senegalese wages",
        "senegalese housing", "senegalese mortgage",
        "cbao senegal", "sgbs bank",
        "bicis senegal", "ecobank senegal",
        "senegalese oil", "sangomar oil field",
        "senegalese gas", "gta gas field",
        "senegalese tourism", "senegalese fishing",
        "senegalese agriculture", "senegalese groundnut",
        "senegalese phosphate", "senegalese gold",
        "senegalese eu trade", "senegal us trade",
        "senegalese tariffs", "senegalese fiscal",
        "senegalese pension fund", "ipres senegal",
        "senegalese industry", "senegalese startup",
        "senegalese fintech", "senegalese real estate",
        "senegalese construction", "senegalese remittances",
        "senegalese diaspora", "senegal imf",
        "faye economic policy",
        "senegal oil production",
        "senegal new oil producer",
    ],
    "geopolitics": [
        "senegalese foreign policy", "senegal nato",
        "senegalese sanctions", "senegalese diplomacy",
        "senegalese troops", "senegal ukraine",
        "senegal russia", "senegalese ambassador",
        "senegal eu", "senegalese defense",
        "senegalese military", "dakar talks",
        "senegal security", "senegalese intelligence",
        "senegal us relations", "senegal china",
        "senegal brics", "senegal africa union",
        "senegal ecowas", "senegal peacekeeping",
        "senegal un", "senegal mali",
        "senegal guinea", "senegal mauritania",
        "senegal gambia", "senegal guinea bissau",
        "senegal sahel crisis",
        "faye foreign policy",
        "senegal west africa stability",
        "senegal france relations",
    ],
    "energy": [
        "senegalese energy", "senegalese oil",
        "senegalese gas", "senegalese electricity",
        "senegalese renewables", "senegalese solar",
        "senegalese wind", "senegalese grid",
        "senegalese climate", "senegalese emissions",
        "senegalese energy transition",
        "senegalese hydrogen", "senegalese lng",
        "senegalese energy prices", "senegalese energy security",
        "senegalese green energy", "senegalese carbon neutral",
        "senegalese net zero", "senegalese fuel prices",
        "sangomar oil senegal",
        "gta gas senegal mauritania",
        "senelec senegal",
        "senegal new oil revenue",
    ],
    "technology": [
        "senegalese tech", "dakar tech", "senegalese startup",
        "senegalese ai", "senegalese fintech",
        "senegalese digital", "senegalese innovation",
        "senegalese unicorn", "senegalese cybersecurity",
        "senegalese software", "senegalese it sector",
        "senegalese ecommerce", "senegalese digital economy",
        "senegalese 5g", "senegalese blockchain",
        "senegalese smart city", "senegalese medtech",
        "senegalese digital transformation",
        "orange senegal", "expresso senegal",
        "senegal digital hub africa",
        "jokkolabs dakar",
    ],
    "health": [
        "senegalese health", "senegalese hospital",
        "senegalese pharma", "senegalese vaccine",
        "senegalese healthcare", "senegalese mental health",
        "senegalese health system", "senegalese medicine",
        "senegalese public health", "senegalese wellbeing",
        "senegalese biotech", "senegalese cancer",
        "senegalese aging population",
        "senegalese malaria", "senegalese tuberculosis",
        "senegalese hiv", "senegalese cholera",
        "senegalese dengue", "senegalese yellow fever",
        "senegalese health reform",
        "senegalese universal health",
        "pasteur institute dakar",
    ],
    "crime": [
        "senegalese corruption", "senegalese fraud",
        "senegalese scandal", "senegalese court",
        "senegalese investigation", "senegalese organized crime",
        "senegalese drug trafficking", "senegalese money laundering",
        "senegalese terrorism", "senegalese police",
        "senegalese gang", "senegalese anti corruption",
        "ofnac senegal", "senegalese cybercrime",
        "senegalese scam", "senegalese arrest",
        "senegalese human trafficking",
        "senegalese protest", "senegalese riot",
        "senegalese political scandal",
        "senegalese jihadist",
        "senegalese casamance conflict",
        "senegalese femicide",
    ],
    "politics": [
        "assemblee nationale senegal",
        "senegalese parliament", "senegalese election",
        "senegalese government", "senegalese minister",
        "senegalese president", "senegalese coalition",
        "senegalese opposition", "pastef senegal",
        "bassirou diomaye faye", "faye senegal",
        "ousmane sonko", "sonko senegal",
        "senegalese policy", "senegalese reform",
        "senegalese immigration", "senegalese diaspora",
        "senegalese welfare", "senegalese citizenship",
        "senegalese referendum", "senegalese judiciary",
        "senegalese rule of law", "senegalese eu relations",
        "senegalese democracy", "senegalese media freedom",
        "senegalese press freedom", "senegalese constitution",
        "senegalese federalism", "senegalese regions",
        "senegalese political transition",
        "senegal france decolonization",
        "senegal cfa franc debate",
    ],
}