
# mood/pipeline/keywords/sv.py
SV_KEYWORDS = {
    "finance": [
        "salvadoran economy", "el salvador gdp",
        "bolsa valores el salvador", "bves",
        "central reserve bank el salvador", "bcr",
        "salvadoran dollar", "usd el salvador",
        "bitcoin el salvador", "el salvador bitcoin",
        "salvadoran inflation", "salvadoran budget",
        "salvadoran exports", "salvadoran trade",
        "salvadoran market", "salvadoran growth",
        "salvadoran debt", "salvadoran deficit",
        "salvadoran unemployment", "salvadoran wages",
        "salvadoran housing", "salvadoran mortgage",
        "banco agricola salvador", "banco davivienda",
        "banco cuscatlan", "banco hipotecario",
        "salvadoran tourism", "salvadoran coffee",
        "salvadoran sugar", "salvadoran textiles",
        "salvadoran manufacturing", "salvadoran agriculture",
        "salvadoran eu trade", "el salvador us trade",
        "salvadoran tariffs", "salvadoran fiscal",
        "salvadoran pension fund", "salvadoran industry",
        "salvadoran startup", "salvadoran fintech",
        "salvadoran real estate", "salvadoran construction",
        "salvadoran remittances", "salvadoran diaspora",
        "el salvador imf deal",
        "salvadoran bitcoin adoption",
        "chivo wallet el salvador",
    ],
    "geopolitics": [
        "salvadoran foreign policy", "el salvador nato",
        "salvadoran sanctions", "salvadoran diplomacy",
        "salvadoran troops", "el salvador ukraine",
        "el salvador russia", "salvadoran ambassador",
        "el salvador eu", "salvadoran defense",
        "salvadoran military", "san salvador talks",
        "el salvador security", "salvadoran intelligence",
        "el salvador us relations", "el salvador caricom",
        "el salvador central america",
        "el salvador honduras", "el salvador guatemala",
        "el salvador gang crackdown",
        "salvadoran peacekeeping", "el salvador un",
        "el salvador china relations",
        "bukele foreign policy",
        "el salvador ms13",
        "el salvador barrio 18",
    ],
    "energy": [
        "salvadoran energy", "salvadoran electricity",
        "salvadoran renewables", "salvadoran solar",
        "salvadoran wind", "salvadoran hydro",
        "salvadoran geothermal", "salvadoran grid",
        "salvadoran climate", "salvadoran emissions",
        "salvadoran energy transition",
        "salvadoran energy prices", "salvadoran energy security",
        "salvadoran green energy", "salvadoran carbon neutral",
        "salvadoran net zero", "salvadoran fuel prices",
        "cel el salvador", "salvadoran energy independence",
        "bitcoin mining el salvador",
        "salvadoran volcano energy",
    ],
    "technology": [
        "salvadoran tech", "san salvador tech",
        "salvadoran startup", "salvadoran ai",
        "salvadoran fintech", "salvadoran digital",
        "salvadoran innovation", "salvadoran cybersecurity",
        "salvadoran software", "salvadoran it sector",
        "salvadoran ecommerce", "salvadoran digital economy",
        "salvadoran blockchain", "salvadoran 5g",
        "salvadoran bitcoin tech",
        "salvadoran digital transformation",
        "tigo el salvador", "claro el salvador",
        "salvadoran digital hub",
        "bitcoin city el salvador",
    ],
    "health": [
        "salvadoran health", "salvadoran hospital",
        "salvadoran pharma", "salvadoran vaccine",
        "salvadoran healthcare", "salvadoran mental health",
        "salvadoran health system", "salvadoran medicine",
        "salvadoran public health", "salvadoran wellbeing",
        "salvadoran cancer", "salvadoran aging population",
        "salvadoran dengue", "salvadoran malaria",
        "salvadoran zika", "salvadoran chikungunya",
        "salvadoran health ministry",
        "salvadoran medical tourism",
        "salvadoran gang violence health",
    ],
    "crime": [
        "salvadoran corruption", "salvadoran fraud",
        "salvadoran scandal", "salvadoran court",
        "salvadoran investigation", "salvadoran organized crime",
        "ms13 el salvador", "barrio 18 el salvador",
        "salvadoran drug trafficking", "salvadoran money laundering",
        "salvadoran terrorism", "salvadoran police",
        "salvadoran gang", "salvadoran anti corruption",
        "salvadoran cybercrime", "salvadoran scam",
        "salvadoran arrest", "salvadoran human trafficking",
        "salvadoran protest", "salvadoran riot",
        "salvadoran political scandal",
        "bukele gang crackdown",
        "salvadoran state of exception",
        "cecot prison el salvador",
        "salvadoran journalist arrested",
        "el faro journalism",
        "possible arrest warrants el faro",
    ],
    "politics": [
        "asamblea legislativa el salvador",
        "salvadoran parliament", "salvadoran election",
        "salvadoran government", "salvadoran minister",
        "salvadoran president", "salvadoran coalition",
        "salvadoran opposition", "nuevas ideas",
        "nayib bukele", "bukele",
        "fmln el salvador", "arena el salvador",
        "salvadoran policy", "salvadoran reform",
        "salvadoran immigration", "salvadoran diaspora",
        "salvadoran welfare", "salvadoran citizenship",
        "salvadoran referendum", "salvadoran judiciary",
        "salvadoran rule of law", "salvadoran eu relations",
        "salvadoran democracy", "salvadoran authoritarianism",
        "salvadoran media freedom", "salvadoran press freedom",
        "salvadoran constitution", "salvadoran reelection",
        "bukele reelection", "salvadoran federalism",
        "salvadoran bitcoin policy",
        "salvadoran gang policy",
        "el faro denounces arrest warrants",
    ],
}