
# mood/pipeline/keywords/th.py
TH_KEYWORDS = {
    "finance": [
        "thai economy", "thailand gdp", "set index",
        "stock exchange thailand", "set thailand",
        "bank of thailand", "bot thailand",
        "thai baht", "thb",
        "thai inflation", "thai budget", "thai exports",
        "thai trade", "thai market", "thai growth",
        "thai debt", "thai deficit", "thai unemployment",
        "thai wages", "thai housing", "thai mortgage",
        "ptt group", "scb bank", "kasikorn bank",
        "bangkok bank", "krungthai bank",
        "cp group", "central group thailand",
        "thai business", "thai investment",
        "thai tourism", "thai manufacturing",
        "thai automotive", "thai agriculture",
        "thai rice exports", "thai rubber",
        "thai eu funds", "thai recovery plan",
        "thai pension fund", "thai industry",
        "thai it sector", "thai startup",
        "thai real estate", "thai construction",
        "thai trade deal", "thailand us trade",
        "thai tariffs", "thai fiscal",
    ],
    "geopolitics": [
        "thai foreign policy", "thailand nato",
        "thai sanctions", "thai diplomacy",
        "thai troops", "thailand ukraine", "thailand russia",
        "thai ambassador", "thailand eu",
        "thai defense", "thai military",
        "bangkok talks", "thailand security",
        "thai intelligence", "thailand china",
        "thailand us relations", "thailand asean",
        "thai south china sea", "thailand myanmar",
        "thai myanmar border", "thailand cambodia",
        "thailand laos", "thailand malaysia",
        "thai peacekeeping", "thailand un",
        "thai middle east", "thailand gulf",
    ],
    "energy": [
        "thai energy", "thai electricity",
        "thai renewables", "thai solar",
        "thai wind", "thai hydro", "thai grid",
        "thai climate", "thai emissions",
        "thai energy transition", "thai hydrogen",
        "thai lng", "thai energy prices",
        "thai energy security", "thai green energy",
        "thai coal", "thai natural gas",
        "thai oil", "thai petrochemical",
        "ptt energy", "thai carbon neutral",
        "thai net zero", "thai fuel prices",
    ],
    "technology": [
        "thai tech", "bangkok tech", "thai startup",
        "thai ai", "thai fintech", "thai digital",
        "thai innovation", "thai unicorn",
        "thai cybersecurity", "thai gaming",
        "thai software", "thai it sector",
        "thai ecommerce", "thai digital economy",
        "thai semiconductor", "thai ev",
        "thai smart city", "thai medtech",
        "thai blockchain", "thai quantum",
    ],
    "health": [
        "thai health", "thai hospital",
        "thai pharma", "thai vaccine",
        "thai healthcare", "thai mental health",
        "thai health system", "thai medicine",
        "thai public health", "thai wellbeing",
        "thai medical tourism", "thai biotech",
        "thai cancer", "thai dengue",
        "thai malaria", "moph thailand",
        "thai aging population",
    ],
    "crime": [
        "thai corruption", "thai fraud",
        "thai scandal", "thai court",
        "thai investigation", "thai organized crime",
        "thai drug trafficking", "thai money laundering",
        "thai terrorism", "thai police",
        "royal thai police", "thai gang",
        "thai anti corruption", "nacc thailand",
        "thai cybercrime", "thai scam",
        "thai arrest", "thai mafia",
        "thai human trafficking",
        "thai protest", "thai riot",
    ],
    "politics": [
        "thai parliament", "thai election",
        "thai government", "thai minister",
        "thai prime minister", "thai coalition",
        "thai opposition", "pheu thai",
        "paetongtarn shinawatra", "thaksin",
        "move forward party", "peoples party thailand",
        "thai policy", "thai reform",
        "thai immigration", "thai welfare",
        "thai citizenship", "thai referendum",
        "thai judiciary", "thai rule of law",
        "thai democracy", "thai king",
        "thai royal family", "thai monarchy",
        "thai media freedom", "thai press freedom",
        "thai constitution", "thai military coup",
        "thai junta", "house speaker thailand",
    ],
}