
# mood/pipeline/keywords/tn.py
TN_KEYWORDS = {
    "finance": [
        "tunisian economy", "tunisia gdp",
        "tunis stock exchange", "bvmt",
        "central bank tunisia", "bct",
        "tunisian dinar", "tnd",
        "tunisian inflation", "tunisian budget",
        "tunisian exports", "tunisian trade",
        "tunisian market", "tunisian growth",
        "tunisian debt", "tunisian deficit",
        "tunisian unemployment", "tunisian wages",
        "tunisian housing", "tunisian mortgage",
        "amen bank tunisia", "biat bank",
        "banque de tunisie", "attijari bank tunisia",
        "tunisian tourism", "tunisian olive oil",
        "tunisian phosphate", "tunisian dates",
        "tunisian textiles", "tunisian manufacturing",
        "tunisian agriculture", "tunisian fisheries",
        "tunisian eu trade", "tunisia us trade",
        "tunisian tariffs", "tunisian fiscal",
        "tunisian pension fund", "tunisian industry",
        "tunisian startup", "tunisian fintech",
        "tunisian real estate", "tunisian construction",
        "tunisian remittances", "tunisian diaspora",
        "tunisia imf deal", "tunisian debt crisis",
        "saied economic policy",
        "tunisian economic crisis",
    ],
    "geopolitics": [
        "tunisian foreign policy", "tunisia nato",
        "tunisian sanctions", "tunisian diplomacy",
        "tunisian troops", "tunisia ukraine",
        "tunisia russia", "tunisian ambassador",
        "tunisia eu", "tunisian defense",
        "tunisian military", "tunis talks",
        "tunisia security", "tunisian intelligence",
        "tunisia us relations", "tunisia china",
        "tunisia brics", "tunisia africa union",
        "tunisia arab league", "tunisia peacekeeping",
        "tunisia un", "tunisia libya",
        "tunisia algeria", "tunisia migration",
        "tunisia eu migration deal",
        "tunisian coast guard",
        "saied foreign policy",
        "tunisia sahel",
        "tunisia iran",
    ],
    "energy": [
        "tunisian energy", "tunisian electricity",
        "tunisian renewables", "tunisian solar",
        "tunisian wind", "tunisian hydro",
        "tunisian grid", "tunisian climate",
        "tunisian emissions", "tunisian energy transition",
        "tunisian hydrogen", "tunisian lng",
        "tunisian energy prices", "tunisian energy security",
        "tunisian green energy", "tunisian carbon neutral",
        "tunisian net zero", "tunisian fuel prices",
        "tunisian gas", "tunisian oil",
        "steg tunisia", "tunisian energy crisis",
        "tunisian green hydrogen",
        "tunisian offshore wind",
        "transmed pipeline tunisia",
    ],
    "technology": [
        "tunisian tech", "tunis tech", "tunisian startup",
        "tunisian ai", "tunisian fintech",
        "tunisian digital", "tunisian innovation",
        "tunisian unicorn", "tunisian cybersecurity",
        "tunisian gaming", "tunisian software",
        "tunisian it sector", "tunisian ecommerce",
        "tunisian digital economy", "tunisian 5g",
        "tunisian blockchain", "tunisian smart city",
        "tunisian medtech", "tunisian biotech",
        "tunisian digital transformation",
        "ooredoo tunisia", "tunisie telecom",
        "tunisian silicon valley",
        "sfax tech hub",
        "eu lawmakers facebook google tunisia",
    ],
    "health": [
        "tunisian health", "tunisian hospital",
        "tunisian pharma", "tunisian vaccine",
        "tunisian healthcare", "tunisian mental health",
        "tunisian health system", "tunisian medicine",
        "tunisian public health", "tunisian wellbeing",
        "tunisian biotech", "tunisian cancer",
        "tunisian aging population",
        "tunisian dengue", "tunisian malaria",
        "tunisian health reform",
        "tunisian universal health",
        "tunisian medical tourism",
        "tunisian health crisis",
    ],
    "crime": [
        "tunisian corruption", "tunisian fraud",
        "tunisian scandal", "tunisian court",
        "tunisian investigation", "tunisian organized crime",
        "tunisian drug trafficking", "tunisian money laundering",
        "tunisian terrorism", "tunisian police",
        "tunisian gang", "tunisian anti corruption",
        "tunisian cybercrime", "tunisian scam",
        "tunisian arrest", "tunisian mafia",
        "tunisian human trafficking",
        "tunisian protest", "tunisian riot",
        "tunisian political prisoner",
        "tunisian dissident",
        "tunisian journalist arrested",
        "tunisian opposition arrested",
        "tunisian femicide",
        "tunisian migration crime",
    ],
    "politics": [
        "assembly of representatives tunisia",
        "tunisian parliament", "tunisian election",
        "tunisian government", "tunisian minister",
        "tunisian president", "tunisian coalition",
        "tunisian opposition", "kais saied", "saied tunisia",
        "ennahda tunisia", "rached ghannouchi",
        "tunisian policy", "tunisian reform",
        "tunisian immigration", "tunisian diaspora",
        "tunisian welfare", "tunisian citizenship",
        "tunisian referendum", "tunisian judiciary",
        "tunisian rule of law", "tunisian eu relations",
        "tunisian democracy", "tunisian authoritarianism",
        "tunisian media freedom", "tunisian press freedom",
        "tunisian constitution", "tunisian coup",
        "tunisian political crisis",
        "tunisian opposition crackdown",
        "tunisian arab spring legacy",
    ],
}