
# mood/pipeline/keywords/tr.py
TR_KEYWORDS = {
    "finance": [
        "turkish economy", "turkey gdp", "bist 100",
        "borsa istanbul", "istanbul stock exchange",
        "central bank turkey", "tcmb",
        "turkish lira", "try",
        "turkish inflation", "turkish budget",
        "turkish exports", "turkish trade",
        "turkish market", "turkish growth",
        "turkish debt", "turkish deficit",
        "turkish unemployment", "turkish wages",
        "turkish housing", "turkish mortgage",
        "akbank", "garanti bank", "is bankasi",
        "ziraat bank", "halkbank turkey",
        "koc holding", "sabanci holding",
        "turkish airlines", "turkcell", "bim turkey",
        "turkish business", "turkish investment",
        "turkish tourism", "turkish manufacturing",
        "turkish automotive", "turkish textile",
        "turkish agriculture", "turkish hazelnut",
        "turkish eu trade", "turkey us trade",
        "turkish tariffs", "turkish fiscal",
        "turkish pension fund", "turkish industry",
        "turkish startup", "turkish unicorn",
        "turkish fintech", "turkish real estate",
        "turkish construction", "turkish logistics",
        "turkish central bank reserves",
        "turkish currency crisis",
        "turkish interest rates",
    ],
    "geopolitics": [
        "turkish foreign policy", "turkey nato",
        "turkish sanctions", "turkish diplomacy",
        "turkish troops", "turkey ukraine", "turkey russia",
        "turkish ambassador", "turkey eu",
        "turkish defense", "turkish military",
        "ankara talks", "turkey security",
        "turkish intelligence", "mit turkey",
        "turkey us relations", "turkey f16",
        "turkey sweden nato", "turkey finland nato",
        "turkey iran relations", "turkey israel",
        "turkey hamas", "turkey middle east",
        "turkey gulf", "turkey saudi",
        "turkey gcc", "turkey qatar",
        "turkey peacekeeping", "turkey un",
        "turkey syria", "turkey kurdish",
        "pkk turkey", "turkey iraq",
        "turkey greece", "turkey cyprus",
        "turkey azerbaijan", "turkey armenia",
        "turkey russia gas", "turkstream",
        "turkey china relations", "turkey india",
        "erdogan foreign policy",
        "turkey drone bayraktar",
    ],
    "energy": [
        "turkish energy", "turkish gas",
        "turkish electricity", "turkish renewables",
        "turkish solar", "turkish wind",
        "turkish hydro", "turkish grid",
        "turkish climate", "turkish emissions",
        "turkish energy transition", "turkish hydrogen",
        "turkish lng", "turkish energy prices",
        "turkish energy security", "turkish green energy",
        "turkish nuclear", "akkuyu nuclear",
        "turkish carbon neutral", "turkish net zero",
        "turkish fuel prices", "turkish coal",
        "turkish natural gas", "turkstream pipeline",
        "turkish energy hub", "turkish energy corridor",
        "botas turkey",
    ],
    "technology": [
        "turkish tech", "istanbul tech", "turkish startup",
        "turkish ai", "turkish fintech", "turkish digital",
        "turkish innovation", "turkish unicorn",
        "turkish cybersecurity", "turkish gaming",
        "turkish software", "turkish it sector",
        "turkish ecommerce", "turkish digital economy",
        "turkish semiconductor", "turkish ev",
        "togg turkey", "turkish smart city",
        "turkish medtech", "turkish biotech",
        "turkish drone technology", "bayraktar tb2",
        "turkish space agency", "tua turkey",
        "turkish 5g", "turkish quantum",
        "trendyol turkey", "getir turkey",
    ],
    "health": [
        "turkish health", "turkish hospital",
        "turkish pharma", "turkish vaccine",
        "turkish healthcare", "turkish mental health",
        "turkish health system", "turkish medicine",
        "turkish public health", "turkish wellbeing",
        "turkish biotech", "turkish cancer",
        "turkish aging population", "turkish birthrate",
        "turkish medical tourism",
        "saglik bakanligi turkey",
        "turkish universal healthcare",
    ],
    "crime": [
        "turkish corruption", "turkish fraud",
        "turkish scandal", "turkish court",
        "turkish investigation", "turkish organized crime",
        "turkish drug trafficking", "turkish money laundering",
        "turkish terrorism", "turkish police",
        "turkish gang", "turkish anti corruption",
        "turkish cybercrime", "turkish scam",
        "turkish arrest", "turkish mafia",
        "turkish human trafficking",
        "turkish protest", "turkish riot",
        "turkish political prisoner",
        "turkish journalist arrested",
        "turkish dissident",
        "turkish opposition arrested",
    ],
    "politics": [
        "grand national assembly", "tbmm turkey",
        "turkish parliament", "turkish election",
        "turkish government", "turkish minister",
        "turkish prime minister", "turkish president",
        "turkish coalition", "turkish opposition",
        "akp turkey", "erdogan", "recep tayyip erdogan",
        "chp turkey", "kemal kilicdaroglu",
        "dem party turkey", "iyi party turkey",
        "turkish policy", "turkish reform",
        "turkish immigration", "turkish refugees",
        "turkish welfare", "turkish citizenship",
        "turkish referendum", "turkish judiciary",
        "turkish rule of law", "turkish eu relations",
        "turkish democracy", "turkish media freedom",
        "turkish press freedom", "turkish constitution",
        "turkish eu accession", "turkish eu candidate",
        "turkish local elections",
        "istanbul mayor", "ekrem imamoglu",
        "turkish central bank independence",
    ],
}