
# mood/pipeline/keywords/tw.py
TW_KEYWORDS = {
    "finance": [
        "taiwan economy", "taiwan gdp", "taiex",
        "taiwan stock exchange", "twse",
        "central bank taiwan", "cbc taiwan",
        "new taiwan dollar", "twd",
        "taiwan inflation", "taiwan budget", "taiwan exports",
        "taiwan trade", "taiwan market", "taiwan growth",
        "taiwan debt", "taiwan deficit", "taiwan unemployment",
        "taiwan wages", "taiwan housing", "taiwan mortgage",
        "tsmc", "taiwan semiconductor",
        "mediatek", "asus", "acer", "htc",
        "foxconn", "hon hai precision",
        "united microelectronics", "umc",
        "taiwan business", "taiwan investment",
        "taiwan tourism", "taiwan manufacturing",
        "taiwan semiconductor industry",
        "taiwan chip exports", "taiwan tech exports",
        "taiwan eu trade", "taiwan us trade",
        "taiwan tariffs", "taiwan fiscal",
        "taiwan pension fund", "taiwan industry",
        "taiwan startup", "taiwan unicorn",
        "taiwan fintech", "taiwan real estate",
        "taiwan construction", "taiwan logistics",
        "taiwan competitive edge",
    ],
    "geopolitics": [
        "taiwan foreign policy", "taiwan nato",
        "taiwan sanctions", "taiwan diplomacy",
        "taiwan troops", "taiwan ukraine", "taiwan russia",
        "taiwan ambassador", "taiwan eu",
        "taiwan defense", "taiwan military",
        "taipei talks", "taiwan security",
        "taiwan intelligence", "taiwan china",
        "taiwan strait", "taiwan strait tension",
        "pla taiwan", "chinese military taiwan",
        "taiwan us relations", "taiwan relations act",
        "taiwan japan relations", "taiwan korea",
        "taiwan independence", "taiwan sovereignty",
        "one china policy", "taiwan recognition",
        "taiwan un", "taiwan who",
        "taiwan middle east", "taiwan peacekeeping",
        "taiwan arms", "taiwan weapons",
        "taiwan missile defense", "taiwan f16",
        "taiwan patriot", "taiwan air defense",
        "taiwan invasion threat", "taiwan blockade",
        "taiwan reunification", "taiwan status quo",
    ],
    "energy": [
        "taiwan energy", "taiwan nuclear",
        "taiwan electricity", "taiwan renewables",
        "taiwan solar", "taiwan wind", "taiwan hydro",
        "taiwan grid", "taiwan climate",
        "taiwan emissions", "taiwan energy transition",
        "taiwan hydrogen", "taiwan lng",
        "taiwan energy prices", "taiwan energy security",
        "taiwan offshore wind", "taiwan green energy",
        "taiwan coal", "taiwan natural gas",
        "taipower taiwan", "taiwan carbon neutral",
        "taiwan net zero", "taiwan fuel prices",
        "taiwan nuclear phase out",
        "taiwan energy crisis",
    ],
    "technology": [
        "taiwan tech", "taipei tech", "taiwan startup",
        "taiwan ai", "taiwan semiconductor",
        "tsmc chip", "taiwan chip",
        "taiwan digital", "taiwan innovation",
        "taiwan robotics", "taiwan ev",
        "taiwan battery", "taiwan quantum",
        "taiwan cybersecurity", "taiwan gaming",
        "taiwan software", "taiwan it sector",
        "taiwan unicorn", "taiwan fintech",
        "taiwan space", "taiwan 5g",
        "taiwan display", "taiwan led",
        "taiwan medtech", "taiwan biotech",
        "taiwan supply chain", "taiwan chip war",
        "taiwan semiconductor dominance",
        "taiwan leo satellite", "digitimes taiwan",
        "taiwan hsinchu", "science park taiwan",
    ],
    "health": [
        "taiwan health", "taiwan hospital",
        "taiwan pharma", "taiwan vaccine",
        "taiwan healthcare", "taiwan mental health",
        "taiwan health system", "taiwan medicine",
        "taiwan public health", "taiwan wellbeing",
        "taiwan biotech", "taiwan cancer",
        "taiwan aging population", "taiwan birthrate",
        "taiwan traditional medicine",
        "mohw taiwan", "taiwan nhi",
        "taiwan universal healthcare",
        "taiwan biomedical",
    ],
    "crime": [
        "taiwan corruption", "taiwan fraud",
        "taiwan scandal", "taiwan court",
        "taiwan investigation", "taiwan organized crime",
        "taiwan drug trafficking", "taiwan money laundering",
        "taiwan terrorism", "taiwan police",
        "taiwan gang", "taiwan anti corruption",
        "taiwan cybercrime", "taiwan scam",
        "taiwan arrest", "taiwan mafia",
        "taiwan human trafficking",
        "taiwan protest", "taiwan riot",
        "taiwan political scandal",
        "taiwan espionage", "taiwan spy",
        "chinese spy taiwan",
    ],
    "politics": [
        "legislative yuan", "taiwan parliament",
        "taiwan election", "taiwan government",
        "taiwan minister", "taiwan prime minister",
        "taiwan president", "taiwan coalition",
        "taiwan opposition", "dpp taiwan",
        "democratic progressive party",
        "lai ching te", "william lai",
        "kmt taiwan", "kuomintang",
        "eric chu", "han kuo yu",
        "tpp taiwan", "ko wen je",
        "taiwan policy", "taiwan reform",
        "taiwan immigration", "taiwan diaspora",
        "taiwan welfare", "taiwan citizenship",
        "taiwan referendum", "taiwan judiciary",
        "taiwan rule of law", "taiwan eu relations",
        "taiwan democracy", "taiwan media freedom",
        "taiwan press freedom", "taiwan constitution",
        "taiwan autonomy", "taiwan self governance",
        "taiwan cross strait relations",
        "taiwan mainland relations",
    ],
}