
# mood/pipeline/keywords/tz.py
TZ_KEYWORDS = {
    "finance": [
        "tanzanian economy", "tanzania gdp",
        "dar es salaam stock exchange", "dse tanzania",
        "bank of tanzania", "bot",
        "tanzanian shilling", "tzs",
        "tanzanian inflation", "tanzanian budget",
        "tanzanian exports", "tanzanian trade",
        "tanzanian market", "tanzanian growth",
        "tanzanian debt", "tanzanian deficit",
        "tanzanian unemployment", "tanzanian wages",
        "tanzanian housing", "tanzanian mortgage",
        "crdb bank tanzania", "nmb bank tanzania",
        "stanbic tanzania", "absa tanzania",
        "tanzanian gold", "tanzanian tanzanite",
        "tanzanian diamonds", "tanzanian coffee",
        "tanzanian tea", "tanzanian tobacco",
        "tanzanian cashew", "tanzanian sisal",
        "tanzanian business", "tanzanian investment",
        "tanzanian tourism", "tanzanian manufacturing",
        "tanzanian agriculture", "tanzanian fisheries",
        "tanzanian eu trade", "tanzania us trade",
        "tanzanian tariffs", "tanzanian fiscal",
        "tanzanian pension fund", "nssf tanzania",
        "tanzanian industry", "tanzanian startup",
        "tanzanian fintech", "tanzanian real estate",
        "tanzanian construction", "tanzanian remittances",
        "tanzanian diaspora", "tanzania imf",
        "hassan economic policy",
        "tanzanian natural gas",
        "tanzanian lng project",
        "ta issue tanzania",
    ],
    "geopolitics": [
        "tanzanian foreign policy", "tanzania nato",
        "tanzanian sanctions", "tanzanian diplomacy",
        "tanzanian troops", "tanzania ukraine",
        "tanzania russia", "tanzanian ambassador",
        "tanzania eu", "tanzanian defense",
        "tanzanian military", "dar es salaam talks",
        "tanzania security", "tanzanian intelligence",
        "tanzania us relations", "tanzania china",
        "tanzania brics", "tanzania africa union",
        "tanzania igad", "tanzania peacekeeping",
        "tanzania un", "tanzania drc",
        "tanzania mozambique", "tanzania kenya",
        "tanzania uganda", "tanzania malawi",
        "tanzania burundi",
        "hassan foreign policy",
        "tanzania east africa community",
        "tanzanian election observer",
        "zanzibar autonomy",
    ],
    "energy": [
        "tanzanian energy", "tanzanian electricity",
        "tanzanian renewables", "tanzanian solar",
        "tanzanian wind", "tanzanian hydro",
        "tanzanian grid", "tanzanian climate",
        "tanzanian emissions", "tanzanian energy transition",
        "tanzanian hydrogen", "tanzanian lng",
        "tanzanian energy prices", "tanzanian energy security",
        "tanzanian green energy", "tanzanian carbon neutral",
        "tanzanian net zero", "tanzanian fuel prices",
        "tanzanian natural gas", "tanzania lng project",
        "julius nyerere hydropower",
        "tanesco tanzania",
        "tanzanian geothermal",
        "tanzanian offshore gas",
    ],
    "technology": [
        "tanzanian tech", "dar es salaam tech",
        "tanzanian startup", "tanzanian ai",
        "tanzanian fintech", "tanzanian digital",
        "tanzanian innovation", "tanzanian cybersecurity",
        "tanzanian gaming", "tanzanian software",
        "tanzanian it sector", "tanzanian ecommerce",
        "tanzanian digital economy", "tanzanian 5g",
        "tanzanian blockchain", "tanzanian smart city",
        "tanzanian medtech", "tanzanian digital transformation",
        "vodacom tanzania", "airtel tanzania",
        "tanzanian mpesa", "tanzanian mobile money",
        "tanzanian tech hub",
        "buni hub tanzania",
    ],
    "health": [
        "tanzanian health", "tanzanian hospital",
        "tanzanian pharma", "tanzanian vaccine",
        "tanzanian healthcare", "tanzanian mental health",
        "tanzanian health system", "tanzanian medicine",
        "tanzanian public health", "tanzanian wellbeing",
        "tanzanian malaria", "tanzanian tuberculosis",
        "tanzanian hiv", "tanzanian cholera",
        "tanzanian health reform",
        "tanzanian universal health",
        "muhimbili hospital tanzania",
        "tanzanian maternal health",
        "tfda tanzania",
        "tanzanian community health",
    ],
    "crime": [
        "tanzanian corruption", "tanzanian fraud",
        "tanzanian scandal", "tanzanian court",
        "tanzanian investigation", "tanzanian organized crime",
        "tanzanian drug trafficking", "tanzanian money laundering",
        "tanzanian terrorism", "tanzanian police",
        "tanzanian gang", "tanzanian anti corruption",
        "pccb tanzania", "tanzanian cybercrime",
        "tanzanian scam", "tanzanian arrest",
        "tanzanian human trafficking",
        "tanzanian protest", "tanzanian riot",
        "tanzanian political scandal",
        "tanzanian opposition arrested",
        "tanzanian femicide",
        "tanzanian election violence",
        "zanzibar separatism",
    ],
    "politics": [
        "national assembly tanzania", "tanzanian parliament",
        "tanzanian election", "tanzanian government",
        "tanzanian minister", "tanzanian president",
        "tanzanian coalition", "tanzanian opposition",
        "ccm tanzania", "samia suluhu hassan",
        "hassan tanzania", "chadema tanzania",
        "tanzanian policy", "tanzanian reform",
        "tanzanian immigration", "tanzanian diaspora",
        "tanzanian welfare", "tanzanian citizenship",
        "tanzanian referendum", "tanzanian judiciary",
        "tanzanian rule of law", "tanzanian eu relations",
        "tanzanian democracy", "tanzanian media freedom",
        "tanzanian press freedom", "tanzanian constitution",
        "tanzanian federalism", "tanzanian regions",
        "zanzibar politics",
        "tanzanian political stability",
        "tanzanian vision 2025",
        "tanzanian affairs magazine",
    ],
}
