
# mood/pipeline/keywords/ua.py
UA_KEYWORDS = {
    "finance": [
        "ukrainian economy", "ukraine gdp",
        "kyiv stock exchange", "pfts ukraine",
        "national bank ukraine", "nbu",
        "ukrainian hryvnia", "uah",
        "ukrainian inflation", "ukrainian budget",
        "ukrainian exports", "ukrainian trade",
        "ukrainian market", "ukrainian growth",
        "ukrainian debt", "ukrainian deficit",
        "ukrainian unemployment", "ukrainian wages",
        "ukrainian housing", "ukrainian reconstruction",
        "ukrainian aid", "ukraine imf",
        "ukraine world bank", "ukrainian bonds",
        "ukrainian agriculture", "ukrainian grain",
        "ukrainian steel", "ukrainian iron ore",
        "ukrainian corn exports", "ukrainian wheat",
        "ukrainian defense industry", "ukrainian weapons exports",
        "ukrainian drone industry", "ukrainian military production",
        "naftogaz ukraine", "ukrhydroenergo",
        "ukrainian banking", "privatbank",
        "raiffeisen ukraine", "ukrsibbank",
        "ukrainian business", "ukrainian investment",
        "ukrainian recovery plan", "ukraine marshall plan",
        "ukrainian eu funds", "ukrainian pension fund",
        "ukrainian it sector", "ukrainian startup",
        "ukrainian outsourcing", "ukrainian tech",
        "ukraine reconstruction conference",
    ],
    "geopolitics": [
        "ukrainian foreign policy", "ukraine nato",
        "ukrainian sanctions", "ukrainian diplomacy",
        "ukrainian troops", "ukraine russia",
        "ukrainian war", "russian invasion ukraine",
        "kyiv", "zelensky", "volodymyr zelensky",
        "ukrainian military", "ukrainian defense",
        "ukrainian frontline", "ukrainian counterattack",
        "ukrainian offensive", "ukrainian ceasefire",
        "ukrainian peace talks", "ukraine peace deal",
        "ukrainian weapons", "ukrainian drones",
        "ukrainian combat drones", "ukraine f16",
        "ukraine air defense", "ukrainian patriot",
        "ukraine nato membership", "ukraine eu accession",
        "ukrainian border", "ukrainian occupied territories",
        "ukrainian crimea", "donbas ukraine",
        "ukrainian allies", "ukraine support",
        "ukraine us relations", "ukraine eu relations",
        "ukraine germany relations", "ukraine uk relations",
        "ukrainian intelligence", "sbu ukraine",
        "ukrainian foreign minister", "dmytro kuleba",
        "andrii sybiha",
    ],
    "energy": [
        "ukrainian energy", "ukrainian electricity",
        "ukrainian gas", "ukrainian nuclear",
        "zaporizhzhia nuclear", "ukrainian renewables",
        "ukrainian grid", "ukrainian power plant",
        "ukrainian blackout", "ukrainian energy attack",
        "ukrainian energy infrastructure",
        "ukrainian pipeline", "ukrainian lng",
        "ukrainian energy security", "ukrainian energy prices",
        "ukrainian energy reconstruction",
        "naftogaz energy", "ukrainian solar",
        "ukrainian wind", "ukrainian hydro",
        "ukrainian coal", "ukrainian energy independence",
    ],
    "technology": [
        "ukrainian tech", "kyiv tech", "ukrainian startup",
        "ukrainian ai", "ukrainian fintech",
        "ukrainian digital", "ukrainian innovation",
        "ukrainian unicorn", "ukrainian cybersecurity",
        "ukrainian gaming", "ukrainian software",
        "ukrainian it sector", "ukrainian outsourcing",
        "grammarly ukraine", "gitlab ukraine",
        "ukrainian drone tech", "ukrainian defense tech",
        "ukrainian semiconductor", "ukrainian quantum",
        "diia ukraine", "ukrainian e-government",
        "ukrainian digital transformation",
    ],
    "health": [
        "ukrainian health", "ukrainian hospital",
        "ukrainian pharma", "ukrainian vaccine",
        "ukrainian healthcare", "ukrainian mental health",
        "ukrainian health system", "ukrainian medicine",
        "ukrainian war wounded", "ukrainian casualties",
        "ukrainian ptsd", "ukrainian war trauma",
        "ukrainian public health", "ukrainian wellbeing",
        "ukrainian medical aid", "ukrainian blood donors",
        "ukrainian medical evacuation",
    ],
    "crime": [
        "ukrainian corruption", "ukrainian fraud",
        "ukrainian scandal", "ukrainian court",
        "ukrainian investigation", "ukrainian organized crime",
        "ukrainian drug trafficking", "ukrainian money laundering",
        "ukrainian terrorism", "ukrainian police",
        "natspolitsiya ukraine", "ukrainian gang",
        "ukrainian anti corruption", "nabu ukraine",
        "ukrainian oligarch", "ukrainian fraud scheme",
        "ukrainian smuggling", "ukrainian human trafficking",
        "ukrainian war crimes", "russian war crimes ukraine",
        "bucha massacre", "mariupol siege",
        "ukrainian postal service damaged",
    ],
    "politics": [
        "verkhovna rada", "ukrainian parliament",
        "ukrainian election", "ukrainian government",
        "ukrainian minister", "ukrainian prime minister",
        "ukrainian coalition", "ukrainian opposition",
        "volodymyr zelensky", "zelensky",
        "denys shmyhal", "ruslan stefanchuk",
        "ukrainian policy", "ukrainian reform",
        "ukrainian immigration", "ukrainian refugees",
        "ukrainian welfare", "ukrainian citizenship",
        "ukrainian referendum", "ukrainian judiciary",
        "ukrainian rule of law", "ukrainian eu relations",
        "ukrainian democracy", "ukrainian president",
        "ukrainian media freedom",
        "ukrainian martial law",
        "ukrainian wartime politics",
        "ukrainian reconstruction politics",
        "ukraine eu candidate status",
        "ukraine nato application",
    ],
}
