
# mood/pipeline/keywords/ug.py
UG_KEYWORDS = {
    "finance": [
        "ugandan economy", "uganda gdp",
        "uganda securities exchange", "use uganda",
        "bank of uganda", "bou",
        "ugandan shilling", "ugx",
        "ugandan inflation", "ugandan budget",
        "ugandan exports", "ugandan trade",
        "ugandan market", "ugandan growth",
        "ugandan debt", "ugandan deficit",
        "ugandan unemployment", "ugandan wages",
        "ugandan housing", "ugandan mortgage",
        "stanbic bank uganda", "dfcu bank",
        "centenary bank uganda", "absa uganda",
        "ugandan oil", "kingfisher oil uganda",
        "tilenga oil uganda", "eacop pipeline",
        "ugandan coffee", "ugandan tea",
        "ugandan flowers", "ugandan fish",
        "ugandan business", "ugandan investment",
        "ugandan tourism", "ugandan manufacturing",
        "ugandan agriculture", "ugandan maize",
        "ugandan eu trade", "uganda us trade",
        "ugandan tariffs", "ugandan fiscal",
        "ugandan pension fund", "nssf uganda",
        "ugandan industry", "ugandan startup",
        "ugandan fintech", "ugandan real estate",
        "ugandan construction", "ugandan remittances",
        "ugandan diaspora", "uganda imf",
        "museveni economic policy",
        "ugandan oil pipeline",
        "affordable housing uganda",
    ],
    "geopolitics": [
        "ugandan foreign policy", "uganda nato",
        "ugandan sanctions", "ugandan diplomacy",
        "ugandan troops", "uganda ukraine",
        "uganda russia", "ugandan ambassador",
        "uganda eu", "ugandan defense",
        "ugandan military", "kampala talks",
        "uganda security", "ugandan intelligence",
        "iso uganda", "uganda us relations",
        "uganda china", "uganda brics",
        "uganda africa union", "uganda igad",
        "uganda peacekeeping", "uganda un",
        "uganda drc", "uganda congo",
        "uganda south sudan", "uganda kenya",
        "uganda rwanda", "uganda somalia",
        "museveni foreign policy",
        "uganda east africa community",
        "eacop geopolitics",
        "ugandan election observer",
    ],
    "energy": [
        "ugandan energy", "ugandan electricity",
        "ugandan renewables", "ugandan solar",
        "ugandan wind", "ugandan hydro",
        "ugandan grid", "ugandan climate",
        "ugandan emissions", "ugandan energy transition",
        "ugandan hydrogen", "ugandan lng",
        "ugandan energy prices", "ugandan energy security",
        "ugandan green energy", "ugandan carbon neutral",
        "ugandan net zero", "ugandan fuel prices",
        "ugandan oil", "eacop pipeline uganda",
        "karuma dam uganda", "isimba dam",
        "uegcl uganda", "umeme uganda",
        "ugandan energy crisis",
        "ugandan oil production",
    ],
    "technology": [
        "ugandan tech", "kampala tech", "ugandan startup",
        "ugandan ai", "ugandan fintech",
        "ugandan digital", "ugandan innovation",
        "ugandan unicorn", "ugandan cybersecurity",
        "ugandan gaming", "ugandan software",
        "ugandan it sector", "ugandan ecommerce",
        "ugandan digital economy", "ugandan 5g",
        "ugandan blockchain", "ugandan smart city",
        "ugandan medtech", "ugandan digital transformation",
        "mtn uganda", "airtel uganda",
        "ugandan silicon valley",
        "hive colab uganda",
        "ugandan tech hub",
    ],
    "health": [
        "ugandan health", "ugandan hospital",
        "ugandan pharma", "ugandan vaccine",
        "ugandan healthcare", "ugandan mental health",
        "ugandan health system", "ugandan medicine",
        "ugandan public health", "ugandan wellbeing",
        "ugandan malaria", "ugandan tuberculosis",
        "ugandan hiv", "ugandan cholera",
        "ugandan ebola", "ugandan mpox",
        "ugandan health reform",
        "ugandan universal health",
        "mulago hospital uganda",
        "ugandan maternal health",
        "nms uganda",
        "missing child uganda pond",
    ],
    "crime": [
        "ugandan corruption", "ugandan fraud",
        "ugandan scandal", "ugandan court",
        "ugandan investigation", "ugandan organized crime",
        "ugandan drug trafficking", "ugandan money laundering",
        "ugandan terrorism", "ugandan police",
        "ugandan gang", "ugandan anti corruption",
        "inspectorate uganda", "cid uganda",
        "ugandan cybercrime", "ugandan scam",
        "ugandan arrest", "ugandan human trafficking",
        "ugandan protest", "ugandan riot",
        "ugandan political scandal",
        "ugandan lgbtq law",
        "ugandan anti homosexuality",
        "ugandan election violence",
        "ugandan femicide",
        "adf uganda drc",
    ],
    "politics": [
        "parliament of uganda", "ugandan parliament",
        "ugandan election", "ugandan government",
        "ugandan minister", "ugandan president",
        "ugandan coalition", "ugandan opposition",
        "nrm uganda", "yoweri museveni", "museveni",
        "nup uganda", "bobi wine",
        "robert kyagulanyi",
        "ugandan policy", "ugandan reform",
        "ugandan immigration", "ugandan diaspora",
        "ugandan welfare", "ugandan citizenship",
        "ugandan referendum", "ugandan judiciary",
        "ugandan rule of law", "ugandan eu relations",
        "ugandan democracy", "ugandan media freedom",
        "ugandan press freedom", "ugandan constitution",
        "ugandan federalism", "ugandan regions",
        "ugandan term limits",
        "ugandan political prisoners",
        "ugandan opposition crackdown",
        "steel mills uganda housing",
    ],
}

