
# mood/pipeline/keywords/us.py
US_KEYWORDS = {
    "finance": [
        "us economy", "american economy", "us gdp",
        "s&p 500", "nasdaq", "dow jones", "nyse",
        "federal reserve", "fed", "fed funds rate",
        "us inflation", "us budget", "us exports",
        "us trade", "us market", "us growth",
        "us debt", "us deficit", "us unemployment",
        "us wages", "us housing", "us mortgage",
        "us interest rates", "us rate hike",
        "us treasury", "us bonds", "us yield",
        "jpmorgan", "bank of america", "goldman sachs",
        "morgan stanley", "citigroup", "wells fargo",
        "blackrock", "american express", "capital one",
        "apple", "microsoft", "amazon", "google",
        "meta", "nvidia", "tesla", "alphabet",
        "us business", "us investment",
        "us manufacturing", "us retail",
        "us trade deficit", "us trade surplus",
        "us tariffs", "us sanctions economy",
        "us fiscal policy", "us stimulus",
        "us pension fund", "us social security",
        "us real estate", "us construction",
        "wall street", "us stock market",
        "us corporate earnings", "us gdp growth",
        "us recession", "us soft landing",
        "us consumer spending", "us retail sales",
        "us jobs report", "us payrolls",
        "us cpi", "us ppi", "us pce",
    ],
    "geopolitics": [
        "us foreign policy", "us nato",
        "us sanctions", "us diplomacy",
        "us troops", "us military",
        "us ukraine", "us russia",
        "us ambassador", "us eu relations",
        "us defense", "pentagon",
        "washington talks", "us security",
        "us intelligence", "cia", "nsa",
        "us china relations", "us taiwan",
        "us iran war", "us iran strikes",
        "us israel relations", "us middle east",
        "us saudi relations", "us gulf",
        "us india relations", "us quad",
        "us japan alliance", "us korea",
        "us peacekeeping", "us un",
        "us africa", "us latin america",
        "trump foreign policy", "trump sanctions",
        "trump tariffs", "trump china",
        "trump iran", "trump ukraine",
        "trump nato", "trump eu",
        "us kharg island strikes",
        "us airstrikes iran",
        "us military operation",
        "us drone strike",
    ],
    "energy": [
        "us energy", "us oil", "us gas",
        "us electricity", "us renewables",
        "us solar", "us wind", "us grid",
        "us climate", "us emissions",
        "us energy transition", "us hydrogen",
        "us lng", "us energy prices",
        "us energy security", "us green energy",
        "us coal", "us natural gas",
        "us carbon neutral", "us net zero",
        "us fuel prices", "us gas prices",
        "us strategic petroleum reserve",
        "us oil production", "us shale",
        "us fracking", "us offshore drilling",
        "us energy independence",
        "us inflation reduction act energy",
        "us clean energy",
    ],
    "technology": [
        "us tech", "silicon valley", "us startup",
        "us ai", "us artificial intelligence",
        "us semiconductor", "us chip",
        "us digital", "us innovation",
        "us unicorn", "us fintech",
        "us cybersecurity", "us hacking",
        "us software", "us it sector",
        "us ecommerce", "us digital economy",
        "us ev", "us autonomous vehicle",
        "us quantum computing", "us space",
        "nasa", "spacex", "us satellite",
        "us 5g", "us blockchain",
        "us big tech regulation",
        "us antitrust tech",
        "us ai regulation", "us ai safety",
        "openai", "anthropic", "google ai",
        "microsoft ai", "nvidia chip",
        "us chip export ban", "us chip sanctions",
        "chips act", "us semiconductor industry",
    ],
    "health": [
        "us health", "us hospital",
        "us pharma", "us vaccine",
        "us healthcare", "us mental health",
        "us health system", "us medicine",
        "us public health", "us wellbeing",
        "us biotech", "us cancer",
        "us aging population", "us birthrate",
        "fda approval", "us drug approval",
        "us health insurance", "us medicare",
        "us medicaid", "us obamacare",
        "us health reform", "us drug prices",
        "us opioid crisis", "us addiction",
        "us cdc", "us nih",
        "us pandemic preparedness",
        "us bird flu", "us outbreak",
        "us mental health crisis",
    ],
    "crime": [
        "us corruption", "us fraud",
        "us scandal", "us court",
        "us investigation", "us organized crime",
        "us drug trafficking", "us money laundering",
        "us terrorism", "us police",
        "us gang", "us anti corruption",
        "us cybercrime", "us scam",
        "us arrest", "us indicted",
        "us convicted", "us sentenced",
        "us mafia", "us cartel",
        "us human trafficking",
        "us mass shooting", "us gun violence",
        "us protest", "us riot",
        "us political scandal",
        "us impeachment", "us indictment",
        "us doj investigation",
        "us fbi investigation",
        "us wall street fraud",
        "us insider trading",
        "us white collar crime",
    ],
    "politics": [
        "us congress", "us senate", "us house",
        "us parliament", "us election",
        "us government", "us minister",
        "us president", "us administration",
        "us coalition", "us opposition",
        "republican party", "democratic party",
        "donald trump", "trump",
        "joe biden", "kamala harris",
        "us policy", "us reform",
        "us immigration", "us border",
        "us welfare", "us citizenship",
        "us judiciary", "us supreme court",
        "us rule of law", "us democracy",
        "us media freedom", "us press freedom",
        "us constitution", "us federalism",
        "us state politics", "us midterms",
        "us filibuster", "us debt ceiling",
        "us government shutdown",
        "us executive order",
        "us doge", "elon musk doge",
        "us tariff policy", "us trade war",
        "us iran war policy",
        "us broadcast license",
        "us media regulation",
    ],
}
