
# mood/pipeline/keywords/uy.py
UY_KEYWORDS = {
    "finance": [
        "uruguayan economy", "uruguay gdp",
        "bolsa valores montevideo", "bvm uruguay",
        "central bank uruguay", "bcu",
        "uruguayan peso", "uyu",
        "uruguayan inflation", "uruguayan budget",
        "uruguayan exports", "uruguayan trade",
        "uruguayan market", "uruguayan growth",
        "uruguayan debt", "uruguayan deficit",
        "uruguayan unemployment", "uruguayan wages",
        "uruguayan housing", "uruguayan mortgage",
        "banco republica uruguay", "brou",
        "banco itau uruguay", "scotiabank uruguay",
        "bbva uruguay", "santander uruguay",
        "antel uruguay", "ute uruguay",
        "uruguayan beef exports", "uruguayan wool",
        "uruguayan soybean", "uruguayan dairy",
        "uruguayan wine", "uruguayan rice",
        "uruguayan business", "uruguayan investment",
        "uruguayan tourism", "uruguayan manufacturing",
        "uruguayan agriculture", "uruguayan forestry",
        "uruguayan eu trade", "uruguay us trade",
        "uruguayan tariffs", "uruguayan fiscal",
        "uruguayan pension fund", "afap uruguay",
        "uruguayan industry", "uruguayan startup",
        "uruguayan fintech", "uruguayan real estate",
        "uruguayan construction", "uruguayan remittances",
        "uruguayan free trade zone",
        "uruguay crypto regulation",
        "mercadopago uruguay",
    ],
    "geopolitics": [
        "uruguayan foreign policy", "uruguay nato",
        "uruguayan sanctions", "uruguayan diplomacy",
        "uruguayan troops", "uruguay ukraine",
        "uruguay russia", "uruguayan ambassador",
        "uruguay eu", "uruguayan defense",
        "uruguayan military", "montevideo talks",
        "uruguay security", "uruguayan intelligence",
        "uruguay us relations", "uruguay argentina",
        "uruguay brazil", "uruguay mercosur",
        "uruguay pacific alliance",
        "uruguayan peacekeeping", "uruguay un",
        "uruguay brics", "uruguay g20",
        "orsi foreign policy",
        "uruguay china relations",
        "uruguay us base",
    ],
    "energy": [
        "uruguayan energy", "uruguayan electricity",
        "uruguayan renewables", "uruguayan solar",
        "uruguayan wind", "uruguayan hydro",
        "uruguayan grid", "uruguayan climate",
        "uruguayan emissions", "uruguayan energy transition",
        "uruguayan hydrogen", "uruguayan lng",
        "uruguayan energy prices", "uruguayan energy security",
        "uruguayan green energy", "uruguayan carbon neutral",
        "uruguayan net zero", "uruguayan fuel prices",
        "ute energy uruguay", "uruguayan offshore wind",
        "uruguayan green hydrogen",
        "uruguay renewable leader",
        "uruguayan energy exports",
    ],
    "technology": [
        "uruguayan tech", "montevideo tech",
        "uruguayan startup", "uruguayan ai",
        "uruguayan fintech", "uruguayan digital",
        "uruguayan innovation", "uruguayan unicorn",
        "uruguayan cybersecurity", "uruguayan gaming",
        "uruguayan software", "uruguayan it sector",
        "uruguayan ecommerce", "uruguayan digital economy",
        "uruguayan semiconductor", "uruguayan ev",
        "uruguayan smart city", "uruguayan medtech",
        "uruguayan biotech", "uruguayan quantum",
        "uruguayan space", "uruguayan 5g",
        "uruguayan blockchain",
        "pedidos ya uruguay",
        "uruguayan crypto hub",
        "plan ceibal uruguay",
    ],
    "health": [
        "uruguayan health", "uruguayan hospital",
        "uruguayan pharma", "uruguayan vaccine",
        "uruguayan healthcare", "uruguayan mental health",
        "uruguayan health system", "uruguayan medicine",
        "uruguayan public health", "uruguayan wellbeing",
        "uruguayan biotech", "uruguayan cancer",
        "uruguayan aging population", "uruguayan birthrate",
        "msp uruguay", "uruguayan drug approval",
        "uruguayan cannabis regulation",
        "uruguayan health reform",
        "uruguayan universal healthcare",
    ],
    "crime": [
        "uruguayan corruption", "uruguayan fraud",
        "uruguayan scandal", "uruguayan court",
        "uruguayan investigation", "uruguayan organized crime",
        "uruguayan drug trafficking", "uruguayan money laundering",
        "uruguayan terrorism", "uruguayan police",
        "uruguayan gang", "uruguayan anti corruption",
        "uruguayan cybercrime", "uruguayan scam",
        "uruguayan arrest", "uruguayan mafia",
        "uruguayan human trafficking",
        "uruguayan protest", "uruguayan riot",
        "uruguayan political scandal",
        "uruguayan femicide",
        "uruguayan organized crime growth",
    ],
    "politics": [
        "asamblea general uruguay", "camara representantes",
        "uruguayan parliament", "uruguayan election",
        "uruguayan government", "uruguayan minister",
        "uruguayan president", "uruguayan coalition",
        "uruguayan opposition", "frente amplio",
        "yamandu orsi", "orsi uruguay",
        "partido nacional uruguay", "partido colorado",
        "uruguayan policy", "uruguayan reform",
        "uruguayan immigration", "uruguayan diaspora",
        "uruguayan welfare", "uruguayan citizenship",
        "uruguayan referendum", "uruguayan judiciary",
        "uruguayan rule of law", "uruguayan eu relations",
        "uruguayan democracy", "uruguayan media freedom",
        "uruguayan press freedom", "uruguayan constitution",
        "uruguayan federalism", "uruguayan regions",
        "uruguayan cannabis law",
        "uruguayan social model",
        "uruguayan welfare state",
    ],
}

