
# mood/pipeline/keywords/uz.py
UZ_KEYWORDS = {
    "finance": [
        "uzbekistan economy", "uzbekistan gdp",
        "tashkent stock exchange", "uzse",
        "central bank uzbekistan", "cbu",
        "uzbekistani som", "uzs",
        "uzbekistan inflation", "uzbekistan budget",
        "uzbekistan exports", "uzbekistan trade",
        "uzbekistan market", "uzbekistan growth",
        "uzbekistan debt", "uzbekistan deficit",
        "uzbekistan unemployment", "uzbekistan wages",
        "uzbekistan housing", "uzbekistan mortgage",
        "uzbekistan gold", "uzbekistan cotton",
        "uzbekistan gas", "uzbekistan uranium",
        "uzbekistan copper", "uzbekistan minerals",
        "ipak yuli bank", "kapitalbank uzbekistan",
        "uzbekistan business", "uzbekistan investment",
        "uzbekistan tourism", "uzbekistan manufacturing",
        "uzbekistan agriculture", "uzbekistan fruit",
        "uzbekistan eu funds", "uzbekistan industry",
        "uzbekistan startup", "uzbekistan fintech",
        "uzbekistan belt road", "uzbekistan logistics",
        "uzbekistan remittances", "uzbekistan diaspora",
        "uzbekistan trade deficit",
    ],
    "geopolitics": [
        "uzbekistan foreign policy", "uzbekistan nato",
        "uzbekistan sanctions", "uzbekistan diplomacy",
        "uzbekistan troops", "uzbekistan ukraine",
        "uzbekistan russia", "uzbekistan ambassador",
        "uzbekistan eu", "uzbekistan defense",
        "uzbekistan military", "tashkent talks",
        "uzbekistan security", "uzbekistan intelligence",
        "uzbekistan china", "uzbekistan us relations",
        "uzbekistan csto", "uzbekistan sco",
        "uzbekistan central asia", "uzbekistan afghanistan",
        "uzbekistan peacekeeping", "uzbekistan un",
        "uzbekistan tajikistan border",
        "uzbekistan kyrgyzstan border",
    ],
    "energy": [
        "uzbekistan energy", "uzbekistan gas",
        "uzbekistan electricity", "uzbekistan renewables",
        "uzbekistan solar", "uzbekistan wind",
        "uzbekistan hydro", "uzbekistan grid",
        "uzbekistan climate", "uzbekistan emissions",
        "uzbekistan energy transition", "uzbekistan hydrogen",
        "uzbekistan energy prices", "uzbekistan energy security",
        "uzbekistan nuclear", "uzbekistan uranium",
        "uzbekistan pipeline", "uzbekistan carbon neutral",
        "uzbekistan net zero", "uzbekistan fuel prices",
        "uzbekenergo", "uzbekistan power plants",
    ],
    "technology": [
        "uzbekistan tech", "tashkent tech",
        "uzbekistan startup", "uzbekistan ai",
        "uzbekistan fintech", "uzbekistan digital",
        "uzbekistan innovation", "uzbekistan cybersecurity",
        "uzbekistan software", "uzbekistan it sector",
        "uzbekistan ecommerce", "uzbekistan digital economy",
        "uzbekistan blockchain", "uzbekistan smart city",
        "uzbekistan 5g", "uzbekistan medtech",
        "uzbekistan digital transformation",
        "uzcard uzbekistan", "click uzbekistan",
    ],
    "health": [
        "uzbekistan health", "uzbekistan hospital",
        "uzbekistan pharma", "uzbekistan vaccine",
        "uzbekistan healthcare", "uzbekistan mental health",
        "uzbekistan health system", "uzbekistan medicine",
        "uzbekistan public health", "uzbekistan wellbeing",
        "uzbekistan biotech", "uzbekistan cancer",
        "uzbekistan tuberculosis", "uzbekistan malaria",
        "uzbekistan aging population",
        "uzbekistan traditional medicine",
    ],
    "crime": [
        "uzbekistan corruption", "uzbekistan fraud",
        "uzbekistan scandal", "uzbekistan court",
        "uzbekistan investigation", "uzbekistan organized crime",
        "uzbekistan drug trafficking", "uzbekistan money laundering",
        "uzbekistan terrorism", "uzbekistan police",
        "uzbekistan gang", "uzbekistan anti corruption",
        "uzbekistan cybercrime", "uzbekistan scam",
        "uzbekistan arrest", "uzbekistan human trafficking",
        "uzbekistan protest", "uzbekistan riot",
        "uzbekistan political prisoner",
        "uzbekistan dissident",
    ],
    "politics": [
        "oliy majlis", "uzbekistan parliament",
        "uzbekistan election", "uzbekistan government",
        "uzbekistan minister", "uzbekistan president",
        "liberal democratic party uzbekistan",
        "shavkat mirziyoyev", "mirziyoyev",
        "uzbekistan policy", "uzbekistan reform",
        "uzbekistan immigration", "uzbekistan diaspora",
        "uzbekistan welfare", "uzbekistan citizenship",
        "uzbekistan referendum", "uzbekistan judiciary",
        "uzbekistan rule of law", "uzbekistan eu relations",
        "uzbekistan democracy", "uzbekistan media freedom",
        "uzbekistan press freedom", "uzbekistan constitution",
        "uzbekistan modernization",
        "trade deficit uzbekistan",
    ],
}
