
# mood/pipeline/keywords/ve.py
VE_KEYWORDS = {
    "finance": [
        "venezuelan economy", "venezuela gdp",
        "caracas stock exchange", "bvc venezuela",
        "central bank venezuela", "bcv",
        "venezuelan bolivar", "ves",
        "venezuelan inflation", "venezuelan hyperinflation",
        "venezuelan budget", "venezuelan exports",
        "venezuelan trade", "venezuelan market",
        "venezuelan growth", "venezuelan debt",
        "venezuelan deficit", "venezuelan unemployment",
        "venezuelan wages", "venezuelan housing",
        "venezuelan economic collapse",
        "venezuelan currency crisis",
        "pdvsa", "venezuelan oil company",
        "venezuelan oil revenue",
        "venezuelan sanctions economy",
        "venezuelan frozen assets",
        "venezuelan remittances", "venezuelan diaspora",
        "venezuelan reconstruction",
        "venezuelan business", "venezuelan investment",
        "venezuela dollarization",
        "venezuela economic recovery",
        "chevron venezuela", "venezuela oil exports",
    ],
    "geopolitics": [
        "venezuelan foreign policy", "venezuela nato",
        "venezuelan sanctions", "venezuelan diplomacy",
        "venezuelan troops", "venezuela ukraine",
        "venezuela russia", "venezuelan ambassador",
        "venezuela eu", "venezuelan defense",
        "venezuelan military", "caracas talks",
        "venezuela security", "venezuelan intelligence",
        "sebin venezuela", "venezuela us relations",
        "venezuela colombia", "venezuela brazil",
        "venezuela guyana", "essequibo dispute",
        "venezuela cuba", "venezuela iran",
        "venezuela china relations", "venezuela russia ally",
        "venezuela peacekeeping", "venezuela un",
        "venezuela brics", "maduro foreign policy",
        "delcy rodriguez foreign",
        "venezuela migration crisis",
        "venezuela opposition exile",
    ],
    "energy": [
        "venezuelan energy", "venezuelan oil", "pdvsa",
        "venezuelan gas", "venezuelan electricity",
        "venezuelan renewables", "venezuelan grid",
        "venezuelan climate", "venezuelan emissions",
        "venezuelan energy crisis", "venezuelan blackout",
        "venezuelan fuel shortage", "venezuelan energy prices",
        "venezuelan energy security",
        "venezuelan oil production collapse",
        "venezuelan oil sanctions",
        "chevron venezuela oil",
        "venezuelan refinery", "venezuelan petrochemical",
        "orinoco belt venezuela",
    ],
    "technology": [
        "venezuelan tech", "caracas tech",
        "venezuelan startup", "venezuelan ai",
        "venezuelan fintech", "venezuelan digital",
        "venezuelan innovation", "venezuelan cybersecurity",
        "venezuelan software", "venezuelan it sector",
        "venezuelan ecommerce", "venezuelan digital economy",
        "venezuelan internet censorship",
        "venezuelan vpn usage",
        "venezuelan mobile banking",
        "venezuelan blockchain",
        "venezuelan cryptocurrency",
        "petro cryptocurrency venezuela",
    ],
    "health": [
        "venezuelan health", "venezuelan hospital",
        "venezuelan pharma", "venezuelan vaccine",
        "venezuelan healthcare", "venezuelan mental health",
        "venezuelan health system", "venezuelan medicine",
        "venezuelan public health", "venezuelan wellbeing",
        "venezuelan health crisis", "venezuelan medicine shortage",
        "venezuelan malaria", "venezuelan malnutrition",
        "venezuelan dengue", "venezuelan disease outbreak",
        "venezuelan medical aid", "who venezuela",
        "venezuelan child health",
        "venezuelan humanitarian health",
    ],
    "crime": [
        "venezuelan corruption", "venezuelan fraud",
        "venezuelan scandal", "venezuelan court",
        "venezuelan investigation", "venezuelan organized crime",
        "venezuelan drug trafficking", "venezuelan money laundering",
        "venezuelan terrorism", "venezuelan police",
        "venezuelan gang", "tren de aragua",
        "venezuelan anti corruption",
        "venezuelan cybercrime", "venezuelan scam",
        "venezuelan arrest", "venezuelan mafia",
        "venezuelan human trafficking",
        "venezuelan protest", "venezuelan riot",
        "venezuelan political prisoner",
        "venezuelan opposition arrested",
        "venezuelan dissident",
        "maduro corruption",
        "venezuelan election fraud",
    ],
    "politics": [
        "asamblea nacional venezuela",
        "venezuelan parliament", "venezuelan election",
        "venezuelan government", "venezuelan minister",
        "venezuelan president", "venezuelan coalition",
        "venezuelan opposition", "psuv venezuela",
        "nicolas maduro", "maduro",
        "edmundo gonzalez", "maria corina machado",
        "voluntad popular venezuela",
        "venezuelan policy", "venezuelan reform",
        "venezuelan immigration", "venezuelan refugees",
        "venezuelan welfare", "venezuelan citizenship",
        "venezuelan referendum", "venezuelan judiciary",
        "venezuelan rule of law", "venezuelan eu relations",
        "venezuelan democracy", "venezuelan authoritarianism",
        "venezuelan media freedom", "venezuelan press freedom",
        "venezuelan constitution", "venezuelan chavismo",
        "venezuelan nostalgia",
        "venezuelan election fraud 2024",
        "venezuela opposition crackdown",
    ],
}