
# mood/pipeline/keywords/vn.py
VN_KEYWORDS = {
    "finance": [
        "vietnamese economy", "vietnam gdp", "vn index",
        "ho chi minh stock exchange", "hsx vietnam",
        "state bank vietnam", "sbv vietnam",
        "vietnamese dong", "vnd",
        "vietnamese inflation", "vietnamese budget",
        "vietnamese exports", "vietnamese trade",
        "vietnamese market", "vietnamese growth",
        "vietnamese debt", "vietnamese deficit",
        "vietnamese unemployment", "vietnamese wages",
        "vietnamese housing", "vietnamese mortgage",
        "vingroup", "vietcombank", "vietinbank",
        "bidv vietnam", "techcombank",
        "vinfast", "vinhomes", "masan group",
        "vietnamese business", "vietnamese investment",
        "vietnamese tourism", "vietnamese manufacturing",
        "vietnamese automotive", "vietnamese agriculture",
        "vietnamese rice exports", "vietnamese coffee",
        "vietnamese seafood", "vietnamese textiles",
        "vietnamese eu funds", "vietnamese recovery plan",
        "vietnamese pension fund", "vietnamese industry",
        "vietnamese it sector", "vietnamese startup",
        "vietnamese real estate", "vietnamese construction",
        "vietnam us trade", "vietnamese tariffs",
        "vietnamese trade deal", "vietnamese fiscal",
        "vietnamese fdi", "vietnamese remittances",
    ],
    "geopolitics": [
        "vietnamese foreign policy", "vietnam nato",
        "vietnamese sanctions", "vietnamese diplomacy",
        "vietnamese troops", "vietnam ukraine",
        "vietnam russia", "vietnamese ambassador",
        "vietnam eu", "vietnamese defense",
        "vietnamese military", "hanoi talks",
        "vietnam security", "vietnamese intelligence",
        "vietnam china relations", "south china sea vietnam",
        "vietnam us relations", "vietnam asean",
        "vietnam japan relations", "vietnam india",
        "vietnam cambodia", "vietnam laos",
        "vietnamese peacekeeping", "vietnam un",
        "vietnam middle east", "vietnam gulf",
        "vietnam spratly islands", "vietnam paracel islands",
        "vietnam maritime dispute",
    ],
    "energy": [
        "vietnamese energy", "vietnamese electricity",
        "vietnamese renewables", "vietnamese solar",
        "vietnamese wind", "vietnamese hydro",
        "vietnamese grid", "vietnamese climate",
        "vietnamese emissions", "vietnamese energy transition",
        "vietnamese hydrogen", "vietnamese lng",
        "vietnamese energy prices", "vietnamese energy security",
        "vietnamese green energy", "vietnamese coal",
        "vietnamese natural gas", "vietnamese oil",
        "vietnamese carbon neutral", "vietnamese net zero",
        "vietnamese fuel prices", "petrovietnam",
        "evn vietnam", "vietnamese offshore wind",
    ],
    "technology": [
        "vietnamese tech", "hanoi tech", "vietnamese startup",
        "vietnamese ai", "vietnamese fintech",
        "vietnamese digital", "vietnamese innovation",
        "vietnamese unicorn", "vietnamese cybersecurity",
        "vietnamese gaming", "vietnamese software",
        "vietnamese it sector", "vietnamese outsourcing",
        "vietnamese ecommerce", "vietnamese digital economy",
        "vietnamese semiconductor", "vietnamese ev",
        "vinfast ev", "vietnamese smart city",
        "vietnamese medtech", "vietnamese blockchain",
        "momo vietnam", "zalo vietnam",
        "vng corporation", "vietnamese quantum",
    ],
    "health": [
        "vietnamese health", "vietnamese hospital",
        "vietnamese pharma", "vietnamese vaccine",
        "vietnamese healthcare", "vietnamese mental health",
        "vietnamese health system", "vietnamese medicine",
        "vietnamese public health", "vietnamese wellbeing",
        "vietnamese medical tourism", "vietnamese biotech",
        "vietnamese cancer", "vietnamese dengue",
        "vietnamese malaria", "moh vietnam",
        "vietnamese aging population",
        "vietnamese traditional medicine",
    ],
    "crime": [
        "vietnamese corruption", "vietnamese fraud",
        "vietnamese scandal", "vietnamese court",
        "vietnamese investigation", "vietnamese organized crime",
        "vietnamese drug trafficking", "vietnamese money laundering",
        "vietnamese terrorism", "vietnamese police",
        "công an vietnam", "vietnamese gang",
        "vietnamese anti corruption",
        "vietnamese cybercrime", "vietnamese scam",
        "vietnamese arrest", "vietnamese mafia",
        "vietnamese human trafficking",
        "vietnamese protest", "vietnamese riot",
        "vietnamese political prisoner",
        "vietnamese dissident",
    ],
    "politics": [
        "national assembly vietnam", "vietnamese parliament",
        "vietnamese election", "vietnamese government",
        "vietnamese minister", "vietnamese prime minister",
        "vietnamese coalition", "vietnamese opposition",
        "communist party vietnam", "cpv vietnam",
        "to lam", "nguyen phu trong",
        "vietnamese politburo", "vietnamese policy",
        "vietnamese reform", "doi moi vietnam",
        "vietnamese immigration", "vietnamese diaspora",
        "vietnamese welfare", "vietnamese citizenship",
        "vietnamese referendum", "vietnamese judiciary",
        "vietnamese rule of law", "vietnamese eu relations",
        "vietnamese democracy", "vietnamese president",
        "vietnamese media freedom", "vietnamese press freedom",
        "vietnamese constitution", "vietnamese censorship",
        "vietnamese internet freedom",
    ],
}