
# mood/pipeline/keywords/ye.py
YE_KEYWORDS = {
    "finance": [
        "yemen economy", "yemen gdp",
        "central bank yemen", "cby",
        "yemeni rial", "yer",
        "yemen inflation", "yemen budget",
        "yemen exports", "yemen trade",
        "yemen market", "yemen growth",
        "yemen debt", "yemen deficit",
        "yemen unemployment", "yemen wages",
        "yemen housing", "yemen reconstruction",
        "yemen aid", "yemen imf",
        "yemen world bank", "yemen bonds",
        "yemen agriculture", "yemen fishing",
        "yemen oil revenue", "yemen gas revenue",
        "yemen economic collapse",
        "yemen currency crisis",
        "yemen remittances", "yemen diaspora",
        "yemen reconstruction fund",
        "yemen business", "yemen investment",
        "yemeni rial collapse",
        "yemen trade routes",
        "yemen port hodeidah",
        "yemen port aden",
    ],
    "geopolitics": [
        "yemen foreign policy", "yemen nato",
        "yemen sanctions", "yemen diplomacy",
        "yemen troops", "yemen ukraine",
        "yemen russia", "yemen ambassador",
        "yemen eu", "yemen defense",
        "yemen military", "sanaa talks",
        "yemen security", "yemen intelligence",
        "yemen us relations", "yemen us strikes",
        "yemen iran relations", "yemen houthis",
        "houthi rebels", "ansarallah",
        "houthi attacks", "houthi missiles",
        "houthi drones", "houthi red sea",
        "red sea attacks", "houthi shipping",
        "houthi israel", "houthi gulf",
        "yemen saudi war", "saudi coalition yemen",
        "yemen civil war", "yemen conflict",
        "yemen peace talks", "yemen ceasefire",
        "yemen gcc", "yemen qatar",
        "yemen peacekeeping", "yemen un",
        "yemen china relations", "yemen india",
        "strait hormuz yemen",
        "bab el mandeb strait",
        "yemen us military strikes",
    ],
    "energy": [
        "yemen energy", "yemen oil", "yemen gas",
        "yemen electricity", "yemen renewables",
        "yemen solar", "yemen grid",
        "yemen climate", "yemen emissions",
        "yemen energy crisis", "yemen fuel shortage",
        "yemen energy prices", "yemen energy security",
        "yemen oil fields", "yemen oil production",
        "yemen lng", "yemen refinery",
        "yemen power outage", "yemen blackout",
        "yemen energy infrastructure",
        "marib dam yemen",
    ],
    "technology": [
        "yemen tech", "sanaa tech", "yemen startup",
        "yemen ai", "yemen fintech",
        "yemen digital", "yemen innovation",
        "yemen cybersecurity", "yemen software",
        "yemen it sector", "yemen internet",
        "yemen mobile banking", "yemen connectivity",
        "yemen digital economy",
        "yemen telecom", "yemen mobile network",
    ],
    "health": [
        "yemen health", "yemen hospital",
        "yemen pharma", "yemen vaccine",
        "yemen healthcare", "yemen mental health",
        "yemen health system", "yemen medicine",
        "yemen public health", "yemen wellbeing",
        "yemen cholera", "yemen malaria",
        "yemen famine", "yemen starvation",
        "yemen humanitarian crisis",
        "yemen war wounded", "yemen casualties",
        "yemen medical aid", "who yemen",
        "yemen child malnutrition",
        "yemen health collapse",
        "yemen disease outbreak",
    ],
    "crime": [
        "yemen corruption", "yemen fraud",
        "yemen scandal", "yemen court",
        "yemen investigation", "yemen organized crime",
        "yemen drug trafficking", "yemen money laundering",
        "yemen terrorism", "yemen police",
        "yemen gang", "yemen anti corruption",
        "yemen cybercrime", "yemen scam",
        "yemen arrest", "yemen human trafficking",
        "yemen war crimes", "houthi war crimes",
        "yemen atrocities", "saudi coalition war crimes",
        "yemen political prisoner",
        "yemen kidnapping",
        "yemen smuggling",
    ],
    "politics": [
        "yemen parliament", "yemen election",
        "yemen government", "yemen minister",
        "yemen prime minister", "yemen president",
        "yemen coalition", "yemen opposition",
        "rashad al alimi", "yemen presidential council",
        "houthi government", "sanaa government",
        "aden government", "yemen internationally recognized",
        "yemen policy", "yemen reform",
        "yemen immigration", "yemen refugees",
        "yemen welfare", "yemen citizenship",
        "yemen judiciary", "yemen rule of law",
        "yemen democracy", "yemen media freedom",
        "yemen press freedom", "yemen constitution",
        "yemen human rights", "yemen tribal",
        "yemen southern separatists", "sct yemen",
        "yemen peace process",
        "un envoy yemen",
        "stockholm agreement yemen",
        "yemen transitional government",
    ],
}

