
# mood/pipeline/keywords/za.py
ZA_KEYWORDS = {
    "finance": [
        "south african economy", "south africa gdp",
        "johannesburg stock exchange", "jse",
        "south african reserve bank", "sarb",
        "south african rand", "zar",
        "south african inflation", "south african budget",
        "south african exports", "south african trade",
        "south african market", "south african growth",
        "south african debt", "south african deficit",
        "south african unemployment", "south african wages",
        "south african housing", "south african mortgage",
        "standard bank sa", "absa bank",
        "firstrand bank", "nedbank", "capitec",
        "anglo american", "bhp billiton sa",
        "sasol", "shoprite", "pick n pay",
        "naspers", "prosus", "vodacom",
        "mtn south africa", "discovery sa",
        "south african business", "south african investment",
        "south african tourism", "south african manufacturing",
        "south african mining", "south african gold",
        "south african platinum", "south african diamonds",
        "south african agriculture", "south african wine",
        "south african eu trade", "south africa us trade",
        "south african tariffs", "south african fiscal",
        "south african pension fund", "gepf south africa",
        "south african industry", "south african startup",
        "south african fintech", "south african real estate",
        "south african construction", "south african logistics",
        "south african eskom", "south african loadshedding",
        "south african power crisis",
    ],
    "geopolitics": [
        "south african foreign policy", "south africa nato",
        "south african sanctions", "south african diplomacy",
        "south african troops", "south africa ukraine",
        "south africa russia", "south african ambassador",
        "south africa eu", "south african defense",
        "south african military", "sandf",
        "pretoria talks", "south africa security",
        "south african intelligence", "ssa south africa",
        "south africa us relations", "south africa china",
        "south africa brics", "south africa g20",
        "south africa africa union", "south africa sadc",
        "south africa peacekeeping", "south africa un",
        "south africa israel icj",
        "south africa russia relations",
        "ramaphosa foreign policy",
        "south africa middle east",
        "south africa drc conflict",
        "sandf deployment",
    ],
    "energy": [
        "south african energy", "eskom",
        "south african electricity", "south african renewables",
        "south african solar", "south african wind",
        "south african grid", "south african climate",
        "south african emissions", "south african energy transition",
        "south african hydrogen", "south african lng",
        "south african energy prices", "south african energy security",
        "south african green energy", "south african carbon neutral",
        "south african net zero", "south african fuel prices",
        "south african coal", "south african nuclear",
        "koeberg nuclear", "south african loadshedding",
        "south african power outage",
        "south african just energy transition",
        "south african renewable energy",
        "reippp south africa",
    ],
    "technology": [
        "south african tech", "cape town tech",
        "south african startup", "south african ai",
        "south african fintech", "south african digital",
        "south african innovation", "south african unicorn",
        "south african cybersecurity", "south african gaming",
        "south african software", "south african it sector",
        "south african ecommerce", "south african digital economy",
        "south african semiconductor", "south african ev",
        "south african smart city", "south african medtech",
        "south african biotech", "south african quantum",
        "south african space", "sansa south africa",
        "south african 5g", "south african blockchain",
        "naspers tech", "takealot south africa",
    ],
    "health": [
        "south african health", "south african hospital",
        "south african pharma", "south african vaccine",
        "south african healthcare", "south african mental health",
        "south african health system", "south african medicine",
        "south african public health", "south african wellbeing",
        "south african biotech", "south african cancer",
        "south african aging population",
        "south african hiv", "south african aids",
        "south african tuberculosis", "south african malaria",
        "south african national health insurance", "nhi south africa",
        "south african health reform",
        "groote schuur hospital",
    ],
    "crime": [
        "south african corruption", "south african fraud",
        "south african scandal", "south african court",
        "south african investigation", "south african organized crime",
        "south african drug trafficking", "south african money laundering",
        "south african terrorism", "south african police", "saps",
        "south african gang", "south african anti corruption",
        "south african cybercrime", "south african scam",
        "south african arrest", "south african mafia",
        "south african human trafficking",
        "south african protest", "south african riot",
        "south african political scandal",
        "zuma corruption", "gupta corruption",
        "south african state capture",
        "south african femicide",
        "south african farm murders",
        "south african gang violence",
        "cape town gangs",
    ],
    "politics": [
        "national assembly south africa",
        "south african parliament", "south african election",
        "south african government", "south african minister",
        "south african president", "south african coalition",
        "south african opposition", "anc south africa",
        "cyril ramaphosa", "ramaphosa",
        "da south africa", "john steenhuisen",
        "eff south africa", "julius malema",
        "mk party", "jacob zuma",
        "south african policy", "south african reform",
        "south african immigration", "south african diaspora",
        "south african welfare", "south african citizenship",
        "south african referendum", "south african judiciary",
        "south african rule of law", "south african eu relations",
        "south african democracy", "south african media freedom",
        "south african press freedom", "south african constitution",
        "south african federalism", "south african provinces",
        "south african land reform",
        "south african government of national unity",
        "south african gnu",
        "sandf saps joint operation",
    ],
}