
# mood/pipeline/keywords/zm.py
ZM_KEYWORDS = {
    "finance": [
        "zambian economy", "zambia gdp",
        "lusaka stock exchange", "luse zambia",
        "bank of zambia", "boz",
        "zambian kwacha", "zmw",
        "zambian inflation", "zambian budget",
        "zambian exports", "zambian trade",
        "zambian market", "zambian growth",
        "zambian debt", "zambian deficit",
        "zambian unemployment", "zambian wages",
        "zambian housing", "zambian mortgage",
        "zanaco bank", "first national bank zambia",
        "stanbic zambia", "absa zambia",
        "zambian copper", "first quantum minerals",
        "glencore zambia", "konkola copper",
        "zambian cobalt", "zambian emerald",
        "zambian business", "zambian investment",
        "zambian tourism", "zambian manufacturing",
        "zambian agriculture", "zambian maize",
        "zambian tobacco", "zambian cotton",
        "zambian eu trade", "zambia us trade",
        "zambian tariffs", "zambian fiscal",
        "zambian pension fund", "napsa zambia",
        "zambian industry", "zambian startup",
        "zambian fintech", "zambian real estate",
        "zambian construction", "zambian remittances",
        "zambian diaspora", "zambia imf deal",
        "hichilema economic policy",
        "zambian debt restructuring",
        "zesco zambia energy",
        "ppp zambia pensions",
        "public pension zambia",
    ],
    "geopolitics": [
        "zambian foreign policy", "zambia nato",
        "zambian sanctions", "zambian diplomacy",
        "zambian troops", "zambia ukraine",
        "zambia russia", "zambian ambassador",
        "zambia eu", "zambian defense",
        "zambian military", "lusaka talks",
        "zambia security", "zambian intelligence",
        "zambia us relations", "zambia china",
        "zambia brics", "zambia africa union",
        "zambia sadc", "zambia peacekeeping",
        "zambia un", "zambia drc",
        "zambia zimbabwe", "zambia mozambique",
        "zambia tanzania", "zambia malawi",
        "zambia angola", "zambia namibia",
        "hichilema foreign policy",
        "zambia east africa community",
        "zambia copper belt geopolitics",
    ],
    "energy": [
        "zambian energy", "zambian electricity",
        "zambian renewables", "zambian solar",
        "zambian wind", "zambian hydro",
        "zambian grid", "zambian climate",
        "zambian emissions", "zambian energy transition",
        "zambian hydrogen", "zambian energy prices",
        "zambian energy security", "zambian green energy",
        "zambian carbon neutral", "zambian net zero",
        "zambian fuel prices", "zambian coal",
        "zesco zambia", "zambian hydroelectric",
        "kariba dam zambia",
        "zambian energy crisis",
        "zambian power outage",
        "zambian solar project",
        "ceo zesco separate ways",
    ],
    "technology": [
        "zambian tech", "lusaka tech", "zambian startup",
        "zambian ai", "zambian fintech",
        "zambian digital", "zambian innovation",
        "zambian cybersecurity", "zambian software",
        "zambian it sector", "zambian ecommerce",
        "zambian digital economy", "zambian 5g",
        "zambian blockchain", "zambian smart city",
        "zambian medtech", "zambian digital transformation",
        "mtn zambia", "airtel zambia",
        "zambian mobile money",
        "zambian tech hub",
        "zambian silicon valley",
    ],
    "health": [
        "zambian health", "zambian hospital",
        "zambian pharma", "zambian vaccine",
        "zambian healthcare", "zambian mental health",
        "zambian health system", "zambian medicine",
        "zambian public health", "zambian wellbeing",
        "zambian malaria", "zambian tuberculosis",
        "zambian hiv", "zambian cholera",
        "zambian health reform",
        "zambian universal health",
        "university teaching hospital zambia",
        "zambian maternal health",
        "zambia medicines board",
    ],
    "crime": [
        "zambian corruption", "zambian fraud",
        "zambian scandal", "zambian court",
        "zambian investigation", "zambian organized crime",
        "zambian drug trafficking", "zambian money laundering",
        "zambian terrorism", "zambian police",
        "zambian gang", "zambian anti corruption",
        "acc zambia", "zambian cybercrime",
        "zambian scam", "zambian arrest",
        "zambian human trafficking",
        "zambian protest", "zambian riot",
        "zambian political scandal",
        "zambian election violence",
        "zambian femicide",
        "looting public pensions zambia",
    ],
    "politics": [
        "national assembly zambia", "zambian parliament",
        "zambian election", "zambian government",
        "zambian minister", "zambian president",
        "zambian coalition", "zambian opposition",
        "upnd zambia", "hakainde hichilema",
        "hichilema zambia", "pf zambia",
        "edgar lungu", "zambian policy",
        "zambian reform", "zambian immigration",
        "zambian diaspora", "zambian welfare",
        "zambian citizenship", "zambian referendum",
        "zambian judiciary", "zambian rule of law",
        "zambian eu relations", "zambian democracy",
        "zambian media freedom", "zambian press freedom",
        "zambian constitution", "zambian federalism",
        "zambian provinces", "zambian devolution",
        "zambian political stability",
        "zambian copper belt politics",
    ],
}