
# mood/pipeline/keywords/zw.py
ZW_KEYWORDS = {
    "finance": [
        "zimbabwean economy", "zimbabwe gdp",
        "zimbabwe stock exchange", "zse",
        "reserve bank zimbabwe", "rbz",
        "zimbabwean dollar", "zig",
        "zimbabwean inflation", "zimbabwean budget",
        "zimbabwean exports", "zimbabwean trade",
        "zimbabwean market", "zimbabwean growth",
        "zimbabwean debt", "zimbabwean deficit",
        "zimbabwean unemployment", "zimbabwean wages",
        "zimbabwean housing", "zimbabwean mortgage",
        "cbs bank zimbabwe", "cbz bank",
        "stanbic zimbabwe", "steward bank",
        "zimbabwean gold", "zimbabwean platinum",
        "zimbabwean diamonds", "marange diamonds",
        "zimbabwean tobacco", "zimbabwean chrome",
        "zimbabwean coal", "zimbabwean lithium",
        "zimbabwean business", "zimbabwean investment",
        "zimbabwean tourism", "zimbabwean manufacturing",
        "zimbabwean agriculture", "zimbabwean maize",
        "zimbabwean eu trade", "zimbabwe us trade",
        "zimbabwean tariffs", "zimbabwean fiscal",
        "zimbabwean pension fund", "zimbabwean industry",
        "zimbabwean startup", "zimbabwean fintech",
        "zimbabwean real estate", "zimbabwean construction",
        "zimbabwean remittances", "zimbabwean diaspora",
        "zimbabwe imf", "mnangagwa economic policy",
        "zimbabwean currency crisis",
        "zimbabwean hyperinflation legacy",
        "zimbabwean dollarization",
    ],
    "geopolitics": [
        "zimbabwean foreign policy", "zimbabwe nato",
        "zimbabwean sanctions", "zimbabwean diplomacy",
        "zimbabwean troops", "zimbabwe ukraine",
        "zimbabwe russia", "zimbabwean ambassador",
        "zimbabwe eu", "zimbabwean defense",
        "zimbabwean military", "harare talks",
        "zimbabwe security", "zimbabwean intelligence",
        "css zimbabwe", "zimbabwe us relations",
        "zimbabwe china", "zimbabwe brics",
        "zimbabwe africa union", "zimbabwe sadc",
        "zimbabwe peacekeeping", "zimbabwe un",
        "zimbabwe south africa", "zimbabwe zambia",
        "zimbabwe mozambique", "zimbabwe botswana",
        "zimbabwe namibia", "zimbabwe malawi",
        "mnangagwa foreign policy",
        "zimbabwe eu sanctions",
        "zimbabwe us sanctions",
        "zimbabwe land reform legacy",
        "zimbabwe white farmers",
    ],
    "energy": [
        "zimbabwean energy", "zimbabwean electricity",
        "zimbabwean renewables", "zimbabwean solar",
        "zimbabwean wind", "zimbabwean hydro",
        "zimbabwean grid", "zimbabwean climate",
        "zimbabwean emissions", "zimbabwean energy transition",
        "zimbabwean hydrogen", "zimbabwean coal",
        "zimbabwean energy prices", "zimbabwean energy security",
        "zimbabwean green energy", "zimbabwean carbon neutral",
        "zimbabwean net zero", "zimbabwean fuel prices",
        "kariba dam zimbabwe", "hwange power station",
        "zesa zimbabwe", "zimbabwean power outage",
        "zimbabwean loadshedding",
        "zimbabwean energy crisis",
        "zimbabwean solar project",
    ],
    "technology": [
        "zimbabwean tech", "harare tech", "zimbabwean startup",
        "zimbabwean ai", "zimbabwean fintech",
        "zimbabwean digital", "zimbabwean innovation",
        "zimbabwean cybersecurity", "zimbabwean software",
        "zimbabwean it sector", "zimbabwean ecommerce",
        "zimbabwean digital economy", "zimbabwean 5g",
        "zimbabwean blockchain", "zimbabwean smart city",
        "zimbabwean medtech", "zimbabwean digital transformation",
        "econet zimbabwe", "netone zimbabwe",
        "zimbabwean mobile money", "ecocash zimbabwe",
        "zimbabwean tech hub",
        "zimbabwean silicon valley",
    ],
    "health": [
        "zimbabwean health", "zimbabwean hospital",
        "zimbabwean pharma", "zimbabwean vaccine",
        "zimbabwean healthcare", "zimbabwean mental health",
        "zimbabwean health system", "zimbabwean medicine",
        "zimbabwean public health", "zimbabwean wellbeing",
        "zimbabwean malaria", "zimbabwean tuberculosis",
        "zimbabwean hiv", "zimbabwean cholera",
        "zimbabwean health reform",
        "zimbabwean universal health",
        "parirenyatwa hospital zimbabwe",
        "zimbabwean maternal health",
        "mcaz zimbabwe",
        "zimbabwean health crisis",
        "zimbabwean doctor shortage",
    ],
    "crime": [
        "zimbabwean corruption", "zimbabwean fraud",
        "zimbabwean scandal", "zimbabwean court",
        "zimbabwean investigation", "zimbabwean organized crime",
        "zimbabwean drug trafficking", "zimbabwean money laundering",
        "zimbabwean terrorism", "zimbabwean police",
        "zimbabwean gang", "zimbabwean anti corruption",
        "zacc zimbabwe", "zimbabwean cybercrime",
        "zimbabwean scam", "zimbabwean arrest",
        "zimbabwean human trafficking",
        "zimbabwean protest", "zimbabwean riot",
        "zimbabwean political scandal",
        "zimbabwean opposition arrested",
        "zimbabwean political prisoner",
        "mnangagwa corruption",
        "zimbabwean election violence",
        "zimbabwean femicide",
        "zimbabwean gold mafia",
    ],
    "politics": [
        "parliament of zimbabwe", "zimbabwean parliament",
        "zimbabwean election", "zimbabwean government",
        "zimbabwean minister", "zimbabwean president",
        "zimbabwean coalition", "zimbabwean opposition",
        "zanu pf", "emmerson mnangagwa", "mnangagwa",
        "mdc zimbabwe", "chamisa zimbabwe",
        "nelson chamisa", "citizens coalition zimbabwe",
        "zimbabwean policy", "zimbabwean reform",
        "zimbabwean immigration", "zimbabwean diaspora",
        "zimbabwean welfare", "zimbabwean citizenship",
        "zimbabwean referendum", "zimbabwean judiciary",
        "zimbabwean rule of law", "zimbabwean eu relations",
        "zimbabwean democracy", "zimbabwean media freedom",
        "zimbabwean press freedom", "zimbabwean constitution",
        "zimbabwean federalism", "zimbabwean provinces",
        "zimbabwean political instability",
        "zimbabwean mugabe legacy",
        "zimbabwean land reform politics",
        "zimbabwean sanctions politics",
    ],
}