# mood/pipeline/api_sources.py
# ============================================================
# RSS Feed Sources — modular, extendable by region
# V1: DE (English feeds) | V2: US, GB, JP, IN | V3: CN, FR, ES
# ============================================================

FEED_SOURCES = [
    # ── V1 — Germany (English language feeds) ───────────────
    {
        "name": "DW Business",
        "url": "https://rss.dw.com/rdf/rss-en-bus",
        "region": "DE",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "DW Germany",
        "url": "https://rss.dw.com/rdf/rss-en-ger",
        "region": "DE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "DW Europe",
        "url": "https://rss.dw.com/rdf/rss-en-eu",
        "region": "DE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Reuters World",
        "url": "https://feeds.reuters.com/reuters/worldNews",
        "region": "DE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Spiegel International",
        "url": "https://www.spiegel.de/international/index.rss",
        "region": "DE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── V1.5 — Switzerland (English language feeds) ─────────
    {
        "name": "SwissInfo Latest",
        "url": "https://cdn.prod.swi-services.ch/rss/eng/rssxml/latest-news/rss",
        "region": "CH",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Local Switzerland",
        "url": "https://feeds.thelocal.com/rss/ch",
        "region": "CH",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Le News Switzerland",
        "url": "https://lenews.ch/feed",
        "region": "CH",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── V2 — Austria (German — needs FinBERT) ───────────────
    {
        "name": "ORF News",
        "url": "https://rss.orf.at/news.xml",
        "region": "AT",
        "language": "DE",
        "category": "general",
        "active": False,
    },
    {
        "name": "Der Standard",
        "url": "https://www.derstandard.at/rss",
        "region": "AT",
        "language": "DE",
        "category": "general",
        "active": False,
    },
    {
        "name": "FinTech News Switzerland",
        "url": "https://fintechnews.ch/feed",
        "region": "CH",
        "language": "EN",
        "category": "finance",
        "active": False,
    },
    # ── V1.5 — Austria (English language feeds) ─────────
    {
        "name": "The Local Austria",
        "url": "https://feeds.thelocal.com/rss/at",
        "region": "AT",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Vienna Times",
        "url": "https://viennatimes.com/feed",
        "region": "AT",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    # ── V1.5 — Western Europe ────────────────────────────
    # BBC ersetzen:
    {
        "name": "Telegraph Business",
        "url": "https://www.telegraph.co.uk/business/rss.xml",
        "region": "GB",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "City AM",
        "url": "https://www.cityam.com/feed/",
        "region": "GB",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "The Guardian",
        "url": "https://www.theguardian.com/uk/business/rss",
        "region": "GB",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "The Local France",
        "url": "https://feeds.thelocal.com/rss/fr",
        "region": "FR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "France24 Business",
        "url": "https://www.france24.com/en/business/rss",
        "region": "FR",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "DutchNews",
        "url": "https://www.dutchnews.nl/feed/",
        "region": "NL",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Local NL",
        "url": "https://feeds.thelocal.com/rss/nl",
        "region": "NL",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Local Belgium",
        "url": "https://feeds.thelocal.com/rss/be",
        "region": "BE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Northern Europe ──────────────────────────────────
    {
        "name": "The Local Sweden",
        "url": "https://feeds.thelocal.com/rss/se",
        "region": "SE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Local Norway",
        "url": "https://feeds.thelocal.com/rss/no",
        "region": "NO",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Local Denmark",
        "url": "https://feeds.thelocal.com/rss/dk",
        "region": "DK",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "CPH Post Denmark",
        "url": "https://cphpost.dk/feed/",
        "region": "DK",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Yle News Finland",
        "url": "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS",
        "region": "FI",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Helsinki Times",
        "url": "https://helsinkitimes.fi/?format=feed",
        "region": "FI",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Iceland Monitor",
        "url": "https://icelandmonitor.mbl.is/rss/",
        "region": "IS",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Eastern Europe ───────────────────────────────────
    {
        "name": "Notes from Poland",
        "url": "https://notesfrompoland.com/feed/",
        "region": "PL",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Prague Daily Monitor",
        "url": "https://www.praguemonitor.com/feed/",
        "region": "CZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Budapest Times",
        "url": "https://budapesttimes.hu/feed/",
        "region": "HU",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Daily News Hungary",
        "url": "https://dailynewshungary.com/feed/",
        "region": "HU",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Hungary Today",
        "url": "https://hungarytoday.hu/feed/",
        "region": "HU",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Romania Insider",
        "url": "https://www.romania-insider.com/feed",
        "region": "RO",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Slovak Spectator",
        "url": "https://spectator.sme.sk/rss/",
        "region": "SK",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Sofia Globe",
        "url": "https://sofiaglobe.com/feed/",
        "region": "BG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Balkans ──────────────────────────────────────────
    {
        "name": "Balkan Insight",
        "url": "https://balkaninsight.com/feed/",
        "region": "RS",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Sarajevo Times",
        "url": "https://sarajevotimes.com/feed/",
        "region": "BA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Meta Macedonia",
        "url": "https://www.meta.mk/en/feed/",
        "region": "MK",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Slovenia Times",
        "url": "https://www.sloveniatimes.com/feed",
        "region": "SI",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Baltic States ─────────────────────────────────────
    {
        "name": "ERR News Estonia",
        "url": "https://news.err.ee/rss",
        "region": "EE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "LSM Latvia",
        "url": "https://eng.lsm.lv/rss/",
        "region": "LV",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Baltic Times",
        "url": "https://www.baltictimes.com/rss/",
        "region": "LT",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Baltic News Today",
        "url": "https://balticnews.com/feed/",
        "region": "LT",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Russia & CIS ─────────────────────────────────────
    {
        "name": "Meduza EN",
        "url": "https://meduza.io/rss/en/all",
        "region": "RU",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Ukraine Pravda",
        "url": "https://www.pravda.com.ua/eng/rss/view_news/",
        "region": "UA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Ukrinform",
        "url": "https://www.ukrinform.net/rss/block-lastnews",
        "region": "UA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Moldova.org",
        "url": "https://www.moldova.org/en/feed/",
        "region": "MD",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Civil Georgia",
        "url": "https://civil.ge/feed",
        "region": "GE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "OC Media",
        "url": "https://oc-media.org/feed/",
        "region": "GE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "JAMnews",
        "url": "https://jam-news.net/feed/",
        "region": "AM",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Southern Europe ───────────────────────────────────
    {
        "name": "The Local Italy",
        "url": "https://feeds.thelocal.com/rss/it",
        "region": "IT",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Local Spain",
        "url": "https://feeds.thelocal.com/rss/es",
        "region": "ES",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Spain In English",
        "url": "https://www.spainenglish.com/feed/",
        "region": "ES",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Portugal News",
        "url": "https://www.theportugalnews.com/rss/",
        "region": "PT",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Portugal Resident",
        "url": "https://www.portugalresident.com/feed/",
        "region": "PT",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Keep Talking Greece",
        "url": "https://www.keeptalkinggreece.com/feed/",
        "region": "GR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Greek City Times",
        "url": "https://greekcitytimes.com/feed/",
        "region": "GR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Japan ────────────────────────────────────────────────
    {
        "name": "Japan Times",
        "url": "https://www.japantimes.co.jp/feed/",
        "region": "JP",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Nikkei Asia",
        "url": "https://asia.nikkei.com/rss/feed/nar",
        "region": "JP",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "Japan Today",
        "url": "https://japantoday.com/feed",
        "region": "JP",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Tokyo Reporter",
        "url": "https://www.tokyoreporter.com/feed/",
        "region": "JP",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── China ────────────────────────────────────────────────
    {
        "name": "South China Morning Post",
        "url": "https://www.scmp.com/rss/91/feed",
        "region": "CN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "China Project",
        "url": "https://thechinaproject.com/feed/",
        "region": "CN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Bloomberg China",
        "url": "https://feeds.bloomberg.com/technology/news.rss",
        "region": "CN",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "The Diplomat",
        "url": "https://thediplomat.com/feed/",
        "region": "CN",
        "language": "EN",
        "category": "geopolitics",
        "active": True,
    },
    # ── India ────────────────────────────────────────────────
    {
        "name": "Times of India",
        "url": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
        "region": "IN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Hindu Business Line",
        "url": "https://www.thehindubusinessline.com/feeder/default.rss",
        "region": "IN",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "Economic Times IN",
        "url": "https://economictimes.indiatimes.com/rssfeedstopstories.cms",
        "region": "IN",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "NDTV EN",
        "url": "https://feeds.feedburner.com/ndtvnews-top-stories",
        "region": "IN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "India Today",
        "url": "https://www.indiatoday.in/rss/home",
        "region": "IN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Mint India",
        "url": "https://www.livemint.com/rss/news",
        "region": "IN",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    # ── Southeast Asia ───────────────────────────────────────
    # ── Singapore ────────────────────────────────────────────
    {
        "name": "Straits Times",
        "url": "https://www.straitstimes.com/news/world/rss.xml",
        "region": "SG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Channel News Asia",
        "url": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
        "region": "SG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "SCMP SEA",
        "url": "https://www.scmp.com/rss/5/feed",
        "region": "SG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Coconuts Singapore",
        "url": "https://coconuts.co/singapore/feed/",
        "region": "SG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Thailand ─────────────────────────────────────────────
    {
        "name": "Bangkok Post",
        "url": "https://www.bangkokpost.com/rss/data/topstories.xml",
        "region": "TH",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Coconuts Bangkok",
        "url": "https://coconuts.co/bangkok/feed/",
        "region": "TH",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Malaysia ─────────────────────────────────────────────
    {
        "name": "Free Malaysia Today",
        "url": "https://www.freemalaysiatoday.com/category/nation/feed/",
        "region": "MY",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Philippines ──────────────────────────────────────────
    {
        "name": "Philippine Star",
        "url": "https://www.philstar.com/rss/headlines",
        "region": "PH",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Rappler PH",
        "url": "https://www.rappler.com/feed/",
        "region": "PH",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Myanmar ──────────────────────────────────────────────
    {
        "name": "Myanmar Now",
        "url": "https://myanmar-now.org/en/feed/",
        "region": "MM",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Frontier Myanmar",
        "url": "https://www.frontiermyanmar.net/en/feed/",
        "region": "MM",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Irrawaddy Myanmar",
        "url": "https://www.irrawaddy.com/feed",
        "region": "MM",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Vietnam ──────────────────────────────────────────────
    {
        "name": "Vietnam News",
        "url": "https://vietnamnews.vn/rss/news.rss",
        "region": "VN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Vietnam Insider",
        "url": "https://vietnaminsider.vn/feed/",
        "region": "VN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Indonesia ────────────────────────────────────────────
    {
        "name": "Indonesia Expat",
        "url": "https://indonesiaexpat.id/feed/",
        "region": "ID",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── South Korea ──────────────────────────────────────────
    {
        "name": "Korea Times",
        "url": "https://www.koreatimes.co.kr/www/rss/rss.xml",
        "region": "KR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Yonhap News",
        "url": "https://en.yna.co.kr/RSS/news.xml",
        "region": "KR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Taiwan ───────────────────────────────────────────────
    {
        "name": "Taipei Times",
        "url": "https://www.taipeitimes.com/xml/index.rss",
        "region": "TW",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Digitimes Taiwan",
        "url": "https://www.digitimes.com/rss/daily.xml",
        "region": "TW",
        "language": "EN",
        "category": "technology",
        "active": True,
    },
    {
        "name": "Taiwan Business Topics",
        "url": "https://topics.amcham.com.tw/feed/",
        "region": "TW",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    # ── Australia ────────────────────────────────────────────
    {
        "name": "ABC Australia",
        "url": "https://www.abc.net.au/news/feed/51120/rss.xml",
        "region": "AU",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Sydney Morning Herald",
        "url": "https://www.smh.com.au/rss/feed.xml",
        "region": "AU",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Guardian Australia",
        "url": "https://www.theguardian.com/australia-news/rss",
        "region": "AU",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── New Zealand ───────────────────────────────────────────
    {
        "name": "RNZ New Zealand",
        "url": "https://www.rnz.co.nz/rss/news.xml",
        "region": "NZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Pacific Islands ───────────────────────────────────────
    {
        "name": "PNG Post Courier",
        "url": "https://postcourier.com.pg/feed/",
        "region": "PG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "RNZ Pacific",
        "url": "https://www.rnz.co.nz/rss/pacific.xml",
        "region": "PG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Fiji Times",
        "url": "https://www.fijitimes.com/feed/",
        "region": "FJ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Kazakhstan ───────────────────────────────────────────
    {
        "name": "Astana Times",
        "url": "https://astanatimes.com/feed/",
        "region": "KZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Uzbekistan ───────────────────────────────────────────
    {
        "name": "Kun.uz EN",
        "url": "https://kun.uz/en/rss/",
        "region": "UZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Kyrgyzstan ───────────────────────────────────────────
    {
        "name": "Akipress",
        "url": "https://akipress.com/rss/news_en.rss",
        "region": "KG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Azerbaijan ───────────────────────────────────────────
    {
        "name": "AzerNews",
        "url": "https://www.azernews.az/rss/",
        "region": "AZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Trend.az",
        "url": "https://en.trend.az/rss/",
        "region": "AZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "OC Media AZ",
        "url": "https://oc-media.org/feed/",
        "region": "AZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Qatar ────────────────────────────────────────────────
    {
        "name": "Al Jazeera",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "region": "QA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Israel ───────────────────────────────────────────────
    {
        "name": "Jerusalem Post",
        "url": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
        "region": "IL",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Times of Israel",
        "url": "https://www.timesofisrael.com/feed/",
        "region": "IL",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── UAE ──────────────────────────────────────────────────
    {
        "name": "Middle East Eye",
        "url": "https://www.middleeasteye.net/rss",
        "region": "AE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Turkey ───────────────────────────────────────────────
    {
        "name": "Al Monitor",
        "url": "https://www.al-monitor.com/rss",
        "region": "TR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Turkish Minute",
        "url": "https://www.turkishminute.com/feed/",
        "region": "TR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Iran ─────────────────────────────────────────────────
    {
        "name": "Iran Front Page",
        "url": "https://ifpnews.com/feed/",
        "region": "IR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Pakistan ─────────────────────────────────────────────
    {
        "name": "Dawn Pakistan",
        "url": "https://www.dawn.com/feeds/home",
        "region": "PK",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Tribune Pakistan",
        "url": "https://tribune.com.pk/feed/rss",
        "region": "PK",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "ARY News EN",
        "url": "https://arynews.tv/feed/",
        "region": "PK",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Gulf States ──────────────────────────────────────────
    {
        "name": "Middle East Monitor",
        "url": "https://www.middleeastmonitor.com/feed/",
        "region": "KW",
        "language": "EN",
        "category": "geopolitics",
        "active": True,
    },
    # ── United States ─────────────────────────────────────────
    {
        "name": "NPR News",
        "url": "https://feeds.npr.org/1001/rss.xml",
        "region": "US",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "PBS NewsHour",
        "url": "https://www.pbs.org/newshour/feeds/rss/headlines",
        "region": "US",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "The Hill",
        "url": "https://thehill.com/feed/",
        "region": "US",
        "language": "EN",
        "category": "politics",
        "active": True,
    },
    {
        "name": "Bloomberg US",
        "url": "https://feeds.bloomberg.com/markets/news.rss",
        "region": "US",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "WSJ",
        "url": "https://feeds.content.dowjones.io/public/rss/mw_realtimeheadlines",
        "region": "US",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "CNN US",
        "url": "http://rss.cnn.com/rss/cnn_topstories.rss",
        "region": "US",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Fox News",
        "url": "https://moxie.foxnews.com/google-publisher/latest.xml",
        "region": "US",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Axios",
        "url": "https://api.axios.com/feed/",
        "region": "US",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Foreign Policy",
        "url": "https://foreignpolicy.com/feed/",
        "region": "US",
        "language": "EN",
        "category": "geopolitics",
        "active": True,
    },
    {
        "name": "Defense One",
        "url": "https://www.defenseone.com/rss/all/",
        "region": "US",
        "language": "EN",
        "category": "geopolitics",
        "active": False,
    },
    # ── Canada ───────────────────────────────────────────────
    {
        "name": "CBC Canada",
        "url": "https://www.cbc.ca/cmlink/rss-topstories",
        "region": "CA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "National Post",
        "url": "https://nationalpost.com/feed/",
        "region": "CA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Financial Post",
        "url": "https://financialpost.com/feed/",
        "region": "CA",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    {
        "name": "Global News CA",
        "url": "https://globalnews.ca/feed/",
        "region": "CA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Brazil ───────────────────────────────────────────────
    {
        "name": "Brazil Wire",
        "url": "https://www.brasilwire.com/feed/",
        "region": "BR",
        "language": "EN",
        "category": "politics",
        "active": True,
    },
    {
        "name": "Agencia Brasil",
        "url": "https://agenciabrasil.ebc.com.br/en/rss/ultimasnoticias/feed.xml",
        "region": "BR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Folha EN",
        "url": "https://www1.folha.uol.com.br/internacional/en/rss091.xml",
        "region": "BR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Merco Press",
        "url": "https://en.mercopress.com/rss",
        "region": "BR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Latin America Reports",
        "url": "https://latinamericareports.com/feed/",
        "region": "BR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Bloomberg Brazil",
        "url": "https://feeds.bloomberg.com/bview/news.rss",
        "region": "BR",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    # ── Mexico ───────────────────────────────────────────────
    {
        "name": "Mexico News Daily",
        "url": "https://mexiconewsdaily.com/feed/",
        "region": "MX",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Borderland Beat",
        "url": "https://www.borderlandbeat.com/feeds/posts/default",
        "region": "MX",
        "language": "EN",
        "category": "crime",
        "active": True,
    },
    {
        "name": "Yucatan Times",
        "url": "https://www.theyucatantimes.com/feed/",
        "region": "MX",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Colombia ─────────────────────────────────────────────
    {
        "name": "Colombia Reports",
        "url": "https://colombiareports.com/feed/",
        "region": "CO",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Insight Crime",
        "url": "https://insightcrime.org/feed/",
        "region": "CO",
        "language": "EN",
        "category": "crime",
        "active": True,
    },
    # ── Venezuela ────────────────────────────────────────────
    {
        "name": "Caracas Chronicles",
        "url": "https://www.caracaschronicles.com/feed/",
        "region": "VE",
        "language": "EN",
        "category": "politics",
        "active": True,
    },
    # ── Peru ─────────────────────────────────────────────────
    {
        "name": "Peru Reports",
        "url": "https://perureports.com/feed/",
        "region": "PE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Andes News Agency",
        "url": "https://andina.pe/ingles/rss/ultimas-noticias.xml",
        "region": "PE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Ecuador ──────────────────────────────────────────────
    {
        "name": "Ecuador Times",
        "url": "https://www.ecuadortimes.net/feed/",
        "region": "EC",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Argentina ────────────────────────────────────────────
    {
        "name": "Buenos Aires Herald",
        "url": "https://www.buenosairesherald.com/feed/",
        "region": "AR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Jamaica ──────────────────────────────────────────────
    {
        "name": "Jamaica Observer",
        "url": "https://www.jamaicaobserver.com/feed/",
        "region": "JM",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Barbados ─────────────────────────────────────────────
    {
        "name": "Barbados Today",
        "url": "https://barbadostoday.bb/feed/",
        "region": "BB",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Dominican Republic ────────────────────────────────────
    {
        "name": "Dominican Today",
        "url": "https://dominicantoday.com/feed/",
        "region": "DO",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Grenada ──────────────────────────────────────────────
    {
        "name": "Now Grenada",
        "url": "https://www.nowgrenada.com/feed/",
        "region": "GD",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Antigua ──────────────────────────────────────────────
    {
        "name": "Antigua Observer",
        "url": "https://antiguaobserver.com/feed/",
        "region": "AG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Costa Rica ────────────────────────────────────────────
    {
        "name": "Tico Times",
        "url": "https://ticotimes.net/feed/",
        "region": "CR",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── El Salvador ──────────────────────────────────────────
    {
        "name": "El Faro EN",
        "url": "https://elfaro.net/en/feed/",
        "region": "SV",
        "language": "EN",
        "category": "politics",
        "active": True,
    },
    # ── South Africa ─────────────────────────────────────────
    {
        "name": "AllAfrica",
        "url": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
        "region": "ZA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Mail & Guardian",
        "url": "https://mg.co.za/feed/",
        "region": "ZA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "News24",
        "url": "https://feeds.news24.com/articles/news24/TopStories/rss",
        "region": "ZA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Nigeria ──────────────────────────────────────────────
    {
        "name": "Premium Times NG",
        "url": "https://www.premiumtimesng.com/feed/",
        "region": "NG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Vanguard NG",
        "url": "https://www.vanguardngr.com/feed/",
        "region": "NG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Punch NG",
        "url": "https://punchng.com/feed/",
        "region": "NG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Kenya ────────────────────────────────────────────────
    {
        "name": "Capital FM KE",
        "url": "https://www.capitalfm.co.ke/news/feed/",
        "region": "KE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "KBC Kenya",
        "url": "https://www.kbc.co.ke/feed/",
        "region": "KE",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Ghana ────────────────────────────────────────────────
    {
        "name": "Ghana Business News",
        "url": "https://www.ghanabusinessnews.com/feed/",
        "region": "GH",
        "language": "EN",
        "category": "finance",
        "active": True,
    },
    # ── Pan-Africa West ──────────────────────────────────────────
    {
        "name": "Africa News",
        "url": "https://www.africanews.com/feed/rss",
        "region": "NG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Uganda ───────────────────────────────────────────────
    {
        "name": "Independent UG",
        "url": "https://www.independent.co.ug/feed/",
        "region": "UG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Rwanda ───────────────────────────────────────────────
    {
        "name": "Rwanda Dispatch",
        "url": "https://rwandadispatch.com/feed/",
        "region": "RW",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Tanzania ─────────────────────────────────────────────
    {
        "name": "Tanzanian Affairs",
        "url": "https://www.tzaffairs.org/feed/",
        "region": "TZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Zambia ───────────────────────────────────────────────
    {
        "name": "Zambia Daily Mail",
        "url": "https://www.daily-mail.co.zm/feed/",
        "region": "ZM",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    {
        "name": "Lusaka Times",
        "url": "https://www.lusakatimes.com/feed/",
        "region": "ZM",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Mozambique ───────────────────────────────────────────
    {
        "name": "Club of Mozambique",
        "url": "https://clubofmozambique.com/feed/",
        "region": "MZ",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Namibia ──────────────────────────────────────────────
    {
        "name": "The Namibian",
        "url": "https://www.namibian.com.na/feed/",
        "region": "NA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Egypt ────────────────────────────────────────────────
    {
        "name": "Egypt Independent",
        "url": "https://egyptindependent.com/feed/",
        "region": "EG",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Morocco ──────────────────────────────────────────────
    {
        "name": "Morocco World News",
        "url": "https://www.moroccoworldnews.com/feed/",
        "region": "MA",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Tunisia ──────────────────────────────────────────────
    {
        "name": "Tunisia Live",
        "url": "https://www.tunisia-live.net/feed/",
        "region": "TN",
        "language": "EN",
        "category": "general",
        "active": True,
    },
    # ── Libya ────────────────────────────────────────────────
    {
        "name": "Libya Herald",
        "url": "https://libyaherald.com/feed/",
        "region": "LY",
        "language": "EN",
        "category": "general",
        "active": True,
    },
]
